// Bootstrap Icons - 檔案文件分類  
// 包含：檔案、資料夾、文件類型、儲存等相關圖標

export const filesIcons = [
  // 基本檔案
  { name: 'File', class: 'bi-file' },
  { name: 'File Fill', class: 'bi-file-fill' },
  { name: 'Files', class: 'bi-files' },
  { name: 'Files Alt', class: 'bi-files-alt' },
  
  // 檔案操作
  { name: 'File Arrow Down', class: 'bi-file-arrow-down' },
  { name: 'File Arrow Down Fill', class: 'bi-file-arrow-down-fill' },
  { name: 'File Arrow Up', class: 'bi-file-arrow-up' },
  { name: 'File Arrow Up Fill', class: 'bi-file-arrow-up-fill' },
  { name: 'File Check', class: 'bi-file-check' },
  { name: 'File Check Fill', class: 'bi-file-check-fill' },
  { name: 'File Diff', class: 'bi-file-diff' },
  { name: 'File Diff Fill', class: 'bi-file-diff-fill' },
  { name: 'File Earmark', class: 'bi-file-earmark' },
  { name: 'File Earmark Arrow Down', class: 'bi-file-earmark-arrow-down' },
  { name: 'File Earmark Arrow Down Fill', class: 'bi-file-earmark-arrow-down-fill' },
  { name: 'File Earmark Arrow Up', class: 'bi-file-earmark-arrow-up' },
  { name: 'File Earmark Arrow Up Fill', class: 'bi-file-earmark-arrow-up-fill' },
  { name: 'File Earmark Check', class: 'bi-file-earmark-check' },
  { name: 'File Earmark Check Fill', class: 'bi-file-earmark-check-fill' },
  { name: 'File Earmark Diff', class: 'bi-file-earmark-diff' },
  { name: 'File Earmark Diff Fill', class: 'bi-file-earmark-diff-fill' },
  { name: 'File Earmark Fill', class: 'bi-file-earmark-fill' },
  { name: 'File Earmark Lock', class: 'bi-file-earmark-lock' },
  { name: 'File Earmark Lock Fill', class: 'bi-file-earmark-lock-fill' },
  { name: 'File Earmark Lock2', class: 'bi-file-earmark-lock2' },
  { name: 'File Earmark Lock2 Fill', class: 'bi-file-earmark-lock2-fill' },
  { name: 'File Earmark Medical', class: 'bi-file-earmark-medical' },
  { name: 'File Earmark Medical Fill', class: 'bi-file-earmark-medical-fill' },
  { name: 'File Earmark Minus', class: 'bi-file-earmark-minus' },
  { name: 'File Earmark Minus Fill', class: 'bi-file-earmark-minus-fill' },
  { name: 'File Earmark Person', class: 'bi-file-earmark-person' },
  { name: 'File Earmark Person Fill', class: 'bi-file-earmark-person-fill' },
  { name: 'File Earmark Play', class: 'bi-file-earmark-play' },
  { name: 'File Earmark Play Fill', class: 'bi-file-earmark-play-fill' },
  { name: 'File Earmark Plus', class: 'bi-file-earmark-plus' },
  { name: 'File Earmark Plus Fill', class: 'bi-file-earmark-plus-fill' },
  { name: 'File Earmark Post', class: 'bi-file-earmark-post' },
  { name: 'File Earmark Post Fill', class: 'bi-file-earmark-post-fill' },
  { name: 'File Earmark Richtext', class: 'bi-file-earmark-richtext' },
  { name: 'File Earmark Richtext Fill', class: 'bi-file-earmark-richtext-fill' },
  { name: 'File Earmark Ruled', class: 'bi-file-earmark-ruled' },
  { name: 'File Earmark Ruled Fill', class: 'bi-file-earmark-ruled-fill' },
  { name: 'File Earmark Slides', class: 'bi-file-earmark-slides' },
  { name: 'File Earmark Slides Fill', class: 'bi-file-earmark-slides-fill' },
  { name: 'File Earmark Spreadsheet', class: 'bi-file-earmark-spreadsheet' },
  { name: 'File Earmark Spreadsheet Fill', class: 'bi-file-earmark-spreadsheet-fill' },
  { name: 'File Earmark Text', class: 'bi-file-earmark-text' },
  { name: 'File Earmark Text Fill', class: 'bi-file-earmark-text-fill' },
  { name: 'File Earmark Word', class: 'bi-file-earmark-word' },
  { name: 'File Earmark Word Fill', class: 'bi-file-earmark-word-fill' },
  { name: 'File Earmark X', class: 'bi-file-earmark-x' },
  { name: 'File Earmark X Fill', class: 'bi-file-earmark-x-fill' },
  { name: 'File Earmark Zip', class: 'bi-file-earmark-zip' },
  { name: 'File Earmark Zip Fill', class: 'bi-file-earmark-zip-fill' },
  { name: 'File Lock', class: 'bi-file-lock' },
  { name: 'File Lock Fill', class: 'bi-file-lock-fill' },
  { name: 'File Lock2', class: 'bi-file-lock2' },
  { name: 'File Lock2 Fill', class: 'bi-file-lock2-fill' },
  { name: 'File Medical', class: 'bi-file-medical' },
  { name: 'File Medical Fill', class: 'bi-file-medical-fill' },
  { name: 'File Minus', class: 'bi-file-minus' },
  { name: 'File Minus Fill', class: 'bi-file-minus-fill' },
  { name: 'File Person', class: 'bi-file-person' },
  { name: 'File Person Fill', class: 'bi-file-person-fill' },
  { name: 'File Play', class: 'bi-file-play' },
  { name: 'File Play Fill', class: 'bi-file-play-fill' },
  { name: 'File Plus', class: 'bi-file-plus' },
  { name: 'File Plus Fill', class: 'bi-file-plus-fill' },
  { name: 'File Post', class: 'bi-file-post' },
  { name: 'File Post Fill', class: 'bi-file-post-fill' },
  { name: 'File Richtext', class: 'bi-file-richtext' },
  { name: 'File Richtext Fill', class: 'bi-file-richtext-fill' },
  { name: 'File Ruled', class: 'bi-file-ruled' },
  { name: 'File Ruled Fill', class: 'bi-file-ruled-fill' },
  { name: 'File Slides', class: 'bi-file-slides' },
  { name: 'File Slides Fill', class: 'bi-file-slides-fill' },
  { name: 'File Spreadsheet', class: 'bi-file-spreadsheet' },
  { name: 'File Spreadsheet Fill', class: 'bi-file-spreadsheet-fill' },
  { name: 'File Text', class: 'bi-file-text' },
  { name: 'File Text Fill', class: 'bi-file-text-fill' },
  { name: 'File Word', class: 'bi-file-word' },
  { name: 'File Word Fill', class: 'bi-file-word-fill' },
  { name: 'File X', class: 'bi-file-x' },
  { name: 'File X Fill', class: 'bi-file-x-fill' },
  { name: 'File Zip', class: 'bi-file-zip' },
  { name: 'File Zip Fill', class: 'bi-file-zip-fill' },
  
  // 資料夾
  { name: 'Folder', class: 'bi-folder' },
  { name: 'Folder Fill', class: 'bi-folder-fill' },
  { name: 'Folder2', class: 'bi-folder2' },
  { name: 'Folder2 Open', class: 'bi-folder2-open' },
  { name: 'Folder Check', class: 'bi-folder-check' },
  { name: 'Folder Fill', class: 'bi-folder-fill' },
  { name: 'Folder Minus', class: 'bi-folder-minus' },
  { name: 'Folder Plus', class: 'bi-folder-plus' },
  { name: 'Folder Symlink', class: 'bi-folder-symlink' },
  { name: 'Folder Symlink Fill', class: 'bi-folder-symlink-fill' },
  { name: 'Folder X', class: 'bi-folder-x' },
  
  // 圖像檔案
  { name: 'File Earmark Image', class: 'bi-file-earmark-image' },
  { name: 'File Earmark Image Fill', class: 'bi-file-earmark-image-fill' },
  { name: 'File Image', class: 'bi-file-image' },
  { name: 'File Image Fill', class: 'bi-file-image-fill' },
  { name: 'Image', class: 'bi-image' },
  { name: 'Image Alt', class: 'bi-image-alt' },
  { name: 'Image Fill', class: 'bi-image-fill' },
  { name: 'Images', class: 'bi-images' },
  
  // 程式碼檔案
  { name: 'File Code', class: 'bi-file-code' },
  { name: 'File Code Fill', class: 'bi-file-code-fill' },
  { name: 'File Earmark Code', class: 'bi-file-earmark-code' },
  { name: 'File Earmark Code Fill', class: 'bi-file-earmark-code-fill' },
  
  // PDF 檔案
  { name: 'File Earmark Pdf', class: 'bi-file-earmark-pdf' },
  { name: 'File Earmark Pdf Fill', class: 'bi-file-earmark-pdf-fill' },
  { name: 'File Pdf', class: 'bi-file-pdf' },
  { name: 'File Pdf Fill', class: 'bi-file-pdf-fill' },
  
  // 音樂檔案
  { name: 'File Earmark Music', class: 'bi-file-earmark-music' },
  { name: 'File Earmark Music Fill', class: 'bi-file-earmark-music-fill' },
  { name: 'File Music', class: 'bi-file-music' },
  { name: 'File Music Fill', class: 'bi-file-music-fill' },
  
  // 二進制檔案
  { name: 'File Binary', class: 'bi-file-binary' },
  { name: 'File Binary Fill', class: 'bi-file-binary-fill' },
  { name: 'File Earmark Binary', class: 'bi-file-earmark-binary' },
  { name: 'File Earmark Binary Fill', class: 'bi-file-earmark-binary-fill' },
  
  // 儲存裝置
  { name: 'Archive', class: 'bi-archive' },
  { name: 'Archive Fill', class: 'bi-archive-fill' },
  
  // 下載上傳
  { name: 'Download', class: 'bi-download' },
  { name: 'Upload', class: 'bi-upload' }
]

export const categoryInfo = {
  id: 'files',
  name: '檔案文件',
  description: '檔案、資料夾、文件類型相關圖標',
  priority: 'medium'
}