// Bootstrap Icons - 通用基礎圖標分類
// 包含：最常用的基礎圖標，如首頁、搜尋、設定等

export const generalIcons = [
  // 基本操作
  { name: 'House', class: 'bi-house' },
  { name: 'House Door', class: 'bi-house-door' },
  { name: 'House Door Fill', class: 'bi-house-door-fill' },
  { name: 'House Fill', class: 'bi-house-fill' },
  { name: 'Search', class: 'bi-search' },
  { name: 'Search Heart', class: 'bi-search-heart' },
  { name: 'Search Heart Fill', class: 'bi-search-heart-fill' },
  { name: 'Gear', class: 'bi-gear' },
  { name: 'Gear Fill', class: 'bi-gear-fill' },
  { name: 'Gear Wide', class: 'bi-gear-wide' },
  { name: 'Gear Wide Connected', class: 'bi-gear-wide-connected' },
  
  // 導航與箭頭
  { name: 'Arrow Up', class: 'bi-arrow-up' },
  { name: 'Arrow Down', class: 'bi-arrow-down' },
  { name: 'Arrow Left', class: 'bi-arrow-left' },
  { name: 'Arrow Right', class: 'bi-arrow-right' },
  { name: 'Arrow Up Circle', class: 'bi-arrow-up-circle' },
  { name: 'Arrow Down Circle', class: 'bi-arrow-down-circle' },
  { name: 'Arrow Left Circle', class: 'bi-arrow-left-circle' },
  { name: 'Arrow Right Circle', class: 'bi-arrow-right-circle' },
  { name: 'Arrow Up Circle Fill', class: 'bi-arrow-up-circle-fill' },
  { name: 'Arrow Down Circle Fill', class: 'bi-arrow-down-circle-fill' },
  { name: 'Arrow Left Circle Fill', class: 'bi-arrow-left-circle-fill' },
  { name: 'Arrow Right Circle Fill', class: 'bi-arrow-right-circle-fill' },
  { name: 'Arrow Up Short', class: 'bi-arrow-up-short' },
  { name: 'Arrow Down Short', class: 'bi-arrow-down-short' },
  { name: 'Arrow Left Short', class: 'bi-arrow-left-short' },
  { name: 'Arrow Right Short', class: 'bi-arrow-right-short' },
  { name: 'Arrow Clockwise', class: 'bi-arrow-clockwise' },
  { name: 'Arrow Counterclockwise', class: 'bi-arrow-counterclockwise' },
  { name: 'Arrow Repeat', class: 'bi-arrow-repeat' },
  { name: 'Arrow Return Left', class: 'bi-arrow-return-left' },
  { name: 'Arrow Return Right', class: 'bi-arrow-return-right' },
  
  // 基本形狀與符號
  { name: 'Circle', class: 'bi-circle' },
  { name: 'Circle Fill', class: 'bi-circle-fill' },
  { name: 'Circle Half', class: 'bi-circle-half' },
  { name: 'Square', class: 'bi-square' },
  { name: 'Square Fill', class: 'bi-square-fill' },
  { name: 'Square Half', class: 'bi-square-half' },
  { name: 'Triangle', class: 'bi-triangle' },
  { name: 'Triangle Fill', class: 'bi-triangle-fill' },
  { name: 'Triangle Half', class: 'bi-triangle-half' },
  { name: 'Diamond', class: 'bi-diamond' },
  { name: 'Diamond Fill', class: 'bi-diamond-fill' },
  { name: 'Diamond Half', class: 'bi-diamond-half' },
  
  // 常用操作符號
  { name: 'Plus', class: 'bi-plus' },
  { name: 'Plus Circle', class: 'bi-plus-circle' },
  { name: 'Plus Circle Fill', class: 'bi-plus-circle-fill' },
  { name: 'Plus Square', class: 'bi-plus-square' },
  { name: 'Plus Square Fill', class: 'bi-plus-square-fill' },
  { name: 'Plus Lg', class: 'bi-plus-lg' },
  { name: 'Dash', class: 'bi-dash' },
  { name: 'Dash Circle', class: 'bi-dash-circle' },
  { name: 'Dash Circle Fill', class: 'bi-dash-circle-fill' },
  { name: 'Dash Square', class: 'bi-dash-square' },
  { name: 'Dash Square Fill', class: 'bi-dash-square-fill' },
  { name: 'Dash Lg', class: 'bi-dash-lg' },
  { name: 'X', class: 'bi-x' },
  { name: 'X Circle', class: 'bi-x-circle' },
  { name: 'X Circle Fill', class: 'bi-x-circle-fill' },
  { name: 'X Square', class: 'bi-x-square' },
  { name: 'X Square Fill', class: 'bi-x-square-fill' },
  { name: 'X Lg', class: 'bi-x-lg' },
  
  // 檢查與確認
  { name: 'Check', class: 'bi-check' },
  { name: 'Check Circle', class: 'bi-check-circle' },
  { name: 'Check Circle Fill', class: 'bi-check-circle-fill' },
  { name: 'Check Square', class: 'bi-check-square' },
  { name: 'Check Square Fill', class: 'bi-check-square-fill' },
  { name: 'Check Lg', class: 'bi-check-lg' },
  { name: 'Check2', class: 'bi-check2' },
  { name: 'Check2 All', class: 'bi-check2-all' },
  { name: 'Check2 Circle', class: 'bi-check2-circle' },
  { name: 'Check2 Square', class: 'bi-check2-square' },
  
  // 星形與評級
  { name: 'Star', class: 'bi-star' },
  { name: 'Star Fill', class: 'bi-star-fill' },
  { name: 'Star Half', class: 'bi-star-half' },
  { name: 'Stars', class: 'bi-stars' },
  
  // 心形與喜愛
  { name: 'Heart', class: 'bi-heart' },
  { name: 'Heart Fill', class: 'bi-heart-fill' },
  { name: 'Heart Half', class: 'bi-heart-half' },
  { name: 'Hearts', class: 'bi-hearts' },
  
  // 訊息與通知
  { name: 'Bell', class: 'bi-bell' },
  { name: 'Bell Fill', class: 'bi-bell-fill' },
  { name: 'Bell Slash', class: 'bi-bell-slash' },
  { name: 'Bell Slash Fill', class: 'bi-bell-slash-fill' },
  
  // 問號與協助
  { name: 'Question', class: 'bi-question' },
  { name: 'Question Circle', class: 'bi-question-circle' },
  { name: 'Question Circle Fill', class: 'bi-question-circle-fill' },
  { name: 'Question Diamond', class: 'bi-question-diamond' },
  { name: 'Question Diamond Fill', class: 'bi-question-diamond-fill' },
  { name: 'Question Lg', class: 'bi-question-lg' },
  { name: 'Question Octagon', class: 'bi-question-octagon' },
  { name: 'Question Octagon Fill', class: 'bi-question-octagon-fill' },
  { name: 'Question Square', class: 'bi-question-square' },
  { name: 'Question Square Fill', class: 'bi-question-square-fill' },
  
  // 資訊與提示
  { name: 'Info', class: 'bi-info' },
  { name: 'Info Circle', class: 'bi-info-circle' },
  { name: 'Info Circle Fill', class: 'bi-info-circle-fill' },
  { name: 'Info Square', class: 'bi-info-square' },
  { name: 'Info Square Fill', class: 'bi-info-square-fill' },
  { name: 'Info Lg', class: 'bi-info-lg' },
  
  // 警告與錯誤
  { name: 'Exclamation', class: 'bi-exclamation' },
  { name: 'Exclamation Circle', class: 'bi-exclamation-circle' },
  { name: 'Exclamation Circle Fill', class: 'bi-exclamation-circle-fill' },
  { name: 'Exclamation Diamond', class: 'bi-exclamation-diamond' },
  { name: 'Exclamation Diamond Fill', class: 'bi-exclamation-diamond-fill' },
  { name: 'Exclamation Lg', class: 'bi-exclamation-lg' },
  { name: 'Exclamation Octagon', class: 'bi-exclamation-octagon' },
  { name: 'Exclamation Octagon Fill', class: 'bi-exclamation-octagon-fill' },
  { name: 'Exclamation Square', class: 'bi-exclamation-square' },
  { name: 'Exclamation Square Fill', class: 'bi-exclamation-square-fill' },
  { name: 'Exclamation Triangle', class: 'bi-exclamation-triangle' },
  { name: 'Exclamation Triangle Fill', class: 'bi-exclamation-triangle-fill' },
  
  // 更多箭頭變化
  { name: 'Arrow Bar Up', class: 'bi-arrow-bar-up' },
  { name: 'Arrow Bar Down', class: 'bi-arrow-bar-down' },
  { name: 'Arrow Bar Left', class: 'bi-arrow-bar-left' },
  { name: 'Arrow Bar Right', class: 'bi-arrow-bar-right' },
  { name: 'Arrow Up Square', class: 'bi-arrow-up-square' },
  { name: 'Arrow Down Square', class: 'bi-arrow-down-square' },
  { name: 'Arrow Left Square', class: 'bi-arrow-left-square' },
  { name: 'Arrow Right Square', class: 'bi-arrow-right-square' },
  { name: 'Arrow Up Square Fill', class: 'bi-arrow-up-square-fill' },
  { name: 'Arrow Down Square Fill', class: 'bi-arrow-down-square-fill' },
  { name: 'Arrow Left Square Fill', class: 'bi-arrow-left-square-fill' },
  { name: 'Arrow Right Square Fill', class: 'bi-arrow-right-square-fill' },
  { name: 'Arrows Angle Contract', class: 'bi-arrows-angle-contract' },
  { name: 'Arrows Angle Expand', class: 'bi-arrows-angle-expand' },
  { name: 'Arrows Collapse', class: 'bi-arrows-collapse' },
  { name: 'Arrows Expand', class: 'bi-arrows-expand' },
  { name: 'Arrows Fullscreen', class: 'bi-arrows-fullscreen' },
  { name: 'Arrows Move', class: 'bi-arrows-move' },
  
  // 更多形狀
  { name: 'Pentagon', class: 'bi-pentagon' },
  { name: 'Pentagon Fill', class: 'bi-pentagon-fill' },
  { name: 'Pentagon Half', class: 'bi-pentagon-half' },
  { name: 'Hexagon', class: 'bi-hexagon' },
  { name: 'Hexagon Fill', class: 'bi-hexagon-fill' },
  { name: 'Hexagon Half', class: 'bi-hexagon-half' },
  { name: 'Octagon', class: 'bi-octagon' },
  { name: 'Octagon Fill', class: 'bi-octagon-fill' },
  { name: 'Octagon Half', class: 'bi-octagon-half' },
  
  // 點與標記
  { name: 'Dot', class: 'bi-dot' },
  { name: 'Three Dots', class: 'bi-three-dots' },
  { name: 'Three Dots Vertical', class: 'bi-three-dots-vertical' },
  { name: 'Grid', class: 'bi-grid' },
  { name: 'Grid 1x2', class: 'bi-grid-1x2' },
  { name: 'Grid 1x2 Fill', class: 'bi-grid-1x2-fill' },
  { name: 'Grid 3x2', class: 'bi-grid-3x2' },
  { name: 'Grid 3x2 Gap', class: 'bi-grid-3x2-gap' },
  { name: 'Grid 3x2 Gap Fill', class: 'bi-grid-3x2-gap-fill' },
  { name: 'Grid 3x3', class: 'bi-grid-3x3' },
  { name: 'Grid 3x3 Gap', class: 'bi-grid-3x3-gap' },
  { name: 'Grid 3x3 Gap Fill', class: 'bi-grid-3x3-gap-fill' },
  { name: 'Grid Fill', class: 'bi-grid-fill' },
  
  // 鎖定與解鎖
  { name: 'Lock', class: 'bi-lock' },
  { name: 'Lock Fill', class: 'bi-lock-fill' },
  { name: 'Unlock', class: 'bi-unlock' },
  { name: 'Unlock Fill', class: 'bi-unlock-fill' },
  { name: 'Shield Lock', class: 'bi-shield-lock' },
  { name: 'Shield Lock Fill', class: 'bi-shield-lock-fill' },
  
  // 盾牌與安全
  { name: 'Shield', class: 'bi-shield' },
  { name: 'Shield Check', class: 'bi-shield-check' },
  { name: 'Shield Exclamation', class: 'bi-shield-exclamation' },
  { name: 'Shield Fill', class: 'bi-shield-fill' },
  { name: 'Shield Fill Check', class: 'bi-shield-fill-check' },
  { name: 'Shield Fill Exclamation', class: 'bi-shield-fill-exclamation' },
  { name: 'Shield Fill Minus', class: 'bi-shield-fill-minus' },
  { name: 'Shield Fill Plus', class: 'bi-shield-fill-plus' },
  { name: 'Shield Fill X', class: 'bi-shield-fill-x' },
  { name: 'Shield Minus', class: 'bi-shield-minus' },
  { name: 'Shield Plus', class: 'bi-shield-plus' },
  { name: 'Shield Slash', class: 'bi-shield-slash' },
  { name: 'Shield Slash Fill', class: 'bi-shield-slash-fill' },
  { name: 'Shield X', class: 'bi-shield-x' },
  
  // 眼睛與顯示
  { name: 'Eye', class: 'bi-eye' },
  { name: 'Eye Fill', class: 'bi-eye-fill' },
  { name: 'Eye Slash', class: 'bi-eye-slash' },
  { name: 'Eye Slash Fill', class: 'bi-eye-slash-fill' },
  { name: 'Eyeglasses', class: 'bi-eyeglasses' },
  
  // 書籤與標籤
  { name: 'Bookmark', class: 'bi-bookmark' },
  { name: 'Bookmark Check', class: 'bi-bookmark-check' },
  { name: 'Bookmark Check Fill', class: 'bi-bookmark-check-fill' },
  { name: 'Bookmark Dash', class: 'bi-bookmark-dash' },
  { name: 'Bookmark Dash Fill', class: 'bi-bookmark-dash-fill' },
  { name: 'Bookmark Fill', class: 'bi-bookmark-fill' },
  { name: 'Bookmark Heart', class: 'bi-bookmark-heart' },
  { name: 'Bookmark Heart Fill', class: 'bi-bookmark-heart-fill' },
  { name: 'Bookmark Plus', class: 'bi-bookmark-plus' },
  { name: 'Bookmark Plus Fill', class: 'bi-bookmark-plus-fill' },
  { name: 'Bookmark Star', class: 'bi-bookmark-star' },
  { name: 'Bookmark Star Fill', class: 'bi-bookmark-star-fill' },
  { name: 'Bookmark X', class: 'bi-bookmark-x' },
  { name: 'Bookmark X Fill', class: 'bi-bookmark-x-fill' },
  { name: 'Bookmarks', class: 'bi-bookmarks' },
  { name: 'Bookmarks Fill', class: 'bi-bookmarks-fill' },
  
  // 旗標與標籤
  { name: 'Flag', class: 'bi-flag' },
  { name: 'Flag Fill', class: 'bi-flag-fill' },
  { name: 'Tag', class: 'bi-tag' },
  { name: 'Tag Fill', class: 'bi-tag-fill' },
  { name: 'Tags', class: 'bi-tags' },
  { name: 'Tags Fill', class: 'bi-tags-fill' },
  
  // 分享與連結
  { name: 'Share', class: 'bi-share' },
  { name: 'Share Fill', class: 'bi-share-fill' },
  { name: 'Link', class: 'bi-link' },
  { name: 'Link 45deg', class: 'bi-link-45deg' },
  
  // 下載與上傳
  { name: 'Download', class: 'bi-download' },
  { name: 'Upload', class: 'bi-upload' },
  { name: 'Cloud Download', class: 'bi-cloud-download' },
  { name: 'Cloud Download Fill', class: 'bi-cloud-download-fill' },
  { name: 'Cloud Upload', class: 'bi-cloud-upload' },
  { name: 'Cloud Upload Fill', class: 'bi-cloud-upload-fill' },
  
  // 雲端與同步
  { name: 'Cloud', class: 'bi-cloud' },
  { name: 'Cloud Arrow Down', class: 'bi-cloud-arrow-down' },
  { name: 'Cloud Arrow Down Fill', class: 'bi-cloud-arrow-down-fill' },
  { name: 'Cloud Arrow Up', class: 'bi-cloud-arrow-up' },
  { name: 'Cloud Arrow Up Fill', class: 'bi-cloud-arrow-up-fill' },
  { name: 'Cloud Check', class: 'bi-cloud-check' },
  { name: 'Cloud Check Fill', class: 'bi-cloud-check-fill' },
  { name: 'Cloud Drizzle', class: 'bi-cloud-drizzle' },
  { name: 'Cloud Drizzle Fill', class: 'bi-cloud-drizzle-fill' },
  { name: 'Cloud Fill', class: 'bi-cloud-fill' },
  { name: 'Cloud Fog', class: 'bi-cloud-fog' },
  { name: 'Cloud Fog Fill', class: 'bi-cloud-fog-fill' },
  { name: 'Cloud Fog2', class: 'bi-cloud-fog2' },
  { name: 'Cloud Fog2 Fill', class: 'bi-cloud-fog2-fill' },
  { name: 'Cloud Hail', class: 'bi-cloud-hail' },
  { name: 'Cloud Hail Fill', class: 'bi-cloud-hail-fill' },
  { name: 'Cloud Haze', class: 'bi-cloud-haze' },
  { name: 'Cloud Haze Fill', class: 'bi-cloud-haze-fill' },
  { name: 'Cloud Haze2', class: 'bi-cloud-haze2' },
  { name: 'Cloud Haze2 Fill', class: 'bi-cloud-haze2-fill' },
  { name: 'Cloud Lightning', class: 'bi-cloud-lightning' },
  { name: 'Cloud Lightning Fill', class: 'bi-cloud-lightning-fill' },
  { name: 'Cloud Lightning Rain', class: 'bi-cloud-lightning-rain' },
  { name: 'Cloud Lightning Rain Fill', class: 'bi-cloud-lightning-rain-fill' },
  { name: 'Cloud Minus', class: 'bi-cloud-minus' },
  { name: 'Cloud Minus Fill', class: 'bi-cloud-minus-fill' },
  { name: 'Cloud Moon', class: 'bi-cloud-moon' },
  { name: 'Cloud Moon Fill', class: 'bi-cloud-moon-fill' },
  { name: 'Cloud Plus', class: 'bi-cloud-plus' },
  { name: 'Cloud Plus Fill', class: 'bi-cloud-plus-fill' },
  { name: 'Cloud Rain', class: 'bi-cloud-rain' },
  { name: 'Cloud Rain Fill', class: 'bi-cloud-rain-fill' },
  { name: 'Cloud Rain Heavy', class: 'bi-cloud-rain-heavy' },
  { name: 'Cloud Rain Heavy Fill', class: 'bi-cloud-rain-heavy-fill' },
  { name: 'Cloud Slash', class: 'bi-cloud-slash' },
  { name: 'Cloud Slash Fill', class: 'bi-cloud-slash-fill' },
  { name: 'Cloud Snow', class: 'bi-cloud-snow' },
  { name: 'Cloud Snow Fill', class: 'bi-cloud-snow-fill' },
  { name: 'Cloud Sun', class: 'bi-cloud-sun' },
  { name: 'Cloud Sun Fill', class: 'bi-cloud-sun-fill' },
  { name: 'Clouds', class: 'bi-clouds' },
  { name: 'Clouds Fill', class: 'bi-clouds-fill' },
  { name: 'Cloudy', class: 'bi-cloudy' },
  { name: 'Cloudy Fill', class: 'bi-cloudy-fill' },
  
  // 太陽與月亮
  { name: 'Sun', class: 'bi-sun' },
  { name: 'Sun Fill', class: 'bi-sun-fill' },
  { name: 'Sunrise', class: 'bi-sunrise' },
  { name: 'Sunrise Fill', class: 'bi-sunrise-fill' },
  { name: 'Sunset', class: 'bi-sunset' },
  { name: 'Sunset Fill', class: 'bi-sunset-fill' },
  { name: 'Moon', class: 'bi-moon' },
  { name: 'Moon Fill', class: 'bi-moon-fill' },
  { name: 'Moon Stars', class: 'bi-moon-stars' },
  { name: 'Moon Stars Fill', class: 'bi-moon-stars-fill' },
  { name: 'Brightness Alt High', class: 'bi-brightness-alt-high' },
  { name: 'Brightness Alt High Fill', class: 'bi-brightness-alt-high-fill' },
  { name: 'Brightness Alt Low', class: 'bi-brightness-alt-low' },
  { name: 'Brightness Alt Low Fill', class: 'bi-brightness-alt-low-fill' },
  { name: 'Brightness High', class: 'bi-brightness-high' },
  { name: 'Brightness High Fill', class: 'bi-brightness-high-fill' },
  { name: 'Brightness Low', class: 'bi-brightness-low' },
  { name: 'Brightness Low Fill', class: 'bi-brightness-low-fill' },
  
  // 垃圾桶與刪除
  { name: 'Trash', class: 'bi-trash' },
  { name: 'Trash Fill', class: 'bi-trash-fill' },
  { name: 'Trash2', class: 'bi-trash2' },
  { name: 'Trash2 Fill', class: 'bi-trash2-fill' },
  { name: 'Trash3', class: 'bi-trash3' },
  { name: 'Trash3 Fill', class: 'bi-trash3-fill' },
  
  // 編輯與鉛筆
  { name: 'Pencil', class: 'bi-pencil' },
  { name: 'Pencil Fill', class: 'bi-pencil-fill' },
  { name: 'Pencil Square', class: 'bi-pencil-square' },
  { name: 'Pen', class: 'bi-pen' },
  { name: 'Pen Fill', class: 'bi-pen-fill' },
  { name: 'Brush', class: 'bi-brush' },
  { name: 'Brush Fill', class: 'bi-brush-fill' },
  { name: 'Eraser', class: 'bi-eraser' },
  { name: 'Eraser Fill', class: 'bi-eraser-fill' },
  
  // 剪貼簿
  { name: 'Clipboard', class: 'bi-clipboard' },
  { name: 'Clipboard Check', class: 'bi-clipboard-check' },
  { name: 'Clipboard Check Fill', class: 'bi-clipboard-check-fill' },
  { name: 'Clipboard Data', class: 'bi-clipboard-data' },
  { name: 'Clipboard Data Fill', class: 'bi-clipboard-data-fill' },
  { name: 'Clipboard Fill', class: 'bi-clipboard-fill' },
  { name: 'Clipboard Heart', class: 'bi-clipboard-heart' },
  { name: 'Clipboard Heart Fill', class: 'bi-clipboard-heart-fill' },
  { name: 'Clipboard Minus', class: 'bi-clipboard-minus' },
  { name: 'Clipboard Minus Fill', class: 'bi-clipboard-minus-fill' },
  { name: 'Clipboard Plus', class: 'bi-clipboard-plus' },
  { name: 'Clipboard Plus Fill', class: 'bi-clipboard-plus-fill' },
  { name: 'Clipboard Pulse', class: 'bi-clipboard-pulse' },
  { name: 'Clipboard X', class: 'bi-clipboard-x' },
  { name: 'Clipboard X Fill', class: 'bi-clipboard-x-fill' },
  { name: 'Clipboard2', class: 'bi-clipboard2' },
  { name: 'Clipboard2 Check', class: 'bi-clipboard2-check' },
  { name: 'Clipboard2 Check Fill', class: 'bi-clipboard2-check-fill' },
  { name: 'Clipboard2 Data', class: 'bi-clipboard2-data' },
  { name: 'Clipboard2 Data Fill', class: 'bi-clipboard2-data-fill' },
  { name: 'Clipboard2 Fill', class: 'bi-clipboard2-fill' },
  { name: 'Clipboard2 Heart', class: 'bi-clipboard2-heart' },
  { name: 'Clipboard2 Heart Fill', class: 'bi-clipboard2-heart-fill' },
  { name: 'Clipboard2 Minus', class: 'bi-clipboard2-minus' },
  { name: 'Clipboard2 Minus Fill', class: 'bi-clipboard2-minus-fill' },
  { name: 'Clipboard2 Plus', class: 'bi-clipboard2-plus' },
  { name: 'Clipboard2 Plus Fill', class: 'bi-clipboard2-plus-fill' },
  { name: 'Clipboard2 Pulse', class: 'bi-clipboard2-pulse' },
  { name: 'Clipboard2 Pulse Fill', class: 'bi-clipboard2-pulse-fill' },
  { name: 'Clipboard2 X', class: 'bi-clipboard2-x' },
  { name: 'Clipboard2 X Fill', class: 'bi-clipboard2-x-fill' },
  
  // 箱子與封包
  { name: 'Box', class: 'bi-box' },
  { name: 'Box Fill', class: 'bi-box-fill' },
  { name: 'Box Seam', class: 'bi-box-seam' },
  { name: 'Box Seam Fill', class: 'bi-box-seam-fill' },
  { name: 'Box2', class: 'bi-box2' },
  { name: 'Box2 Fill', class: 'bi-box2-fill' },
  { name: 'Box2 Heart', class: 'bi-box2-heart' },
  { name: 'Box2 Heart Fill', class: 'bi-box2-heart-fill' },
  { name: 'Boxes', class: 'bi-boxes' },
  
  // 時鐘與時間
  { name: 'Clock', class: 'bi-clock' },
  { name: 'Clock Fill', class: 'bi-clock-fill' },
  { name: 'Clock History', class: 'bi-clock-history' },
  { name: 'Alarm', class: 'bi-alarm' },
  { name: 'Alarm Fill', class: 'bi-alarm-fill' },
  { name: 'Stopwatch', class: 'bi-stopwatch' },
  { name: 'Stopwatch Fill', class: 'bi-stopwatch-fill' },
  { name: 'Smartwatch', class: 'bi-smartwatch' },
  { name: 'Watch', class: 'bi-watch' },
  
  // 日曆
  { name: 'Calendar', class: 'bi-calendar' },
  { name: 'Calendar Check', class: 'bi-calendar-check' },
  { name: 'Calendar Check Fill', class: 'bi-calendar-check-fill' },
  { name: 'Calendar Date', class: 'bi-calendar-date' },
  { name: 'Calendar Date Fill', class: 'bi-calendar-date-fill' },
  { name: 'Calendar Day', class: 'bi-calendar-day' },
  { name: 'Calendar Day Fill', class: 'bi-calendar-day-fill' },
  { name: 'Calendar Event', class: 'bi-calendar-event' },
  { name: 'Calendar Event Fill', class: 'bi-calendar-event-fill' },
  { name: 'Calendar Fill', class: 'bi-calendar-fill' },
  { name: 'Calendar Heart', class: 'bi-calendar-heart' },
  { name: 'Calendar Heart Fill', class: 'bi-calendar-heart-fill' },
  { name: 'Calendar Minus', class: 'bi-calendar-minus' },
  { name: 'Calendar Minus Fill', class: 'bi-calendar-minus-fill' },
  { name: 'Calendar Month', class: 'bi-calendar-month' },
  { name: 'Calendar Month Fill', class: 'bi-calendar-month-fill' },
  { name: 'Calendar Plus', class: 'bi-calendar-plus' },
  { name: 'Calendar Plus Fill', class: 'bi-calendar-plus-fill' },
  { name: 'Calendar Range', class: 'bi-calendar-range' },
  { name: 'Calendar Range Fill', class: 'bi-calendar-range-fill' },
  { name: 'Calendar Week', class: 'bi-calendar-week' },
  { name: 'Calendar Week Fill', class: 'bi-calendar-week-fill' },
  { name: 'Calendar X', class: 'bi-calendar-x' },
  { name: 'Calendar X Fill', class: 'bi-calendar-x-fill' },
  { name: 'Calendar2', class: 'bi-calendar2' },
  { name: 'Calendar2 Check', class: 'bi-calendar2-check' },
  { name: 'Calendar2 Check Fill', class: 'bi-calendar2-check-fill' },
  { name: 'Calendar2 Date', class: 'bi-calendar2-date' },
  { name: 'Calendar2 Date Fill', class: 'bi-calendar2-date-fill' },
  { name: 'Calendar2 Day', class: 'bi-calendar2-day' },
  { name: 'Calendar2 Day Fill', class: 'bi-calendar2-day-fill' },
  { name: 'Calendar2 Event', class: 'bi-calendar2-event' },
  { name: 'Calendar2 Event Fill', class: 'bi-calendar2-event-fill' },
  { name: 'Calendar2 Fill', class: 'bi-calendar2-fill' },
  { name: 'Calendar2 Heart', class: 'bi-calendar2-heart' },
  { name: 'Calendar2 Heart Fill', class: 'bi-calendar2-heart-fill' },
  { name: 'Calendar2 Minus', class: 'bi-calendar2-minus' },
  { name: 'Calendar2 Minus Fill', class: 'bi-calendar2-minus-fill' },
  { name: 'Calendar2 Month', class: 'bi-calendar2-month' },
  { name: 'Calendar2 Month Fill', class: 'bi-calendar2-month-fill' },
  { name: 'Calendar2 Plus', class: 'bi-calendar2-plus' },
  { name: 'Calendar2 Plus Fill', class: 'bi-calendar2-plus-fill' },
  { name: 'Calendar2 Range', class: 'bi-calendar2-range' },
  { name: 'Calendar2 Range Fill', class: 'bi-calendar2-range-fill' },
  { name: 'Calendar2 Week', class: 'bi-calendar2-week' },
  { name: 'Calendar2 Week Fill', class: 'bi-calendar2-week-fill' },
  { name: 'Calendar2 X', class: 'bi-calendar2-x' },
  { name: 'Calendar2 X Fill', class: 'bi-calendar2-x-fill' },
  { name: 'Calendar3', class: 'bi-calendar3' },
  { name: 'Calendar3 Event', class: 'bi-calendar3-event' },
  { name: 'Calendar3 Event Fill', class: 'bi-calendar3-event-fill' },
  { name: 'Calendar3 Fill', class: 'bi-calendar3-fill' },
  { name: 'Calendar3 Range', class: 'bi-calendar3-range' },
  { name: 'Calendar3 Range Fill', class: 'bi-calendar3-range-fill' },
  { name: 'Calendar3 Week', class: 'bi-calendar3-week' },
  { name: 'Calendar3 Week Fill', class: 'bi-calendar3-week-fill' },
  { name: 'Calendar4', class: 'bi-calendar4' },
  { name: 'Calendar4 Event', class: 'bi-calendar4-event' },
  { name: 'Calendar4 Range', class: 'bi-calendar4-range' },
  { name: 'Calendar4 Week', class: 'bi-calendar4-week' },
  
  // 鑰匙
  { name: 'Key', class: 'bi-key' },
  { name: 'Key Fill', class: 'bi-key-fill' },
  
  // 燈泡與想法
  { name: 'Lightbulb', class: 'bi-lightbulb' },
  { name: 'Lightbulb Fill', class: 'bi-lightbulb-fill' },
  { name: 'Lightbulb Off', class: 'bi-lightbulb-off' },
  { name: 'Lightbulb Off Fill', class: 'bi-lightbulb-off-fill' },
  
  // 閃電
  { name: 'Lightning', class: 'bi-lightning' },
  { name: 'Lightning Charge', class: 'bi-lightning-charge' },
  { name: 'Lightning Charge Fill', class: 'bi-lightning-charge-fill' },
  { name: 'Lightning Fill', class: 'bi-lightning-fill' },
  
  // 放大鏡與縮放
  { name: 'Zoom In', class: 'bi-zoom-in' },
  { name: 'Zoom Out', class: 'bi-zoom-out' },
  
  // 濾鏡與篩選
  { name: 'Filter', class: 'bi-filter' },
  { name: 'Filter Circle', class: 'bi-filter-circle' },
  { name: 'Filter Circle Fill', class: 'bi-filter-circle-fill' },
  { name: 'Filter Left', class: 'bi-filter-left' },
  { name: 'Filter Right', class: 'bi-filter-right' },
  { name: 'Filter Square', class: 'bi-filter-square' },
  { name: 'Filter Square Fill', class: 'bi-filter-square-fill' },
  { name: 'Funnel', class: 'bi-funnel' },
  { name: 'Funnel Fill', class: 'bi-funnel-fill' },
  
  // 排序
  { name: 'Sort Alpha Down', class: 'bi-sort-alpha-down' },
  { name: 'Sort Alpha Down Alt', class: 'bi-sort-alpha-down-alt' },
  { name: 'Sort Alpha Up', class: 'bi-sort-alpha-up' },
  { name: 'Sort Alpha Up Alt', class: 'bi-sort-alpha-up-alt' },
  { name: 'Sort Down', class: 'bi-sort-down' },
  { name: 'Sort Down Alt', class: 'bi-sort-down-alt' },
  { name: 'Sort Numeric Down', class: 'bi-sort-numeric-down' },
  { name: 'Sort Numeric Down Alt', class: 'bi-sort-numeric-down-alt' },
  { name: 'Sort Numeric Up', class: 'bi-sort-numeric-up' },
  { name: 'Sort Numeric Up Alt', class: 'bi-sort-numeric-up-alt' },
  { name: 'Sort Up', class: 'bi-sort-up' },
  { name: 'Sort Up Alt', class: 'bi-sort-up-alt' },
  
  // 箭頭更多變化
  { name: 'Arrow 90deg Down', class: 'bi-arrow-90deg-down' },
  { name: 'Arrow 90deg Left', class: 'bi-arrow-90deg-left' },
  { name: 'Arrow 90deg Right', class: 'bi-arrow-90deg-right' },
  { name: 'Arrow 90deg Up', class: 'bi-arrow-90deg-up' },
  { name: 'Arrow Down Left', class: 'bi-arrow-down-left' },
  { name: 'Arrow Down Left Circle', class: 'bi-arrow-down-left-circle' },
  { name: 'Arrow Down Left Circle Fill', class: 'bi-arrow-down-left-circle-fill' },
  { name: 'Arrow Down Left Square', class: 'bi-arrow-down-left-square' },
  { name: 'Arrow Down Left Square Fill', class: 'bi-arrow-down-left-square-fill' },
  { name: 'Arrow Down Right', class: 'bi-arrow-down-right' },
  { name: 'Arrow Down Right Circle', class: 'bi-arrow-down-right-circle' },
  { name: 'Arrow Down Right Circle Fill', class: 'bi-arrow-down-right-circle-fill' },
  { name: 'Arrow Down Right Square', class: 'bi-arrow-down-right-square' },
  { name: 'Arrow Down Right Square Fill', class: 'bi-arrow-down-right-square-fill' },
  { name: 'Arrow Left Right', class: 'bi-arrow-left-right' },
  { name: 'Arrow Through Heart', class: 'bi-arrow-through-heart' },
  { name: 'Arrow Through Heart Fill', class: 'bi-arrow-through-heart-fill' },
  { name: 'Arrow Up Left', class: 'bi-arrow-up-left' },
  { name: 'Arrow Up Left Circle', class: 'bi-arrow-up-left-circle' },
  { name: 'Arrow Up Left Circle Fill', class: 'bi-arrow-up-left-circle-fill' },
  { name: 'Arrow Up Left Square', class: 'bi-arrow-up-left-square' },
  { name: 'Arrow Up Left Square Fill', class: 'bi-arrow-up-left-square-fill' },
  { name: 'Arrow Up Right', class: 'bi-arrow-up-right' },
  { name: 'Arrow Up Right Circle', class: 'bi-arrow-up-right-circle' },
  { name: 'Arrow Up Right Circle Fill', class: 'bi-arrow-up-right-circle-fill' },
  { name: 'Arrow Up Right Square', class: 'bi-arrow-up-right-square' },
  { name: 'Arrow Up Right Square Fill', class: 'bi-arrow-up-right-square-fill' },
  { name: 'Arrows', class: 'bi-arrows' },
  { name: 'Arrows Collapse Vertical', class: 'bi-arrows-collapse-vertical' },
  { name: 'Arrows Expand Vertical', class: 'bi-arrows-expand-vertical' },
  { name: 'Arrows Vertical', class: 'bi-arrows-vertical' },
  
  // 購物車與商店
  { name: 'Cart', class: 'bi-cart' },
  { name: 'Cart Check', class: 'bi-cart-check' },
  { name: 'Cart Check Fill', class: 'bi-cart-check-fill' },
  { name: 'Cart Dash', class: 'bi-cart-dash' },
  { name: 'Cart Dash Fill', class: 'bi-cart-dash-fill' },
  { name: 'Cart Fill', class: 'bi-cart-fill' },
  { name: 'Cart Plus', class: 'bi-cart-plus' },
  { name: 'Cart Plus Fill', class: 'bi-cart-plus-fill' },
  { name: 'Cart X', class: 'bi-cart-x' },
  { name: 'Cart X Fill', class: 'bi-cart-x-fill' },
  { name: 'Cart2', class: 'bi-cart2' },
  { name: 'Cart3', class: 'bi-cart3' },
  { name: 'Cart4', class: 'bi-cart4' },
  { name: 'Shop', class: 'bi-shop' },
  { name: 'Shop Window', class: 'bi-shop-window' },
  { name: 'Bag', class: 'bi-bag' },
  { name: 'Bag Check', class: 'bi-bag-check' },
  { name: 'Bag Check Fill', class: 'bi-bag-check-fill' },
  { name: 'Bag Dash', class: 'bi-bag-dash' },
  { name: 'Bag Dash Fill', class: 'bi-bag-dash-fill' },
  { name: 'Bag Fill', class: 'bi-bag-fill' },
  { name: 'Bag Heart', class: 'bi-bag-heart' },
  { name: 'Bag Heart Fill', class: 'bi-bag-heart-fill' },
  { name: 'Bag Plus', class: 'bi-bag-plus' },
  { name: 'Bag Plus Fill', class: 'bi-bag-plus-fill' },
  { name: 'Bag X', class: 'bi-bag-x' },
  { name: 'Bag X Fill', class: 'bi-bag-x-fill' },
  { name: 'Basket', class: 'bi-basket' },
  { name: 'Basket Fill', class: 'bi-basket-fill' },
  { name: 'Basket2', class: 'bi-basket2' },
  { name: 'Basket2 Fill', class: 'bi-basket2-fill' },
  { name: 'Basket3', class: 'bi-basket3' },
  { name: 'Basket3 Fill', class: 'bi-basket3-fill' }
]

export const categoryInfo = {
  id: 'general',
  name: '通用圖標',
  description: '最常用的基礎圖標',
  priority: 'immediate'
}