// Bootstrap Icons - 其他分類
// 包含：商業、地理、工具、運動、交通等其他圖標

export const othersIcons = [
  // 商業相關
  { name: 'Cart', class: 'bi-cart' },
  { name: 'Cart Fill', class: 'bi-cart-fill' },
  { name: 'Cart2', class: 'bi-cart2' },
  { name: 'Cart3', class: 'bi-cart3' },
  { name: 'Cart4', class: 'bi-cart4' },
  { name: 'Cart Check', class: 'bi-cart-check' },
  { name: 'Cart Check Fill', class: 'bi-cart-check-fill' },
  { name: 'Cart Dash', class: 'bi-cart-dash' },
  { name: 'Cart Dash Fill', class: 'bi-cart-dash-fill' },
  { name: 'Cart Plus', class: 'bi-cart-plus' },
  { name: 'Cart Plus Fill', class: 'bi-cart-plus-fill' },
  { name: 'Cart X', class: 'bi-cart-x' },
  { name: 'Cart X Fill', class: 'bi-cart-x-fill' },
  { name: 'Cash', class: 'bi-cash' },
  { name: 'Cash Stack', class: 'bi-cash-stack' },
  { name: 'Credit Card', class: 'bi-credit-card' },
  { name: 'Credit Card 2 Back', class: 'bi-credit-card-2-back' },
  { name: 'Credit Card 2 Back Fill', class: 'bi-credit-card-2-back-fill' },
  { name: 'Credit Card 2 Front', class: 'bi-credit-card-2-front' },
  { name: 'Credit Card 2 Front Fill', class: 'bi-credit-card-2-front-fill' },
  { name: 'Credit Card Fill', class: 'bi-credit-card-fill' },
  { name: 'Currency Bitcoin', class: 'bi-currency-bitcoin' },
  { name: 'Currency Dollar', class: 'bi-currency-dollar' },
  { name: 'Currency Euro', class: 'bi-currency-euro' },
  { name: 'Currency Exchange', class: 'bi-currency-exchange' },
  { name: 'Currency Pound', class: 'bi-currency-pound' },
  { name: 'Currency Yen', class: 'bi-currency-yen' },
  
  // 地理位置
  { name: 'Geo', class: 'bi-geo' },
  { name: 'Geo Alt', class: 'bi-geo-alt' },
  { name: 'Geo Alt Fill', class: 'bi-geo-alt-fill' },
  { name: 'Geo Fill', class: 'bi-geo-fill' },
  { name: 'Map', class: 'bi-map' },
  { name: 'Map Fill', class: 'bi-map-fill' },
  { name: 'Pin', class: 'bi-pin' },
  { name: 'Pin Angle', class: 'bi-pin-angle' },
  { name: 'Pin Angle Fill', class: 'bi-pin-angle-fill' },
  { name: 'Pin Fill', class: 'bi-pin-fill' },
  { name: 'Pin Map', class: 'bi-pin-map' },
  { name: 'Pin Map Fill', class: 'bi-pin-map-fill' },
  { name: 'Signpost', class: 'bi-signpost' },
  { name: 'Signpost 2', class: 'bi-signpost-2' },
  { name: 'Signpost 2 Fill', class: 'bi-signpost-2-fill' },
  { name: 'Signpost Fill', class: 'bi-signpost-fill' },
  { name: 'Signpost Split', class: 'bi-signpost-split' },
  { name: 'Signpost Split Fill', class: 'bi-signpost-split-fill' },
  
  // 天氣
  { name: 'Brightness High', class: 'bi-brightness-high' },
  { name: 'Brightness High Fill', class: 'bi-brightness-high-fill' },
  { name: 'Brightness Low', class: 'bi-brightness-low' },
  { name: 'Brightness Low Fill', class: 'bi-brightness-low-fill' },
  { name: 'Cloud', class: 'bi-cloud' },
  { name: 'Cloud Arrow Down', class: 'bi-cloud-arrow-down' },
  { name: 'Cloud Arrow Down Fill', class: 'bi-cloud-arrow-down-fill' },
  { name: 'Cloud Arrow Up', class: 'bi-cloud-arrow-up' },
  { name: 'Cloud Arrow Up Fill', class: 'bi-cloud-arrow-up-fill' },
  { name: 'Cloud Check', class: 'bi-cloud-check' },
  { name: 'Cloud Check Fill', class: 'bi-cloud-check-fill' },
  { name: 'Cloud Download', class: 'bi-cloud-download' },
  { name: 'Cloud Download Fill', class: 'bi-cloud-download-fill' },
  { name: 'Cloud Drizzle', class: 'bi-cloud-drizzle' },
  { name: 'Cloud Drizzle Fill', class: 'bi-cloud-drizzle-fill' },
  { name: 'Cloud Fill', class: 'bi-cloud-fill' },
  { name: 'Cloud Fog', class: 'bi-cloud-fog' },
  { name: 'Cloud Fog Fill', class: 'bi-cloud-fog-fill' },
  { name: 'Cloud Fog2', class: 'bi-cloud-fog2' },
  { name: 'Cloud Fog2 Fill', class: 'bi-cloud-fog2-fill' },
  { name: 'Cloud Hail', class: 'bi-cloud-hail' },
  { name: 'Cloud Hail Fill', class: 'bi-cloud-hail-fill' },
  { name: 'Cloud Lightning', class: 'bi-cloud-lightning' },
  { name: 'Cloud Lightning Fill', class: 'bi-cloud-lightning-fill' },
  { name: 'Cloud Lightning Rain', class: 'bi-cloud-lightning-rain' },
  { name: 'Cloud Lightning Rain Fill', class: 'bi-cloud-lightning-rain-fill' },
  { name: 'Cloud Minus', class: 'bi-cloud-minus' },
  { name: 'Cloud Minus Fill', class: 'bi-cloud-minus-fill' },
  { name: 'Cloud Moon', class: 'bi-cloud-moon' },
  { name: 'Cloud Moon Fill', class: 'bi-cloud-moon-fill' },
  { name: 'Cloud Plus', class: 'bi-cloud-plus' },
  { name: 'Cloud Plus Fill', class: 'bi-cloud-plus-fill' },
  { name: 'Cloud Rain', class: 'bi-cloud-rain' },
  { name: 'Cloud Rain Fill', class: 'bi-cloud-rain-fill' },
  { name: 'Cloud Rain Heavy', class: 'bi-cloud-rain-heavy' },
  { name: 'Cloud Rain Heavy Fill', class: 'bi-cloud-rain-heavy-fill' },
  { name: 'Cloud Slash', class: 'bi-cloud-slash' },
  { name: 'Cloud Slash Fill', class: 'bi-cloud-slash-fill' },
  { name: 'Cloud Snow', class: 'bi-cloud-snow' },
  { name: 'Cloud Snow Fill', class: 'bi-cloud-snow-fill' },
  { name: 'Cloud Sun', class: 'bi-cloud-sun' },
  { name: 'Cloud Sun Fill', class: 'bi-cloud-sun-fill' },
  { name: 'Cloud Upload', class: 'bi-cloud-upload' },
  { name: 'Cloud Upload Fill', class: 'bi-cloud-upload-fill' },
  { name: 'Clouds', class: 'bi-clouds' },
  { name: 'Clouds Fill', class: 'bi-clouds-fill' },
  { name: 'Cloudy', class: 'bi-cloudy' },
  { name: 'Cloudy Fill', class: 'bi-cloudy-fill' },
  { name: 'Lightning', class: 'bi-lightning' },
  { name: 'Lightning Charge', class: 'bi-lightning-charge' },
  { name: 'Lightning Charge Fill', class: 'bi-lightning-charge-fill' },
  { name: 'Lightning Fill', class: 'bi-lightning-fill' },
  { name: 'Moon', class: 'bi-moon' },
  { name: 'Moon Fill', class: 'bi-moon-fill' },
  { name: 'Moon Stars', class: 'bi-moon-stars' },
  { name: 'Moon Stars Fill', class: 'bi-moon-stars-fill' },
  { name: 'Sun', class: 'bi-sun' },
  { name: 'Sun Fill', class: 'bi-sun-fill' },
  { name: 'Sunrise', class: 'bi-sunrise' },
  { name: 'Sunrise Fill', class: 'bi-sunrise-fill' },
  { name: 'Sunset', class: 'bi-sunset' },
  { name: 'Sunset Fill', class: 'bi-sunset-fill' },
  { name: 'Thermometer', class: 'bi-thermometer' },
  { name: 'Thermometer Half', class: 'bi-thermometer-half' },
  { name: 'Thermometer High', class: 'bi-thermometer-high' },
  { name: 'Thermometer Low', class: 'bi-thermometer-low' },
  { name: 'Thermometer Snow', class: 'bi-thermometer-snow' },
  { name: 'Thermometer Sun', class: 'bi-thermometer-sun' },
  { name: 'Tornado', class: 'bi-tornado' },
  { name: 'Tropical Storm', class: 'bi-tropical-storm' },
  { name: 'Umbrella', class: 'bi-umbrella' },
  { name: 'Umbrella Fill', class: 'bi-umbrella-fill' },
  { name: 'Wind', class: 'bi-wind' },
  
  
  // 時間相關
  { name: 'Clock', class: 'bi-clock' },
  { name: 'Clock Fill', class: 'bi-clock-fill' },
  { name: 'Clock History', class: 'bi-clock-history' },
  { name: 'Stopwatch', class: 'bi-stopwatch' },
  { name: 'Stopwatch Fill', class: 'bi-stopwatch-fill' },
  { name: 'Watch', class: 'bi-watch' },
  { name: 'Calendar', class: 'bi-calendar' },
  { name: 'Calendar2', class: 'bi-calendar2' },
  { name: 'Calendar2 Check', class: 'bi-calendar2-check' },
  { name: 'Calendar2 Check Fill', class: 'bi-calendar2-check-fill' },
  { name: 'Calendar2 Date', class: 'bi-calendar2-date' },
  { name: 'Calendar2 Date Fill', class: 'bi-calendar2-date-fill' },
  { name: 'Calendar2 Day', class: 'bi-calendar2-day' },
  { name: 'Calendar2 Day Fill', class: 'bi-calendar2-day-fill' },
  { name: 'Calendar2 Event', class: 'bi-calendar2-event' },
  { name: 'Calendar2 Event Fill', class: 'bi-calendar2-event-fill' },
  { name: 'Calendar2 Fill', class: 'bi-calendar2-fill' },
  { name: 'Calendar2 Heart', class: 'bi-calendar2-heart' },
  { name: 'Calendar2 Heart Fill', class: 'bi-calendar2-heart-fill' },
  { name: 'Calendar2 Minus', class: 'bi-calendar2-minus' },
  { name: 'Calendar2 Minus Fill', class: 'bi-calendar2-minus-fill' },
  { name: 'Calendar2 Month', class: 'bi-calendar2-month' },
  { name: 'Calendar2 Month Fill', class: 'bi-calendar2-month-fill' },
  { name: 'Calendar2 Plus', class: 'bi-calendar2-plus' },
  { name: 'Calendar2 Plus Fill', class: 'bi-calendar2-plus-fill' },
  { name: 'Calendar2 Range', class: 'bi-calendar2-range' },
  { name: 'Calendar2 Range Fill', class: 'bi-calendar2-range-fill' },
  { name: 'Calendar2 Week', class: 'bi-calendar2-week' },
  { name: 'Calendar2 Week Fill', class: 'bi-calendar2-week-fill' },
  { name: 'Calendar2 X', class: 'bi-calendar2-x' },
  { name: 'Calendar2 X Fill', class: 'bi-calendar2-x-fill' },
  { name: 'Calendar3', class: 'bi-calendar3' },
  { name: 'Calendar3 Event', class: 'bi-calendar3-event' },
  { name: 'Calendar3 Event Fill', class: 'bi-calendar3-event-fill' },
  { name: 'Calendar3 Fill', class: 'bi-calendar3-fill' },
  { name: 'Calendar3 Range', class: 'bi-calendar3-range' },
  { name: 'Calendar3 Range Fill', class: 'bi-calendar3-range-fill' },
  { name: 'Calendar3 Week', class: 'bi-calendar3-week' },
  { name: 'Calendar3 Week Fill', class: 'bi-calendar3-week-fill' },
  { name: 'Calendar4', class: 'bi-calendar4' },
  { name: 'Calendar4 Event', class: 'bi-calendar4-event' },
  { name: 'Calendar4 Range', class: 'bi-calendar4-range' },
  { name: 'Calendar4 Week', class: 'bi-calendar4-week' },
  { name: 'Calendar Check', class: 'bi-calendar-check' },
  { name: 'Calendar Check Fill', class: 'bi-calendar-check-fill' },
  { name: 'Calendar Date', class: 'bi-calendar-date' },
  { name: 'Calendar Date Fill', class: 'bi-calendar-date-fill' },
  { name: 'Calendar Day', class: 'bi-calendar-day' },
  { name: 'Calendar Day Fill', class: 'bi-calendar-day-fill' },
  { name: 'Calendar Event', class: 'bi-calendar-event' },
  { name: 'Calendar Event Fill', class: 'bi-calendar-event-fill' },
  { name: 'Calendar Fill', class: 'bi-calendar-fill' },
  { name: 'Calendar Heart', class: 'bi-calendar-heart' },
  { name: 'Calendar Heart Fill', class: 'bi-calendar-heart-fill' },
  { name: 'Calendar Minus', class: 'bi-calendar-minus' },
  { name: 'Calendar Minus Fill', class: 'bi-calendar-minus-fill' },
  { name: 'Calendar Month', class: 'bi-calendar-month' },
  { name: 'Calendar Month Fill', class: 'bi-calendar-month-fill' },
  { name: 'Calendar Plus', class: 'bi-calendar-plus' },
  { name: 'Calendar Plus Fill', class: 'bi-calendar-plus-fill' },
  { name: 'Calendar Range', class: 'bi-calendar-range' },
  { name: 'Calendar Range Fill', class: 'bi-calendar-range-fill' },
  { name: 'Calendar Week', class: 'bi-calendar-week' },
  { name: 'Calendar Week Fill', class: 'bi-calendar-week-fill' },
  { name: 'Calendar X', class: 'bi-calendar-x' },
  { name: 'Calendar X Fill', class: 'bi-calendar-x-fill' },
  
  
  // 交通工具
  { name: 'Bus Front', class: 'bi-bus-front' },
  { name: 'Bus Front Fill', class: 'bi-bus-front-fill' },
  { name: 'Car Front', class: 'bi-car-front' },
  { name: 'Car Front Fill', class: 'bi-car-front-fill' },
  { name: 'Truck', class: 'bi-truck' },
  { name: 'Truck Flatbed', class: 'bi-truck-flatbed' },
  { name: 'Truck Front', class: 'bi-truck-front' },
  { name: 'Truck Front Fill', class: 'bi-truck-front-fill' },
  { name: 'Airplane', class: 'bi-airplane' },
  { name: 'Airplane Engines', class: 'bi-airplane-engines' },
  { name: 'Airplane Engines Fill', class: 'bi-airplane-engines-fill' },
  { name: 'Airplane Fill', class: 'bi-airplane-fill' },
  { name: 'Train Front', class: 'bi-train-front' },
  { name: 'Train Front Fill', class: 'bi-train-front-fill' },
  { name: 'Train Freight Front', class: 'bi-train-freight-front' },
  { name: 'Train Freight Front Fill', class: 'bi-train-freight-front-fill' },
  { name: 'Train Lightrail Front', class: 'bi-train-lightrail-front' },
  { name: 'Train Lightrail Front Fill', class: 'bi-train-lightrail-front-fill' },
  { name: 'Submarine', class: 'bi-submarine' },
  { name: 'Taxi Front', class: 'bi-taxi-front' },
  { name: 'Taxi Front Fill', class: 'bi-taxi-front-fill' },
  { name: 'Ev Front', class: 'bi-ev-front' },
  { name: 'Ev Front Fill', class: 'bi-ev-front-fill' },
  { name: 'Ev Station', class: 'bi-ev-station' },
  { name: 'Ev Station Fill', class: 'bi-ev-station-fill' },
  { name: 'Fuel Pump', class: 'bi-fuel-pump' },
  { name: 'Fuel Pump Fill', class: 'bi-fuel-pump-fill' },
  { name: 'Fuel Pump Diesel', class: 'bi-fuel-pump-diesel' },
  { name: 'Fuel Pump Diesel Fill', class: 'bi-fuel-pump-diesel-fill' },
  
  // 健康與醫療
  { name: 'Heart', class: 'bi-heart' },
  { name: 'Heart Fill', class: 'bi-heart-fill' },
  { name: 'Heart Half', class: 'bi-heart-half' },
  { name: 'Heart Arrow', class: 'bi-heart-arrow' },
  { name: 'Heart Pulse', class: 'bi-heart-pulse' },
  { name: 'Heart Pulse Fill', class: 'bi-heart-pulse-fill' },
  { name: 'Bandaid', class: 'bi-bandaid' },
  { name: 'Bandaid Fill', class: 'bi-bandaid-fill' },
  { name: 'Capsule', class: 'bi-capsule' },
  { name: 'Capsule Pill', class: 'bi-capsule-pill' },
  { name: 'Hospital', class: 'bi-hospital' },
  { name: 'Hospital Fill', class: 'bi-hospital-fill' },
  { name: 'Plus', class: 'bi-plus' },
  { name: 'Plus Circle', class: 'bi-plus-circle' },
  { name: 'Plus Circle Fill', class: 'bi-plus-circle-fill' },
  { name: 'Plus Square', class: 'bi-plus-square' },
  { name: 'Plus Square Fill', class: 'bi-plus-square-fill' },
  
  // 運動與健身擴展
  { name: 'Bicycle', class: 'bi-bicycle' },
  { name: 'Scooter', class: 'bi-scooter' },
  { name: 'Activity', class: 'bi-activity' },
  
  // 家具與物品
  { name: 'House', class: 'bi-house' },
  { name: 'House Fill', class: 'bi-house-fill' },
  { name: 'House Door', class: 'bi-house-door' },
  { name: 'House Door Fill', class: 'bi-house-door-fill' },
  { name: 'House Heart', class: 'bi-house-heart' },
  { name: 'House Heart Fill', class: 'bi-house-heart-fill' },
  { name: 'Building', class: 'bi-building' },
  { name: 'Building Fill', class: 'bi-building-fill' },
  { name: 'Buildings', class: 'bi-buildings' },
  { name: 'Buildings Fill', class: 'bi-buildings-fill' },
  
  // 安全與保護
  { name: 'Shield', class: 'bi-shield' },
  { name: 'Shield Fill', class: 'bi-shield-fill' },
  { name: 'Shield Check', class: 'bi-shield-check' },
  { name: 'Shield Check Fill', class: 'bi-shield-check-fill' },
  { name: 'Shield Exclamation', class: 'bi-shield-exclamation' },
  { name: 'Shield Exclamation Fill', class: 'bi-shield-exclamation-fill' },
  { name: 'Shield Fill Check', class: 'bi-shield-fill-check' },
  { name: 'Shield Fill Exclamation', class: 'bi-shield-fill-exclamation' },
  { name: 'Shield Fill Minus', class: 'bi-shield-fill-minus' },
  { name: 'Shield Fill Plus', class: 'bi-shield-fill-plus' },
  { name: 'Shield Fill X', class: 'bi-shield-fill-x' },
  { name: 'Shield Lock', class: 'bi-shield-lock' },
  { name: 'Shield Lock Fill', class: 'bi-shield-lock-fill' },
  { name: 'Shield Minus', class: 'bi-shield-minus' },
  { name: 'Shield Minus Fill', class: 'bi-shield-minus-fill' },
  { name: 'Shield Plus', class: 'bi-shield-plus' },
  { name: 'Shield Plus Fill', class: 'bi-shield-plus-fill' },
  { name: 'Shield Slash', class: 'bi-shield-slash' },
  { name: 'Shield Slash Fill', class: 'bi-shield-slash-fill' },
  { name: 'Shield X', class: 'bi-shield-x' },
  { name: 'Shield X Fill', class: 'bi-shield-x-fill' },
  
  // 食物與飲料
  { name: 'Cup', class: 'bi-cup' },
  { name: 'Cup Fill', class: 'bi-cup-fill' },
  { name: 'Cup Hot', class: 'bi-cup-hot' },
  { name: 'Cup Hot Fill', class: 'bi-cup-hot-fill' },
  { name: 'Cup Straw', class: 'bi-cup-straw' },
  
  // 賞勵與成就
  { name: 'Award', class: 'bi-award' },
  { name: 'Award Fill', class: 'bi-award-fill' },
  { name: 'Trophy', class: 'bi-trophy' },
  { name: 'Trophy Fill', class: 'bi-trophy-fill' },
  { name: 'Star', class: 'bi-star' },
  { name: 'Star Fill', class: 'bi-star-fill' },
  { name: 'Star Half', class: 'bi-star-half' },
  { name: 'Stars', class: 'bi-stars' },
  
  // 遊戲與娛樂
  { name: 'Controller', class: 'bi-controller' },
  { name: 'Dice 1', class: 'bi-dice-1' },
  { name: 'Dice 1 Fill', class: 'bi-dice-1-fill' },
  { name: 'Dice 2', class: 'bi-dice-2' },
  { name: 'Dice 2 Fill', class: 'bi-dice-2-fill' },
  { name: 'Dice 3', class: 'bi-dice-3' },
  { name: 'Dice 3 Fill', class: 'bi-dice-3-fill' },
  { name: 'Dice 4', class: 'bi-dice-4' },
  { name: 'Dice 4 Fill', class: 'bi-dice-4-fill' },
  { name: 'Dice 5', class: 'bi-dice-5' },
  { name: 'Dice 5 Fill', class: 'bi-dice-5-fill' },
  { name: 'Dice 6', class: 'bi-dice-6' },
  { name: 'Dice 6 Fill', class: 'bi-dice-6-fill' },
  { name: 'Suit Club', class: 'bi-suit-club' },
  { name: 'Suit Club Fill', class: 'bi-suit-club-fill' },
  { name: 'Suit Diamond', class: 'bi-suit-diamond' },
  { name: 'Suit Diamond Fill', class: 'bi-suit-diamond-fill' },
  { name: 'Suit Heart', class: 'bi-suit-heart' },
  { name: 'Suit Heart Fill', class: 'bi-suit-heart-fill' },
  { name: 'Suit Spade', class: 'bi-suit-spade' },
  { name: 'Suit Spade Fill', class: 'bi-suit-spade-fill' },
  
  // 工具擴展
  { name: 'Hammer', class: 'bi-hammer' },
  { name: 'Screwdriver', class: 'bi-screwdriver' },
  { name: 'Tools', class: 'bi-tools' },
  { name: 'Wrench', class: 'bi-wrench' },
  { name: 'Wrench Adjustable', class: 'bi-wrench-adjustable' },
  { name: 'Wrench Adjustable Circle', class: 'bi-wrench-adjustable-circle' },
  { name: 'Wrench Adjustable Circle Fill', class: 'bi-wrench-adjustable-circle-fill' },
  
  // 科技與電子產品
  { name: 'Smartwatch', class: 'bi-smartwatch' },
  { name: 'Watch', class: 'bi-watch' },
  { name: 'Tablet', class: 'bi-tablet' },
  { name: 'Tablet Fill', class: 'bi-tablet-fill' },
  { name: 'Tablet Landscape', class: 'bi-tablet-landscape' },
  { name: 'Tablet Landscape Fill', class: 'bi-tablet-landscape-fill' },
  { name: 'Laptop', class: 'bi-laptop' },
  { name: 'Laptop Fill', class: 'bi-laptop-fill' },
  { name: 'Pc', class: 'bi-pc' },
  { name: 'Pc Display', class: 'bi-pc-display' },
  { name: 'Pc Display Horizontal', class: 'bi-pc-display-horizontal' },
  { name: 'Mouse', class: 'bi-mouse' },
  { name: 'Mouse Fill', class: 'bi-mouse-fill' },
  { name: 'Mouse2', class: 'bi-mouse2' },
  { name: 'Mouse2 Fill', class: 'bi-mouse2-fill' },
  { name: 'Mouse3', class: 'bi-mouse3' },
  { name: 'Mouse3 Fill', class: 'bi-mouse3-fill' },
  
  // 發電與電力
  { name: 'Battery', class: 'bi-battery' },
  { name: 'Battery Charging', class: 'bi-battery-charging' },
  { name: 'Battery Full', class: 'bi-battery-full' },
  { name: 'Battery Half', class: 'bi-battery-half' },
  { name: 'Power', class: 'bi-power' },
  { name: 'Plug', class: 'bi-plug' },
  { name: 'Plug Fill', class: 'bi-plug-fill' },
  { name: 'Lightning', class: 'bi-lightning' },
  { name: 'Lightning Fill', class: 'bi-lightning-fill' },
  { name: 'Lightning Charge', class: 'bi-lightning-charge' },
  { name: 'Lightning Charge Fill', class: 'bi-lightning-charge-fill' }
]

export const categoryInfo = {
  id: 'others',
  name: '其他圖標',
  description: '商業、地理、工具、天氣等其他圖標',
  priority: 'low'
}