// 完整的 Bootstrap Icons 列表（按官網順序）
// 參考：https://icons.getbootstrap.com/
export const allBootstrapIcons = [
  // 0-9
  { name: '0 Circle', class: 'bi-0-circle' },
  { name: '0 Circle Fill', class: 'bi-0-circle-fill' },
  { name: '0 Square', class: 'bi-0-square' },
  { name: '0 Square Fill', class: 'bi-0-square-fill' },
  { name: '1 Circle', class: 'bi-1-circle' },
  { name: '1 Circle Fill', class: 'bi-1-circle-fill' },
  { name: '1 Square', class: 'bi-1-square' },
  { name: '1 Square Fill', class: 'bi-1-square-fill' },
  { name: '2 Circle', class: 'bi-2-circle' },
  { name: '2 Circle Fill', class: 'bi-2-circle-fill' },
  { name: '2 Square', class: 'bi-2-square' },
  { name: '2 Square Fill', class: 'bi-2-square-fill' },
  { name: '3 Circle', class: 'bi-3-circle' },
  { name: '3 Circle Fill', class: 'bi-3-circle-fill' },
  { name: '3 Square', class: 'bi-3-square' },
  { name: '3 Square Fill', class: 'bi-3-square-fill' },
  { name: '4 Circle', class: 'bi-4-circle' },
  { name: '4 Circle Fill', class: 'bi-4-circle-fill' },
  { name: '4 Square', class: 'bi-4-square' },
  { name: '4 Square Fill', class: 'bi-4-square-fill' },
  { name: '5 Circle', class: 'bi-5-circle' },
  { name: '5 Circle Fill', class: 'bi-5-circle-fill' },
  { name: '5 Square', class: 'bi-5-square' },
  { name: '5 Square Fill', class: 'bi-5-square-fill' },
  { name: '6 Circle', class: 'bi-6-circle' },
  { name: '6 Circle Fill', class: 'bi-6-circle-fill' },
  { name: '6 Square', class: 'bi-6-square' },
  { name: '6 Square Fill', class: 'bi-6-square-fill' },
  { name: '7 Circle', class: 'bi-7-circle' },
  { name: '7 Circle Fill', class: 'bi-7-circle-fill' },
  { name: '7 Square', class: 'bi-7-square' },
  { name: '7 Square Fill', class: 'bi-7-square-fill' },
  { name: '8 Circle', class: 'bi-8-circle' },
  { name: '8 Circle Fill', class: 'bi-8-circle-fill' },
  { name: '8 Square', class: 'bi-8-square' },
  { name: '8 Square Fill', class: 'bi-8-square-fill' },
  { name: '9 Circle', class: 'bi-9-circle' },
  { name: '9 Circle Fill', class: 'bi-9-circle-fill' },
  { name: '9 Square', class: 'bi-9-square' },
  { name: '9 Square Fill', class: 'bi-9-square-fill' },
  { name: '123', class: 'bi-123' },
  
  // A
  { name: 'Activity', class: 'bi-activity' },
  { name: 'Airplane', class: 'bi-airplane' },
  { name: 'Airplane Engines', class: 'bi-airplane-engines' },
  { name: 'Airplane Engines Fill', class: 'bi-airplane-engines-fill' },
  { name: 'Airplane Fill', class: 'bi-airplane-fill' },
  { name: 'Alarm', class: 'bi-alarm' },
  { name: 'Alarm Fill', class: 'bi-alarm-fill' },
  { name: 'Alexa', class: 'bi-alexa' },
  { name: 'Align Bottom', class: 'bi-align-bottom' },
  { name: 'Align Center', class: 'bi-align-center' },
  { name: 'Align End', class: 'bi-align-end' },
  { name: 'Align Middle', class: 'bi-align-middle' },
  { name: 'Align Start', class: 'bi-align-start' },
  { name: 'Align Top', class: 'bi-align-top' },
  { name: 'Alipay', class: 'bi-alipay' },
  { name: 'Alt', class: 'bi-alt' },
  { name: 'Amazon', class: 'bi-amazon' },
  { name: 'Android', class: 'bi-android' },
  { name: 'Android2', class: 'bi-android2' },
  { name: 'App', class: 'bi-app' },
  { name: 'App Indicator', class: 'bi-app-indicator' },
  { name: 'Apple', class: 'bi-apple' },
  { name: 'Archive', class: 'bi-archive' },
  { name: 'Archive Fill', class: 'bi-archive-fill' },
  { name: 'Arrow 90deg Down', class: 'bi-arrow-90deg-down' },
  { name: 'Arrow 90deg Left', class: 'bi-arrow-90deg-left' },
  { name: 'Arrow 90deg Right', class: 'bi-arrow-90deg-right' },
  { name: 'Arrow 90deg Up', class: 'bi-arrow-90deg-up' },
  { name: 'Arrow Bar Down', class: 'bi-arrow-bar-down' },
  { name: 'Arrow Bar Left', class: 'bi-arrow-bar-left' },
  { name: 'Arrow Bar Right', class: 'bi-arrow-bar-right' },
  { name: 'Arrow Bar Up', class: 'bi-arrow-bar-up' },
  { name: 'Arrow Clockwise', class: 'bi-arrow-clockwise' },
  { name: 'Arrow Counterclockwise', class: 'bi-arrow-counterclockwise' },
  { name: 'Arrow Down', class: 'bi-arrow-down' },
  { name: 'Arrow Down Circle', class: 'bi-arrow-down-circle' },
  { name: 'Arrow Down Circle Fill', class: 'bi-arrow-down-circle-fill' },
  { name: 'Arrow Down Left', class: 'bi-arrow-down-left' },
  { name: 'Arrow Down Left Circle', class: 'bi-arrow-down-left-circle' },
  { name: 'Arrow Down Left Circle Fill', class: 'bi-arrow-down-left-circle-fill' },
  { name: 'Arrow Down Left Square', class: 'bi-arrow-down-left-square' },
  { name: 'Arrow Down Left Square Fill', class: 'bi-arrow-down-left-square-fill' },
  { name: 'Arrow Down Right', class: 'bi-arrow-down-right' },
  { name: 'Arrow Down Right Circle', class: 'bi-arrow-down-right-circle' },
  { name: 'Arrow Down Right Circle Fill', class: 'bi-arrow-down-right-circle-fill' },
  { name: 'Arrow Down Right Square', class: 'bi-arrow-down-right-square' },
  { name: 'Arrow Down Right Square Fill', class: 'bi-arrow-down-right-square-fill' },
  { name: 'Arrow Down Short', class: 'bi-arrow-down-short' },
  { name: 'Arrow Down Square', class: 'bi-arrow-down-square' },
  { name: 'Arrow Down Square Fill', class: 'bi-arrow-down-square-fill' },
  { name: 'Arrow Down Up', class: 'bi-arrow-down-up' },
  { name: 'Arrow Left', class: 'bi-arrow-left' },
  { name: 'Arrow Left Circle', class: 'bi-arrow-left-circle' },
  { name: 'Arrow Left Circle Fill', class: 'bi-arrow-left-circle-fill' },
  { name: 'Arrow Left Right', class: 'bi-arrow-left-right' },
  { name: 'Arrow Left Short', class: 'bi-arrow-left-short' },
  { name: 'Arrow Left Square', class: 'bi-arrow-left-square' },
  { name: 'Arrow Left Square Fill', class: 'bi-arrow-left-square-fill' },
  { name: 'Arrow Repeat', class: 'bi-arrow-repeat' },
  { name: 'Arrow Return Left', class: 'bi-arrow-return-left' },
  { name: 'Arrow Return Right', class: 'bi-arrow-return-right' },
  { name: 'Arrow Right', class: 'bi-arrow-right' },
  { name: 'Arrow Right Circle', class: 'bi-arrow-right-circle' },
  { name: 'Arrow Right Circle Fill', class: 'bi-arrow-right-circle-fill' },
  { name: 'Arrow Right Short', class: 'bi-arrow-right-short' },
  { name: 'Arrow Right Square', class: 'bi-arrow-right-square' },
  { name: 'Arrow Right Square Fill', class: 'bi-arrow-right-square-fill' },
  { name: 'Arrow Through Heart', class: 'bi-arrow-through-heart' },
  { name: 'Arrow Through Heart Fill', class: 'bi-arrow-through-heart-fill' },
  { name: 'Arrow Up', class: 'bi-arrow-up' },
  { name: 'Arrow Up Circle', class: 'bi-arrow-up-circle' },
  { name: 'Arrow Up Circle Fill', class: 'bi-arrow-up-circle-fill' },
  { name: 'Arrow Up Left', class: 'bi-arrow-up-left' },
  { name: 'Arrow Up Left Circle', class: 'bi-arrow-up-left-circle' },
  { name: 'Arrow Up Left Circle Fill', class: 'bi-arrow-up-left-circle-fill' },
  { name: 'Arrow Up Left Square', class: 'bi-arrow-up-left-square' },
  { name: 'Arrow Up Left Square Fill', class: 'bi-arrow-up-left-square-fill' },
  { name: 'Arrow Up Right', class: 'bi-arrow-up-right' },
  { name: 'Arrow Up Right Circle', class: 'bi-arrow-up-right-circle' },
  { name: 'Arrow Up Right Circle Fill', class: 'bi-arrow-up-right-circle-fill' },
  { name: 'Arrow Up Right Square', class: 'bi-arrow-up-right-square' },
  { name: 'Arrow Up Right Square Fill', class: 'bi-arrow-up-right-square-fill' },
  { name: 'Arrow Up Short', class: 'bi-arrow-up-short' },
  { name: 'Arrow Up Square', class: 'bi-arrow-up-square' },
  { name: 'Arrow Up Square Fill', class: 'bi-arrow-up-square-fill' },
  { name: 'Arrows', class: 'bi-arrows' },
  { name: 'Arrows Angle Contract', class: 'bi-arrows-angle-contract' },
  { name: 'Arrows Angle Expand', class: 'bi-arrows-angle-expand' },
  { name: 'Arrows Collapse', class: 'bi-arrows-collapse' },
  { name: 'Arrows Expand', class: 'bi-arrows-expand' },
  { name: 'Arrows Fullscreen', class: 'bi-arrows-fullscreen' },
  { name: 'Arrows Move', class: 'bi-arrows-move' },
  { name: 'Arrows Vertical', class: 'bi-arrows-vertical' },
  { name: 'Aspect Ratio', class: 'bi-aspect-ratio' },
  { name: 'Aspect Ratio Fill', class: 'bi-aspect-ratio-fill' },
  { name: 'Asterisk', class: 'bi-asterisk' },
  { name: 'At', class: 'bi-at' },
  { name: 'Award', class: 'bi-award' },
  { name: 'Award Fill', class: 'bi-award-fill' },
  
  // B
  { name: 'Back', class: 'bi-back' },
  { name: 'Backpack', class: 'bi-backpack' },
  { name: 'Backpack Fill', class: 'bi-backpack-fill' },
  { name: 'Backpack2', class: 'bi-backpack2' },
  { name: 'Backpack2 Fill', class: 'bi-backpack2-fill' },
  { name: 'Backpack3', class: 'bi-backpack3' },
  { name: 'Backpack3 Fill', class: 'bi-backpack3-fill' },
  { name: 'Backpack4', class: 'bi-backpack4' },
  { name: 'Backpack4 Fill', class: 'bi-backpack4-fill' },
  { name: 'Backspace', class: 'bi-backspace' },
  { name: 'Backspace Fill', class: 'bi-backspace-fill' },
  { name: 'Backspace Reverse', class: 'bi-backspace-reverse' },
  { name: 'Backspace Reverse Fill', class: 'bi-backspace-reverse-fill' },
  { name: 'Badge 3D', class: 'bi-badge-3d' },
  { name: 'Badge 3D Fill', class: 'bi-badge-3d-fill' },
  { name: 'Badge 4K', class: 'bi-badge-4k' },
  { name: 'Badge 4K Fill', class: 'bi-badge-4k-fill' },
  { name: 'Badge 8K', class: 'bi-badge-8k' },
  { name: 'Badge 8K Fill', class: 'bi-badge-8k-fill' },
  { name: 'Badge Ad', class: 'bi-badge-ad' },
  { name: 'Badge Ad Fill', class: 'bi-badge-ad-fill' },
  { name: 'Badge AR', class: 'bi-badge-ar' },
  { name: 'Badge AR Fill', class: 'bi-badge-ar-fill' },
  { name: 'Badge CC', class: 'bi-badge-cc' },
  { name: 'Badge CC Fill', class: 'bi-badge-cc-fill' },
  { name: 'Badge HD', class: 'bi-badge-hd' },
  { name: 'Badge HD Fill', class: 'bi-badge-hd-fill' },
  { name: 'Badge SD', class: 'bi-badge-sd' },
  { name: 'Badge SD Fill', class: 'bi-badge-sd-fill' },
  { name: 'Badge TM', class: 'bi-badge-tm' },
  { name: 'Badge TM Fill', class: 'bi-badge-tm-fill' },
  { name: 'Badge VO', class: 'bi-badge-vo' },
  { name: 'Badge VO Fill', class: 'bi-badge-vo-fill' },
  { name: 'Badge VR', class: 'bi-badge-vr' },
  { name: 'Badge VR Fill', class: 'bi-badge-vr-fill' },
  { name: 'Badge WC', class: 'bi-badge-wc' },
  { name: 'Badge WC Fill', class: 'bi-badge-wc-fill' },
  { name: 'Bag', class: 'bi-bag' },
  { name: 'Bag Check', class: 'bi-bag-check' },
  { name: 'Bag Check Fill', class: 'bi-bag-check-fill' },
  { name: 'Bag Dash', class: 'bi-bag-dash' },
  { name: 'Bag Dash Fill', class: 'bi-bag-dash-fill' },
  { name: 'Bag Fill', class: 'bi-bag-fill' },
  { name: 'Bag Heart', class: 'bi-bag-heart' },
  { name: 'Bag Heart Fill', class: 'bi-bag-heart-fill' },
  { name: 'Bag Plus', class: 'bi-bag-plus' },
  { name: 'Bag Plus Fill', class: 'bi-bag-plus-fill' },
  { name: 'Bag X', class: 'bi-bag-x' },
  { name: 'Bag X Fill', class: 'bi-bag-x-fill' },
  { name: 'Balloon', class: 'bi-balloon' },
  { name: 'Balloon Fill', class: 'bi-balloon-fill' },
  { name: 'Balloon Heart', class: 'bi-balloon-heart' },
  { name: 'Balloon Heart Fill', class: 'bi-balloon-heart-fill' },
  { name: 'Ban', class: 'bi-ban' },
  { name: 'Ban Fill', class: 'bi-ban-fill' },
  { name: 'Bandaid', class: 'bi-bandaid' },
  { name: 'Bandaid Fill', class: 'bi-bandaid-fill' },
  { name: 'Bank', class: 'bi-bank' },
  { name: 'Bank2', class: 'bi-bank2' },
  { name: 'Bar Chart', class: 'bi-bar-chart' },
  { name: 'Bar Chart Fill', class: 'bi-bar-chart-fill' },
  { name: 'Bar Chart Line', class: 'bi-bar-chart-line' },
  { name: 'Bar Chart Line Fill', class: 'bi-bar-chart-line-fill' },
  { name: 'Bar Chart Steps', class: 'bi-bar-chart-steps' },
  { name: 'Basket', class: 'bi-basket' },
  { name: 'Basket Fill', class: 'bi-basket-fill' },
  { name: 'Basket2', class: 'bi-basket2' },
  { name: 'Basket2 Fill', class: 'bi-basket2-fill' },
  { name: 'Basket3', class: 'bi-basket3' },
  { name: 'Basket3 Fill', class: 'bi-basket3-fill' },
  { name: 'Battery', class: 'bi-battery' },
  { name: 'Battery Charging', class: 'bi-battery-charging' },
  { name: 'Battery Full', class: 'bi-battery-full' },
  { name: 'Battery Half', class: 'bi-battery-half' },
  { name: 'Behance', class: 'bi-behance' },
  { name: 'Bell', class: 'bi-bell' },
  { name: 'Bell Fill', class: 'bi-bell-fill' },
  { name: 'Bell Slash', class: 'bi-bell-slash' },
  { name: 'Bell Slash Fill', class: 'bi-bell-slash-fill' },
  { name: 'Bezier', class: 'bi-bezier' },
  { name: 'Bezier2', class: 'bi-bezier2' },
  { name: 'Bicycle', class: 'bi-bicycle' },
  { name: 'Bing', class: 'bi-bing' },
  { name: 'Binoculars', class: 'bi-binoculars' },
  { name: 'Binoculars Fill', class: 'bi-binoculars-fill' },
  { name: 'Blockquote Left', class: 'bi-blockquote-left' },
  { name: 'Blockquote Right', class: 'bi-blockquote-right' },
  { name: 'Bluetooth', class: 'bi-bluetooth' },
  { name: 'Body Text', class: 'bi-body-text' },
  { name: 'Book', class: 'bi-book' },
  { name: 'Book Fill', class: 'bi-book-fill' },
  { name: 'Book Half', class: 'bi-book-half' },
  { name: 'Bookmark', class: 'bi-bookmark' },
  { name: 'Bookmark Check', class: 'bi-bookmark-check' },
  { name: 'Bookmark Check Fill', class: 'bi-bookmark-check-fill' },
  { name: 'Bookmark Dash', class: 'bi-bookmark-dash' },
  { name: 'Bookmark Dash Fill', class: 'bi-bookmark-dash-fill' },
  { name: 'Bookmark Fill', class: 'bi-bookmark-fill' },
  { name: 'Bookmark Heart', class: 'bi-bookmark-heart' },
  { name: 'Bookmark Heart Fill', class: 'bi-bookmark-heart-fill' },
  { name: 'Bookmark Plus', class: 'bi-bookmark-plus' },
  { name: 'Bookmark Plus Fill', class: 'bi-bookmark-plus-fill' },
  { name: 'Bookmark Star', class: 'bi-bookmark-star' },
  { name: 'Bookmark Star Fill', class: 'bi-bookmark-star-fill' },
  { name: 'Bookmark X', class: 'bi-bookmark-x' },
  { name: 'Bookmark X Fill', class: 'bi-bookmark-x-fill' },
  { name: 'Bookmarks', class: 'bi-bookmarks' },
  { name: 'Bookmarks Fill', class: 'bi-bookmarks-fill' },
  { name: 'Bookshelf', class: 'bi-bookshelf' },
  { name: 'Boombox', class: 'bi-boombox' },
  { name: 'Boombox Fill', class: 'bi-boombox-fill' },
  { name: 'Bootstrap', class: 'bi-bootstrap' },
  { name: 'Bootstrap Fill', class: 'bi-bootstrap-fill' },
  { name: 'Bootstrap Icons', class: 'bi-bootstrap-icons' },
  { name: 'Bootstrap Reboot', class: 'bi-bootstrap-reboot' },
  { name: 'Border', class: 'bi-border' },
  { name: 'Border All', class: 'bi-border-all' },
  { name: 'Border Bottom', class: 'bi-border-bottom' },
  { name: 'Border Center', class: 'bi-border-center' },
  { name: 'Border Inner', class: 'bi-border-inner' },
  { name: 'Border Left', class: 'bi-border-left' },
  { name: 'Border Middle', class: 'bi-border-middle' },
  { name: 'Border Outer', class: 'bi-border-outer' },
  { name: 'Border Right', class: 'bi-border-right' },
  { name: 'Border Style', class: 'bi-border-style' },
  { name: 'Border Top', class: 'bi-border-top' },
  { name: 'Border Width', class: 'bi-border-width' },
  { name: 'Bounding Box', class: 'bi-bounding-box' },
  { name: 'Bounding Box Circles', class: 'bi-bounding-box-circles' },
  { name: 'Box', class: 'bi-box' },
  { name: 'Box Arrow Down', class: 'bi-box-arrow-down' },
  { name: 'Box Arrow Down Left', class: 'bi-box-arrow-down-left' },
  { name: 'Box Arrow Down Right', class: 'bi-box-arrow-down-right' },
  { name: 'Box Arrow In Down', class: 'bi-box-arrow-in-down' },
  { name: 'Box Arrow In Down Left', class: 'bi-box-arrow-in-down-left' },
  { name: 'Box Arrow In Down Right', class: 'bi-box-arrow-in-down-right' },
  { name: 'Box Arrow In Left', class: 'bi-box-arrow-in-left' },
  { name: 'Box Arrow In Right', class: 'bi-box-arrow-in-right' },
  { name: 'Box Arrow In Up', class: 'bi-box-arrow-in-up' },
  { name: 'Box Arrow In Up Left', class: 'bi-box-arrow-in-up-left' },
  { name: 'Box Arrow In Up Right', class: 'bi-box-arrow-in-up-right' },
  { name: 'Box Arrow Left', class: 'bi-box-arrow-left' },
  { name: 'Box Arrow Right', class: 'bi-box-arrow-right' },
  { name: 'Box Arrow Up', class: 'bi-box-arrow-up' },
  { name: 'Box Arrow Up Left', class: 'bi-box-arrow-up-left' },
  { name: 'Box Arrow Up Right', class: 'bi-box-arrow-up-right' },
  { name: 'Box Fill', class: 'bi-box-fill' },
  { name: 'Box Seam', class: 'bi-box-seam' },
  { name: 'Box Seam Fill', class: 'bi-box-seam-fill' },
  { name: 'Box2', class: 'bi-box2' },
  { name: 'Box2 Fill', class: 'bi-box2-fill' },
  { name: 'Box2 Heart', class: 'bi-box2-heart' },
  { name: 'Box2 Heart Fill', class: 'bi-box2-heart-fill' },
  { name: 'Boxes', class: 'bi-boxes' },
  { name: 'Braces', class: 'bi-braces' },
  { name: 'Braces Asterisk', class: 'bi-braces-asterisk' },
  { name: 'Bricks', class: 'bi-bricks' },
  { name: 'Briefcase', class: 'bi-briefcase' },
  { name: 'Briefcase Fill', class: 'bi-briefcase-fill' },
  { name: 'Brightness Alt High', class: 'bi-brightness-alt-high' },
  { name: 'Brightness Alt High Fill', class: 'bi-brightness-alt-high-fill' },
  { name: 'Brightness Alt Low', class: 'bi-brightness-alt-low' },
  { name: 'Brightness Alt Low Fill', class: 'bi-brightness-alt-low-fill' },
  { name: 'Brightness High', class: 'bi-brightness-high' },
  { name: 'Brightness High Fill', class: 'bi-brightness-high-fill' },
  { name: 'Brightness Low', class: 'bi-brightness-low' },
  { name: 'Brightness Low Fill', class: 'bi-brightness-low-fill' },
  { name: 'Brilliance', class: 'bi-brilliance' },
  { name: 'Broadcast', class: 'bi-broadcast' },
  { name: 'Broadcast Pin', class: 'bi-broadcast-pin' },
  { name: 'Browser Chrome', class: 'bi-browser-chrome' },
  { name: 'Browser Edge', class: 'bi-browser-edge' },
  { name: 'Browser Firefox', class: 'bi-browser-firefox' },
  { name: 'Browser Safari', class: 'bi-browser-safari' },
  { name: 'Brush', class: 'bi-brush' },
  { name: 'Brush Fill', class: 'bi-brush-fill' },
  { name: 'Bucket', class: 'bi-bucket' },
  { name: 'Bucket Fill', class: 'bi-bucket-fill' },
  { name: 'Bug', class: 'bi-bug' },
  { name: 'Bug Fill', class: 'bi-bug-fill' },
  { name: 'Building', class: 'bi-building' },
  { name: 'Building Add', class: 'bi-building-add' },
  { name: 'Building Check', class: 'bi-building-check' },
  { name: 'Building Dash', class: 'bi-building-dash' },
  { name: 'Building Down', class: 'bi-building-down' },
  { name: 'Building Exclamation', class: 'bi-building-exclamation' },
  { name: 'Building Fill', class: 'bi-building-fill' },
  { name: 'Building Fill Add', class: 'bi-building-fill-add' },
  { name: 'Building Fill Check', class: 'bi-building-fill-check' },
  { name: 'Building Fill Dash', class: 'bi-building-fill-dash' },
  { name: 'Building Fill Down', class: 'bi-building-fill-down' },
  { name: 'Building Fill Exclamation', class: 'bi-building-fill-exclamation' },
  { name: 'Building Fill Gear', class: 'bi-building-fill-gear' },
  { name: 'Building Fill Lock', class: 'bi-building-fill-lock' },
  { name: 'Building Fill Slash', class: 'bi-building-fill-slash' },
  { name: 'Building Fill Up', class: 'bi-building-fill-up' },
  { name: 'Building Fill X', class: 'bi-building-fill-x' },
  { name: 'Building Gear', class: 'bi-building-gear' },
  { name: 'Building Lock', class: 'bi-building-lock' },
  { name: 'Building Slash', class: 'bi-building-slash' },
  { name: 'Building Up', class: 'bi-building-up' },
  { name: 'Building X', class: 'bi-building-x' },
  { name: 'Buildings', class: 'bi-buildings' },
  { name: 'Buildings Fill', class: 'bi-buildings-fill' },
  { name: 'Bullseye', class: 'bi-bullseye' },
  { name: 'Bus Front', class: 'bi-bus-front' },
  { name: 'Bus Front Fill', class: 'bi-bus-front-fill' },
  
  // C
  { name: 'C Circle', class: 'bi-c-circle' },
  { name: 'C Circle Fill', class: 'bi-c-circle-fill' },
  { name: 'C Square', class: 'bi-c-square' },
  { name: 'C Square Fill', class: 'bi-c-square-fill' },
  { name: 'Cake', class: 'bi-cake' },
  { name: 'Cake Fill', class: 'bi-cake-fill' },
  { name: 'Cake2', class: 'bi-cake2' },
  { name: 'Cake2 Fill', class: 'bi-cake2-fill' },
  { name: 'Calculator', class: 'bi-calculator' },
  { name: 'Calculator Fill', class: 'bi-calculator-fill' },
  { name: 'Calendar', class: 'bi-calendar' },
  { name: 'Calendar Check', class: 'bi-calendar-check' },
  { name: 'Calendar Check Fill', class: 'bi-calendar-check-fill' },
  { name: 'Calendar Date', class: 'bi-calendar-date' },
  { name: 'Calendar Date Fill', class: 'bi-calendar-date-fill' },
  { name: 'Calendar Day', class: 'bi-calendar-day' },
  { name: 'Calendar Day Fill', class: 'bi-calendar-day-fill' },
  { name: 'Calendar Event', class: 'bi-calendar-event' },
  { name: 'Calendar Event Fill', class: 'bi-calendar-event-fill' },
  { name: 'Calendar Fill', class: 'bi-calendar-fill' },
  { name: 'Calendar Heart', class: 'bi-calendar-heart' },
  { name: 'Calendar Heart Fill', class: 'bi-calendar-heart-fill' },
  { name: 'Calendar Minus', class: 'bi-calendar-minus' },
  { name: 'Calendar Minus Fill', class: 'bi-calendar-minus-fill' },
  { name: 'Calendar Month', class: 'bi-calendar-month' },
  { name: 'Calendar Month Fill', class: 'bi-calendar-month-fill' },
  { name: 'Calendar Plus', class: 'bi-calendar-plus' },
  { name: 'Calendar Plus Fill', class: 'bi-calendar-plus-fill' },
  { name: 'Calendar Range', class: 'bi-calendar-range' },
  { name: 'Calendar Range Fill', class: 'bi-calendar-range-fill' },
  { name: 'Calendar Week', class: 'bi-calendar-week' },
  { name: 'Calendar Week Fill', class: 'bi-calendar-week-fill' },
  { name: 'Calendar X', class: 'bi-calendar-x' },
  { name: 'Calendar X Fill', class: 'bi-calendar-x-fill' },
  { name: 'Calendar2', class: 'bi-calendar2' },
  { name: 'Calendar2 Check', class: 'bi-calendar2-check' },
  { name: 'Calendar2 Check Fill', class: 'bi-calendar2-check-fill' },
  { name: 'Calendar2 Date', class: 'bi-calendar2-date' },
  { name: 'Calendar2 Date Fill', class: 'bi-calendar2-date-fill' },
  { name: 'Calendar2 Day', class: 'bi-calendar2-day' },
  { name: 'Calendar2 Day Fill', class: 'bi-calendar2-day-fill' },
  { name: 'Calendar2 Event', class: 'bi-calendar2-event' },
  { name: 'Calendar2 Event Fill', class: 'bi-calendar2-event-fill' },
  { name: 'Calendar2 Fill', class: 'bi-calendar2-fill' },
  { name: 'Calendar2 Heart', class: 'bi-calendar2-heart' },
  { name: 'Calendar2 Heart Fill', class: 'bi-calendar2-heart-fill' },
  { name: 'Calendar2 Minus', class: 'bi-calendar2-minus' },
  { name: 'Calendar2 Minus Fill', class: 'bi-calendar2-minus-fill' },
  { name: 'Calendar2 Month', class: 'bi-calendar2-month' },
  { name: 'Calendar2 Month Fill', class: 'bi-calendar2-month-fill' },
  { name: 'Calendar2 Plus', class: 'bi-calendar2-plus' },
  { name: 'Calendar2 Plus Fill', class: 'bi-calendar2-plus-fill' },
  { name: 'Calendar2 Range', class: 'bi-calendar2-range' },
  { name: 'Calendar2 Range Fill', class: 'bi-calendar2-range-fill' },
  { name: 'Calendar2 Week', class: 'bi-calendar2-week' },
  { name: 'Calendar2 Week Fill', class: 'bi-calendar2-week-fill' },
  { name: 'Calendar2 X', class: 'bi-calendar2-x' },
  { name: 'Calendar2 X Fill', class: 'bi-calendar2-x-fill' },
  { name: 'Calendar3', class: 'bi-calendar3' },
  { name: 'Calendar3 Event', class: 'bi-calendar3-event' },
  { name: 'Calendar3 Event Fill', class: 'bi-calendar3-event-fill' },
  { name: 'Calendar3 Fill', class: 'bi-calendar3-fill' },
  { name: 'Calendar3 Range', class: 'bi-calendar3-range' },
  { name: 'Calendar3 Range Fill', class: 'bi-calendar3-range-fill' },
  { name: 'Calendar3 Week', class: 'bi-calendar3-week' },
  { name: 'Calendar3 Week Fill', class: 'bi-calendar3-week-fill' },
  { name: 'Calendar4', class: 'bi-calendar4' },
  { name: 'Calendar4 Event', class: 'bi-calendar4-event' },
  { name: 'Calendar4 Range', class: 'bi-calendar4-range' },
  { name: 'Calendar4 Week', class: 'bi-calendar4-week' },
  { name: 'Camera', class: 'bi-camera' },
  { name: 'Camera Fill', class: 'bi-camera-fill' },
  { name: 'Camera Reels', class: 'bi-camera-reels' },
  { name: 'Camera Reels Fill', class: 'bi-camera-reels-fill' },
  { name: 'Camera Video', class: 'bi-camera-video' },
  { name: 'Camera Video Fill', class: 'bi-camera-video-fill' },
  { name: 'Camera Video Off', class: 'bi-camera-video-off' },
  { name: 'Camera Video Off Fill', class: 'bi-camera-video-off-fill' },
  { name: 'Camera2', class: 'bi-camera2' },
  { name: 'Capslock', class: 'bi-capslock' },
  { name: 'Capslock Fill', class: 'bi-capslock-fill' },
  { name: 'Capsule', class: 'bi-capsule' },
  { name: 'Capsule Pill', class: 'bi-capsule-pill' },
  { name: 'Car Front', class: 'bi-car-front' },
  { name: 'Car Front Fill', class: 'bi-car-front-fill' },
  { name: 'Card Checklist', class: 'bi-card-checklist' },
  { name: 'Card Heading', class: 'bi-card-heading' },
  { name: 'Card Image', class: 'bi-card-image' },
  { name: 'Card List', class: 'bi-card-list' },
  { name: 'Card Text', class: 'bi-card-text' },
  { name: 'Caret Down', class: 'bi-caret-down' },
  { name: 'Caret Down Fill', class: 'bi-caret-down-fill' },
  { name: 'Caret Down Square', class: 'bi-caret-down-square' },
  { name: 'Caret Down Square Fill', class: 'bi-caret-down-square-fill' },
  { name: 'Caret Left', class: 'bi-caret-left' },
  { name: 'Caret Left Fill', class: 'bi-caret-left-fill' },
  { name: 'Caret Left Square', class: 'bi-caret-left-square' },
  { name: 'Caret Left Square Fill', class: 'bi-caret-left-square-fill' },
  { name: 'Caret Right', class: 'bi-caret-right' },
  { name: 'Caret Right Fill', class: 'bi-caret-right-fill' },
  { name: 'Caret Right Square', class: 'bi-caret-right-square' },
  { name: 'Caret Right Square Fill', class: 'bi-caret-right-square-fill' },
  { name: 'Caret Up', class: 'bi-caret-up' },
  { name: 'Caret Up Fill', class: 'bi-caret-up-fill' },
  { name: 'Caret Up Square', class: 'bi-caret-up-square' },
  { name: 'Caret Up Square Fill', class: 'bi-caret-up-square-fill' },
  { name: 'Cart', class: 'bi-cart' },
  { name: 'Cart Check', class: 'bi-cart-check' },
  { name: 'Cart Check Fill', class: 'bi-cart-check-fill' },
  { name: 'Cart Dash', class: 'bi-cart-dash' },
  { name: 'Cart Dash Fill', class: 'bi-cart-dash-fill' },
  { name: 'Cart Fill', class: 'bi-cart-fill' },
  { name: 'Cart Plus', class: 'bi-cart-plus' },
  { name: 'Cart Plus Fill', class: 'bi-cart-plus-fill' },
  { name: 'Cart X', class: 'bi-cart-x' },
  { name: 'Cart X Fill', class: 'bi-cart-x-fill' },
  { name: 'Cart2', class: 'bi-cart2' },
  { name: 'Cart3', class: 'bi-cart3' },
  { name: 'Cart4', class: 'bi-cart4' },
  { name: 'Cash', class: 'bi-cash' },
  { name: 'Cash Coin', class: 'bi-cash-coin' },
  { name: 'Cash Stack', class: 'bi-cash-stack' },
  { name: 'Cassette', class: 'bi-cassette' },
  { name: 'Cassette Fill', class: 'bi-cassette-fill' },
  { name: 'Cast', class: 'bi-cast' },
  { name: 'CC Circle', class: 'bi-cc-circle' },
  { name: 'CC Circle Fill', class: 'bi-cc-circle-fill' },
  { name: 'CC Square', class: 'bi-cc-square' },
  { name: 'CC Square Fill', class: 'bi-cc-square-fill' },
  { name: 'Chat', class: 'bi-chat' },
  { name: 'Chat Dots', class: 'bi-chat-dots' },
  { name: 'Chat Dots Fill', class: 'bi-chat-dots-fill' },
  { name: 'Chat Fill', class: 'bi-chat-fill' },
  { name: 'Chat Heart', class: 'bi-chat-heart' },
  { name: 'Chat Heart Fill', class: 'bi-chat-heart-fill' },
  { name: 'Chat Left', class: 'bi-chat-left' },
  { name: 'Chat Left Dots', class: 'bi-chat-left-dots' },
  { name: 'Chat Left Dots Fill', class: 'bi-chat-left-dots-fill' },
  { name: 'Chat Left Fill', class: 'bi-chat-left-fill' },
  { name: 'Chat Left Heart', class: 'bi-chat-left-heart' },
  { name: 'Chat Left Heart Fill', class: 'bi-chat-left-heart-fill' },
  { name: 'Chat Left Quote', class: 'bi-chat-left-quote' },
  { name: 'Chat Left Quote Fill', class: 'bi-chat-left-quote-fill' },
  { name: 'Chat Left Text', class: 'bi-chat-left-text' },
  { name: 'Chat Left Text Fill', class: 'bi-chat-left-text-fill' },
  { name: 'Chat Quote', class: 'bi-chat-quote' },
  { name: 'Chat Quote Fill', class: 'bi-chat-quote-fill' },
  { name: 'Chat Right', class: 'bi-chat-right' },
  { name: 'Chat Right Dots', class: 'bi-chat-right-dots' },
  { name: 'Chat Right Dots Fill', class: 'bi-chat-right-dots-fill' },
  { name: 'Chat Right Fill', class: 'bi-chat-right-fill' },
  { name: 'Chat Right Heart', class: 'bi-chat-right-heart' },
  { name: 'Chat Right Heart Fill', class: 'bi-chat-right-heart-fill' },
  { name: 'Chat Right Quote', class: 'bi-chat-right-quote' },
  { name: 'Chat Right Quote Fill', class: 'bi-chat-right-quote-fill' },
  { name: 'Chat Right Text', class: 'bi-chat-right-text' },
  { name: 'Chat Right Text Fill', class: 'bi-chat-right-text-fill' },
  { name: 'Chat Square', class: 'bi-chat-square' },
  { name: 'Chat Square Dots', class: 'bi-chat-square-dots' },
  { name: 'Chat Square Dots Fill', class: 'bi-chat-square-dots-fill' },
  { name: 'Chat Square Fill', class: 'bi-chat-square-fill' },
  { name: 'Chat Square Heart', class: 'bi-chat-square-heart' },
  { name: 'Chat Square Heart Fill', class: 'bi-chat-square-heart-fill' },
  { name: 'Chat Square Quote', class: 'bi-chat-square-quote' },
  { name: 'Chat Square Quote Fill', class: 'bi-chat-square-quote-fill' },
  { name: 'Chat Square Text', class: 'bi-chat-square-text' },
  { name: 'Chat Square Text Fill', class: 'bi-chat-square-text-fill' },
  { name: 'Chat Text', class: 'bi-chat-text' },
  { name: 'Chat Text Fill', class: 'bi-chat-text-fill' },
  { name: 'Check', class: 'bi-check' },
  { name: 'Check All', class: 'bi-check-all' },
  { name: 'Check Circle', class: 'bi-check-circle' },
  { name: 'Check Circle Fill', class: 'bi-check-circle-fill' },
  { name: 'Check Lg', class: 'bi-check-lg' },
  { name: 'Check Square', class: 'bi-check-square' },
  { name: 'Check Square Fill', class: 'bi-check-square-fill' },
  { name: 'Check2', class: 'bi-check2' },
  { name: 'Check2 All', class: 'bi-check2-all' },
  { name: 'Check2 Circle', class: 'bi-check2-circle' },
  { name: 'Check2 Square', class: 'bi-check2-square' },
  { name: 'Chevron Bar Contract', class: 'bi-chevron-bar-contract' },
  { name: 'Chevron Bar Down', class: 'bi-chevron-bar-down' },
  { name: 'Chevron Bar Expand', class: 'bi-chevron-bar-expand' },
  { name: 'Chevron Bar Left', class: 'bi-chevron-bar-left' },
  { name: 'Chevron Bar Right', class: 'bi-chevron-bar-right' },
  { name: 'Chevron Bar Up', class: 'bi-chevron-bar-up' },
  { name: 'Chevron Compact Down', class: 'bi-chevron-compact-down' },
  { name: 'Chevron Compact Left', class: 'bi-chevron-compact-left' },
  { name: 'Chevron Compact Right', class: 'bi-chevron-compact-right' },
  { name: 'Chevron Compact Up', class: 'bi-chevron-compact-up' },
  { name: 'Chevron Contract', class: 'bi-chevron-contract' },
  { name: 'Chevron Double Down', class: 'bi-chevron-double-down' },
  { name: 'Chevron Double Left', class: 'bi-chevron-double-left' },
  { name: 'Chevron Double Right', class: 'bi-chevron-double-right' },
  { name: 'Chevron Double Up', class: 'bi-chevron-double-up' },
  { name: 'Chevron Down', class: 'bi-chevron-down' },
  { name: 'Chevron Expand', class: 'bi-chevron-expand' },
  { name: 'Chevron Left', class: 'bi-chevron-left' },
  { name: 'Chevron Right', class: 'bi-chevron-right' },
  { name: 'Chevron Up', class: 'bi-chevron-up' },
  { name: 'Circle', class: 'bi-circle' },
  { name: 'Circle Fill', class: 'bi-circle-fill' },
  { name: 'Circle Half', class: 'bi-circle-half' },
  { name: 'Circle Square', class: 'bi-circle-square' },
  { name: 'Clipboard', class: 'bi-clipboard' },
  { name: 'Clipboard Check', class: 'bi-clipboard-check' },
  { name: 'Clipboard Check Fill', class: 'bi-clipboard-check-fill' },
  { name: 'Clipboard Data', class: 'bi-clipboard-data' },
  { name: 'Clipboard Data Fill', class: 'bi-clipboard-data-fill' },
  { name: 'Clipboard Fill', class: 'bi-clipboard-fill' },
  { name: 'Clipboard Heart', class: 'bi-clipboard-heart' },
  { name: 'Clipboard Heart Fill', class: 'bi-clipboard-heart-fill' },
  { name: 'Clipboard Minus', class: 'bi-clipboard-minus' },
  { name: 'Clipboard Minus Fill', class: 'bi-clipboard-minus-fill' },
  { name: 'Clipboard Plus', class: 'bi-clipboard-plus' },
  { name: 'Clipboard Plus Fill', class: 'bi-clipboard-plus-fill' },
  { name: 'Clipboard Pulse', class: 'bi-clipboard-pulse' },
  { name: 'Clipboard X', class: 'bi-clipboard-x' },
  { name: 'Clipboard X Fill', class: 'bi-clipboard-x-fill' },
  { name: 'Clipboard2', class: 'bi-clipboard2' },
  { name: 'Clipboard2 Check', class: 'bi-clipboard2-check' },
  { name: 'Clipboard2 Check Fill', class: 'bi-clipboard2-check-fill' },
  { name: 'Clipboard2 Data', class: 'bi-clipboard2-data' },
  { name: 'Clipboard2 Data Fill', class: 'bi-clipboard2-data-fill' },
  { name: 'Clipboard2 Fill', class: 'bi-clipboard2-fill' },
  { name: 'Clipboard2 Heart', class: 'bi-clipboard2-heart' },
  { name: 'Clipboard2 Heart Fill', class: 'bi-clipboard2-heart-fill' },
  { name: 'Clipboard2 Minus', class: 'bi-clipboard2-minus' },
  { name: 'Clipboard2 Minus Fill', class: 'bi-clipboard2-minus-fill' },
  { name: 'Clipboard2 Plus', class: 'bi-clipboard2-plus' },
  { name: 'Clipboard2 Plus Fill', class: 'bi-clipboard2-plus-fill' },
  { name: 'Clipboard2 Pulse', class: 'bi-clipboard2-pulse' },
  { name: 'Clipboard2 Pulse Fill', class: 'bi-clipboard2-pulse-fill' },
  { name: 'Clipboard2 X', class: 'bi-clipboard2-x' },
  { name: 'Clipboard2 X Fill', class: 'bi-clipboard2-x-fill' },
  { name: 'Clock', class: 'bi-clock' },
  { name: 'Clock Fill', class: 'bi-clock-fill' },
  { name: 'Clock History', class: 'bi-clock-history' },
  { name: 'Cloud', class: 'bi-cloud' },
  { name: 'Cloud Arrow Down', class: 'bi-cloud-arrow-down' },
  { name: 'Cloud Arrow Down Fill', class: 'bi-cloud-arrow-down-fill' },
  { name: 'Cloud Arrow Up', class: 'bi-cloud-arrow-up' },
  { name: 'Cloud Arrow Up Fill', class: 'bi-cloud-arrow-up-fill' },
  { name: 'Cloud Check', class: 'bi-cloud-check' },
  { name: 'Cloud Check Fill', class: 'bi-cloud-check-fill' },
  { name: 'Cloud Download', class: 'bi-cloud-download' },
  { name: 'Cloud Download Fill', class: 'bi-cloud-download-fill' },
  { name: 'Cloud Drizzle', class: 'bi-cloud-drizzle' },
  { name: 'Cloud Drizzle Fill', class: 'bi-cloud-drizzle-fill' },
  { name: 'Cloud Fill', class: 'bi-cloud-fill' },
  { name: 'Cloud Fog', class: 'bi-cloud-fog' },
  { name: 'Cloud Fog Fill', class: 'bi-cloud-fog-fill' },
  { name: 'Cloud Fog2', class: 'bi-cloud-fog2' },
  { name: 'Cloud Fog2 Fill', class: 'bi-cloud-fog2-fill' },
  { name: 'Cloud Hail', class: 'bi-cloud-hail' },
  { name: 'Cloud Hail Fill', class: 'bi-cloud-hail-fill' },
  { name: 'Cloud Haze', class: 'bi-cloud-haze' },
  { name: 'Cloud Haze Fill', class: 'bi-cloud-haze-fill' },
  { name: 'Cloud Haze2', class: 'bi-cloud-haze2' },
  { name: 'Cloud Haze2 Fill', class: 'bi-cloud-haze2-fill' },
  { name: 'Cloud Lightning', class: 'bi-cloud-lightning' },
  { name: 'Cloud Lightning Fill', class: 'bi-cloud-lightning-fill' },
  { name: 'Cloud Lightning Rain', class: 'bi-cloud-lightning-rain' },
  { name: 'Cloud Lightning Rain Fill', class: 'bi-cloud-lightning-rain-fill' },
  { name: 'Cloud Minus', class: 'bi-cloud-minus' },
  { name: 'Cloud Minus Fill', class: 'bi-cloud-minus-fill' },
  { name: 'Cloud Moon', class: 'bi-cloud-moon' },
  { name: 'Cloud Moon Fill', class: 'bi-cloud-moon-fill' },
  { name: 'Cloud Plus', class: 'bi-cloud-plus' },
  { name: 'Cloud Plus Fill', class: 'bi-cloud-plus-fill' },
  { name: 'Cloud Rain', class: 'bi-cloud-rain' },
  { name: 'Cloud Rain Fill', class: 'bi-cloud-rain-fill' },
  { name: 'Cloud Rain Heavy', class: 'bi-cloud-rain-heavy' },
  { name: 'Cloud Rain Heavy Fill', class: 'bi-cloud-rain-heavy-fill' },
  { name: 'Cloud Slash', class: 'bi-cloud-slash' },
  { name: 'Cloud Slash Fill', class: 'bi-cloud-slash-fill' },
  { name: 'Cloud Sleet', class: 'bi-cloud-sleet' },
  { name: 'Cloud Sleet Fill', class: 'bi-cloud-sleet-fill' },
  { name: 'Cloud Snow', class: 'bi-cloud-snow' },
  { name: 'Cloud Snow Fill', class: 'bi-cloud-snow-fill' },
  { name: 'Cloud Sun', class: 'bi-cloud-sun' },
  { name: 'Cloud Sun Fill', class: 'bi-cloud-sun-fill' },
  { name: 'Cloud Upload', class: 'bi-cloud-upload' },
  { name: 'Cloud Upload Fill', class: 'bi-cloud-upload-fill' },
  { name: 'Clouds', class: 'bi-clouds' },
  { name: 'Clouds Fill', class: 'bi-clouds-fill' },
  { name: 'Cloudy', class: 'bi-cloudy' },
  { name: 'Cloudy Fill', class: 'bi-cloudy-fill' },
  { name: 'Code', class: 'bi-code' },
  { name: 'Code Slash', class: 'bi-code-slash' },
  { name: 'Code Square', class: 'bi-code-square' },
  { name: 'Coin', class: 'bi-coin' },
  { name: 'Collection', class: 'bi-collection' },
  { name: 'Collection Fill', class: 'bi-collection-fill' },
  { name: 'Collection Play', class: 'bi-collection-play' },
  { name: 'Collection Play Fill', class: 'bi-collection-play-fill' },
  { name: 'Columns', class: 'bi-columns' },
  { name: 'Columns Gap', class: 'bi-columns-gap' },
  { name: 'Command', class: 'bi-command' },
  { name: 'Compass', class: 'bi-compass' },
  { name: 'Compass Fill', class: 'bi-compass-fill' },
  { name: 'Cone', class: 'bi-cone' },
  { name: 'Cone Striped', class: 'bi-cone-striped' },
  { name: 'Controller', class: 'bi-controller' },
  { name: 'Cookie', class: 'bi-cookie' },
  { name: 'Copy', class: 'bi-copy' },
  { name: 'CPU', class: 'bi-cpu' },
  { name: 'CPU Fill', class: 'bi-cpu-fill' },
  { name: 'Credit Card', class: 'bi-credit-card' },
  { name: 'Credit Card 2 Back', class: 'bi-credit-card-2-back' },
  { name: 'Credit Card 2 Back Fill', class: 'bi-credit-card-2-back-fill' },
  { name: 'Credit Card 2 Front', class: 'bi-credit-card-2-front' },
  { name: 'Credit Card 2 Front Fill', class: 'bi-credit-card-2-front-fill' },
  { name: 'Credit Card Fill', class: 'bi-credit-card-fill' },
  { name: 'Crop', class: 'bi-crop' },
  { name: 'Crosshair', class: 'bi-crosshair' },
  { name: 'Crosshair2', class: 'bi-crosshair2' },
  { name: 'Cup', class: 'bi-cup' },
  { name: 'Cup Fill', class: 'bi-cup-fill' },
  { name: 'Cup Hot', class: 'bi-cup-hot' },
  { name: 'Cup Hot Fill', class: 'bi-cup-hot-fill' },
  { name: 'Cup Straw', class: 'bi-cup-straw' },
  { name: 'Currency Bitcoin', class: 'bi-currency-bitcoin' },
  { name: 'Currency Dollar', class: 'bi-currency-dollar' },
  { name: 'Currency Euro', class: 'bi-currency-euro' },
  { name: 'Currency Exchange', class: 'bi-currency-exchange' },
  { name: 'Currency Pound', class: 'bi-currency-pound' },
  { name: 'Currency Rupee', class: 'bi-currency-rupee' },
  { name: 'Currency Yen', class: 'bi-currency-yen' },
  { name: 'Cursor', class: 'bi-cursor' },
  { name: 'Cursor Fill', class: 'bi-cursor-fill' },
  { name: 'Cursor Text', class: 'bi-cursor-text' },
  
  // D
  { name: 'Dash', class: 'bi-dash' },
  { name: 'Dash Circle', class: 'bi-dash-circle' },
  { name: 'Dash Circle Dotted', class: 'bi-dash-circle-dotted' },
  { name: 'Dash Circle Fill', class: 'bi-dash-circle-fill' },
  { name: 'Dash Lg', class: 'bi-dash-lg' },
  { name: 'Dash Square', class: 'bi-dash-square' },
  { name: 'Dash Square Dotted', class: 'bi-dash-square-dotted' },
  { name: 'Dash Square Fill', class: 'bi-dash-square-fill' },
  { name: 'Database', class: 'bi-database' },
  { name: 'Database Add', class: 'bi-database-add' },
  { name: 'Database Check', class: 'bi-database-check' },
  { name: 'Database Dash', class: 'bi-database-dash' },
  { name: 'Database Down', class: 'bi-database-down' },
  { name: 'Database Exclamation', class: 'bi-database-exclamation' },
  { name: 'Database Fill', class: 'bi-database-fill' },
  { name: 'Database Fill Add', class: 'bi-database-fill-add' },
  { name: 'Database Fill Check', class: 'bi-database-fill-check' },
  { name: 'Database Fill Dash', class: 'bi-database-fill-dash' },
  { name: 'Database Fill Down', class: 'bi-database-fill-down' },
  { name: 'Database Fill Exclamation', class: 'bi-database-fill-exclamation' },
  { name: 'Database Fill Gear', class: 'bi-database-fill-gear' },
  { name: 'Database Fill Lock', class: 'bi-database-fill-lock' },
  { name: 'Database Fill Slash', class: 'bi-database-fill-slash' },
  { name: 'Database Fill Up', class: 'bi-database-fill-up' },
  { name: 'Database Fill X', class: 'bi-database-fill-x' },
  { name: 'Database Gear', class: 'bi-database-gear' },
  { name: 'Database Lock', class: 'bi-database-lock' },
  { name: 'Database Slash', class: 'bi-database-slash' },
  { name: 'Database Up', class: 'bi-database-up' },
  { name: 'Database X', class: 'bi-database-x' },
  { name: 'Device HDD', class: 'bi-device-hdd' },
  { name: 'Device HDD Fill', class: 'bi-device-hdd-fill' },
  { name: 'Device SSD', class: 'bi-device-ssd' },
  { name: 'Device SSD Fill', class: 'bi-device-ssd-fill' },
  { name: 'Diagram 2', class: 'bi-diagram-2' },
  { name: 'Diagram 2 Fill', class: 'bi-diagram-2-fill' },
  { name: 'Diagram 3', class: 'bi-diagram-3' },
  { name: 'Diagram 3 Fill', class: 'bi-diagram-3-fill' },
  { name: 'Diamond', class: 'bi-diamond' },
  { name: 'Diamond Fill', class: 'bi-diamond-fill' },
  { name: 'Diamond Half', class: 'bi-diamond-half' },
  { name: 'Dice 1', class: 'bi-dice-1' },
  { name: 'Dice 1 Fill', class: 'bi-dice-1-fill' },
  { name: 'Dice 2', class: 'bi-dice-2' },
  { name: 'Dice 2 Fill', class: 'bi-dice-2-fill' },
  { name: 'Dice 3', class: 'bi-dice-3' },
  { name: 'Dice 3 Fill', class: 'bi-dice-3-fill' },
  { name: 'Dice 4', class: 'bi-dice-4' },
  { name: 'Dice 4 Fill', class: 'bi-dice-4-fill' },
  { name: 'Dice 5', class: 'bi-dice-5' },
  { name: 'Dice 5 Fill', class: 'bi-dice-5-fill' },
  { name: 'Dice 6', class: 'bi-dice-6' },
  { name: 'Dice 6 Fill', class: 'bi-dice-6-fill' },
  { name: 'Disc', class: 'bi-disc' },
  { name: 'Disc Fill', class: 'bi-disc-fill' },
  { name: 'Discord', class: 'bi-discord' },
  { name: 'Display', class: 'bi-display' },
  { name: 'Display Fill', class: 'bi-display-fill' },
  { name: 'Displayport', class: 'bi-displayport' },
  { name: 'Displayport Fill', class: 'bi-displayport-fill' },
  { name: 'Distribute Horizontal', class: 'bi-distribute-horizontal' },
  { name: 'Distribute Vertical', class: 'bi-distribute-vertical' },
  { name: 'Door Closed', class: 'bi-door-closed' },
  { name: 'Door Closed Fill', class: 'bi-door-closed-fill' },
  { name: 'Door Open', class: 'bi-door-open' },
  { name: 'Door Open Fill', class: 'bi-door-open-fill' },
  { name: 'Dot', class: 'bi-dot' },
  { name: 'Download', class: 'bi-download' },
  { name: 'Dpad', class: 'bi-dpad' },
  { name: 'Dpad Fill', class: 'bi-dpad-fill' },
  { name: 'Dribbble', class: 'bi-dribbble' },
  { name: 'Dropbox', class: 'bi-dropbox' },
  { name: 'Droplet', class: 'bi-droplet' },
  { name: 'Droplet Fill', class: 'bi-droplet-fill' },
  { name: 'Droplet Half', class: 'bi-droplet-half' },
  { name: 'Duffle', class: 'bi-duffle' },
  { name: 'Duffle Fill', class: 'bi-duffle-fill' },
  
  // E
  { name: 'Ear', class: 'bi-ear' },
  { name: 'Ear Fill', class: 'bi-ear-fill' },
  { name: 'Earbuds', class: 'bi-earbuds' },
  { name: 'Easel', class: 'bi-easel' },
  { name: 'Easel Fill', class: 'bi-easel-fill' },
  { name: 'Easel2', class: 'bi-easel2' },
  { name: 'Easel2 Fill', class: 'bi-easel2-fill' },
  { name: 'Easel3', class: 'bi-easel3' },
  { name: 'Easel3 Fill', class: 'bi-easel3-fill' },
  { name: 'Egg', class: 'bi-egg' },
  { name: 'Egg Fill', class: 'bi-egg-fill' },
  { name: 'Egg Fried', class: 'bi-egg-fried' },
  { name: 'Eject', class: 'bi-eject' },
  { name: 'Eject Fill', class: 'bi-eject-fill' },
  { name: 'Emoji Angry', class: 'bi-emoji-angry' },
  { name: 'Emoji Angry Fill', class: 'bi-emoji-angry-fill' },
  { name: 'Emoji Astonished', class: 'bi-emoji-astonished' },
  { name: 'Emoji Astonished Fill', class: 'bi-emoji-astonished-fill' },
  { name: 'Emoji Dizzy', class: 'bi-emoji-dizzy' },
  { name: 'Emoji Dizzy Fill', class: 'bi-emoji-dizzy-fill' },
  { name: 'Emoji Expressionless', class: 'bi-emoji-expressionless' },
  { name: 'Emoji Expressionless Fill', class: 'bi-emoji-expressionless-fill' },
  { name: 'Emoji Frown', class: 'bi-emoji-frown' },
  { name: 'Emoji Frown Fill', class: 'bi-emoji-frown-fill' },
  { name: 'Emoji Grimace', class: 'bi-emoji-grimace' },
  { name: 'Emoji Grimace Fill', class: 'bi-emoji-grimace-fill' },
  { name: 'Emoji Grin', class: 'bi-emoji-grin' },
  { name: 'Emoji Grin Fill', class: 'bi-emoji-grin-fill' },
  { name: 'Emoji Heart Eyes', class: 'bi-emoji-heart-eyes' },
  { name: 'Emoji Heart Eyes Fill', class: 'bi-emoji-heart-eyes-fill' },
  { name: 'Emoji Kiss', class: 'bi-emoji-kiss' },
  { name: 'Emoji Kiss Fill', class: 'bi-emoji-kiss-fill' },
  { name: 'Emoji Laughing', class: 'bi-emoji-laughing' },
  { name: 'Emoji Laughing Fill', class: 'bi-emoji-laughing-fill' },
  { name: 'Emoji Neutral', class: 'bi-emoji-neutral' },
  { name: 'Emoji Neutral Fill', class: 'bi-emoji-neutral-fill' },
  { name: 'Emoji Smile', class: 'bi-emoji-smile' },
  { name: 'Emoji Smile Fill', class: 'bi-emoji-smile-fill' },
  { name: 'Emoji Smile Upside Down', class: 'bi-emoji-smile-upside-down' },
  { name: 'Emoji Smile Upside Down Fill', class: 'bi-emoji-smile-upside-down-fill' },
  { name: 'Emoji Sunglasses', class: 'bi-emoji-sunglasses' },
  { name: 'Emoji Sunglasses Fill', class: 'bi-emoji-sunglasses-fill' },
  { name: 'Emoji Surprise', class: 'bi-emoji-surprise' },
  { name: 'Emoji Surprise Fill', class: 'bi-emoji-surprise-fill' },
  { name: 'Emoji Tear', class: 'bi-emoji-tear' },
  { name: 'Emoji Tear Fill', class: 'bi-emoji-tear-fill' },
  { name: 'Emoji Wink', class: 'bi-emoji-wink' },
  { name: 'Emoji Wink Fill', class: 'bi-emoji-wink-fill' },
  { name: 'Envelope', class: 'bi-envelope' },
  { name: 'Envelope Arrow Down', class: 'bi-envelope-arrow-down' },
  { name: 'Envelope Arrow Down Fill', class: 'bi-envelope-arrow-down-fill' },
  { name: 'Envelope Arrow Up', class: 'bi-envelope-arrow-up' },
  { name: 'Envelope Arrow Up Fill', class: 'bi-envelope-arrow-up-fill' },
  { name: 'Envelope At', class: 'bi-envelope-at' },
  { name: 'Envelope At Fill', class: 'bi-envelope-at-fill' },
  { name: 'Envelope Check', class: 'bi-envelope-check' },
  { name: 'Envelope Check Fill', class: 'bi-envelope-check-fill' },
  { name: 'Envelope Dash', class: 'bi-envelope-dash' },
  { name: 'Envelope Dash Fill', class: 'bi-envelope-dash-fill' },
  { name: 'Envelope Exclamation', class: 'bi-envelope-exclamation' },
  { name: 'Envelope Exclamation Fill', class: 'bi-envelope-exclamation-fill' },
  { name: 'Envelope Fill', class: 'bi-envelope-fill' },
  { name: 'Envelope Heart', class: 'bi-envelope-heart' },
  { name: 'Envelope Heart Fill', class: 'bi-envelope-heart-fill' },
  { name: 'Envelope Open', class: 'bi-envelope-open' },
  { name: 'Envelope Open Fill', class: 'bi-envelope-open-fill' },
  { name: 'Envelope Open Heart', class: 'bi-envelope-open-heart' },
  { name: 'Envelope Open Heart Fill', class: 'bi-envelope-open-heart-fill' },
  { name: 'Envelope Paper', class: 'bi-envelope-paper' },
  { name: 'Envelope Paper Fill', class: 'bi-envelope-paper-fill' },
  { name: 'Envelope Paper Heart', class: 'bi-envelope-paper-heart' },
  { name: 'Envelope Paper Heart Fill', class: 'bi-envelope-paper-heart-fill' },
  { name: 'Envelope Plus', class: 'bi-envelope-plus' },
  { name: 'Envelope Plus Fill', class: 'bi-envelope-plus-fill' },
  { name: 'Envelope Slash', class: 'bi-envelope-slash' },
  { name: 'Envelope Slash Fill', class: 'bi-envelope-slash-fill' },
  { name: 'Envelope X', class: 'bi-envelope-x' },
  { name: 'Envelope X Fill', class: 'bi-envelope-x-fill' },
  { name: 'Eraser', class: 'bi-eraser' },
  { name: 'Eraser Fill', class: 'bi-eraser-fill' },
  { name: 'Escape', class: 'bi-escape' },
  { name: 'Ethernet', class: 'bi-ethernet' },
  { name: 'EV Front', class: 'bi-ev-front' },
  { name: 'EV Front Fill', class: 'bi-ev-front-fill' },
  { name: 'EV Station', class: 'bi-ev-station' },
  { name: 'EV Station Fill', class: 'bi-ev-station-fill' },
  { name: 'Exclamation', class: 'bi-exclamation' },
  { name: 'Exclamation Circle', class: 'bi-exclamation-circle' },
  { name: 'Exclamation Circle Fill', class: 'bi-exclamation-circle-fill' },
  { name: 'Exclamation Diamond', class: 'bi-exclamation-diamond' },
  { name: 'Exclamation Diamond Fill', class: 'bi-exclamation-diamond-fill' },
  { name: 'Exclamation Lg', class: 'bi-exclamation-lg' },
  { name: 'Exclamation Octagon', class: 'bi-exclamation-octagon' },
  { name: 'Exclamation Octagon Fill', class: 'bi-exclamation-octagon-fill' },
  { name: 'Exclamation Square', class: 'bi-exclamation-square' },
  { name: 'Exclamation Square Fill', class: 'bi-exclamation-square-fill' },
  { name: 'Exclamation Triangle', class: 'bi-exclamation-triangle' },
  { name: 'Exclamation Triangle Fill', class: 'bi-exclamation-triangle-fill' },
  { name: 'Exclude', class: 'bi-exclude' },
  { name: 'Explicit', class: 'bi-explicit' },
  { name: 'Explicit Fill', class: 'bi-explicit-fill' },
  { name: 'Exposure', class: 'bi-exposure' },
  { name: 'Eye', class: 'bi-eye' },
  { name: 'Eye Fill', class: 'bi-eye-fill' },
  { name: 'Eye Slash', class: 'bi-eye-slash' },
  { name: 'Eye Slash Fill', class: 'bi-eye-slash-fill' },
  { name: 'Eyedropper', class: 'bi-eyedropper' },
  { name: 'Eyeglasses', class: 'bi-eyeglasses' },
  
  
  // Importing F-Z sections
  ...require('./allBootstrapIconsComplete.js').allBootstrapIconsFtoZ
]