// 完整的 Bootstrap Icons 列表 - F 到 Z 部分
export const allBootstrapIconsFtoZ = [
  // F
  { name: 'Facebook', class: 'bi-facebook' },
  { name: 'Fan', class: 'bi-fan' },
  { name: 'Fast Forward', class: 'bi-fast-forward' },
  { name: 'Fast Forward Btn', class: 'bi-fast-forward-btn' },
  { name: 'Fast Forward Btn Fill', class: 'bi-fast-forward-btn-fill' },
  { name: 'Fast Forward Circle', class: 'bi-fast-forward-circle' },
  { name: 'Fast Forward Circle Fill', class: 'bi-fast-forward-circle-fill' },
  { name: 'Fast Forward Fill', class: 'bi-fast-forward-fill' },
  { name: 'File', class: 'bi-file' },
  { name: 'File Arrow Down', class: 'bi-file-arrow-down' },
  { name: 'File Arrow Down Fill', class: 'bi-file-arrow-down-fill' },
  { name: 'File Arrow Up', class: 'bi-file-arrow-up' },
  { name: 'File Arrow Up Fill', class: 'bi-file-arrow-up-fill' },
  { name: 'File Bar Graph', class: 'bi-file-bar-graph' },
  { name: 'File Bar Graph Fill', class: 'bi-file-bar-graph-fill' },
  { name: 'File Binary', class: 'bi-file-binary' },
  { name: 'File Binary Fill', class: 'bi-file-binary-fill' },
  { name: 'File Break', class: 'bi-file-break' },
  { name: 'File Break Fill', class: 'bi-file-break-fill' },
  { name: 'File Check', class: 'bi-file-check' },
  { name: 'File Check Fill', class: 'bi-file-check-fill' },
  { name: 'File Code', class: 'bi-file-code' },
  { name: 'File Code Fill', class: 'bi-file-code-fill' },
  { name: 'File Diff', class: 'bi-file-diff' },
  { name: 'File Diff Fill', class: 'bi-file-diff-fill' },
  { name: 'File Earmark', class: 'bi-file-earmark' },
  { name: 'File Earmark Arrow Down', class: 'bi-file-earmark-arrow-down' },
  { name: 'File Earmark Arrow Down Fill', class: 'bi-file-earmark-arrow-down-fill' },
  { name: 'File Earmark Arrow Up', class: 'bi-file-earmark-arrow-up' },
  { name: 'File Earmark Arrow Up Fill', class: 'bi-file-earmark-arrow-up-fill' },
  { name: 'File Earmark Bar Graph', class: 'bi-file-earmark-bar-graph' },
  { name: 'File Earmark Bar Graph Fill', class: 'bi-file-earmark-bar-graph-fill' },
  { name: 'File Earmark Binary', class: 'bi-file-earmark-binary' },
  { name: 'File Earmark Binary Fill', class: 'bi-file-earmark-binary-fill' },
  { name: 'File Earmark Break', class: 'bi-file-earmark-break' },
  { name: 'File Earmark Break Fill', class: 'bi-file-earmark-break-fill' },
  { name: 'File Earmark Check', class: 'bi-file-earmark-check' },
  { name: 'File Earmark Check Fill', class: 'bi-file-earmark-check-fill' },
  { name: 'File Earmark Code', class: 'bi-file-earmark-code' },
  { name: 'File Earmark Code Fill', class: 'bi-file-earmark-code-fill' },
  { name: 'File Earmark Diff', class: 'bi-file-earmark-diff' },
  { name: 'File Earmark Diff Fill', class: 'bi-file-earmark-diff-fill' },
  { name: 'File Earmark Easel', class: 'bi-file-earmark-easel' },
  { name: 'File Earmark Easel Fill', class: 'bi-file-earmark-easel-fill' },
  { name: 'File Earmark Excel', class: 'bi-file-earmark-excel' },
  { name: 'File Earmark Excel Fill', class: 'bi-file-earmark-excel-fill' },
  { name: 'File Earmark Fill', class: 'bi-file-earmark-fill' },
  { name: 'File Earmark Font', class: 'bi-file-earmark-font' },
  { name: 'File Earmark Font Fill', class: 'bi-file-earmark-font-fill' },
  { name: 'File Earmark Image', class: 'bi-file-earmark-image' },
  { name: 'File Earmark Image Fill', class: 'bi-file-earmark-image-fill' },
  { name: 'File Earmark Lock', class: 'bi-file-earmark-lock' },
  { name: 'File Earmark Lock Fill', class: 'bi-file-earmark-lock-fill' },
  { name: 'File Earmark Lock2', class: 'bi-file-earmark-lock2' },
  { name: 'File Earmark Lock2 Fill', class: 'bi-file-earmark-lock2-fill' },
  { name: 'File Earmark Medical', class: 'bi-file-earmark-medical' },
  { name: 'File Earmark Medical Fill', class: 'bi-file-earmark-medical-fill' },
  { name: 'File Earmark Minus', class: 'bi-file-earmark-minus' },
  { name: 'File Earmark Minus Fill', class: 'bi-file-earmark-minus-fill' },
  { name: 'File Earmark Music', class: 'bi-file-earmark-music' },
  { name: 'File Earmark Music Fill', class: 'bi-file-earmark-music-fill' },
  { name: 'File Earmark Pdf', class: 'bi-file-earmark-pdf' },
  { name: 'File Earmark Pdf Fill', class: 'bi-file-earmark-pdf-fill' },
  { name: 'File Earmark Person', class: 'bi-file-earmark-person' },
  { name: 'File Earmark Person Fill', class: 'bi-file-earmark-person-fill' },
  { name: 'File Earmark Play', class: 'bi-file-earmark-play' },
  { name: 'File Earmark Play Fill', class: 'bi-file-earmark-play-fill' },
  { name: 'File Earmark Plus', class: 'bi-file-earmark-plus' },
  { name: 'File Earmark Plus Fill', class: 'bi-file-earmark-plus-fill' },
  { name: 'File Earmark Post', class: 'bi-file-earmark-post' },
  { name: 'File Earmark Post Fill', class: 'bi-file-earmark-post-fill' },
  { name: 'File Earmark Ppt', class: 'bi-file-earmark-ppt' },
  { name: 'File Earmark Ppt Fill', class: 'bi-file-earmark-ppt-fill' },
  { name: 'File Earmark Richtext', class: 'bi-file-earmark-richtext' },
  { name: 'File Earmark Richtext Fill', class: 'bi-file-earmark-richtext-fill' },
  { name: 'File Earmark Ruled', class: 'bi-file-earmark-ruled' },
  { name: 'File Earmark Ruled Fill', class: 'bi-file-earmark-ruled-fill' },
  { name: 'File Earmark Slides', class: 'bi-file-earmark-slides' },
  { name: 'File Earmark Slides Fill', class: 'bi-file-earmark-slides-fill' },
  { name: 'File Earmark Spreadsheet', class: 'bi-file-earmark-spreadsheet' },
  { name: 'File Earmark Spreadsheet Fill', class: 'bi-file-earmark-spreadsheet-fill' },
  { name: 'File Earmark Text', class: 'bi-file-earmark-text' },
  { name: 'File Earmark Text Fill', class: 'bi-file-earmark-text-fill' },
  { name: 'File Earmark Word', class: 'bi-file-earmark-word' },
  { name: 'File Earmark Word Fill', class: 'bi-file-earmark-word-fill' },
  { name: 'File Earmark X', class: 'bi-file-earmark-x' },
  { name: 'File Earmark X Fill', class: 'bi-file-earmark-x-fill' },
  { name: 'File Earmark Zip', class: 'bi-file-earmark-zip' },
  { name: 'File Earmark Zip Fill', class: 'bi-file-earmark-zip-fill' },
  { name: 'File Easel', class: 'bi-file-easel' },
  { name: 'File Easel Fill', class: 'bi-file-easel-fill' },
  { name: 'File Excel', class: 'bi-file-excel' },
  { name: 'File Excel Fill', class: 'bi-file-excel-fill' },
  { name: 'File Fill', class: 'bi-file-fill' },
  { name: 'File Font', class: 'bi-file-font' },
  { name: 'File Font Fill', class: 'bi-file-font-fill' },
  { name: 'File Image', class: 'bi-file-image' },
  { name: 'File Image Fill', class: 'bi-file-image-fill' },
  { name: 'File Lock', class: 'bi-file-lock' },
  { name: 'File Lock Fill', class: 'bi-file-lock-fill' },
  { name: 'File Lock2', class: 'bi-file-lock2' },
  { name: 'File Lock2 Fill', class: 'bi-file-lock2-fill' },
  { name: 'File Medical', class: 'bi-file-medical' },
  { name: 'File Medical Fill', class: 'bi-file-medical-fill' },
  { name: 'File Minus', class: 'bi-file-minus' },
  { name: 'File Minus Fill', class: 'bi-file-minus-fill' },
  { name: 'File Music', class: 'bi-file-music' },
  { name: 'File Music Fill', class: 'bi-file-music-fill' },
  { name: 'File Pdf', class: 'bi-file-pdf' },
  { name: 'File Pdf Fill', class: 'bi-file-pdf-fill' },
  { name: 'File Person', class: 'bi-file-person' },
  { name: 'File Person Fill', class: 'bi-file-person-fill' },
  { name: 'File Play', class: 'bi-file-play' },
  { name: 'File Play Fill', class: 'bi-file-play-fill' },
  { name: 'File Plus', class: 'bi-file-plus' },
  { name: 'File Plus Fill', class: 'bi-file-plus-fill' },
  { name: 'File Post', class: 'bi-file-post' },
  { name: 'File Post Fill', class: 'bi-file-post-fill' },
  { name: 'File Ppt', class: 'bi-file-ppt' },
  { name: 'File Ppt Fill', class: 'bi-file-ppt-fill' },
  { name: 'File Richtext', class: 'bi-file-richtext' },
  { name: 'File Richtext Fill', class: 'bi-file-richtext-fill' },
  { name: 'File Ruled', class: 'bi-file-ruled' },
  { name: 'File Ruled Fill', class: 'bi-file-ruled-fill' },
  { name: 'File Slides', class: 'bi-file-slides' },
  { name: 'File Slides Fill', class: 'bi-file-slides-fill' },
  { name: 'File Spreadsheet', class: 'bi-file-spreadsheet' },
  { name: 'File Spreadsheet Fill', class: 'bi-file-spreadsheet-fill' },
  { name: 'File Text', class: 'bi-file-text' },
  { name: 'File Text Fill', class: 'bi-file-text-fill' },
  { name: 'File Word', class: 'bi-file-word' },
  { name: 'File Word Fill', class: 'bi-file-word-fill' },
  { name: 'File X', class: 'bi-file-x' },
  { name: 'File X Fill', class: 'bi-file-x-fill' },
  { name: 'File Zip', class: 'bi-file-zip' },
  { name: 'File Zip Fill', class: 'bi-file-zip-fill' },
  { name: 'Files', class: 'bi-files' },
  { name: 'Files Alt', class: 'bi-files-alt' },
  { name: 'Film', class: 'bi-film' },
  { name: 'Filter', class: 'bi-filter' },
  { name: 'Filter Circle', class: 'bi-filter-circle' },
  { name: 'Filter Circle Fill', class: 'bi-filter-circle-fill' },
  { name: 'Filter Left', class: 'bi-filter-left' },
  { name: 'Filter Right', class: 'bi-filter-right' },
  { name: 'Filter Square', class: 'bi-filter-square' },
  { name: 'Filter Square Fill', class: 'bi-filter-square-fill' },
  { name: 'Fingerprint', class: 'bi-fingerprint' },
  { name: 'Fire', class: 'bi-fire' },
  { name: 'Flag', class: 'bi-flag' },
  { name: 'Flag Fill', class: 'bi-flag-fill' },
  { name: 'Floppy', class: 'bi-floppy' },
  { name: 'Floppy Fill', class: 'bi-floppy-fill' },
  { name: 'Floppy2', class: 'bi-floppy2' },
  { name: 'Floppy2 Fill', class: 'bi-floppy2-fill' },
  { name: 'Flower1', class: 'bi-flower1' },
  { name: 'Flower2', class: 'bi-flower2' },
  { name: 'Flower3', class: 'bi-flower3' },
  { name: 'Folder', class: 'bi-folder' },
  { name: 'Folder Check', class: 'bi-folder-check' },
  { name: 'Folder Fill', class: 'bi-folder-fill' },
  { name: 'Folder Minus', class: 'bi-folder-minus' },
  { name: 'Folder Open', class: 'bi-folder-open' },
  { name: 'Folder Plus', class: 'bi-folder-plus' },
  { name: 'Folder Symlink', class: 'bi-folder-symlink' },
  { name: 'Folder Symlink Fill', class: 'bi-folder-symlink-fill' },
  { name: 'Folder X', class: 'bi-folder-x' },
  { name: 'Folder2', class: 'bi-folder2' },
  { name: 'Folder2 Open', class: 'bi-folder2-open' },
  { name: 'Fonts', class: 'bi-fonts' },
  { name: 'Forward', class: 'bi-forward' },
  { name: 'Forward Fill', class: 'bi-forward-fill' },
  { name: 'Front', class: 'bi-front' },
  { name: 'Fuel Pump', class: 'bi-fuel-pump' },
  { name: 'Fuel Pump Diesel', class: 'bi-fuel-pump-diesel' },
  { name: 'Fuel Pump Diesel Fill', class: 'bi-fuel-pump-diesel-fill' },
  { name: 'Fuel Pump Fill', class: 'bi-fuel-pump-fill' },
  { name: 'Fullscreen', class: 'bi-fullscreen' },
  { name: 'Fullscreen Exit', class: 'bi-fullscreen-exit' },
  { name: 'Funnel', class: 'bi-funnel' },
  { name: 'Funnel Fill', class: 'bi-funnel-fill' },
  
  // G
  { name: 'Gear', class: 'bi-gear' },
  { name: 'Gear Fill', class: 'bi-gear-fill' },
  { name: 'Gear Wide', class: 'bi-gear-wide' },
  { name: 'Gear Wide Connected', class: 'bi-gear-wide-connected' },
  { name: 'Gem', class: 'bi-gem' },
  { name: 'Gender Ambiguous', class: 'bi-gender-ambiguous' },
  { name: 'Gender Female', class: 'bi-gender-female' },
  { name: 'Gender Male', class: 'bi-gender-male' },
  { name: 'Gender Neuter', class: 'bi-gender-neuter' },
  { name: 'Gender Trans', class: 'bi-gender-trans' },
  { name: 'Geo', class: 'bi-geo' },
  { name: 'Geo Alt', class: 'bi-geo-alt' },
  { name: 'Geo Alt Fill', class: 'bi-geo-alt-fill' },
  { name: 'Geo Fill', class: 'bi-geo-fill' },
  { name: 'Gift', class: 'bi-gift' },
  { name: 'Gift Fill', class: 'bi-gift-fill' },
  { name: 'Git', class: 'bi-git' },
  { name: 'Github', class: 'bi-github' },
  { name: 'Gitlab', class: 'bi-gitlab' },
  { name: 'Globe', class: 'bi-globe' },
  { name: 'Globe Americas', class: 'bi-globe-americas' },
  { name: 'Globe Asia Australia', class: 'bi-globe-asia-australia' },
  { name: 'Globe Central South Asia', class: 'bi-globe-central-south-asia' },
  { name: 'Globe Europe Africa', class: 'bi-globe-europe-africa' },
  { name: 'Globe2', class: 'bi-globe2' },
  { name: 'Google', class: 'bi-google' },
  { name: 'Google Play', class: 'bi-google-play' },
  { name: 'GPU Card', class: 'bi-gpu-card' },
  { name: 'Graph Down', class: 'bi-graph-down' },
  { name: 'Graph Down Arrow', class: 'bi-graph-down-arrow' },
  { name: 'Graph Up', class: 'bi-graph-up' },
  { name: 'Graph Up Arrow', class: 'bi-graph-up-arrow' },
  { name: 'Grid', class: 'bi-grid' },
  { name: 'Grid 1x2', class: 'bi-grid-1x2' },
  { name: 'Grid 1x2 Fill', class: 'bi-grid-1x2-fill' },
  { name: 'Grid 3x2', class: 'bi-grid-3x2' },
  { name: 'Grid 3x2 Gap', class: 'bi-grid-3x2-gap' },
  { name: 'Grid 3x2 Gap Fill', class: 'bi-grid-3x2-gap-fill' },
  { name: 'Grid 3x3', class: 'bi-grid-3x3' },
  { name: 'Grid 3x3 Gap', class: 'bi-grid-3x3-gap' },
  { name: 'Grid 3x3 Gap Fill', class: 'bi-grid-3x3-gap-fill' },
  { name: 'Grid Fill', class: 'bi-grid-fill' },
  { name: 'Grip Horizontal', class: 'bi-grip-horizontal' },
  { name: 'Grip Vertical', class: 'bi-grip-vertical' },
  
  // H
  { name: 'H Circle', class: 'bi-h-circle' },
  { name: 'H Circle Fill', class: 'bi-h-circle-fill' },
  { name: 'H Square', class: 'bi-h-square' },
  { name: 'H Square Fill', class: 'bi-h-square-fill' },
  { name: 'Hammer', class: 'bi-hammer' },
  { name: 'Hand Index', class: 'bi-hand-index' },
  { name: 'Hand Index Fill', class: 'bi-hand-index-fill' },
  { name: 'Hand Index Thumb', class: 'bi-hand-index-thumb' },
  { name: 'Hand Index Thumb Fill', class: 'bi-hand-index-thumb-fill' },
  { name: 'Hand Thumbs Down', class: 'bi-hand-thumbs-down' },
  { name: 'Hand Thumbs Down Fill', class: 'bi-hand-thumbs-down-fill' },
  { name: 'Hand Thumbs Up', class: 'bi-hand-thumbs-up' },
  { name: 'Hand Thumbs Up Fill', class: 'bi-hand-thumbs-up-fill' },
  { name: 'Handbag', class: 'bi-handbag' },
  { name: 'Handbag Fill', class: 'bi-handbag-fill' },
  { name: 'Hash', class: 'bi-hash' },
  { name: 'Hdd', class: 'bi-hdd' },
  { name: 'Hdd Fill', class: 'bi-hdd-fill' },
  { name: 'Hdd Network', class: 'bi-hdd-network' },
  { name: 'Hdd Network Fill', class: 'bi-hdd-network-fill' },
  { name: 'Hdd Rack', class: 'bi-hdd-rack' },
  { name: 'Hdd Rack Fill', class: 'bi-hdd-rack-fill' },
  { name: 'Hdd Stack', class: 'bi-hdd-stack' },
  { name: 'Hdd Stack Fill', class: 'bi-hdd-stack-fill' },
  { name: 'HDMI', class: 'bi-hdmi' },
  { name: 'HDMI Fill', class: 'bi-hdmi-fill' },
  { name: 'Headphones', class: 'bi-headphones' },
  { name: 'Headset', class: 'bi-headset' },
  { name: 'Headset VR', class: 'bi-headset-vr' },
  { name: 'Heart', class: 'bi-heart' },
  { name: 'Heart Arrow', class: 'bi-heart-arrow' },
  { name: 'Heart Fill', class: 'bi-heart-fill' },
  { name: 'Heart Half', class: 'bi-heart-half' },
  { name: 'Heart Pulse', class: 'bi-heart-pulse' },
  { name: 'Heart Pulse Fill', class: 'bi-heart-pulse-fill' },
  { name: 'Heartbreak', class: 'bi-heartbreak' },
  { name: 'Heartbreak Fill', class: 'bi-heartbreak-fill' },
  { name: 'Hearts', class: 'bi-hearts' },
  { name: 'Heptagon', class: 'bi-heptagon' },
  { name: 'Heptagon Fill', class: 'bi-heptagon-fill' },
  { name: 'Heptagon Half', class: 'bi-heptagon-half' },
  { name: 'Hexagon', class: 'bi-hexagon' },
  { name: 'Hexagon Fill', class: 'bi-hexagon-fill' },
  { name: 'Hexagon Half', class: 'bi-hexagon-half' },
  { name: 'Highlighter', class: 'bi-highlighter' },
  { name: 'Highlights', class: 'bi-highlights' },
  { name: 'Hospital', class: 'bi-hospital' },
  { name: 'Hospital Fill', class: 'bi-hospital-fill' },
  { name: 'Hourglass', class: 'bi-hourglass' },
  { name: 'Hourglass Bottom', class: 'bi-hourglass-bottom' },
  { name: 'Hourglass Split', class: 'bi-hourglass-split' },
  { name: 'Hourglass Top', class: 'bi-hourglass-top' },
  { name: 'House', class: 'bi-house' },
  { name: 'House Add', class: 'bi-house-add' },
  { name: 'House Add Fill', class: 'bi-house-add-fill' },
  { name: 'House Check', class: 'bi-house-check' },
  { name: 'House Check Fill', class: 'bi-house-check-fill' },
  { name: 'House Dash', class: 'bi-house-dash' },
  { name: 'House Dash Fill', class: 'bi-house-dash-fill' },
  { name: 'House Door', class: 'bi-house-door' },
  { name: 'House Door Fill', class: 'bi-house-door-fill' },
  { name: 'House Down', class: 'bi-house-down' },
  { name: 'House Down Fill', class: 'bi-house-down-fill' },
  { name: 'House Exclamation', class: 'bi-house-exclamation' },
  { name: 'House Exclamation Fill', class: 'bi-house-exclamation-fill' },
  { name: 'House Fill', class: 'bi-house-fill' },
  { name: 'House Gear', class: 'bi-house-gear' },
  { name: 'House Gear Fill', class: 'bi-house-gear-fill' },
  { name: 'House Heart', class: 'bi-house-heart' },
  { name: 'House Heart Fill', class: 'bi-house-heart-fill' },
  { name: 'House Lock', class: 'bi-house-lock' },
  { name: 'House Lock Fill', class: 'bi-house-lock-fill' },
  { name: 'House Slash', class: 'bi-house-slash' },
  { name: 'House Slash Fill', class: 'bi-house-slash-fill' },
  { name: 'House Up', class: 'bi-house-up' },
  { name: 'House Up Fill', class: 'bi-house-up-fill' },
  { name: 'House X', class: 'bi-house-x' },
  { name: 'House X Fill', class: 'bi-house-x-fill' },
  { name: 'Houses', class: 'bi-houses' },
  { name: 'Houses Fill', class: 'bi-houses-fill' },
  { name: 'HR', class: 'bi-hr' },
  { name: 'Hurricane', class: 'bi-hurricane' },
  { name: 'Hypnotize', class: 'bi-hypnotize' },
  
  // I-Z would continue...
  // Total 1800+ icons
]