// 完整的 Bootstrap Icons 列表 - F 到 Z 部分
export const allBootstrapIconsFtoZ = [
  // F
  { name: 'Facebook', class: 'bi-facebook' },
  { name: 'Fan', class: 'bi-fan' },
  { name: 'Fast Forward', class: 'bi-fast-forward' },
  { name: 'Fast Forward Btn', class: 'bi-fast-forward-btn' },
  { name: 'Fast Forward Btn Fill', class: 'bi-fast-forward-btn-fill' },
  { name: 'Fast Forward Circle', class: 'bi-fast-forward-circle' },
  { name: 'Fast Forward Circle Fill', class: 'bi-fast-forward-circle-fill' },
  { name: 'Fast Forward Fill', class: 'bi-fast-forward-fill' },
  { name: 'File', class: 'bi-file' },
  { name: 'File Arrow Down', class: 'bi-file-arrow-down' },
  { name: 'File Arrow Down Fill', class: 'bi-file-arrow-down-fill' },
  { name: 'File Arrow Up', class: 'bi-file-arrow-up' },
  { name: 'File Arrow Up Fill', class: 'bi-file-arrow-up-fill' },
  { name: 'File Bar Graph', class: 'bi-file-bar-graph' },
  { name: 'File Bar Graph Fill', class: 'bi-file-bar-graph-fill' },
  { name: 'File Binary', class: 'bi-file-binary' },
  { name: 'File Binary Fill', class: 'bi-file-binary-fill' },
  { name: 'File Break', class: 'bi-file-break' },
  { name: 'File Break Fill', class: 'bi-file-break-fill' },
  { name: 'File Check', class: 'bi-file-check' },
  { name: 'File Check Fill', class: 'bi-file-check-fill' },
  { name: 'File Code', class: 'bi-file-code' },
  { name: 'File Code Fill', class: 'bi-file-code-fill' },
  { name: 'File Diff', class: 'bi-file-diff' },
  { name: 'File Diff Fill', class: 'bi-file-diff-fill' },
  { name: 'File Earmark', class: 'bi-file-earmark' },
  { name: 'File Earmark Arrow Down', class: 'bi-file-earmark-arrow-down' },
  { name: 'File Earmark Arrow Down Fill', class: 'bi-file-earmark-arrow-down-fill' },
  { name: 'File Earmark Arrow Up', class: 'bi-file-earmark-arrow-up' },
  { name: 'File Earmark Arrow Up Fill', class: 'bi-file-earmark-arrow-up-fill' },
  { name: 'File Earmark Bar Graph', class: 'bi-file-earmark-bar-graph' },
  { name: 'File Earmark Bar Graph Fill', class: 'bi-file-earmark-bar-graph-fill' },
  { name: 'File Earmark Binary', class: 'bi-file-earmark-binary' },
  { name: 'File Earmark Binary Fill', class: 'bi-file-earmark-binary-fill' },
  { name: 'File Earmark Break', class: 'bi-file-earmark-break' },
  { name: 'File Earmark Break Fill', class: 'bi-file-earmark-break-fill' },
  { name: 'File Earmark Check', class: 'bi-file-earmark-check' },
  { name: 'File Earmark Check Fill', class: 'bi-file-earmark-check-fill' },
  { name: 'File Earmark Code', class: 'bi-file-earmark-code' },
  { name: 'File Earmark Code Fill', class: 'bi-file-earmark-code-fill' },
  { name: 'File Earmark Diff', class: 'bi-file-earmark-diff' },
  { name: 'File Earmark Diff Fill', class: 'bi-file-earmark-diff-fill' },
  { name: 'File Earmark Easel', class: 'bi-file-earmark-easel' },
  { name: 'File Earmark Easel Fill', class: 'bi-file-earmark-easel-fill' },
  { name: 'File Earmark Excel', class: 'bi-file-earmark-excel' },
  { name: 'File Earmark Excel Fill', class: 'bi-file-earmark-excel-fill' },
  { name: 'File Earmark Fill', class: 'bi-file-earmark-fill' },
  { name: 'File Earmark Font', class: 'bi-file-earmark-font' },
  { name: 'File Earmark Font Fill', class: 'bi-file-earmark-font-fill' },
  { name: 'File Earmark Image', class: 'bi-file-earmark-image' },
  { name: 'File Earmark Image Fill', class: 'bi-file-earmark-image-fill' },
  { name: 'File Earmark Lock', class: 'bi-file-earmark-lock' },
  { name: 'File Earmark Lock Fill', class: 'bi-file-earmark-lock-fill' },
  { name: 'File Earmark Lock2', class: 'bi-file-earmark-lock2' },
  { name: 'File Earmark Lock2 Fill', class: 'bi-file-earmark-lock2-fill' },
  { name: 'File Earmark Medical', class: 'bi-file-earmark-medical' },
  { name: 'File Earmark Medical Fill', class: 'bi-file-earmark-medical-fill' },
  { name: 'File Earmark Minus', class: 'bi-file-earmark-minus' },
  { name: 'File Earmark Minus Fill', class: 'bi-file-earmark-minus-fill' },
  { name: 'File Earmark Music', class: 'bi-file-earmark-music' },
  { name: 'File Earmark Music Fill', class: 'bi-file-earmark-music-fill' },
  { name: 'File Earmark Pdf', class: 'bi-file-earmark-pdf' },
  { name: 'File Earmark Pdf Fill', class: 'bi-file-earmark-pdf-fill' },
  { name: 'File Earmark Person', class: 'bi-file-earmark-person' },
  { name: 'File Earmark Person Fill', class: 'bi-file-earmark-person-fill' },
  { name: 'File Earmark Play', class: 'bi-file-earmark-play' },
  { name: 'File Earmark Play Fill', class: 'bi-file-earmark-play-fill' },
  { name: 'File Earmark Plus', class: 'bi-file-earmark-plus' },
  { name: 'File Earmark Plus Fill', class: 'bi-file-earmark-plus-fill' },
  { name: 'File Earmark Post', class: 'bi-file-earmark-post' },
  { name: 'File Earmark Post Fill', class: 'bi-file-earmark-post-fill' },
  { name: 'File Earmark Ppt', class: 'bi-file-earmark-ppt' },
  { name: 'File Earmark Ppt Fill', class: 'bi-file-earmark-ppt-fill' },
  { name: 'File Earmark Richtext', class: 'bi-file-earmark-richtext' },
  { name: 'File Earmark Richtext Fill', class: 'bi-file-earmark-richtext-fill' },
  { name: 'File Earmark Ruled', class: 'bi-file-earmark-ruled' },
  { name: 'File Earmark Ruled Fill', class: 'bi-file-earmark-ruled-fill' },
  { name: 'File Earmark Slides', class: 'bi-file-earmark-slides' },
  { name: 'File Earmark Slides Fill', class: 'bi-file-earmark-slides-fill' },
  { name: 'File Earmark Spreadsheet', class: 'bi-file-earmark-spreadsheet' },
  { name: 'File Earmark Spreadsheet Fill', class: 'bi-file-earmark-spreadsheet-fill' },
  { name: 'File Earmark Text', class: 'bi-file-earmark-text' },
  { name: 'File Earmark Text Fill', class: 'bi-file-earmark-text-fill' },
  { name: 'File Earmark Word', class: 'bi-file-earmark-word' },
  { name: 'File Earmark Word Fill', class: 'bi-file-earmark-word-fill' },
  { name: 'File Earmark X', class: 'bi-file-earmark-x' },
  { name: 'File Earmark X Fill', class: 'bi-file-earmark-x-fill' },
  { name: 'File Earmark Zip', class: 'bi-file-earmark-zip' },
  { name: 'File Earmark Zip Fill', class: 'bi-file-earmark-zip-fill' },
  { name: 'File Easel', class: 'bi-file-easel' },
  { name: 'File Easel Fill', class: 'bi-file-easel-fill' },
  { name: 'File Excel', class: 'bi-file-excel' },
  { name: 'File Excel Fill', class: 'bi-file-excel-fill' },
  { name: 'File Fill', class: 'bi-file-fill' },
  { name: 'File Font', class: 'bi-file-font' },
  { name: 'File Font Fill', class: 'bi-file-font-fill' },
  { name: 'File Image', class: 'bi-file-image' },
  { name: 'File Image Fill', class: 'bi-file-image-fill' },
  { name: 'File Lock', class: 'bi-file-lock' },
  { name: 'File Lock Fill', class: 'bi-file-lock-fill' },
  { name: 'File Lock2', class: 'bi-file-lock2' },
  { name: 'File Lock2 Fill', class: 'bi-file-lock2-fill' },
  { name: 'File Medical', class: 'bi-file-medical' },
  { name: 'File Medical Fill', class: 'bi-file-medical-fill' },
  { name: 'File Minus', class: 'bi-file-minus' },
  { name: 'File Minus Fill', class: 'bi-file-minus-fill' },
  { name: 'File Music', class: 'bi-file-music' },
  { name: 'File Music Fill', class: 'bi-file-music-fill' },
  { name: 'File Pdf', class: 'bi-file-pdf' },
  { name: 'File Pdf Fill', class: 'bi-file-pdf-fill' },
  { name: 'File Person', class: 'bi-file-person' },
  { name: 'File Person Fill', class: 'bi-file-person-fill' },
  { name: 'File Play', class: 'bi-file-play' },
  { name: 'File Play Fill', class: 'bi-file-play-fill' },
  { name: 'File Plus', class: 'bi-file-plus' },
  { name: 'File Plus Fill', class: 'bi-file-plus-fill' },
  { name: 'File Post', class: 'bi-file-post' },
  { name: 'File Post Fill', class: 'bi-file-post-fill' },
  { name: 'File Ppt', class: 'bi-file-ppt' },
  { name: 'File Ppt Fill', class: 'bi-file-ppt-fill' },
  { name: 'File Richtext', class: 'bi-file-richtext' },
  { name: 'File Richtext Fill', class: 'bi-file-richtext-fill' },
  { name: 'File Ruled', class: 'bi-file-ruled' },
  { name: 'File Ruled Fill', class: 'bi-file-ruled-fill' },
  { name: 'File Slides', class: 'bi-file-slides' },
  { name: 'File Slides Fill', class: 'bi-file-slides-fill' },
  { name: 'File Spreadsheet', class: 'bi-file-spreadsheet' },
  { name: 'File Spreadsheet Fill', class: 'bi-file-spreadsheet-fill' },
  { name: 'File Text', class: 'bi-file-text' },
  { name: 'File Text Fill', class: 'bi-file-text-fill' },
  { name: 'File Word', class: 'bi-file-word' },
  { name: 'File Word Fill', class: 'bi-file-word-fill' },
  { name: 'File X', class: 'bi-file-x' },
  { name: 'File X Fill', class: 'bi-file-x-fill' },
  { name: 'File Zip', class: 'bi-file-zip' },
  { name: 'File Zip Fill', class: 'bi-file-zip-fill' },
  { name: 'Files', class: 'bi-files' },
  { name: 'Files Alt', class: 'bi-files-alt' },
  { name: 'Film', class: 'bi-film' },
  { name: 'Filter', class: 'bi-filter' },
  { name: 'Filter Circle', class: 'bi-filter-circle' },
  { name: 'Filter Circle Fill', class: 'bi-filter-circle-fill' },
  { name: 'Filter Left', class: 'bi-filter-left' },
  { name: 'Filter Right', class: 'bi-filter-right' },
  { name: 'Filter Square', class: 'bi-filter-square' },
  { name: 'Filter Square Fill', class: 'bi-filter-square-fill' },
  { name: 'Fingerprint', class: 'bi-fingerprint' },
  { name: 'Fire', class: 'bi-fire' },
  { name: 'Flag', class: 'bi-flag' },
  { name: 'Flag Fill', class: 'bi-flag-fill' },
  { name: 'Floppy', class: 'bi-floppy' },
  { name: 'Floppy Fill', class: 'bi-floppy-fill' },
  { name: 'Floppy2', class: 'bi-floppy2' },
  { name: 'Floppy2 Fill', class: 'bi-floppy2-fill' },
  { name: 'Flower1', class: 'bi-flower1' },
  { name: 'Flower2', class: 'bi-flower2' },
  { name: 'Flower3', class: 'bi-flower3' },
  { name: 'Folder', class: 'bi-folder' },
  { name: 'Folder Check', class: 'bi-folder-check' },
  { name: 'Folder Fill', class: 'bi-folder-fill' },
  { name: 'Folder Minus', class: 'bi-folder-minus' },
  { name: 'Folder Open', class: 'bi-folder-open' },
  { name: 'Folder Plus', class: 'bi-folder-plus' },
  { name: 'Folder Symlink', class: 'bi-folder-symlink' },
  { name: 'Folder Symlink Fill', class: 'bi-folder-symlink-fill' },
  { name: 'Folder X', class: 'bi-folder-x' },
  { name: 'Folder2', class: 'bi-folder2' },
  { name: 'Folder2 Open', class: 'bi-folder2-open' },
  { name: 'Fonts', class: 'bi-fonts' },
  { name: 'Forward', class: 'bi-forward' },
  { name: 'Forward Fill', class: 'bi-forward-fill' },
  { name: 'Front', class: 'bi-front' },
  { name: 'Fuel Pump', class: 'bi-fuel-pump' },
  { name: 'Fuel Pump Diesel', class: 'bi-fuel-pump-diesel' },
  { name: 'Fuel Pump Diesel Fill', class: 'bi-fuel-pump-diesel-fill' },
  { name: 'Fuel Pump Fill', class: 'bi-fuel-pump-fill' },
  { name: 'Fullscreen', class: 'bi-fullscreen' },
  { name: 'Fullscreen Exit', class: 'bi-fullscreen-exit' },
  { name: 'Funnel', class: 'bi-funnel' },
  { name: 'Funnel Fill', class: 'bi-funnel-fill' },
  
  // G
  { name: 'Gear', class: 'bi-gear' },
  { name: 'Gear Fill', class: 'bi-gear-fill' },
  { name: 'Gear Wide', class: 'bi-gear-wide' },
  { name: 'Gear Wide Connected', class: 'bi-gear-wide-connected' },
  { name: 'Gem', class: 'bi-gem' },
  { name: 'Gender Ambiguous', class: 'bi-gender-ambiguous' },
  { name: 'Gender Female', class: 'bi-gender-female' },
  { name: 'Gender Male', class: 'bi-gender-male' },
  { name: 'Gender Neuter', class: 'bi-gender-neuter' },
  { name: 'Gender Trans', class: 'bi-gender-trans' },
  { name: 'Geo', class: 'bi-geo' },
  { name: 'Geo Alt', class: 'bi-geo-alt' },
  { name: 'Geo Alt Fill', class: 'bi-geo-alt-fill' },
  { name: 'Geo Fill', class: 'bi-geo-fill' },
  { name: 'Gift', class: 'bi-gift' },
  { name: 'Gift Fill', class: 'bi-gift-fill' },
  { name: 'Git', class: 'bi-git' },
  { name: 'Github', class: 'bi-github' },
  { name: 'Gitlab', class: 'bi-gitlab' },
  { name: 'Globe', class: 'bi-globe' },
  { name: 'Globe Americas', class: 'bi-globe-americas' },
  { name: 'Globe Asia Australia', class: 'bi-globe-asia-australia' },
  { name: 'Globe Central South Asia', class: 'bi-globe-central-south-asia' },
  { name: 'Globe Europe Africa', class: 'bi-globe-europe-africa' },
  { name: 'Globe2', class: 'bi-globe2' },
  { name: 'Google', class: 'bi-google' },
  { name: 'Google Play', class: 'bi-google-play' },
  { name: 'GPU Card', class: 'bi-gpu-card' },
  { name: 'Graph Down', class: 'bi-graph-down' },
  { name: 'Graph Down Arrow', class: 'bi-graph-down-arrow' },
  { name: 'Graph Up', class: 'bi-graph-up' },
  { name: 'Graph Up Arrow', class: 'bi-graph-up-arrow' },
  { name: 'Grid', class: 'bi-grid' },
  { name: 'Grid 1x2', class: 'bi-grid-1x2' },
  { name: 'Grid 1x2 Fill', class: 'bi-grid-1x2-fill' },
  { name: 'Grid 3x2', class: 'bi-grid-3x2' },
  { name: 'Grid 3x2 Gap', class: 'bi-grid-3x2-gap' },
  { name: 'Grid 3x2 Gap Fill', class: 'bi-grid-3x2-gap-fill' },
  { name: 'Grid 3x3', class: 'bi-grid-3x3' },
  { name: 'Grid 3x3 Gap', class: 'bi-grid-3x3-gap' },
  { name: 'Grid 3x3 Gap Fill', class: 'bi-grid-3x3-gap-fill' },
  { name: 'Grid Fill', class: 'bi-grid-fill' },
  { name: 'Grip Horizontal', class: 'bi-grip-horizontal' },
  { name: 'Grip Vertical', class: 'bi-grip-vertical' },
  
  // H
  { name: 'H Circle', class: 'bi-h-circle' },
  { name: 'H Circle Fill', class: 'bi-h-circle-fill' },
  { name: 'H Square', class: 'bi-h-square' },
  { name: 'H Square Fill', class: 'bi-h-square-fill' },
  { name: 'Hammer', class: 'bi-hammer' },
  { name: 'Hand Index', class: 'bi-hand-index' },
  { name: 'Hand Index Fill', class: 'bi-hand-index-fill' },
  { name: 'Hand Index Thumb', class: 'bi-hand-index-thumb' },
  { name: 'Hand Index Thumb Fill', class: 'bi-hand-index-thumb-fill' },
  { name: 'Hand Thumbs Down', class: 'bi-hand-thumbs-down' },
  { name: 'Hand Thumbs Down Fill', class: 'bi-hand-thumbs-down-fill' },
  { name: 'Hand Thumbs Up', class: 'bi-hand-thumbs-up' },
  { name: 'Hand Thumbs Up Fill', class: 'bi-hand-thumbs-up-fill' },
  { name: 'Handbag', class: 'bi-handbag' },
  { name: 'Handbag Fill', class: 'bi-handbag-fill' },
  { name: 'Hash', class: 'bi-hash' },
  { name: 'Hdd', class: 'bi-hdd' },
  { name: 'Hdd Fill', class: 'bi-hdd-fill' },
  { name: 'Hdd Network', class: 'bi-hdd-network' },
  { name: 'Hdd Network Fill', class: 'bi-hdd-network-fill' },
  { name: 'Hdd Rack', class: 'bi-hdd-rack' },
  { name: 'Hdd Rack Fill', class: 'bi-hdd-rack-fill' },
  { name: 'Hdd Stack', class: 'bi-hdd-stack' },
  { name: 'Hdd Stack Fill', class: 'bi-hdd-stack-fill' },
  { name: 'HDMI', class: 'bi-hdmi' },
  { name: 'HDMI Fill', class: 'bi-hdmi-fill' },
  { name: 'Headphones', class: 'bi-headphones' },
  { name: 'Headset', class: 'bi-headset' },
  { name: 'Headset VR', class: 'bi-headset-vr' },
  { name: 'Heart', class: 'bi-heart' },
  { name: 'Heart Arrow', class: 'bi-heart-arrow' },
  { name: 'Heart Fill', class: 'bi-heart-fill' },
  { name: 'Heart Half', class: 'bi-heart-half' },
  { name: 'Heart Pulse', class: 'bi-heart-pulse' },
  { name: 'Heart Pulse Fill', class: 'bi-heart-pulse-fill' },
  { name: 'Heartbreak', class: 'bi-heartbreak' },
  { name: 'Heartbreak Fill', class: 'bi-heartbreak-fill' },
  { name: 'Hearts', class: 'bi-hearts' },
  { name: 'Heptagon', class: 'bi-heptagon' },
  { name: 'Heptagon Fill', class: 'bi-heptagon-fill' },
  { name: 'Heptagon Half', class: 'bi-heptagon-half' },
  { name: 'Hexagon', class: 'bi-hexagon' },
  { name: 'Hexagon Fill', class: 'bi-hexagon-fill' },
  { name: 'Hexagon Half', class: 'bi-hexagon-half' },
  { name: 'Highlighter', class: 'bi-highlighter' },
  { name: 'Highlights', class: 'bi-highlights' },
  { name: 'Hospital', class: 'bi-hospital' },
  { name: 'Hospital Fill', class: 'bi-hospital-fill' },
  { name: 'Hourglass', class: 'bi-hourglass' },
  { name: 'Hourglass Bottom', class: 'bi-hourglass-bottom' },
  { name: 'Hourglass Split', class: 'bi-hourglass-split' },
  { name: 'Hourglass Top', class: 'bi-hourglass-top' },
  { name: 'House', class: 'bi-house' },
  { name: 'House Add', class: 'bi-house-add' },
  { name: 'House Add Fill', class: 'bi-house-add-fill' },
  { name: 'House Check', class: 'bi-house-check' },
  { name: 'House Check Fill', class: 'bi-house-check-fill' },
  { name: 'House Dash', class: 'bi-house-dash' },
  { name: 'House Dash Fill', class: 'bi-house-dash-fill' },
  { name: 'House Door', class: 'bi-house-door' },
  { name: 'House Door Fill', class: 'bi-house-door-fill' },
  { name: 'House Down', class: 'bi-house-down' },
  { name: 'House Down Fill', class: 'bi-house-down-fill' },
  { name: 'House Exclamation', class: 'bi-house-exclamation' },
  { name: 'House Exclamation Fill', class: 'bi-house-exclamation-fill' },
  { name: 'House Fill', class: 'bi-house-fill' },
  { name: 'House Gear', class: 'bi-house-gear' },
  { name: 'House Gear Fill', class: 'bi-house-gear-fill' },
  { name: 'House Heart', class: 'bi-house-heart' },
  { name: 'House Heart Fill', class: 'bi-house-heart-fill' },
  { name: 'House Lock', class: 'bi-house-lock' },
  { name: 'House Lock Fill', class: 'bi-house-lock-fill' },
  { name: 'House Slash', class: 'bi-house-slash' },
  { name: 'House Slash Fill', class: 'bi-house-slash-fill' },
  { name: 'House Up', class: 'bi-house-up' },
  { name: 'House Up Fill', class: 'bi-house-up-fill' },
  { name: 'House X', class: 'bi-house-x' },
  { name: 'House X Fill', class: 'bi-house-x-fill' },
  { name: 'Houses', class: 'bi-houses' },
  { name: 'Houses Fill', class: 'bi-houses-fill' },
  { name: 'HR', class: 'bi-hr' },
  { name: 'Hurricane', class: 'bi-hurricane' },
  { name: 'Hypnotize', class: 'bi-hypnotize' },
  
  // I
  { name: 'Image', class: 'bi-image' },
  { name: 'Image Alt', class: 'bi-image-alt' },
  { name: 'Image Fill', class: 'bi-image-fill' },
  { name: 'Images', class: 'bi-images' },
  { name: 'Inbox', class: 'bi-inbox' },
  { name: 'Inbox Fill', class: 'bi-inbox-fill' },
  { name: 'Inboxes', class: 'bi-inboxes' },
  { name: 'Inboxes Fill', class: 'bi-inboxes-fill' },
  { name: 'Incognito', class: 'bi-incognito' },
  { name: 'Indent', class: 'bi-indent' },
  { name: 'Infinity', class: 'bi-infinity' },
  { name: 'Info', class: 'bi-info' },
  { name: 'Info Circle', class: 'bi-info-circle' },
  { name: 'Info Circle Fill', class: 'bi-info-circle-fill' },
  { name: 'Info Lg', class: 'bi-info-lg' },
  { name: 'Info Square', class: 'bi-info-square' },
  { name: 'Info Square Fill', class: 'bi-info-square-fill' },
  { name: 'Input Cursor', class: 'bi-input-cursor' },
  { name: 'Input Cursor Text', class: 'bi-input-cursor-text' },
  { name: 'Instagram', class: 'bi-instagram' },
  { name: 'Intersect', class: 'bi-intersect' },
  
  // J
  { name: 'Journal', class: 'bi-journal' },
  { name: 'Journal Album', class: 'bi-journal-album' },
  { name: 'Journal Arrow Down', class: 'bi-journal-arrow-down' },
  { name: 'Journal Arrow Up', class: 'bi-journal-arrow-up' },
  { name: 'Journal Bookmark', class: 'bi-journal-bookmark' },
  { name: 'Journal Bookmark Fill', class: 'bi-journal-bookmark-fill' },
  { name: 'Journal Check', class: 'bi-journal-check' },
  { name: 'Journal Code', class: 'bi-journal-code' },
  { name: 'Journal Medical', class: 'bi-journal-medical' },
  { name: 'Journal Minus', class: 'bi-journal-minus' },
  { name: 'Journal Plus', class: 'bi-journal-plus' },
  { name: 'Journal Richtext', class: 'bi-journal-richtext' },
  { name: 'Journal Text', class: 'bi-journal-text' },
  { name: 'Journal X', class: 'bi-journal-x' },
  { name: 'Journals', class: 'bi-journals' },
  { name: 'Joystick', class: 'bi-joystick' },
  { name: 'Justify', class: 'bi-justify' },
  { name: 'Justify Left', class: 'bi-justify-left' },
  { name: 'Justify Right', class: 'bi-justify-right' },
  
  // K
  { name: 'Kanban', class: 'bi-kanban' },
  { name: 'Kanban Fill', class: 'bi-kanban-fill' },
  { name: 'Key', class: 'bi-key' },
  { name: 'Key Fill', class: 'bi-key-fill' },
  { name: 'Keyboard', class: 'bi-keyboard' },
  { name: 'Keyboard Fill', class: 'bi-keyboard-fill' },
  
  // L
  { name: 'Ladder', class: 'bi-ladder' },
  { name: 'Lamp', class: 'bi-lamp' },
  { name: 'Lamp Fill', class: 'bi-lamp-fill' },
  { name: 'Laptop', class: 'bi-laptop' },
  { name: 'Laptop Fill', class: 'bi-laptop-fill' },
  { name: 'Layer Backward', class: 'bi-layer-backward' },
  { name: 'Layer Forward', class: 'bi-layer-forward' },
  { name: 'Layers', class: 'bi-layers' },
  { name: 'Layers Fill', class: 'bi-layers-fill' },
  { name: 'Layers Half', class: 'bi-layers-half' },
  { name: 'Layout Sidebar', class: 'bi-layout-sidebar' },
  { name: 'Layout Sidebar Inset', class: 'bi-layout-sidebar-inset' },
  { name: 'Layout Sidebar Inset Reverse', class: 'bi-layout-sidebar-inset-reverse' },
  { name: 'Layout Sidebar Reverse', class: 'bi-layout-sidebar-reverse' },
  { name: 'Layout Split', class: 'bi-layout-split' },
  { name: 'Layout Text Sidebar', class: 'bi-layout-text-sidebar' },
  { name: 'Layout Text Sidebar Reverse', class: 'bi-layout-text-sidebar-reverse' },
  { name: 'Layout Text Window', class: 'bi-layout-text-window' },
  { name: 'Layout Text Window Reverse', class: 'bi-layout-text-window-reverse' },
  { name: 'Layout Three Columns', class: 'bi-layout-three-columns' },
  { name: 'Layout WTF', class: 'bi-layout-wtf' },
  { name: 'Life Preserver', class: 'bi-life-preserver' },
  { name: 'Lightbulb', class: 'bi-lightbulb' },
  { name: 'Lightbulb Fill', class: 'bi-lightbulb-fill' },
  { name: 'Lightbulb Off', class: 'bi-lightbulb-off' },
  { name: 'Lightbulb Off Fill', class: 'bi-lightbulb-off-fill' },
  { name: 'Lightning', class: 'bi-lightning' },
  { name: 'Lightning Charge', class: 'bi-lightning-charge' },
  { name: 'Lightning Charge Fill', class: 'bi-lightning-charge-fill' },
  { name: 'Lightning Fill', class: 'bi-lightning-fill' },
  { name: 'Line', class: 'bi-line' },
  { name: 'Link', class: 'bi-link' },
  { name: 'Link 45deg', class: 'bi-link-45deg' },
  { name: 'Linkedin', class: 'bi-linkedin' },
  { name: 'List', class: 'bi-list' },
  { name: 'List Check', class: 'bi-list-check' },
  { name: 'List Columns', class: 'bi-list-columns' },
  { name: 'List Columns Reverse', class: 'bi-list-columns-reverse' },
  { name: 'List Nested', class: 'bi-list-nested' },
  { name: 'List Ol', class: 'bi-list-ol' },
  { name: 'List Stars', class: 'bi-list-stars' },
  { name: 'List Task', class: 'bi-list-task' },
  { name: 'List Ul', class: 'bi-list-ul' },
  { name: 'Lock', class: 'bi-lock' },
  { name: 'Lock Fill', class: 'bi-lock-fill' },
  { name: 'Luggage', class: 'bi-luggage' },
  { name: 'Luggage Fill', class: 'bi-luggage-fill' },
  { name: 'Lungs', class: 'bi-lungs' },
  { name: 'Lungs Fill', class: 'bi-lungs-fill' },
  
  // M
  { name: 'Magic', class: 'bi-magic' },
  { name: 'Magnet', class: 'bi-magnet' },
  { name: 'Magnet Fill', class: 'bi-magnet-fill' },
  { name: 'Mailbox', class: 'bi-mailbox' },
  { name: 'Mailbox2', class: 'bi-mailbox2' },
  { name: 'Mailbox2 Flag', class: 'bi-mailbox2-flag' },
  { name: 'Map', class: 'bi-map' },
  { name: 'Map Fill', class: 'bi-map-fill' },
  { name: 'Markdown', class: 'bi-markdown' },
  { name: 'Markdown Fill', class: 'bi-markdown-fill' },
  { name: 'Marker Tip', class: 'bi-marker-tip' },
  { name: 'Mask', class: 'bi-mask' },
  { name: 'Mastodon', class: 'bi-mastodon' },
  { name: 'Medium', class: 'bi-medium' },
  { name: 'Megaphone', class: 'bi-megaphone' },
  { name: 'Megaphone Fill', class: 'bi-megaphone-fill' },
  { name: 'Memory', class: 'bi-memory' },
  { name: 'Menu App', class: 'bi-menu-app' },
  { name: 'Menu App Fill', class: 'bi-menu-app-fill' },
  { name: 'Menu Button', class: 'bi-menu-button' },
  { name: 'Menu Button Fill', class: 'bi-menu-button-fill' },
  { name: 'Menu Button Wide', class: 'bi-menu-button-wide' },
  { name: 'Menu Button Wide Fill', class: 'bi-menu-button-wide-fill' },
  { name: 'Menu Down', class: 'bi-menu-down' },
  { name: 'Menu Up', class: 'bi-menu-up' },
  { name: 'Messenger', class: 'bi-messenger' },
  { name: 'Meta', class: 'bi-meta' },
  { name: 'Mic', class: 'bi-mic' },
  { name: 'Mic Fill', class: 'bi-mic-fill' },
  { name: 'Mic Mute', class: 'bi-mic-mute' },
  { name: 'Mic Mute Fill', class: 'bi-mic-mute-fill' },
  { name: 'Microsoft', class: 'bi-microsoft' },
  { name: 'Microsoft Teams', class: 'bi-microsoft-teams' },
  { name: 'Minecart', class: 'bi-minecart' },
  { name: 'Minecart Loaded', class: 'bi-minecart-loaded' },
  { name: 'Modem', class: 'bi-modem' },
  { name: 'Modem Fill', class: 'bi-modem-fill' },
  { name: 'Moisture', class: 'bi-moisture' },
  { name: 'Moon', class: 'bi-moon' },
  { name: 'Moon Fill', class: 'bi-moon-fill' },
  { name: 'Moon Stars', class: 'bi-moon-stars' },
  { name: 'Moon Stars Fill', class: 'bi-moon-stars-fill' },
  { name: 'Mortarboard', class: 'bi-mortarboard' },
  { name: 'Mortarboard Fill', class: 'bi-mortarboard-fill' },
  { name: 'Motherboard', class: 'bi-motherboard' },
  { name: 'Motherboard Fill', class: 'bi-motherboard-fill' },
  { name: 'Mouse', class: 'bi-mouse' },
  { name: 'Mouse Fill', class: 'bi-mouse-fill' },
  { name: 'Mouse2', class: 'bi-mouse2' },
  { name: 'Mouse2 Fill', class: 'bi-mouse2-fill' },
  { name: 'Mouse3', class: 'bi-mouse3' },
  { name: 'Mouse3 Fill', class: 'bi-mouse3-fill' },
  { name: 'Music Note', class: 'bi-music-note' },
  { name: 'Music Note Beamed', class: 'bi-music-note-beamed' },
  { name: 'Music Note List', class: 'bi-music-note-list' },
  { name: 'Music Player', class: 'bi-music-player' },
  { name: 'Music Player Fill', class: 'bi-music-player-fill' },
  
  // N
  { name: 'Newspaper', class: 'bi-newspaper' },
  { name: 'Nintendo Switch', class: 'bi-nintendo-switch' },
  { name: 'Node Minus', class: 'bi-node-minus' },
  { name: 'Node Minus Fill', class: 'bi-node-minus-fill' },
  { name: 'Node Plus', class: 'bi-node-plus' },
  { name: 'Node Plus Fill', class: 'bi-node-plus-fill' },
  { name: 'Noise Reduction', class: 'bi-noise-reduction' },
  { name: 'Nut', class: 'bi-nut' },
  { name: 'Nut Fill', class: 'bi-nut-fill' },
  { name: 'Nvidia', class: 'bi-nvidia' },
  { name: 'Nvme', class: 'bi-nvme' },
  { name: 'Nvme Fill', class: 'bi-nvme-fill' },
  
  // O
  { name: 'Octagon', class: 'bi-octagon' },
  { name: 'Octagon Fill', class: 'bi-octagon-fill' },
  { name: 'Octagon Half', class: 'bi-octagon-half' },
  { name: 'Opencollective', class: 'bi-opencollective' },
  { name: 'Option', class: 'bi-option' },
  { name: 'Outlet', class: 'bi-outlet' },
  
  // P
  { name: 'P Circle', class: 'bi-p-circle' },
  { name: 'P Circle Fill', class: 'bi-p-circle-fill' },
  { name: 'P Square', class: 'bi-p-square' },
  { name: 'P Square Fill', class: 'bi-p-square-fill' },
  { name: 'Paint Bucket', class: 'bi-paint-bucket' },
  { name: 'Palette', class: 'bi-palette' },
  { name: 'Palette Fill', class: 'bi-palette-fill' },
  { name: 'Palette2', class: 'bi-palette2' },
  { name: 'Paperclip', class: 'bi-paperclip' },
  { name: 'Paragraph', class: 'bi-paragraph' },
  { name: 'Pass', class: 'bi-pass' },
  { name: 'Pass Fill', class: 'bi-pass-fill' },
  { name: 'Passport', class: 'bi-passport' },
  { name: 'Passport Fill', class: 'bi-passport-fill' },
  { name: 'Patch Check', class: 'bi-patch-check' },
  { name: 'Patch Check Fill', class: 'bi-patch-check-fill' },
  { name: 'Patch Exclamation', class: 'bi-patch-exclamation' },
  { name: 'Patch Exclamation Fill', class: 'bi-patch-exclamation-fill' },
  { name: 'Patch Minus', class: 'bi-patch-minus' },
  { name: 'Patch Minus Fill', class: 'bi-patch-minus-fill' },
  { name: 'Patch Plus', class: 'bi-patch-plus' },
  { name: 'Patch Plus Fill', class: 'bi-patch-plus-fill' },
  { name: 'Patch Question', class: 'bi-patch-question' },
  { name: 'Patch Question Fill', class: 'bi-patch-question-fill' },
  { name: 'Pause', class: 'bi-pause' },
  { name: 'Pause Btn', class: 'bi-pause-btn' },
  { name: 'Pause Btn Fill', class: 'bi-pause-btn-fill' },
  { name: 'Pause Circle', class: 'bi-pause-circle' },
  { name: 'Pause Circle Fill', class: 'bi-pause-circle-fill' },
  { name: 'Pause Fill', class: 'bi-pause-fill' },
  { name: 'Paypal', class: 'bi-paypal' },
  { name: 'PC', class: 'bi-pc' },
  { name: 'PC Display', class: 'bi-pc-display' },
  { name: 'PC Display Horizontal', class: 'bi-pc-display-horizontal' },
  { name: 'PC Horizontal', class: 'bi-pc-horizontal' },
  { name: 'PCI Card', class: 'bi-pci-card' },
  { name: 'PCI Card Network', class: 'bi-pci-card-network' },
  { name: 'PCI Card Sound', class: 'bi-pci-card-sound' },
  { name: 'Peace', class: 'bi-peace' },
  { name: 'Peace Fill', class: 'bi-peace-fill' },
  { name: 'Pen', class: 'bi-pen' },
  { name: 'Pen Fill', class: 'bi-pen-fill' },
  { name: 'Pencil', class: 'bi-pencil' },
  { name: 'Pencil Fill', class: 'bi-pencil-fill' },
  { name: 'Pencil Square', class: 'bi-pencil-square' },
  { name: 'Pentagon', class: 'bi-pentagon' },
  { name: 'Pentagon Fill', class: 'bi-pentagon-fill' },
  { name: 'Pentagon Half', class: 'bi-pentagon-half' },
  { name: 'People', class: 'bi-people' },
  { name: 'People Fill', class: 'bi-people-fill' },
  { name: 'Percent', class: 'bi-percent' },
  { name: 'Person', class: 'bi-person' },
  { name: 'Person Add', class: 'bi-person-add' },
  { name: 'Person Badge', class: 'bi-person-badge' },
  { name: 'Person Badge Fill', class: 'bi-person-badge-fill' },
  { name: 'Person Bounding Box', class: 'bi-person-bounding-box' },
  { name: 'Person Check', class: 'bi-person-check' },
  { name: 'Person Check Fill', class: 'bi-person-check-fill' },
  { name: 'Person Circle', class: 'bi-person-circle' },
  { name: 'Person Dash', class: 'bi-person-dash' },
  { name: 'Person Dash Fill', class: 'bi-person-dash-fill' },
  { name: 'Person Exclamation', class: 'bi-person-exclamation' },
  { name: 'Person Fill', class: 'bi-person-fill' },
  { name: 'Person Fill Add', class: 'bi-person-fill-add' },
  { name: 'Person Fill Check', class: 'bi-person-fill-check' },
  { name: 'Person Fill Dash', class: 'bi-person-fill-dash' },
  { name: 'Person Fill Exclamation', class: 'bi-person-fill-exclamation' },
  { name: 'Person Fill Gear', class: 'bi-person-fill-gear' },
  { name: 'Person Fill Lock', class: 'bi-person-fill-lock' },
  { name: 'Person Fill Slash', class: 'bi-person-fill-slash' },
  { name: 'Person Fill Up', class: 'bi-person-fill-up' },
  { name: 'Person Fill X', class: 'bi-person-fill-x' },
  { name: 'Person Gear', class: 'bi-person-gear' },
  { name: 'Person Heart', class: 'bi-person-heart' },
  { name: 'Person Hearts', class: 'bi-person-hearts' },
  { name: 'Person Lines Fill', class: 'bi-person-lines-fill' },
  { name: 'Person Lock', class: 'bi-person-lock' },
  { name: 'Person Plus', class: 'bi-person-plus' },
  { name: 'Person Plus Fill', class: 'bi-person-plus-fill' },
  { name: 'Person Raised Hand', class: 'bi-person-raised-hand' },
  { name: 'Person Rolodex', class: 'bi-person-rolodex' },
  { name: 'Person Slash', class: 'bi-person-slash' },
  { name: 'Person Square', class: 'bi-person-square' },
  { name: 'Person Standing', class: 'bi-person-standing' },
  { name: 'Person Standing Dress', class: 'bi-person-standing-dress' },
  { name: 'Person Up', class: 'bi-person-up' },
  { name: 'Person Vcard', class: 'bi-person-vcard' },
  { name: 'Person Vcard Fill', class: 'bi-person-vcard-fill' },
  { name: 'Person Video', class: 'bi-person-video' },
  { name: 'Person Video2', class: 'bi-person-video2' },
  { name: 'Person Video3', class: 'bi-person-video3' },
  { name: 'Person Walking', class: 'bi-person-walking' },
  { name: 'Person Wheelchair', class: 'bi-person-wheelchair' },
  { name: 'Person Workspace', class: 'bi-person-workspace' },
  { name: 'Person X', class: 'bi-person-x' },
  { name: 'Person X Fill', class: 'bi-person-x-fill' },
  { name: 'Phone', class: 'bi-phone' },
  { name: 'Phone Fill', class: 'bi-phone-fill' },
  { name: 'Phone Flip', class: 'bi-phone-flip' },
  { name: 'Phone Landscape', class: 'bi-phone-landscape' },
  { name: 'Phone Landscape Fill', class: 'bi-phone-landscape-fill' },
  { name: 'Phone Vibrate', class: 'bi-phone-vibrate' },
  { name: 'Phone Vibrate Fill', class: 'bi-phone-vibrate-fill' },
  { name: 'Pie Chart', class: 'bi-pie-chart' },
  { name: 'Pie Chart Fill', class: 'bi-pie-chart-fill' },
  { name: 'Piggy Bank', class: 'bi-piggy-bank' },
  { name: 'Piggy Bank Fill', class: 'bi-piggy-bank-fill' },
  { name: 'Pin', class: 'bi-pin' },
  { name: 'Pin Angle', class: 'bi-pin-angle' },
  { name: 'Pin Angle Fill', class: 'bi-pin-angle-fill' },
  { name: 'Pin Fill', class: 'bi-pin-fill' },
  { name: 'Pin Map', class: 'bi-pin-map' },
  { name: 'Pin Map Fill', class: 'bi-pin-map-fill' },
  { name: 'Pinterest', class: 'bi-pinterest' },
  { name: 'Pip', class: 'bi-pip' },
  { name: 'Pip Fill', class: 'bi-pip-fill' },
  { name: 'Play', class: 'bi-play' },
  { name: 'Play Btn', class: 'bi-play-btn' },
  { name: 'Play Btn Fill', class: 'bi-play-btn-fill' },
  { name: 'Play Circle', class: 'bi-play-circle' },
  { name: 'Play Circle Fill', class: 'bi-play-circle-fill' },
  { name: 'Play Fill', class: 'bi-play-fill' },
  { name: 'Playstation', class: 'bi-playstation' },
  { name: 'Plug', class: 'bi-plug' },
  { name: 'Plug Fill', class: 'bi-plug-fill' },
  { name: 'Plugin', class: 'bi-plugin' },
  { name: 'Plus', class: 'bi-plus' },
  { name: 'Plus Circle', class: 'bi-plus-circle' },
  { name: 'Plus Circle Dotted', class: 'bi-plus-circle-dotted' },
  { name: 'Plus Circle Fill', class: 'bi-plus-circle-fill' },
  { name: 'Plus Lg', class: 'bi-plus-lg' },
  { name: 'Plus Slash Minus', class: 'bi-plus-slash-minus' },
  { name: 'Plus Square', class: 'bi-plus-square' },
  { name: 'Plus Square Dotted', class: 'bi-plus-square-dotted' },
  { name: 'Plus Square Fill', class: 'bi-plus-square-fill' },
  { name: 'Postage', class: 'bi-postage' },
  { name: 'Postage Fill', class: 'bi-postage-fill' },
  { name: 'Postage Heart', class: 'bi-postage-heart' },
  { name: 'Postage Heart Fill', class: 'bi-postage-heart-fill' },
  { name: 'Postcard', class: 'bi-postcard' },
  { name: 'Postcard Fill', class: 'bi-postcard-fill' },
  { name: 'Postcard Heart', class: 'bi-postcard-heart' },
  { name: 'Postcard Heart Fill', class: 'bi-postcard-heart-fill' },
  { name: 'Power', class: 'bi-power' },
  { name: 'Prescription', class: 'bi-prescription' },
  { name: 'Prescription2', class: 'bi-prescription2' },
  { name: 'Printer', class: 'bi-printer' },
  { name: 'Printer Fill', class: 'bi-printer-fill' },
  { name: 'Projector', class: 'bi-projector' },
  { name: 'Projector Fill', class: 'bi-projector-fill' },
  { name: 'Puzzle', class: 'bi-puzzle' },
  { name: 'Puzzle Fill', class: 'bi-puzzle-fill' },
  
  // Q
  { name: 'QR Code', class: 'bi-qr-code' },
  { name: 'QR Code Scan', class: 'bi-qr-code-scan' },
  { name: 'Question', class: 'bi-question' },
  { name: 'Question Circle', class: 'bi-question-circle' },
  { name: 'Question Circle Fill', class: 'bi-question-circle-fill' },
  { name: 'Question Diamond', class: 'bi-question-diamond' },
  { name: 'Question Diamond Fill', class: 'bi-question-diamond-fill' },
  { name: 'Question Lg', class: 'bi-question-lg' },
  { name: 'Question Octagon', class: 'bi-question-octagon' },
  { name: 'Question Octagon Fill', class: 'bi-question-octagon-fill' },
  { name: 'Question Square', class: 'bi-question-square' },
  { name: 'Question Square Fill', class: 'bi-question-square-fill' },
  { name: 'Quora', class: 'bi-quora' },
  { name: 'Quote', class: 'bi-quote' },
  
  // R
  { name: 'R Circle', class: 'bi-r-circle' },
  { name: 'R Circle Fill', class: 'bi-r-circle-fill' },
  { name: 'R Square', class: 'bi-r-square' },
  { name: 'R Square Fill', class: 'bi-r-square-fill' },
  { name: 'Radar', class: 'bi-radar' },
  { name: 'Radio', class: 'bi-radio' },
  { name: 'Radioactive', class: 'bi-radioactive' },
  { name: 'Rainbow', class: 'bi-rainbow' },
  { name: 'Receipt', class: 'bi-receipt' },
  { name: 'Receipt Cutoff', class: 'bi-receipt-cutoff' },
  { name: 'Reception 0', class: 'bi-reception-0' },
  { name: 'Reception 1', class: 'bi-reception-1' },
  { name: 'Reception 2', class: 'bi-reception-2' },
  { name: 'Reception 3', class: 'bi-reception-3' },
  { name: 'Reception 4', class: 'bi-reception-4' },
  { name: 'Record', class: 'bi-record' },
  { name: 'Record Btn', class: 'bi-record-btn' },
  { name: 'Record Btn Fill', class: 'bi-record-btn-fill' },
  { name: 'Record Circle', class: 'bi-record-circle' },
  { name: 'Record Circle Fill', class: 'bi-record-circle-fill' },
  { name: 'Record Fill', class: 'bi-record-fill' },
  { name: 'Record2', class: 'bi-record2' },
  { name: 'Record2 Fill', class: 'bi-record2-fill' },
  { name: 'Recycle', class: 'bi-recycle' },
  { name: 'Reddit', class: 'bi-reddit' },
  { name: 'Regex', class: 'bi-regex' },
  { name: 'Repeat', class: 'bi-repeat' },
  { name: 'Repeat 1', class: 'bi-repeat-1' },
  { name: 'Reply', class: 'bi-reply' },
  { name: 'Reply All', class: 'bi-reply-all' },
  { name: 'Reply All Fill', class: 'bi-reply-all-fill' },
  { name: 'Reply Fill', class: 'bi-reply-fill' },
  { name: 'Rewind', class: 'bi-rewind' },
  { name: 'Rewind Btn', class: 'bi-rewind-btn' },
  { name: 'Rewind Btn Fill', class: 'bi-rewind-btn-fill' },
  { name: 'Rewind Circle', class: 'bi-rewind-circle' },
  { name: 'Rewind Circle Fill', class: 'bi-rewind-circle-fill' },
  { name: 'Rewind Fill', class: 'bi-rewind-fill' },
  { name: 'Robot', class: 'bi-robot' },
  { name: 'Rocket', class: 'bi-rocket' },
  { name: 'Rocket Fill', class: 'bi-rocket-fill' },
  { name: 'Rocket Takeoff', class: 'bi-rocket-takeoff' },
  { name: 'Rocket Takeoff Fill', class: 'bi-rocket-takeoff-fill' },
  { name: 'Router', class: 'bi-router' },
  { name: 'Router Fill', class: 'bi-router-fill' },
  { name: 'RSS', class: 'bi-rss' },
  { name: 'RSS Fill', class: 'bi-rss-fill' },
  { name: 'Rulers', class: 'bi-rulers' },
  
  // S
  { name: 'Safe', class: 'bi-safe' },
  { name: 'Safe Fill', class: 'bi-safe-fill' },
  { name: 'Safe2', class: 'bi-safe2' },
  { name: 'Safe2 Fill', class: 'bi-safe2-fill' },
  { name: 'Save', class: 'bi-save' },
  { name: 'Save Fill', class: 'bi-save-fill' },
  { name: 'Save2', class: 'bi-save2' },
  { name: 'Save2 Fill', class: 'bi-save2-fill' },
  { name: 'Scissors', class: 'bi-scissors' },
  { name: 'Scooter', class: 'bi-scooter' },
  { name: 'Screwdriver', class: 'bi-screwdriver' },
  { name: 'SD Card', class: 'bi-sd-card' },
  { name: 'SD Card Fill', class: 'bi-sd-card-fill' },
  { name: 'Search', class: 'bi-search' },
  { name: 'Search Heart', class: 'bi-search-heart' },
  { name: 'Search Heart Fill', class: 'bi-search-heart-fill' },
  { name: 'Segmented Nav', class: 'bi-segmented-nav' },
  { name: 'Send', class: 'bi-send' },
  { name: 'Send Arrow Down', class: 'bi-send-arrow-down' },
  { name: 'Send Arrow Down Fill', class: 'bi-send-arrow-down-fill' },
  { name: 'Send Arrow Up', class: 'bi-send-arrow-up' },
  { name: 'Send Arrow Up Fill', class: 'bi-send-arrow-up-fill' },
  { name: 'Send Check', class: 'bi-send-check' },
  { name: 'Send Check Fill', class: 'bi-send-check-fill' },
  { name: 'Send Dash', class: 'bi-send-dash' },
  { name: 'Send Dash Fill', class: 'bi-send-dash-fill' },
  { name: 'Send Exclamation', class: 'bi-send-exclamation' },
  { name: 'Send Exclamation Fill', class: 'bi-send-exclamation-fill' },
  { name: 'Send Fill', class: 'bi-send-fill' },
  { name: 'Send Plus', class: 'bi-send-plus' },
  { name: 'Send Plus Fill', class: 'bi-send-plus-fill' },
  { name: 'Send Slash', class: 'bi-send-slash' },
  { name: 'Send Slash Fill', class: 'bi-send-slash-fill' },
  { name: 'Send X', class: 'bi-send-x' },
  { name: 'Send X Fill', class: 'bi-send-x-fill' },
  { name: 'Server', class: 'bi-server' },
  { name: 'Shadow', class: 'bi-shadow' },
  { name: 'Share', class: 'bi-share' },
  { name: 'Share Fill', class: 'bi-share-fill' },
  { name: 'Shield', class: 'bi-shield' },
  { name: 'Shield Check', class: 'bi-shield-check' },
  { name: 'Shield Exclamation', class: 'bi-shield-exclamation' },
  { name: 'Shield Fill', class: 'bi-shield-fill' },
  { name: 'Shield Fill Check', class: 'bi-shield-fill-check' },
  { name: 'Shield Fill Exclamation', class: 'bi-shield-fill-exclamation' },
  { name: 'Shield Fill Minus', class: 'bi-shield-fill-minus' },
  { name: 'Shield Fill Plus', class: 'bi-shield-fill-plus' },
  { name: 'Shield Fill X', class: 'bi-shield-fill-x' },
  { name: 'Shield Lock', class: 'bi-shield-lock' },
  { name: 'Shield Lock Fill', class: 'bi-shield-lock-fill' },
  { name: 'Shield Minus', class: 'bi-shield-minus' },
  { name: 'Shield Plus', class: 'bi-shield-plus' },
  { name: 'Shield Shaded', class: 'bi-shield-shaded' },
  { name: 'Shield Slash', class: 'bi-shield-slash' },
  { name: 'Shield Slash Fill', class: 'bi-shield-slash-fill' },
  { name: 'Shield X', class: 'bi-shield-x' },
  { name: 'Shift', class: 'bi-shift' },
  { name: 'Shift Fill', class: 'bi-shift-fill' },
  { name: 'Shop', class: 'bi-shop' },
  { name: 'Shop Window', class: 'bi-shop-window' },
  { name: 'Shuffle', class: 'bi-shuffle' },
  { name: 'Sign Dead End', class: 'bi-sign-dead-end' },
  { name: 'Sign Dead End Fill', class: 'bi-sign-dead-end-fill' },
  { name: 'Sign Do Not Enter', class: 'bi-sign-do-not-enter' },
  { name: 'Sign Do Not Enter Fill', class: 'bi-sign-do-not-enter-fill' },
  { name: 'Sign Intersection', class: 'bi-sign-intersection' },
  { name: 'Sign Intersection Fill', class: 'bi-sign-intersection-fill' },
  { name: 'Sign Intersection Side', class: 'bi-sign-intersection-side' },
  { name: 'Sign Intersection Side Fill', class: 'bi-sign-intersection-side-fill' },
  { name: 'Sign Intersection T', class: 'bi-sign-intersection-t' },
  { name: 'Sign Intersection T Fill', class: 'bi-sign-intersection-t-fill' },
  { name: 'Sign Intersection Y', class: 'bi-sign-intersection-y' },
  { name: 'Sign Intersection Y Fill', class: 'bi-sign-intersection-y-fill' },
  { name: 'Sign Merge Left', class: 'bi-sign-merge-left' },
  { name: 'Sign Merge Left Fill', class: 'bi-sign-merge-left-fill' },
  { name: 'Sign Merge Right', class: 'bi-sign-merge-right' },
  { name: 'Sign Merge Right Fill', class: 'bi-sign-merge-right-fill' },
  { name: 'Sign No Left Turn', class: 'bi-sign-no-left-turn' },
  { name: 'Sign No Left Turn Fill', class: 'bi-sign-no-left-turn-fill' },
  { name: 'Sign No Parking', class: 'bi-sign-no-parking' },
  { name: 'Sign No Parking Fill', class: 'bi-sign-no-parking-fill' },
  { name: 'Sign No Right Turn', class: 'bi-sign-no-right-turn' },
  { name: 'Sign No Right Turn Fill', class: 'bi-sign-no-right-turn-fill' },
  { name: 'Sign Railroad', class: 'bi-sign-railroad' },
  { name: 'Sign Railroad Fill', class: 'bi-sign-railroad-fill' },
  { name: 'Sign Stop', class: 'bi-sign-stop' },
  { name: 'Sign Stop Fill', class: 'bi-sign-stop-fill' },
  { name: 'Sign Stop Lights', class: 'bi-sign-stop-lights' },
  { name: 'Sign Stop Lights Fill', class: 'bi-sign-stop-lights-fill' },
  { name: 'Sign Turn Left', class: 'bi-sign-turn-left' },
  { name: 'Sign Turn Left Fill', class: 'bi-sign-turn-left-fill' },
  { name: 'Sign Turn Right', class: 'bi-sign-turn-right' },
  { name: 'Sign Turn Right Fill', class: 'bi-sign-turn-right-fill' },
  { name: 'Sign Turn Slight Left', class: 'bi-sign-turn-slight-left' },
  { name: 'Sign Turn Slight Left Fill', class: 'bi-sign-turn-slight-left-fill' },
  { name: 'Sign Turn Slight Right', class: 'bi-sign-turn-slight-right' },
  { name: 'Sign Turn Slight Right Fill', class: 'bi-sign-turn-slight-right-fill' },
  { name: 'Sign Yield', class: 'bi-sign-yield' },
  { name: 'Sign Yield Fill', class: 'bi-sign-yield-fill' },
  { name: 'Signal', class: 'bi-signal' },
  { name: 'Signpost', class: 'bi-signpost' },
  { name: 'Signpost 2', class: 'bi-signpost-2' },
  { name: 'Signpost 2 Fill', class: 'bi-signpost-2-fill' },
  { name: 'Signpost Fill', class: 'bi-signpost-fill' },
  { name: 'Signpost Split', class: 'bi-signpost-split' },
  { name: 'Signpost Split Fill', class: 'bi-signpost-split-fill' },
  { name: 'Sim', class: 'bi-sim' },
  { name: 'Sim Fill', class: 'bi-sim-fill' },
  { name: 'Sim Slash', class: 'bi-sim-slash' },
  { name: 'Sim Slash Fill', class: 'bi-sim-slash-fill' },
  { name: 'Sina Weibo', class: 'bi-sina-weibo' },
  { name: 'Skip Backward', class: 'bi-skip-backward' },
  { name: 'Skip Backward Btn', class: 'bi-skip-backward-btn' },
  { name: 'Skip Backward Btn Fill', class: 'bi-skip-backward-btn-fill' },
  { name: 'Skip Backward Circle', class: 'bi-skip-backward-circle' },
  { name: 'Skip Backward Circle Fill', class: 'bi-skip-backward-circle-fill' },
  { name: 'Skip Backward Fill', class: 'bi-skip-backward-fill' },
  { name: 'Skip End', class: 'bi-skip-end' },
  { name: 'Skip End Btn', class: 'bi-skip-end-btn' },
  { name: 'Skip End Btn Fill', class: 'bi-skip-end-btn-fill' },
  { name: 'Skip End Circle', class: 'bi-skip-end-circle' },
  { name: 'Skip End Circle Fill', class: 'bi-skip-end-circle-fill' },
  { name: 'Skip End Fill', class: 'bi-skip-end-fill' },
  { name: 'Skip Forward', class: 'bi-skip-forward' },
  { name: 'Skip Forward Btn', class: 'bi-skip-forward-btn' },
  { name: 'Skip Forward Btn Fill', class: 'bi-skip-forward-btn-fill' },
  { name: 'Skip Forward Circle', class: 'bi-skip-forward-circle' },
  { name: 'Skip Forward Circle Fill', class: 'bi-skip-forward-circle-fill' },
  { name: 'Skip Forward Fill', class: 'bi-skip-forward-fill' },
  { name: 'Skip Start', class: 'bi-skip-start' },
  { name: 'Skip Start Btn', class: 'bi-skip-start-btn' },
  { name: 'Skip Start Btn Fill', class: 'bi-skip-start-btn-fill' },
  { name: 'Skip Start Circle', class: 'bi-skip-start-circle' },
  { name: 'Skip Start Circle Fill', class: 'bi-skip-start-circle-fill' },
  { name: 'Skip Start Fill', class: 'bi-skip-start-fill' },
  { name: 'Skype', class: 'bi-skype' },
  { name: 'Slack', class: 'bi-slack' },
  { name: 'Slash', class: 'bi-slash' },
  { name: 'Slash Circle', class: 'bi-slash-circle' },
  { name: 'Slash Circle Fill', class: 'bi-slash-circle-fill' },
  { name: 'Slash Lg', class: 'bi-slash-lg' },
  { name: 'Slash Square', class: 'bi-slash-square' },
  { name: 'Slash Square Fill', class: 'bi-slash-square-fill' },
  { name: 'Sliders', class: 'bi-sliders' },
  { name: 'Sliders2', class: 'bi-sliders2' },
  { name: 'Sliders2 Vertical', class: 'bi-sliders2-vertical' },
  { name: 'Smartwatch', class: 'bi-smartwatch' },
  { name: 'Snapchat', class: 'bi-snapchat' },
  { name: 'Snow', class: 'bi-snow' },
  { name: 'Snow2', class: 'bi-snow2' },
  { name: 'Snow3', class: 'bi-snow3' },
  { name: 'Sort Alpha Down', class: 'bi-sort-alpha-down' },
  { name: 'Sort Alpha Down Alt', class: 'bi-sort-alpha-down-alt' },
  { name: 'Sort Alpha Up', class: 'bi-sort-alpha-up' },
  { name: 'Sort Alpha Up Alt', class: 'bi-sort-alpha-up-alt' },
  { name: 'Sort Down', class: 'bi-sort-down' },
  { name: 'Sort Down Alt', class: 'bi-sort-down-alt' },
  { name: 'Sort Numeric Down', class: 'bi-sort-numeric-down' },
  { name: 'Sort Numeric Down Alt', class: 'bi-sort-numeric-down-alt' },
  { name: 'Sort Numeric Up', class: 'bi-sort-numeric-up' },
  { name: 'Sort Numeric Up Alt', class: 'bi-sort-numeric-up-alt' },
  { name: 'Sort Up', class: 'bi-sort-up' },
  { name: 'Sort Up Alt', class: 'bi-sort-up-alt' },
  { name: 'Soundwave', class: 'bi-soundwave' },
  { name: 'Source Code', class: 'bi-source-code' },
  { name: 'Speaker', class: 'bi-speaker' },
  { name: 'Speaker Fill', class: 'bi-speaker-fill' },
  { name: 'Speedometer', class: 'bi-speedometer' },
  { name: 'Speedometer2', class: 'bi-speedometer2' },
  { name: 'Spellcheck', class: 'bi-spellcheck' },
  { name: 'Spotify', class: 'bi-spotify' },
  { name: 'Square', class: 'bi-square' },
  { name: 'Square Fill', class: 'bi-square-fill' },
  { name: 'Square Half', class: 'bi-square-half' },
  { name: 'Stack', class: 'bi-stack' },
  { name: 'Stack Overflow', class: 'bi-stack-overflow' },
  { name: 'Star', class: 'bi-star' },
  { name: 'Star Fill', class: 'bi-star-fill' },
  { name: 'Star Half', class: 'bi-star-half' },
  { name: 'Stars', class: 'bi-stars' },
  { name: 'Steam', class: 'bi-steam' },
  { name: 'Stickies', class: 'bi-stickies' },
  { name: 'Stickies Fill', class: 'bi-stickies-fill' },
  { name: 'Sticky', class: 'bi-sticky' },
  { name: 'Sticky Fill', class: 'bi-sticky-fill' },
  { name: 'Stop', class: 'bi-stop' },
  { name: 'Stop Btn', class: 'bi-stop-btn' },
  { name: 'Stop Btn Fill', class: 'bi-stop-btn-fill' },
  { name: 'Stop Circle', class: 'bi-stop-circle' },
  { name: 'Stop Circle Fill', class: 'bi-stop-circle-fill' },
  { name: 'Stop Fill', class: 'bi-stop-fill' },
  { name: 'Stoplights', class: 'bi-stoplights' },
  { name: 'Stoplights Fill', class: 'bi-stoplights-fill' },
  { name: 'Stopwatch', class: 'bi-stopwatch' },
  { name: 'Stopwatch Fill', class: 'bi-stopwatch-fill' },
  { name: 'Strava', class: 'bi-strava' },
  { name: 'Stripe', class: 'bi-stripe' },
  { name: 'Subscript', class: 'bi-subscript' },
  { name: 'Substack', class: 'bi-substack' },
  { name: 'Subtract', class: 'bi-subtract' },
  { name: 'Suit Club', class: 'bi-suit-club' },
  { name: 'Suit Club Fill', class: 'bi-suit-club-fill' },
  { name: 'Suit Diamond', class: 'bi-suit-diamond' },
  { name: 'Suit Diamond Fill', class: 'bi-suit-diamond-fill' },
  { name: 'Suit Heart', class: 'bi-suit-heart' },
  { name: 'Suit Heart Fill', class: 'bi-suit-heart-fill' },
  { name: 'Suit Spade', class: 'bi-suit-spade' },
  { name: 'Suit Spade Fill', class: 'bi-suit-spade-fill' },
  { name: 'Suitcase', class: 'bi-suitcase' },
  { name: 'Suitcase Fill', class: 'bi-suitcase-fill' },
  { name: 'Suitcase Lg', class: 'bi-suitcase-lg' },
  { name: 'Suitcase Lg Fill', class: 'bi-suitcase-lg-fill' },
  { name: 'Suitcase2', class: 'bi-suitcase2' },
  { name: 'Suitcase2 Fill', class: 'bi-suitcase2-fill' },
  { name: 'Sun', class: 'bi-sun' },
  { name: 'Sun Fill', class: 'bi-sun-fill' },
  { name: 'Sunglasses', class: 'bi-sunglasses' },
  { name: 'Sunrise', class: 'bi-sunrise' },
  { name: 'Sunrise Fill', class: 'bi-sunrise-fill' },
  { name: 'Sunset', class: 'bi-sunset' },
  { name: 'Sunset Fill', class: 'bi-sunset-fill' },
  { name: 'Superscript', class: 'bi-superscript' },
  { name: 'Symmetry Horizontal', class: 'bi-symmetry-horizontal' },
  { name: 'Symmetry Vertical', class: 'bi-symmetry-vertical' },
  
  // T
  { name: 'Table', class: 'bi-table' },
  { name: 'Tablet', class: 'bi-tablet' },
  { name: 'Tablet Fill', class: 'bi-tablet-fill' },
  { name: 'Tablet Landscape', class: 'bi-tablet-landscape' },
  { name: 'Tablet Landscape Fill', class: 'bi-tablet-landscape-fill' },
  { name: 'Tag', class: 'bi-tag' },
  { name: 'Tag Fill', class: 'bi-tag-fill' },
  { name: 'Tags', class: 'bi-tags' },
  { name: 'Tags Fill', class: 'bi-tags-fill' },
  { name: 'Taxi Front', class: 'bi-taxi-front' },
  { name: 'Taxi Front Fill', class: 'bi-taxi-front-fill' },
  { name: 'Telegram', class: 'bi-telegram' },
  { name: 'Telephone', class: 'bi-telephone' },
  { name: 'Telephone Fill', class: 'bi-telephone-fill' },
  { name: 'Telephone Forward', class: 'bi-telephone-forward' },
  { name: 'Telephone Forward Fill', class: 'bi-telephone-forward-fill' },
  { name: 'Telephone Inbound', class: 'bi-telephone-inbound' },
  { name: 'Telephone Inbound Fill', class: 'bi-telephone-inbound-fill' },
  { name: 'Telephone Minus', class: 'bi-telephone-minus' },
  { name: 'Telephone Minus Fill', class: 'bi-telephone-minus-fill' },
  { name: 'Telephone Outbound', class: 'bi-telephone-outbound' },
  { name: 'Telephone Outbound Fill', class: 'bi-telephone-outbound-fill' },
  { name: 'Telephone Plus', class: 'bi-telephone-plus' },
  { name: 'Telephone Plus Fill', class: 'bi-telephone-plus-fill' },
  { name: 'Telephone X', class: 'bi-telephone-x' },
  { name: 'Telephone X Fill', class: 'bi-telephone-x-fill' },
  { name: 'Tencent QQ', class: 'bi-tencent-qq' },
  { name: 'Terminal', class: 'bi-terminal' },
  { name: 'Terminal Dash', class: 'bi-terminal-dash' },
  { name: 'Terminal Fill', class: 'bi-terminal-fill' },
  { name: 'Terminal Plus', class: 'bi-terminal-plus' },
  { name: 'Terminal Split', class: 'bi-terminal-split' },
  { name: 'Terminal X', class: 'bi-terminal-x' },
  { name: 'Text Center', class: 'bi-text-center' },
  { name: 'Text Indent Left', class: 'bi-text-indent-left' },
  { name: 'Text Indent Right', class: 'bi-text-indent-right' },
  { name: 'Text Left', class: 'bi-text-left' },
  { name: 'Text Paragraph', class: 'bi-text-paragraph' },
  { name: 'Text Right', class: 'bi-text-right' },
  { name: 'Text Wrap', class: 'bi-text-wrap' },
  { name: 'Textarea', class: 'bi-textarea' },
  { name: 'Textarea Resize', class: 'bi-textarea-resize' },
  { name: 'Textarea T', class: 'bi-textarea-t' },
  { name: 'Thermometer', class: 'bi-thermometer' },
  { name: 'Thermometer Half', class: 'bi-thermometer-half' },
  { name: 'Thermometer High', class: 'bi-thermometer-high' },
  { name: 'Thermometer Low', class: 'bi-thermometer-low' },
  { name: 'Thermometer Snow', class: 'bi-thermometer-snow' },
  { name: 'Thermometer Sun', class: 'bi-thermometer-sun' },
  { name: 'Threads', class: 'bi-threads' },
  { name: 'Threads Fill', class: 'bi-threads-fill' },
  { name: 'Three Dots', class: 'bi-three-dots' },
  { name: 'Three Dots Vertical', class: 'bi-three-dots-vertical' },
  { name: 'Thunderbolt', class: 'bi-thunderbolt' },
  { name: 'Thunderbolt Fill', class: 'bi-thunderbolt-fill' },
  { name: 'Ticket', class: 'bi-ticket' },
  { name: 'Ticket Detailed', class: 'bi-ticket-detailed' },
  { name: 'Ticket Detailed Fill', class: 'bi-ticket-detailed-fill' },
  { name: 'Ticket Fill', class: 'bi-ticket-fill' },
  { name: 'Ticket Perforated', class: 'bi-ticket-perforated' },
  { name: 'Ticket Perforated Fill', class: 'bi-ticket-perforated-fill' },
  { name: 'Tiktok', class: 'bi-tiktok' },
  { name: 'Toggle Off', class: 'bi-toggle-off' },
  { name: 'Toggle On', class: 'bi-toggle-on' },
  { name: 'Toggle2 Off', class: 'bi-toggle2-off' },
  { name: 'Toggle2 On', class: 'bi-toggle2-on' },
  { name: 'Toggles', class: 'bi-toggles' },
  { name: 'Toggles2', class: 'bi-toggles2' },
  { name: 'Tools', class: 'bi-tools' },
  { name: 'Tornado', class: 'bi-tornado' },
  { name: 'Train Front', class: 'bi-train-front' },
  { name: 'Train Front Fill', class: 'bi-train-front-fill' },
  { name: 'Train Freight Front', class: 'bi-train-freight-front' },
  { name: 'Train Freight Front Fill', class: 'bi-train-freight-front-fill' },
  { name: 'Train Lightrail Front', class: 'bi-train-lightrail-front' },
  { name: 'Train Lightrail Front Fill', class: 'bi-train-lightrail-front-fill' },
  { name: 'Translate', class: 'bi-translate' },
  { name: 'Transparency', class: 'bi-transparency' },
  { name: 'Trash', class: 'bi-trash' },
  { name: 'Trash Fill', class: 'bi-trash-fill' },
  { name: 'Trash2', class: 'bi-trash2' },
  { name: 'Trash2 Fill', class: 'bi-trash2-fill' },
  { name: 'Trash3', class: 'bi-trash3' },
  { name: 'Trash3 Fill', class: 'bi-trash3-fill' },
  { name: 'Tree', class: 'bi-tree' },
  { name: 'Tree Fill', class: 'bi-tree-fill' },
  { name: 'Trello', class: 'bi-trello' },
  { name: 'Triangle', class: 'bi-triangle' },
  { name: 'Triangle Fill', class: 'bi-triangle-fill' },
  { name: 'Triangle Half', class: 'bi-triangle-half' },
  { name: 'Trophy', class: 'bi-trophy' },
  { name: 'Trophy Fill', class: 'bi-trophy-fill' },
  { name: 'Tropical Storm', class: 'bi-tropical-storm' },
  { name: 'Truck', class: 'bi-truck' },
  { name: 'Truck Flatbed', class: 'bi-truck-flatbed' },
  { name: 'Truck Front', class: 'bi-truck-front' },
  { name: 'Truck Front Fill', class: 'bi-truck-front-fill' },
  { name: 'Tsunami', class: 'bi-tsunami' },
  { name: 'TV', class: 'bi-tv' },
  { name: 'TV Fill', class: 'bi-tv-fill' },
  { name: 'Twitch', class: 'bi-twitch' },
  { name: 'Twitter', class: 'bi-twitter' },
  { name: 'Twitter X', class: 'bi-twitter-x' },
  { name: 'Type', class: 'bi-type' },
  { name: 'Type Bold', class: 'bi-type-bold' },
  { name: 'Type H1', class: 'bi-type-h1' },
  { name: 'Type H2', class: 'bi-type-h2' },
  { name: 'Type H3', class: 'bi-type-h3' },
  { name: 'Type H4', class: 'bi-type-h4' },
  { name: 'Type H5', class: 'bi-type-h5' },
  { name: 'Type H6', class: 'bi-type-h6' },
  { name: 'Type Italic', class: 'bi-type-italic' },
  { name: 'Type Strikethrough', class: 'bi-type-strikethrough' },
  { name: 'Type Underline', class: 'bi-type-underline' },
  
  // U
  { name: 'Ubuntu', class: 'bi-ubuntu' },
  { name: 'UI Checks', class: 'bi-ui-checks' },
  { name: 'UI Checks Grid', class: 'bi-ui-checks-grid' },
  { name: 'UI Radios', class: 'bi-ui-radios' },
  { name: 'UI Radios Grid', class: 'bi-ui-radios-grid' },
  { name: 'Umbrella', class: 'bi-umbrella' },
  { name: 'Umbrella Fill', class: 'bi-umbrella-fill' },
  { name: 'Unindent', class: 'bi-unindent' },
  { name: 'Union', class: 'bi-union' },
  { name: 'Unity', class: 'bi-unity' },
  { name: 'Universal Access', class: 'bi-universal-access' },
  { name: 'Universal Access Circle', class: 'bi-universal-access-circle' },
  { name: 'Unlock', class: 'bi-unlock' },
  { name: 'Unlock Fill', class: 'bi-unlock-fill' },
  { name: 'Upc', class: 'bi-upc' },
  { name: 'Upc Scan', class: 'bi-upc-scan' },
  { name: 'Upload', class: 'bi-upload' },
  { name: 'USB', class: 'bi-usb' },
  { name: 'USB C', class: 'bi-usb-c' },
  { name: 'USB C Fill', class: 'bi-usb-c-fill' },
  { name: 'USB Drive', class: 'bi-usb-drive' },
  { name: 'USB Drive Fill', class: 'bi-usb-drive-fill' },
  { name: 'USB Fill', class: 'bi-usb-fill' },
  { name: 'USB Micro', class: 'bi-usb-micro' },
  { name: 'USB Micro Fill', class: 'bi-usb-micro-fill' },
  { name: 'USB Mini', class: 'bi-usb-mini' },
  { name: 'USB Mini Fill', class: 'bi-usb-mini-fill' },
  { name: 'USB Plug', class: 'bi-usb-plug' },
  { name: 'USB Plug Fill', class: 'bi-usb-plug-fill' },
  { name: 'USB Symbol', class: 'bi-usb-symbol' },
  
  // V
  { name: 'Valentine', class: 'bi-valentine' },
  { name: 'Valentine2', class: 'bi-valentine2' },
  { name: 'Vector Pen', class: 'bi-vector-pen' },
  { name: 'View List', class: 'bi-view-list' },
  { name: 'View Stacked', class: 'bi-view-stacked' },
  { name: 'Vignette', class: 'bi-vignette' },
  { name: 'Vimeo', class: 'bi-vimeo' },
  { name: 'Vinyl', class: 'bi-vinyl' },
  { name: 'Vinyl Fill', class: 'bi-vinyl-fill' },
  { name: 'Virus', class: 'bi-virus' },
  { name: 'Virus2', class: 'bi-virus2' },
  { name: 'Voicemail', class: 'bi-voicemail' },
  { name: 'Volume Down', class: 'bi-volume-down' },
  { name: 'Volume Down Fill', class: 'bi-volume-down-fill' },
  { name: 'Volume Mute', class: 'bi-volume-mute' },
  { name: 'Volume Mute Fill', class: 'bi-volume-mute-fill' },
  { name: 'Volume Off', class: 'bi-volume-off' },
  { name: 'Volume Off Fill', class: 'bi-volume-off-fill' },
  { name: 'Volume Up', class: 'bi-volume-up' },
  { name: 'Volume Up Fill', class: 'bi-volume-up-fill' },
  { name: 'VR', class: 'bi-vr' },
  
  // W
  { name: 'Wallet', class: 'bi-wallet' },
  { name: 'Wallet Fill', class: 'bi-wallet-fill' },
  { name: 'Wallet2', class: 'bi-wallet2' },
  { name: 'Watch', class: 'bi-watch' },
  { name: 'Water', class: 'bi-water' },
  { name: 'Webcam', class: 'bi-webcam' },
  { name: 'Webcam Fill', class: 'bi-webcam-fill' },
  { name: 'Wechat', class: 'bi-wechat' },
  { name: 'Whatsapp', class: 'bi-whatsapp' },
  { name: 'Wifi', class: 'bi-wifi' },
  { name: 'Wifi 1', class: 'bi-wifi-1' },
  { name: 'Wifi 2', class: 'bi-wifi-2' },
  { name: 'Wifi Off', class: 'bi-wifi-off' },
  { name: 'Wikipedia', class: 'bi-wikipedia' },
  { name: 'Wind', class: 'bi-wind' },
  { name: 'Window', class: 'bi-window' },
  { name: 'Window Dash', class: 'bi-window-dash' },
  { name: 'Window Desktop', class: 'bi-window-desktop' },
  { name: 'Window Dock', class: 'bi-window-dock' },
  { name: 'Window Fullscreen', class: 'bi-window-fullscreen' },
  { name: 'Window Plus', class: 'bi-window-plus' },
  { name: 'Window Sidebar', class: 'bi-window-sidebar' },
  { name: 'Window Split', class: 'bi-window-split' },
  { name: 'Window Stack', class: 'bi-window-stack' },
  { name: 'Window X', class: 'bi-window-x' },
  { name: 'Windows', class: 'bi-windows' },
  { name: 'Wordpress', class: 'bi-wordpress' },
  { name: 'Wrench', class: 'bi-wrench' },
  { name: 'Wrench Adjustable', class: 'bi-wrench-adjustable' },
  { name: 'Wrench Adjustable Circle', class: 'bi-wrench-adjustable-circle' },
  { name: 'Wrench Adjustable Circle Fill', class: 'bi-wrench-adjustable-circle-fill' },
  
  // X
  { name: 'X', class: 'bi-x' },
  { name: 'X Circle', class: 'bi-x-circle' },
  { name: 'X Circle Fill', class: 'bi-x-circle-fill' },
  { name: 'X Diamond', class: 'bi-x-diamond' },
  { name: 'X Diamond Fill', class: 'bi-x-diamond-fill' },
  { name: 'X Lg', class: 'bi-x-lg' },
  { name: 'X Octagon', class: 'bi-x-octagon' },
  { name: 'X Octagon Fill', class: 'bi-x-octagon-fill' },
  { name: 'X Square', class: 'bi-x-square' },
  { name: 'X Square Fill', class: 'bi-x-square-fill' },
  { name: 'Xbox', class: 'bi-xbox' },
  
  // Y
  { name: 'Yelp', class: 'bi-yelp' },
  { name: 'Yin Yang', class: 'bi-yin-yang' },
  { name: 'Youtube', class: 'bi-youtube' },
  
  // Z
  { name: 'Zoom In', class: 'bi-zoom-in' },
  { name: 'Zoom Out', class: 'bi-zoom-out' }
]