// 完整的 Emoji 列表
export const allEmojis = [
  // 表情與情緒
  { name: '微笑', emoji: '😀', category: '表情' },
  { name: '露齒笑', emoji: '😃', category: '表情' },
  { name: '大笑', emoji: '😄', category: '表情' },
  { name: '眯眼笑', emoji: '😁', category: '表情' },
  { name: '笑哭', emoji: '😆', category: '表情' },
  { name: '汗笑', emoji: '😅', category: '表情' },
  { name: '笑翻', emoji: '🤣', category: '表情' },
  { name: '喜極而泣', emoji: '😂', category: '表情' },
  { name: '微微笑', emoji: '🙂', category: '表情' },
  { name: '倒臉', emoji: '🙃', category: '表情' },
  { name: '融化', emoji: '🫠', category: '表情' },
  { name: '眨眼', emoji: '😉', category: '表情' },
  { name: '羞笑', emoji: '😊', category: '表情' },
  { name: '天使', emoji: '😇', category: '表情' },
  { name: '愛心眼', emoji: '😍', category: '表情' },
  { name: '星星眼', emoji: '🤩', category: '表情' },
  { name: '飛吻', emoji: '😘', category: '表情' },
  { name: '親吻', emoji: '😗', category: '表情' },
  { name: '微笑2', emoji: '☺️', category: '表情' },
  { name: '親親', emoji: '😚', category: '表情' },
  { name: '含笑', emoji: '😙', category: '表情' },
  { name: '偷笑', emoji: '🥲', category: '表情' },
  { name: '吐舌', emoji: '😋', category: '表情' },
  { name: '吐舌眨眼', emoji: '😜', category: '表情' },
  { name: '搞怪', emoji: '🤪', category: '表情' },
  { name: '吐舌笑', emoji: '😝', category: '表情' },
  { name: '錢', emoji: '🤑', category: '表情' },
  { name: '擁抱', emoji: '🤗', category: '表情' },
  { name: '噓', emoji: '🤭', category: '表情' },
  { name: '偷看', emoji: '🫣', category: '表情' },
  { name: '安靜', emoji: '🤫', category: '表情' },
  { name: '沉思', emoji: '🤔', category: '表情' },
  { name: '敬禮', emoji: '🫡', category: '表情' },
  { name: '拉鍊嘴', emoji: '🤐', category: '表情' },
  { name: '挑眉', emoji: '🤨', category: '表情' },
  { name: '無語', emoji: '😐', category: '表情' },
  { name: '面無表情', emoji: '😑', category: '表情' },
  { name: '無口', emoji: '😶', category: '表情' },
  { name: '雲霧', emoji: '😶‍🌫️', category: '表情' },
  { name: '假笑', emoji: '😏', category: '表情' },
  { name: '不爽', emoji: '😒', category: '表情' },
  { name: '翻白眼', emoji: '🙄', category: '表情' },
  { name: '做鬼臉', emoji: '😬', category: '表情' },
  { name: '呼氣', emoji: '😮‍💨', category: '表情' },
  { name: '說謊', emoji: '🤥', category: '表情' },
  { name: '搖頭', emoji: '🫨', category: '表情' },
  { name: '鬆口氣', emoji: '😌', category: '表情' },
  { name: '沉思2', emoji: '😔', category: '表情' },
  { name: '睏', emoji: '😪', category: '表情' },
  { name: '流口水', emoji: '🤤', category: '表情' },
  { name: '睡覺', emoji: '😴', category: '表情' },
  { name: '口罩', emoji: '😷', category: '表情' },
  { name: '生病', emoji: '🤒', category: '表情' },
  { name: '包紮', emoji: '🤕', category: '表情' },
  { name: '噁心', emoji: '🤢', category: '表情' },
  { name: '嘔吐', emoji: '🤮', category: '表情' },
  { name: '打噴嚏', emoji: '🤧', category: '表情' },
  { name: '熱', emoji: '🥵', category: '表情' },
  { name: '冷', emoji: '🥶', category: '表情' },
  { name: '暈', emoji: '🥴', category: '表情' },
  { name: '頭暈', emoji: '😵', category: '表情' },
  { name: '眼冒金星', emoji: '😵‍💫', category: '表情' },
  { name: '爆炸頭', emoji: '🤯', category: '表情' },
  { name: '牛仔帽', emoji: '🤠', category: '表情' },
  { name: '派對', emoji: '🥳', category: '表情' },
  { name: '偽裝', emoji: '🥸', category: '表情' },
  { name: '墨鏡', emoji: '😎', category: '表情' },
  { name: '書呆子', emoji: '🤓', category: '表情' },
  { name: '單片眼鏡', emoji: '🧐', category: '表情' },
  { name: '困惑', emoji: '😕', category: '表情' },
  { name: '虛線臉', emoji: '🫥', category: '表情' },
  { name: '擔心', emoji: '😟', category: '表情' },
  { name: '微皺眉', emoji: '🙁', category: '表情' },
  { name: '皺眉', emoji: '☹️', category: '表情' },
  { name: '張嘴', emoji: '😮', category: '表情' },
  { name: '無言', emoji: '😯', category: '表情' },
  { name: '驚訝', emoji: '😲', category: '表情' },
  { name: '臉紅', emoji: '😳', category: '表情' },
  { name: '懇求', emoji: '🥺', category: '表情' },
  { name: '握手', emoji: '🫤', category: '表情' },
  { name: '皺眉張嘴', emoji: '😦', category: '表情' },
  { name: '痛苦', emoji: '😧', category: '表情' },
  { name: '害怕', emoji: '😨', category: '表情' },
  { name: '焦慮', emoji: '😰', category: '表情' },
  { name: '悲傷', emoji: '😥', category: '表情' },
  { name: '震驚', emoji: '😢', category: '表情' },
  { name: '哭泣', emoji: '😭', category: '表情' },
  { name: '尖叫', emoji: '😱', category: '表情' },
  { name: '困惑2', emoji: '😖', category: '表情' },
  { name: '受苦', emoji: '😣', category: '表情' },
  { name: '失望', emoji: '😞', category: '表情' },
  { name: '汗', emoji: '😓', category: '表情' },
  { name: '疲憊', emoji: '😩', category: '表情' },
  { name: '累', emoji: '😫', category: '表情' },
  { name: '打哈欠', emoji: '🥱', category: '表情' },
  { name: '生氣', emoji: '😤', category: '表情' },
  { name: '憤怒', emoji: '😡', category: '表情' },
  { name: '暴怒', emoji: '🤬', category: '表情' },
  { name: '骷髏', emoji: '💀', category: '表情' },
  { name: '頭骨', emoji: '☠️', category: '表情' },
  { name: '大便', emoji: '💩', category: '表情' },
  { name: '小丑', emoji: '🤡', category: '表情' },
  { name: '鬼', emoji: '👹', category: '表情' },
  { name: '魔鬼', emoji: '👺', category: '表情' },
  { name: '妖怪', emoji: '👻', category: '表情' },
  { name: '外星人', emoji: '👽', category: '表情' },
  { name: '機器人', emoji: '🤖', category: '表情' },
  
  // 手勢
  { name: '招手', emoji: '👋', category: '手勢' },
  { name: '舉手', emoji: '🤚', category: '手勢' },
  { name: '手掌', emoji: '🖐️', category: '手勢' },
  { name: '五指', emoji: '✋', category: '手勢' },
  { name: '火神禮', emoji: '🖖', category: '手勢' },
  { name: '右手', emoji: '🫱', category: '手勢' },
  { name: '左手', emoji: '🫲', category: '手勢' },
  { name: '掌心向下', emoji: '🫳', category: '手勢' },
  { name: '掌心向上', emoji: '🫴', category: '手勢' },
  { name: '點手指', emoji: '🫵', category: '手勢' },
  { name: 'OK', emoji: '👌', category: '手勢' },
  { name: '夾', emoji: '🤌', category: '手勢' },
  { name: '捏', emoji: '🤏', category: '手勢' },
  { name: '勝利', emoji: '✌️', category: '手勢' },
  { name: '交叉手指', emoji: '🤞', category: '手勢' },
  { name: '手心愛心', emoji: '🫰', category: '手勢' },
  { name: '愛你手勢', emoji: '🤟', category: '手勢' },
  { name: '搖滾', emoji: '🤘', category: '手勢' },
  { name: '打電話', emoji: '🤙', category: '手勢' },
  { name: '手背左', emoji: '👈', category: '手勢' },
  { name: '手背右', emoji: '👉', category: '手勢' },
  { name: '手背上', emoji: '👆', category: '手勢' },
  { name: '中指', emoji: '🖕', category: '手勢' },
  { name: '手背下', emoji: '👇', category: '手勢' },
  { name: '食指上', emoji: '☝️', category: '手勢' },
  { name: '停止', emoji: '🫷', category: '手勢' },
  { name: '來', emoji: '🫸', category: '手勢' },
  { name: '讚', emoji: '👍', category: '手勢' },
  { name: '倒讚', emoji: '👎', category: '手勢' },
  { name: '拳頭', emoji: '✊', category: '手勢' },
  { name: '拳擊', emoji: '👊', category: '手勢' },
  { name: '左拳', emoji: '🤛', category: '手勢' },
  { name: '右拳', emoji: '🤜', category: '手勢' },
  { name: '拍手', emoji: '👏', category: '手勢' },
  { name: '舉雙手', emoji: '🙌', category: '手勢' },
  { name: '手心向上', emoji: '🫶', category: '手勢' },
  { name: '張開雙手', emoji: '👐', category: '手勢' },
  { name: '攤手', emoji: '🤲', category: '手勢' },
  { name: '握手', emoji: '🤝', category: '手勢' },
  { name: '祈禱', emoji: '🙏', category: '手勢' },
  { name: '寫字', emoji: '✍️', category: '手勢' },
  { name: '指甲油', emoji: '💅', category: '手勢' },
  { name: '自拍', emoji: '🤳', category: '手勢' },
  { name: '肌肉', emoji: '💪', category: '手勢' },
  { name: '機械手臂', emoji: '🦾', category: '手勢' },
  { name: '機械腳', emoji: '🦿', category: '手勢' },
  { name: '腿', emoji: '🦵', category: '手勢' },
  { name: '腳', emoji: '🦶', category: '手勢' },
  { name: '耳朵', emoji: '👂', category: '手勢' },
  { name: '助聽器', emoji: '🦻', category: '手勢' },
  { name: '鼻子', emoji: '👃', category: '手勢' },
  { name: '大腦', emoji: '🧠', category: '手勢' },
  { name: '解剖心臟', emoji: '🫀', category: '手勢' },
  { name: '肺', emoji: '🫁', category: '手勢' },
  { name: '牙齒', emoji: '🦷', category: '手勢' },
  { name: '骨頭', emoji: '🦴', category: '手勢' },
  { name: '眼睛', emoji: '👀', category: '手勢' },
  { name: '眼睛單', emoji: '👁️', category: '手勢' },
  { name: '舌頭', emoji: '👅', category: '手勢' },
  { name: '嘴巴', emoji: '👄', category: '手勢' },
  { name: '咬唇', emoji: '🫦', category: '手勢' },
  
  // 人物
  { name: '嬰兒', emoji: '👶', category: '人物' },
  { name: '小孩', emoji: '🧒', category: '人物' },
  { name: '男孩', emoji: '👦', category: '人物' },
  { name: '女孩', emoji: '👧', category: '人物' },
  { name: '成人', emoji: '🧑', category: '人物' },
  { name: '男人', emoji: '👨', category: '人物' },
  { name: '女人', emoji: '👩', category: '人物' },
  { name: '老人', emoji: '🧓', category: '人物' },
  { name: '老爺爺', emoji: '👴', category: '人物' },
  { name: '老奶奶', emoji: '👵', category: '人物' },
  
  // 動物
  { name: '猴臉', emoji: '🐵', category: '動物' },
  { name: '猴子', emoji: '🐒', category: '動物' },
  { name: '猩猩', emoji: '🦍', category: '動物' },
  { name: '紅毛猩猩', emoji: '🦧', category: '動物' },
  { name: '狗臉', emoji: '🐶', category: '動物' },
  { name: '狗', emoji: '🐕', category: '動物' },
  { name: '導盲犬', emoji: '🦮', category: '動物' },
  { name: '貴賓狗', emoji: '🐩', category: '動物' },
  { name: '狼', emoji: '🐺', category: '動物' },
  { name: '狐狸', emoji: '🦊', category: '動物' },
  { name: '浣熊', emoji: '🦝', category: '動物' },
  { name: '貓臉', emoji: '🐱', category: '動物' },
  { name: '貓', emoji: '🐈', category: '動物' },
  { name: '黑貓', emoji: '🐈‍⬛', category: '動物' },
  { name: '獅子', emoji: '🦁', category: '動物' },
  { name: '老虎臉', emoji: '🐯', category: '動物' },
  { name: '老虎', emoji: '🐅', category: '動物' },
  { name: '豹', emoji: '🐆', category: '動物' },
  { name: '馬臉', emoji: '🐴', category: '動物' },
  { name: '駝鹿', emoji: '🫎', category: '動物' },
  { name: '驢', emoji: '🫏', category: '動物' },
  { name: '馬', emoji: '🐎', category: '動物' },
  { name: '獨角獸', emoji: '🦄', category: '動物' },
  { name: '斑馬', emoji: '🦓', category: '動物' },
  { name: '鹿', emoji: '🦌', category: '動物' },
  { name: '野牛', emoji: '🦬', category: '動物' },
  { name: '牛臉', emoji: '🐮', category: '動物' },
  { name: '公牛', emoji: '🐂', category: '動物' },
  { name: '水牛', emoji: '🐃', category: '動物' },
  { name: '乳牛', emoji: '🐄', category: '動物' },
  { name: '豬臉', emoji: '🐷', category: '動物' },
  { name: '豬', emoji: '🐖', category: '動物' },
  { name: '野豬', emoji: '🐗', category: '動物' },
  { name: '豬鼻', emoji: '🐽', category: '動物' },
  { name: '公羊', emoji: '🐏', category: '動物' },
  { name: '綿羊', emoji: '🐑', category: '動物' },
  { name: '山羊', emoji: '🐐', category: '動物' },
  { name: '駱駝', emoji: '🐪', category: '動物' },
  { name: '雙峰駱駝', emoji: '🐫', category: '動物' },
  { name: '長頸鹿', emoji: '🦒', category: '動物' },
  { name: '大象', emoji: '🐘', category: '動物' },
  { name: '猛獁象', emoji: '🦣', category: '動物' },
  { name: '犀牛', emoji: '🦏', category: '動物' },
  { name: '河馬', emoji: '🦛', category: '動物' },
  { name: '老鼠臉', emoji: '🐭', category: '動物' },
  { name: '老鼠', emoji: '🐁', category: '動物' },
  { name: '大鼠', emoji: '🐀', category: '動物' },
  { name: '倉鼠', emoji: '🐹', category: '動物' },
  { name: '兔臉', emoji: '🐰', category: '動物' },
  { name: '兔子', emoji: '🐇', category: '動物' },
  { name: '花栗鼠', emoji: '🐿️', category: '動物' },
  { name: '海狸', emoji: '🦫', category: '動物' },
  { name: '刺蝟', emoji: '🦔', category: '動物' },
  { name: '蝙蝠', emoji: '🦇', category: '動物' },
  { name: '熊', emoji: '🐻', category: '動物' },
  { name: '北極熊', emoji: '🐻‍❄️', category: '動物' },
  { name: '無尾熊', emoji: '🐨', category: '動物' },
  { name: '貓熊', emoji: '🐼', category: '動物' },
  { name: '樹懶', emoji: '🦥', category: '動物' },
  { name: '水獺', emoji: '🦦', category: '動物' },
  { name: '臭鼬', emoji: '🦨', category: '動物' },
  { name: '袋鼠', emoji: '🦘', category: '動物' },
  { name: '獾', emoji: '🦡', category: '動物' },
  { name: '腳印', emoji: '🐾', category: '動物' },
  
  // 鳥類
  { name: '火雞', emoji: '🦃', category: '鳥類' },
  { name: '雞', emoji: '🐔', category: '鳥類' },
  { name: '公雞', emoji: '🐓', category: '鳥類' },
  { name: '小雞', emoji: '🐣', category: '鳥類' },
  { name: '雛鳥', emoji: '🐤', category: '鳥類' },
  { name: '正面雛鳥', emoji: '🐥', category: '鳥類' },
  { name: '鳥', emoji: '🐦', category: '鳥類' },
  { name: '黑鳥', emoji: '🐦‍⬛', category: '鳥類' },
  { name: '企鵝', emoji: '🐧', category: '鳥類' },
  { name: '鴿子', emoji: '🕊️', category: '鳥類' },
  { name: '老鷹', emoji: '🦅', category: '鳥類' },
  { name: '鴨子', emoji: '🦆', category: '鳥類' },
  { name: '天鵝', emoji: '🦢', category: '鳥類' },
  { name: '貓頭鷹', emoji: '🦉', category: '鳥類' },
  { name: '渡渡鳥', emoji: '🦤', category: '鳥類' },
  { name: '羽毛', emoji: '🪶', category: '鳥類' },
  { name: '紅鶴', emoji: '🦩', category: '鳥類' },
  { name: '孔雀', emoji: '🦚', category: '鳥類' },
  { name: '鸚鵡', emoji: '🦜', category: '鳥類' },
  { name: '翅膀', emoji: '🪽', category: '鳥類' },
  { name: '鵝', emoji: '🪿', category: '鳥類' },
  
  // 水生動物
  { name: '青蛙', emoji: '🐸', category: '水生' },
  { name: '鱷魚', emoji: '🐊', category: '水生' },
  { name: '烏龜', emoji: '🐢', category: '水生' },
  { name: '蜥蜴', emoji: '🦎', category: '水生' },
  { name: '蛇', emoji: '🐍', category: '水生' },
  { name: '龍臉', emoji: '🐲', category: '水生' },
  { name: '龍', emoji: '🐉', category: '水生' },
  { name: '蜥蜴龍', emoji: '🦕', category: '水生' },
  { name: '暴龍', emoji: '🦖', category: '水生' },
  { name: '鯨魚', emoji: '🐳', category: '水生' },
  { name: '鯨魚2', emoji: '🐋', category: '水生' },
  { name: '海豚', emoji: '🐬', category: '水生' },
  { name: '海豹', emoji: '🦭', category: '水生' },
  { name: '魚', emoji: '🐟', category: '水生' },
  { name: '熱帶魚', emoji: '🐠', category: '水生' },
  { name: '河豚', emoji: '🐡', category: '水生' },
  { name: '鯊魚', emoji: '🦈', category: '水生' },
  { name: '章魚', emoji: '🐙', category: '水生' },
  { name: '貝殼', emoji: '🐚', category: '水生' },
  { name: '珊瑚', emoji: '🪸', category: '水生' },
  { name: '水母', emoji: '🪼', category: '水生' },
  
  // 昆蟲
  { name: '蝸牛', emoji: '🐌', category: '昆蟲' },
  { name: '蝴蝶', emoji: '🦋', category: '昆蟲' },
  { name: '蟲', emoji: '🐛', category: '昆蟲' },
  { name: '螞蟻', emoji: '🐜', category: '昆蟲' },
  { name: '蜜蜂', emoji: '🐝', category: '昆蟲' },
  { name: '甲蟲', emoji: '🪲', category: '昆蟲' },
  { name: '瓢蟲', emoji: '🐞', category: '昆蟲' },
  { name: '蟋蟀', emoji: '🦗', category: '昆蟲' },
  { name: '蟑螂', emoji: '🪳', category: '昆蟲' },
  { name: '蜘蛛', emoji: '🕷️', category: '昆蟲' },
  { name: '蜘蛛網', emoji: '🕸️', category: '昆蟲' },
  { name: '蠍子', emoji: '🦂', category: '昆蟲' },
  { name: '蚊子', emoji: '🦟', category: '昆蟲' },
  { name: '蒼蠅', emoji: '🪰', category: '昆蟲' },
  { name: '蟲', emoji: '🪱', category: '昆蟲' },
  { name: '微生物', emoji: '🦠', category: '昆蟲' },
  
  // 植物
  { name: '花束', emoji: '💐', category: '植物' },
  { name: '櫻花', emoji: '🌸', category: '植物' },
  { name: '白花', emoji: '💮', category: '植物' },
  { name: '玫瑰', emoji: '🏵️', category: '植物' },
  { name: '紅玫瑰', emoji: '🌹', category: '植物' },
  { name: '枯萎花', emoji: '🥀', category: '植物' },
  { name: '木槿', emoji: '🌺', category: '植物' },
  { name: '向日葵', emoji: '🌻', category: '植物' },
  { name: '花朵', emoji: '🌼', category: '植物' },
  { name: '鬱金香', emoji: '🌷', category: '植物' },
  { name: '蓮花', emoji: '🪷', category: '植物' },
  { name: '幼苗', emoji: '🌱', category: '植物' },
  { name: '種子', emoji: '🪴', category: '植物' },
  { name: '常綠樹', emoji: '🌲', category: '植物' },
  { name: '落葉樹', emoji: '🌳', category: '植物' },
  { name: '棕櫚樹', emoji: '🌴', category: '植物' },
  { name: '仙人掌', emoji: '🌵', category: '植物' },
  { name: '稻穗', emoji: '🌾', category: '植物' },
  { name: '香草', emoji: '🌿', category: '植物' },
  { name: '三葉草', emoji: '☘️', category: '植物' },
  { name: '四葉草', emoji: '🍀', category: '植物' },
  { name: '楓葉', emoji: '🍁', category: '植物' },
  { name: '落葉', emoji: '🍂', category: '植物' },
  { name: '葉子', emoji: '🍃', category: '植物' },
  { name: '空葉', emoji: '🪹', category: '植物' },
  { name: '巢蛋', emoji: '🪺', category: '植物' },
  { name: '蘑菇', emoji: '🍄', category: '植物' },
  
  // 食物
  { name: '葡萄', emoji: '🍇', category: '食物' },
  { name: '瓜', emoji: '🍈', category: '食物' },
  { name: '西瓜', emoji: '🍉', category: '食物' },
  { name: '橘子', emoji: '🍊', category: '食物' },
  { name: '檸檬', emoji: '🍋', category: '食物' },
  { name: '黃檸檬', emoji: '🍋‍🟩', category: '食物' },
  { name: '香蕉', emoji: '🍌', category: '食物' },
  { name: '鳳梨', emoji: '🍍', category: '食物' },
  { name: '芒果', emoji: '🥭', category: '食物' },
  { name: '蘋果', emoji: '🍎', category: '食物' },
  { name: '青蘋果', emoji: '🍏', category: '食物' },
  { name: '梨', emoji: '🍐', category: '食物' },
  { name: '桃子', emoji: '🍑', category: '食物' },
  { name: '櫻桃', emoji: '🍒', category: '食物' },
  { name: '草莓', emoji: '🍓', category: '食物' },
  { name: '藍莓', emoji: '🫐', category: '食物' },
  { name: '奇異果', emoji: '🥝', category: '食物' },
  { name: '番茄', emoji: '🍅', category: '食物' },
  { name: '橄欖', emoji: '🫒', category: '食物' },
  { name: '椰子', emoji: '🥥', category: '食物' },
  { name: '酪梨', emoji: '🥑', category: '食物' },
  { name: '茄子', emoji: '🍆', category: '食物' },
  { name: '馬鈴薯', emoji: '🥔', category: '食物' },
  { name: '胡蘿蔔', emoji: '🥕', category: '食物' },
  { name: '玉米', emoji: '🌽', category: '食物' },
  { name: '辣椒', emoji: '🌶️', category: '食物' },
  { name: '甜椒', emoji: '🫑', category: '食物' },
  { name: '黃瓜', emoji: '🥒', category: '食物' },
  { name: '生菜', emoji: '🥬', category: '食物' },
  { name: '西蘭花', emoji: '🥦', category: '食物' },
  { name: '大蒜', emoji: '🧄', category: '食物' },
  { name: '洋蔥', emoji: '🧅', category: '食物' },
  { name: '薑', emoji: '🫚', category: '食物' },
  { name: '豌豆', emoji: '🫛', category: '食物' },
  { name: '花生', emoji: '🥜', category: '食物' },
  { name: '豆子', emoji: '🫘', category: '食物' },
  { name: '栗子', emoji: '🌰', category: '食物' },
  { name: '根莖', emoji: '🫜', category: '食物' },
  
  // 其他符號
  { name: '愛心', emoji: '❤️', category: '符號' },
  { name: '橙心', emoji: '🧡', category: '符號' },
  { name: '黃心', emoji: '💛', category: '符號' },
  { name: '綠心', emoji: '💚', category: '符號' },
  { name: '藍心', emoji: '💙', category: '符號' },
  { name: '紫心', emoji: '💜', category: '符號' },
  { name: '棕心', emoji: '🤎', category: '符號' },
  { name: '黑心', emoji: '🖤', category: '符號' },
  { name: '灰心', emoji: '🩶', category: '符號' },
  { name: '白心', emoji: '🤍', category: '符號' },
  { name: '粉心', emoji: '🩷', category: '符號' },
  { name: '淺藍心', emoji: '🩵', category: '符號' },
  { name: '破碎心', emoji: '💔', category: '符號' },
  { name: '火心', emoji: '❤️‍🔥', category: '符號' },
  { name: '修復心', emoji: '❤️‍🩹', category: '符號' },
  { name: '感嘆號心', emoji: '❣️', category: '符號' },
  { name: '雙心', emoji: '💕', category: '符號' },
  { name: '旋轉心', emoji: '💞', category: '符號' },
  { name: '跳動心', emoji: '💓', category: '符號' },
  { name: '成長心', emoji: '💗', category: '符號' },
  { name: '閃爍心', emoji: '💖', category: '符號' },
  { name: '箭心', emoji: '💘', category: '符號' },
  { name: '蝴蝶結心', emoji: '💝', category: '符號' },
  { name: '裝飾心', emoji: '💟', category: '符號' },
  { name: '和平', emoji: '☮️', category: '符號' },
  { name: '十字架', emoji: '✝️', category: '符號' },
  { name: '伊斯蘭', emoji: '☪️', category: '符號' },
  { name: '奧姆', emoji: '🕉️', category: '符號' },
  { name: '法輪', emoji: '☸️', category: '符號' },
  { name: '大衛星', emoji: '✡️', category: '符號' },
  { name: '六芒星', emoji: '🔯', category: '符號' },
  { name: '燭臺', emoji: '🕎', category: '符號' },
  { name: '陰陽', emoji: '☯️', category: '符號' },
  { name: '正教十字', emoji: '☦️', category: '符號' },
  { name: '禱告珠', emoji: '🛐', category: '符號' },
  { name: '蛇杖', emoji: '⚛️', category: '符號' },
  { name: '科學', emoji: '🪬', category: '符號' },
  { name: '花', emoji: '⚜️', category: '符號' },
  { name: '警告', emoji: '⚠️', category: '符號' },
  { name: '電', emoji: '⚡', category: '符號' },
  { name: '圓圈', emoji: '⭕', category: '符號' },
  { name: '打叉', emoji: '❌', category: '符號' },
  { name: '禁止', emoji: '🚫', category: '符號' },
  { name: '禁止進入', emoji: '⛔', category: '符號' },
  { name: '100', emoji: '💯', category: '符號' },
  { name: '憤怒', emoji: '💢', category: '符號' },
  { name: '熱', emoji: '♨️', category: '符號' },
  { name: '停', emoji: '🛑', category: '符號' },
  { name: '火', emoji: '🔥', category: '符號' },
  { name: '閃電', emoji: '✨', category: '符號' },
  { name: '星星', emoji: '⭐', category: '符號' },
  { name: '星', emoji: '🌟', category: '符號' },
  { name: '驚嘆號', emoji: '❗', category: '符號' },
  { name: '問號', emoji: '❓', category: '符號' },
  { name: '白驚嘆號', emoji: '❕', category: '符號' },
  { name: '白問號', emoji: '❔', category: '符號' },
  { name: '雙驚嘆號', emoji: '‼️', category: '符號' },
  { name: '感嘆問號', emoji: '⁉️', category: '符號' },
  { name: '對話框', emoji: '💬', category: '符號' },
  { name: '思考框', emoji: '💭', category: '符號' },
  { name: '夢框', emoji: '💤', category: '符號' },
  { name: '咒罵', emoji: '🤬', category: '表情' },
  { name: '惡魔微笑', emoji: '😈', category: '表情' },
  { name: '惡魔生氣', emoji: '👿', category: '表情' },
  { name: '骷髏', emoji: '💀', category: '表情' },
  { name: '骷髏頭', emoji: '☠️', category: '表情' },
  { name: '便便', emoji: '💩', category: '表情' },
  { name: '小丑', emoji: '🤡', category: '表情' },
  { name: '妖怪', emoji: '👹', category: '表情' },
  { name: '鬼', emoji: '👺', category: '表情' },
  { name: '幽靈', emoji: '👻', category: '表情' },
  { name: '外星人', emoji: '👽', category: '表情' },
  { name: '外星怪物', emoji: '👾', category: '表情' },
  { name: '機器人', emoji: '🤖', category: '表情' },
  { name: '南瓜燈', emoji: '🎃', category: '表情' },
  { name: '笑臉貓', emoji: '😺', category: '表情' },
  { name: '開心貓', emoji: '😸', category: '表情' },
  { name: '笑哭貓', emoji: '😹', category: '表情' },
  { name: '愛心貓', emoji: '😻', category: '表情' },
  { name: '壞笑貓', emoji: '😼', category: '表情' },
  { name: '親親貓', emoji: '😽', category: '表情' },
  { name: '疲憊貓', emoji: '🙀', category: '表情' },
  { name: '哭泣貓', emoji: '😿', category: '表情' },
  { name: '生氣貓', emoji: '😾', category: '表情' },
  
  // 手勢
  { name: '揮手', emoji: '👋', category: '手勢' },
  { name: '手背', emoji: '🤚', category: '手勢' },
  { name: '舉手', emoji: '🖐️', category: '手勢' },
  { name: '舉手2', emoji: '✋', category: '手勢' },
  { name: 'Vulcan禮', emoji: '🖖', category: '手勢' },
  { name: '右手', emoji: '🫱', category: '手勢' },
  { name: '左手', emoji: '🫲', category: '手勢' },
  { name: '手掌向下', emoji: '🫳', category: '手勢' },
  { name: '手掌向上', emoji: '🫴', category: '手勢' },
  { name: '手指向左', emoji: '🫵', category: '手勢' },
  { name: 'OK', emoji: '👌', category: '手勢' },
  { name: '捏手指', emoji: '🤌', category: '手勢' },
  { name: '捏', emoji: '🤏', category: '手勢' },
  { name: '勝利', emoji: '✌️', category: '手勢' },
  { name: '交叉手指', emoji: '🤞', category: '手勢' },
  { name: '手指心', emoji: '🫰', category: '手勢' },
  { name: '愛你', emoji: '🤟', category: '手勢' },
  { name: '搖滾', emoji: '🤘', category: '手勢' },
  { name: '打電話', emoji: '🤙', category: '手勢' },
  { name: '左指', emoji: '👈', category: '手勢' },
  { name: '右指', emoji: '👉', category: '手勢' },
  { name: '上指', emoji: '👆', category: '手勢' },
  { name: '中指', emoji: '🖕', category: '手勢' },
  { name: '下指', emoji: '👇', category: '手勢' },
  { name: '食指', emoji: '☝️', category: '手勢' },
  { name: '指向', emoji: '🫵', category: '手勢' },
  { name: '讚', emoji: '👍', category: '手勢' },
  { name: '倒讚', emoji: '👎', category: '手勢' },
  { name: '拳頭', emoji: '✊', category: '手勢' },
  { name: '出拳', emoji: '👊', category: '手勢' },
  { name: '左拳', emoji: '🤛', category: '手勢' },
  { name: '右拳', emoji: '🤜', category: '手勢' },
  { name: '拍手', emoji: '👏', category: '手勢' },
  { name: '舉雙手', emoji: '🙌', category: '手勢' },
  { name: '心形手', emoji: '🫶', category: '手勢' },
  { name: '張開雙手', emoji: '👐', category: '手勢' },
  { name: '合掌', emoji: '🤲', category: '手勢' },
  { name: '握手', emoji: '🤝', category: '手勢' },
  { name: '祈禱', emoji: '🙏', category: '手勢' },
  { name: '寫字', emoji: '✍️', category: '手勢' },
  { name: '指甲油', emoji: '💅', category: '手勢' },
  { name: '自拍', emoji: '🤳', category: '手勢' },
  { name: '肌肉', emoji: '💪', category: '手勢' },
  { name: '機械臂', emoji: '🦾', category: '手勢' },
  { name: '機械腿', emoji: '🦿', category: '手勢' },
  { name: '腿', emoji: '🦵', category: '手勢' },
  { name: '腳', emoji: '🦶', category: '手勢' },
  { name: '耳朵', emoji: '👂', category: '手勢' },
  { name: '助聽器', emoji: '🦻', category: '手勢' },
  { name: '鼻子', emoji: '👃', category: '手勢' },
  { name: '大腦', emoji: '🧠', category: '手勢' },
  { name: '肺', emoji: '🫁', category: '手勢' },
  { name: '牙齒', emoji: '🦷', category: '手勢' },
  { name: '骨頭', emoji: '🦴', category: '手勢' },
  { name: '眼睛', emoji: '👀', category: '手勢' },
  { name: '眼睛2', emoji: '👁️', category: '手勢' },
  { name: '舌頭', emoji: '👅', category: '手勢' },
  { name: '嘴巴', emoji: '👄', category: '手勢' },
  { name: '咬唇', emoji: '🫦', category: '手勢' },
  
  // 人物
  { name: '嬰兒', emoji: '👶', category: '人物' },
  { name: '小孩', emoji: '🧒', category: '人物' },
  { name: '男孩', emoji: '👦', category: '人物' },
  { name: '女孩', emoji: '👧', category: '人物' },
  { name: '成人', emoji: '🧑', category: '人物' },
  { name: '男人', emoji: '👨', category: '人物' },
  { name: '鬍子男', emoji: '🧔', category: '人物' },
  { name: '鬍子男2', emoji: '🧔‍♂️', category: '人物' },
  { name: '鬍子女', emoji: '🧔‍♀️', category: '人物' },
  { name: '紅髮男', emoji: '👨‍🦰', category: '人物' },
  { name: '捲髮男', emoji: '👨‍🦱', category: '人物' },
  { name: '白髮男', emoji: '👨‍🦳', category: '人物' },
  { name: '禿頭男', emoji: '👨‍🦲', category: '人物' },
  { name: '女人', emoji: '👩', category: '人物' },
  { name: '紅髮女', emoji: '👩‍🦰', category: '人物' },
  { name: '捲髮女', emoji: '👩‍🦱', category: '人物' },
  { name: '白髮女', emoji: '👩‍🦳', category: '人物' },
  { name: '禿頭女', emoji: '👩‍🦲', category: '人物' },
  { name: '金髮人', emoji: '👱', category: '人物' },
  { name: '金髮男', emoji: '👱‍♂️', category: '人物' },
  { name: '金髮女', emoji: '👱‍♀️', category: '人物' },
  { name: '老人', emoji: '🧓', category: '人物' },
  { name: '老爺爺', emoji: '👴', category: '人物' },
  { name: '老奶奶', emoji: '👵', category: '人物' },
  
  // 動物
  { name: '猴臉', emoji: '🐵', category: '動物' },
  { name: '猴子', emoji: '🐒', category: '動物' },
  { name: '猩猩', emoji: '🦍', category: '動物' },
  { name: '猩猩2', emoji: '🦧', category: '動物' },
  { name: '狗臉', emoji: '🐶', category: '動物' },
  { name: '狗', emoji: '🐕', category: '動物' },
  { name: '導盲犬', emoji: '🦮', category: '動物' },
  { name: '服務犬', emoji: '🐕‍🦺', category: '動物' },
  { name: '貴賓狗', emoji: '🐩', category: '動物' },
  { name: '狼', emoji: '🐺', category: '動物' },
  { name: '狐狸', emoji: '🦊', category: '動物' },
  { name: '浣熊', emoji: '🦝', category: '動物' },
  { name: '貓臉', emoji: '🐱', category: '動物' },
  { name: '貓', emoji: '🐈', category: '動物' },
  { name: '黑貓', emoji: '🐈‍⬛', category: '動物' },
  { name: '獅子', emoji: '🦁', category: '動物' },
  { name: '老虎臉', emoji: '🐯', category: '動物' },
  { name: '老虎', emoji: '🐅', category: '動物' },
  { name: '豹', emoji: '🐆', category: '動物' },
  { name: '馬臉', emoji: '🐴', category: '動物' },
  { name: '駝鹿', emoji: '🫎', category: '動物' },
  { name: '驢', emoji: '🫏', category: '動物' },
  { name: '馬', emoji: '🐎', category: '動物' },
  { name: '獨角獸', emoji: '🦄', category: '動物' },
  { name: '斑馬', emoji: '🦓', category: '動物' },
  { name: '鹿', emoji: '🦌', category: '動物' },
  { name: '野牛', emoji: '🦬', category: '動物' },
  { name: '牛臉', emoji: '🐮', category: '動物' },
  { name: '公牛', emoji: '🐂', category: '動物' },
  { name: '水牛', emoji: '🐃', category: '動物' },
  { name: '乳牛', emoji: '🐄', category: '動物' },
  { name: '豬臉', emoji: '🐷', category: '動物' },
  { name: '豬', emoji: '🐖', category: '動物' },
  { name: '野豬', emoji: '🐗', category: '動物' },
  { name: '豬鼻', emoji: '🐽', category: '動物' },
  { name: '公羊', emoji: '🐏', category: '動物' },
  { name: '綿羊', emoji: '🐑', category: '動物' },
  { name: '山羊', emoji: '🐐', category: '動物' },
  { name: '駱駝', emoji: '🐪', category: '動物' },
  { name: '雙峰駱駝', emoji: '🐫', category: '動物' },
  { name: '羊駝', emoji: '🦙', category: '動物' },
  { name: '長頸鹿', emoji: '🦒', category: '動物' },
  { name: '大象', emoji: '🐘', category: '動物' },
  { name: '猛獁象', emoji: '🦣', category: '動物' },
  { name: '犀牛', emoji: '🦏', category: '動物' },
  { name: '河馬', emoji: '🦛', category: '動物' },
  { name: '老鼠臉', emoji: '🐭', category: '動物' },
  { name: '老鼠', emoji: '🐁', category: '動物' },
  { name: '大鼠', emoji: '🐀', category: '動物' },
  { name: '倉鼠', emoji: '🐹', category: '動物' },
  { name: '兔臉', emoji: '🐰', category: '動物' },
  { name: '兔子', emoji: '🐇', category: '動物' },
  { name: '花栗鼠', emoji: '🐿️', category: '動物' },
  { name: '海狸', emoji: '🦫', category: '動物' },
  { name: '刺蝟', emoji: '🦔', category: '動物' },
  { name: '蝙蝠', emoji: '🦇', category: '動物' },
  { name: '熊', emoji: '🐻', category: '動物' },
  { name: '北極熊', emoji: '🐻‍❄️', category: '動物' },
  { name: '無尾熊', emoji: '🐨', category: '動物' },
  { name: '熊貓', emoji: '🐼', category: '動物' },
  { name: '樹懶', emoji: '🦥', category: '動物' },
  { name: '水獺', emoji: '🦦', category: '動物' },
  { name: '臭鼬', emoji: '🦨', category: '動物' },
  { name: '袋鼠', emoji: '🦘', category: '動物' },
  { name: '獾', emoji: '🦡', category: '動物' },
  { name: '腳印', emoji: '🐾', category: '動物' },
  
  // 鳥類
  { name: '火雞', emoji: '🦃', category: '動物' },
  { name: '雞', emoji: '🐔', category: '動物' },
  { name: '公雞', emoji: '🐓', category: '動物' },
  { name: '小雞', emoji: '🐣', category: '動物' },
  { name: '破殼小雞', emoji: '🐤', category: '動物' },
  { name: '正面小雞', emoji: '🐥', category: '動物' },
  { name: '小鳥', emoji: '🐦', category: '動物' },
  { name: '企鵝', emoji: '🐧', category: '動物' },
  { name: '鴿子', emoji: '🕊️', category: '動物' },
  { name: '老鷹', emoji: '🦅', category: '動物' },
  { name: '鴨子', emoji: '🦆', category: '動物' },
  { name: '天鵝', emoji: '🦢', category: '動物' },
  { name: '貓頭鷹', emoji: '🦉', category: '動物' },
  { name: '渡渡鳥', emoji: '🦤', category: '動物' },
  { name: '羽毛', emoji: '🪶', category: '動物' },
  { name: '紅鶴', emoji: '🦩', category: '動物' },
  { name: '孔雀', emoji: '🦚', category: '動物' },
  { name: '鸚鵡', emoji: '🦜', category: '動物' },
  { name: '翅膀', emoji: '🪽', category: '動物' },
  { name: '黑鳥', emoji: '🐦‍⬛', category: '動物' },
  { name: '鵝', emoji: '🪿', category: '動物' },
  
  // 水生動物
  { name: '青蛙', emoji: '🐸', category: '動物' },
  { name: '鱷魚', emoji: '🐊', category: '動物' },
  { name: '烏龜', emoji: '🐢', category: '動物' },
  { name: '蜥蜴', emoji: '🦎', category: '動物' },
  { name: '蛇', emoji: '🐍', category: '動物' },
  { name: '龍臉', emoji: '🐲', category: '動物' },
  { name: '龍', emoji: '🐉', category: '動物' },
  { name: '蜥腳龍', emoji: '🦕', category: '動物' },
  { name: '暴龍', emoji: '🦖', category: '動物' },
  { name: '鯨魚', emoji: '🐳', category: '動物' },
  { name: '噴水鯨魚', emoji: '🐋', category: '動物' },
  { name: '海豚', emoji: '🐬', category: '動物' },
  { name: '海豹', emoji: '🦭', category: '動物' },
  { name: '魚', emoji: '🐟', category: '動物' },
  { name: '熱帶魚', emoji: '🐠', category: '動物' },
  { name: '河豚', emoji: '🐡', category: '動物' },
  { name: '鯊魚', emoji: '🦈', category: '動物' },
  { name: '章魚', emoji: '🐙', category: '動物' },
  { name: '貝殼', emoji: '🐚', category: '動物' },
  { name: '珊瑚', emoji: '🪸', category: '動物' },
  { name: '水母', emoji: '🪼', category: '動物' },
  
  // 昆蟲
  { name: '蝸牛', emoji: '🐌', category: '動物' },
  { name: '蝴蝶', emoji: '🦋', category: '動物' },
  { name: '蟲', emoji: '🐛', category: '動物' },
  { name: '螞蟻', emoji: '🐜', category: '動物' },
  { name: '蜜蜂', emoji: '🐝', category: '動物' },
  { name: '甲蟲', emoji: '🪲', category: '動物' },
  { name: '瓢蟲', emoji: '🐞', category: '動物' },
  { name: '蟋蟀', emoji: '🦗', category: '動物' },
  { name: '蟑螂', emoji: '🪳', category: '動物' },
  { name: '蜘蛛', emoji: '🕷️', category: '動物' },
  { name: '蜘蛛網', emoji: '🕸️', category: '動物' },
  { name: '蠍子', emoji: '🦂', category: '動物' },
  { name: '蚊子', emoji: '🦟', category: '動物' },
  { name: '蒼蠅', emoji: '🪰', category: '動物' },
  { name: '蟲子', emoji: '🪱', category: '動物' },
  { name: '微生物', emoji: '🦠', category: '動物' },
  
  // 植物
  { name: '花束', emoji: '💐', category: '植物' },
  { name: '櫻花', emoji: '🌸', category: '植物' },
  { name: '白花', emoji: '💮', category: '植物' },
  { name: '玫瑰', emoji: '🏵️', category: '植物' },
  { name: '紅玫瑰', emoji: '🌹', category: '植物' },
  { name: '枯萎花', emoji: '🥀', category: '植物' },
  { name: '芙蓉', emoji: '🌺', category: '植物' },
  { name: '向日葵', emoji: '🌻', category: '植物' },
  { name: '花朵', emoji: '🌼', category: '植物' },
  { name: '鬱金香', emoji: '🌷', category: '植物' },
  { name: '蓮花', emoji: '🪷', category: '植物' },
  { name: '幼苗', emoji: '🌱', category: '植物' },
  { name: '常青樹', emoji: '🌲', category: '植物' },
  { name: '落葉樹', emoji: '🌳', category: '植物' },
  { name: '棕櫚樹', emoji: '🌴', category: '植物' },
  { name: '仙人掌', emoji: '🌵', category: '植物' },
  { name: '稻穗', emoji: '🌾', category: '植物' },
  { name: '香草', emoji: '🌿', category: '植物' },
  { name: '三葉草', emoji: '☘️', category: '植物' },
  { name: '四葉草', emoji: '🍀', category: '植物' },
  { name: '楓葉', emoji: '🍁', category: '植物' },
  { name: '落葉', emoji: '🍂', category: '植物' },
  { name: '葉子', emoji: '🍃', category: '植物' },
  { name: '空巢', emoji: '🪹', category: '植物' },
  { name: '有蛋巢', emoji: '🪺', category: '植物' },
  { name: '蘑菇', emoji: '🍄', category: '植物' },
  
  // 食物水果
  { name: '葡萄', emoji: '🍇', category: '食物' },
  { name: '哈密瓜', emoji: '🍈', category: '食物' },
  { name: '西瓜', emoji: '🍉', category: '食物' },
  { name: '橘子', emoji: '🍊', category: '食物' },
  { name: '檸檬', emoji: '🍋', category: '食物' },
  { name: '香蕉', emoji: '🍌', category: '食物' },
  { name: '鳳梨', emoji: '🍍', category: '食物' },
  { name: '芒果', emoji: '🥭', category: '食物' },
  { name: '紅蘋果', emoji: '🍎', category: '食物' },
  { name: '青蘋果', emoji: '🍏', category: '食物' },
  { name: '梨', emoji: '🍐', category: '食物' },
  { name: '桃子', emoji: '🍑', category: '食物' },
  { name: '櫻桃', emoji: '🍒', category: '食物' },
  { name: '草莓', emoji: '🍓', category: '食物' },
  { name: '藍莓', emoji: '🫐', category: '食物' },
  { name: '奇異果', emoji: '🥝', category: '食物' },
  { name: '番茄', emoji: '🍅', category: '食物' },
  { name: '橄欖', emoji: '🫒', category: '食物' },
  { name: '椰子', emoji: '🥥', category: '食物' },
  
  // 食物蔬菜
  { name: '酪梨', emoji: '🥑', category: '食物' },
  { name: '茄子', emoji: '🍆', category: '食物' },
  { name: '馬鈴薯', emoji: '🥔', category: '食物' },
  { name: '紅蘿蔔', emoji: '🥕', category: '食物' },
  { name: '玉米', emoji: '🌽', category: '食物' },
  { name: '辣椒', emoji: '🌶️', category: '食物' },
  { name: '甜椒', emoji: '🫑', category: '食物' },
  { name: '黃瓜', emoji: '🥒', category: '食物' },
  { name: '萵苣', emoji: '🥬', category: '食物' },
  { name: '西蘭花', emoji: '🥦', category: '食物' },
  { name: '大蒜', emoji: '🧄', category: '食物' },
  { name: '洋蔥', emoji: '🧅', category: '食物' },
  { name: '豌豆', emoji: '🫛', category: '食物' },
  { name: '豆子', emoji: '🫘', category: '食物' },
  { name: '栗子', emoji: '🌰', category: '食物' },
  { name: '薑', emoji: '🫚', category: '食物' },
  { name: '花生', emoji: '🥜', category: '食物' },
  { name: '豆類', emoji: '🫘', category: '食物' },
  
  // 食物主食
  { name: '麵包', emoji: '🍞', category: '食物' },
  { name: '可頌', emoji: '🥐', category: '食物' },
  { name: '法國麵包', emoji: '🥖', category: '食物' },
  { name: '扁麵包', emoji: '🫓', category: '食物' },
  { name: '椒鹽卷餅', emoji: '🥨', category: '食物' },
  { name: '貝果', emoji: '🥯', category: '食物' },
  { name: '鬆餅', emoji: '🥞', category: '食物' },
  { name: '華夫餅', emoji: '🧇', category: '食物' },
  { name: '起司', emoji: '🧀', category: '食物' },
  { name: '肉骨頭', emoji: '🍖', category: '食物' },
  { name: '雞腿', emoji: '🍗', category: '食物' },
  { name: '牛排', emoji: '🥩', category: '食物' },
  { name: '培根', emoji: '🥓', category: '食物' },
  { name: '漢堡', emoji: '🍔', category: '食物' },
  { name: '薯條', emoji: '🍟', category: '食物' },
  { name: '披薩', emoji: '🍕', category: '食物' },
  { name: '熱狗', emoji: '🌭', category: '食物' },
  { name: '三明治', emoji: '🥪', category: '食物' },
  { name: '塔可', emoji: '🌮', category: '食物' },
  { name: '墨西哥捲餅', emoji: '🌯', category: '食物' },
  { name: '塔瑪利', emoji: '🫔', category: '食物' },
  { name: '口袋餅', emoji: '🥙', category: '食物' },
  { name: '法拉費', emoji: '🧆', category: '食物' },
  { name: '蛋', emoji: '🥚', category: '食物' },
  { name: '煎蛋', emoji: '🍳', category: '食物' },
  { name: '淺鍋', emoji: '🥘', category: '食物' },
  { name: '鍋', emoji: '🍲', category: '食物' },
  { name: '火鍋', emoji: '🫕', category: '食物' },
  { name: '碗食', emoji: '🥣', category: '食物' },
  { name: '沙拉', emoji: '🥗', category: '食物' },
  { name: '爆米花', emoji: '🍿', category: '食物' },
  { name: '奶油', emoji: '🧈', category: '食物' },
  { name: '鹽', emoji: '🧂', category: '食物' },
  { name: '罐頭', emoji: '🥫', category: '食物' },
  
  // 亞洲食物
  { name: '便當', emoji: '🍱', category: '食物' },
  { name: '飯糰', emoji: '🍙', category: '食物' },
  { name: '米飯', emoji: '🍚', category: '食物' },
  { name: '咖哩飯', emoji: '🍛', category: '食物' },
  { name: '拉麵', emoji: '🍜', category: '食物' },
  { name: '義大利麵', emoji: '🍝', category: '食物' },
  { name: '地瓜', emoji: '🍠', category: '食物' },
  { name: '關東煮', emoji: '🍢', category: '食物' },
  { name: '壽司', emoji: '🍣', category: '食物' },
  { name: '炸蝦', emoji: '🍤', category: '食物' },
  { name: '魚板', emoji: '🍥', category: '食物' },
  { name: '月餅', emoji: '🥮', category: '食物' },
  { name: '丸子', emoji: '🍡', category: '食物' },
  { name: '餃子', emoji: '🥟', category: '食物' },
  { name: '幸運餅乾', emoji: '🥠', category: '食物' },
  { name: '外賣盒', emoji: '🥡', category: '食物' },
  
  // 海鮮
  { name: '蟹', emoji: '🦀', category: '食物' },
  { name: '龍蝦', emoji: '🦞', category: '食物' },
  { name: '蝦', emoji: '🦐', category: '食物' },
  { name: '魷魚', emoji: '🦑', category: '食物' },
  { name: '生蠔', emoji: '🦪', category: '食物' },
  
  // 甜點
  { name: '霜淇淋', emoji: '🍦', category: '食物' },
  { name: '刨冰', emoji: '🍧', category: '食物' },
  { name: '冰淇淋', emoji: '🍨', category: '食物' },
  { name: '甜甜圈', emoji: '🍩', category: '食物' },
  { name: '餅乾', emoji: '🍪', category: '食物' },
  { name: '生日蛋糕', emoji: '🎂', category: '食物' },
  { name: '蛋糕', emoji: '🍰', category: '食物' },
  { name: '杯子蛋糕', emoji: '🧁', category: '食物' },
  { name: '派', emoji: '🥧', category: '食物' },
  { name: '巧克力', emoji: '🍫', category: '食物' },
  { name: '糖果', emoji: '🍬', category: '食物' },
  { name: '棒棒糖', emoji: '🍭', category: '食物' },
  { name: '布丁', emoji: '🍮', category: '食物' },
  { name: '蜂蜜', emoji: '🍯', category: '食物' },
  
  // 飲料
  { name: '奶瓶', emoji: '🍼', category: '食物' },
  { name: '牛奶', emoji: '🥛', category: '食物' },
  { name: '熱飲', emoji: '☕', category: '食物' },
  { name: '茶壺', emoji: '🫖', category: '食物' },
  { name: '茶', emoji: '🍵', category: '食物' },
  { name: '清酒', emoji: '🍶', category: '食物' },
  { name: '香檳', emoji: '🍾', category: '食物' },
  { name: '紅酒', emoji: '🍷', category: '食物' },
  { name: '雞尾酒', emoji: '🍸', category: '食物' },
  { name: '熱帶飲料', emoji: '🍹', category: '食物' },
  { name: '啤酒', emoji: '🍺', category: '食物' },
  { name: '乾杯', emoji: '🍻', category: '食物' },
  { name: '碰杯', emoji: '🥂', category: '食物' },
  { name: '威士忌', emoji: '🥃', category: '食物' },
  { name: '杯子吸管', emoji: '🥤', category: '食物' },
  { name: '泡泡茶', emoji: '🧋', category: '食物' },
  { name: '飲料盒', emoji: '🧃', category: '食物' },
  { name: '瑪黛茶', emoji: '🧉', category: '食物' },
  { name: '冰塊', emoji: '🧊', category: '食物' },
  
  // 餐具
  { name: '筷子', emoji: '🥢', category: '食物' },
  { name: '盤子', emoji: '🍽️', category: '食物' },
  { name: '刀叉', emoji: '🍴', category: '食物' },
  { name: '湯匙', emoji: '🥄', category: '食物' },
  { name: '菜刀', emoji: '🔪', category: '食物' },
  { name: '壺', emoji: '🫙', category: '食物' },
  { name: '陶罐', emoji: '🏺', category: '食物' },
  
  // 活動運動
  { name: '世界', emoji: '🌍', category: '活動' },
  { name: '地球美洲', emoji: '🌎', category: '活動' },
  { name: '地球亞洲', emoji: '🌏', category: '活動' },
  { name: '地球經緯', emoji: '🌐', category: '活動' },
  { name: '地圖', emoji: '🗺️', category: '活動' },
  { name: '日本地圖', emoji: '🗾', category: '活動' },
  { name: '指南針', emoji: '🧭', category: '活動' },
  { name: '雪山', emoji: '🏔️', category: '活動' },
  { name: '山', emoji: '⛰️', category: '活動' },
  { name: '火山', emoji: '🌋', category: '活動' },
  { name: '富士山', emoji: '🗻', category: '活動' },
  { name: '露營', emoji: '🏕️', category: '活動' },
  { name: '海灘', emoji: '🏖️', category: '活動' },
  { name: '沙漠', emoji: '🏜️', category: '活動' },
  { name: '荒島', emoji: '🏝️', category: '活動' },
  { name: '國家公園', emoji: '🏞️', category: '活動' },
  
  // 建築
  { name: '體育場', emoji: '🏟️', category: '活動' },
  { name: '古典建築', emoji: '🏛️', category: '活動' },
  { name: '建築工地', emoji: '🏗️', category: '活動' },
  { name: '磚塊', emoji: '🧱', category: '活動' },
  { name: '岩石', emoji: '🪨', category: '活動' },
  { name: '木頭', emoji: '🪵', category: '活動' },
  { name: '小屋', emoji: '🛖', category: '活動' },
  { name: '房屋群', emoji: '🏘️', category: '活動' },
  { name: '廢墟', emoji: '🏚️', category: '活動' },
  { name: '房子', emoji: '🏠', category: '活動' },
  { name: '花園房', emoji: '🏡', category: '活動' },
  { name: '辦公樓', emoji: '🏢', category: '活動' },
  { name: '日本郵局', emoji: '🏣', category: '活動' },
  { name: '郵局', emoji: '🏤', category: '活動' },
  { name: '醫院', emoji: '🏥', category: '活動' },
  { name: '銀行', emoji: '🏦', category: '活動' },
  { name: '旅館', emoji: '🏨', category: '活動' },
  { name: '愛情旅館', emoji: '🏩', category: '活動' },
  { name: '便利店', emoji: '🏪', category: '活動' },
  { name: '學校', emoji: '🏫', category: '活動' },
  { name: '百貨公司', emoji: '🏬', category: '活動' },
  { name: '工廠', emoji: '🏭', category: '活動' },
  { name: '日本城堡', emoji: '🏯', category: '活動' },
  { name: '城堡', emoji: '🏰', category: '活動' },
  { name: '婚禮', emoji: '💒', category: '活動' },
  { name: '東京塔', emoji: '🗼', category: '活動' },
  { name: '自由女神', emoji: '🗽', category: '活動' },
  
  // 宗教
  { name: '教堂', emoji: '⛪', category: '活動' },
  { name: '清真寺', emoji: '🕌', category: '活動' },
  { name: '印度廟', emoji: '🛕', category: '活動' },
  { name: '猶太教堂', emoji: '🕍', category: '活動' },
  { name: '神社', emoji: '⛩️', category: '活動' },
  { name: '卡巴天房', emoji: '🕋', category: '活動' },
  
  // 交通工具
  { name: '噴泉', emoji: '⛲', category: '活動' },
  { name: '帳篷', emoji: '⛺', category: '活動' },
  { name: '霧', emoji: '🌁', category: '活動' },
  { name: '夜景', emoji: '🌃', category: '活動' },
  { name: '城市', emoji: '🏙️', category: '活動' },
  { name: '日出山', emoji: '🌄', category: '活動' },
  { name: '日出', emoji: '🌅', category: '活動' },
  { name: '黃昏', emoji: '🌆', category: '活動' },
  { name: '夕陽', emoji: '🌇', category: '活動' },
  { name: '夜晚', emoji: '🌉', category: '活動' },
  { name: '溫泉', emoji: '♨️', category: '活動' },
  { name: '旋轉木馬', emoji: '🎠', category: '活動' },
  { name: '遊樂場', emoji: '🎡', category: '活動' },
  { name: '雲霄飛車', emoji: '🎢', category: '活動' },
  { name: '理髮店', emoji: '💈', category: '活動' },
  { name: '馬戲團', emoji: '🎪', category: '活動' },
  
  // 交通
  { name: '火車', emoji: '🚂', category: '交通' },
  { name: '蒸汽火車', emoji: '🚃', category: '交通' },
  { name: '鐵路車', emoji: '🚄', category: '交通' },
  { name: '高鐵', emoji: '🚅', category: '交通' },
  { name: '列車', emoji: '🚆', category: '交通' },
  { name: '地鐵', emoji: '🚇', category: '交通' },
  { name: '輕軌', emoji: '🚈', category: '交通' },
  { name: '車站', emoji: '🚉', category: '交通' },
  { name: '有軌電車', emoji: '🚊', category: '交通' },
  { name: '單軌', emoji: '🚝', category: '交通' },
  { name: '山地鐵路', emoji: '🚞', category: '交通' },
  { name: '車廂', emoji: '🚋', category: '交通' },
  { name: '公車', emoji: '🚌', category: '交通' },
  { name: '迎面公車', emoji: '🚍', category: '交通' },
  { name: '無軌電車', emoji: '🚎', category: '交通' },
  { name: '小巴', emoji: '🚐', category: '交通' },
  { name: '救護車', emoji: '🚑', category: '交通' },
  { name: '消防車', emoji: '🚒', category: '交通' },
  { name: '警車', emoji: '🚓', category: '交通' },
  { name: '迎面警車', emoji: '🚔', category: '交通' },
  { name: '計程車', emoji: '🚕', category: '交通' },
  { name: '迎面計程車', emoji: '🚖', category: '交通' },
  { name: '汽車', emoji: '🚗', category: '交通' },
  { name: '迎面汽車', emoji: '🚘', category: '交通' },
  { name: '休旅車', emoji: '🚙', category: '交通' },
  { name: '皮卡', emoji: '🛻', category: '交通' },
  { name: '貨車', emoji: '🚚', category: '交通' },
  { name: '卡車', emoji: '🚛', category: '交通' },
  { name: '拖拉機', emoji: '🚜', category: '交通' },
  { name: '賽車', emoji: '🏎️', category: '交通' },
  { name: '摩托車', emoji: '🏍️', category: '交通' },
  { name: '摩托車2', emoji: '🛵', category: '交通' },
  { name: '輪椅', emoji: '🦽', category: '交通' },
  { name: '電動輪椅', emoji: '🦼', category: '交通' },
  { name: '嘟嘟車', emoji: '🛺', category: '交通' },
  { name: '腳踏車', emoji: '🚲', category: '交通' },
  { name: '滑板車', emoji: '🛴', category: '交通' },
  { name: '滑板', emoji: '🛹', category: '交通' },
  { name: '溜冰鞋', emoji: '🛼', category: '交通' },
  { name: '公車站', emoji: '🚏', category: '交通' },
  { name: '高速公路', emoji: '🛣️', category: '交通' },
  { name: '鐵路', emoji: '🛤️', category: '交通' },
  { name: '油桶', emoji: '🛢️', category: '交通' },
  { name: '加油站', emoji: '⛽', category: '交通' },
  { name: '輪子', emoji: '🛞', category: '交通' },
  { name: '警車燈', emoji: '🚨', category: '交通' },
  { name: '紅綠燈橫', emoji: '🚥', category: '交通' },
  { name: '紅綠燈', emoji: '🚦', category: '交通' },
  { name: '停止標誌', emoji: '🛑', category: '交通' },
  { name: '施工', emoji: '🚧', category: '交通' },
  { name: '錨', emoji: '⚓', category: '交通' },
  { name: '戒指浮標', emoji: '🛟', category: '交通' },
  { name: '帆船', emoji: '⛵', category: '交通' },
  { name: '獨木舟', emoji: '🛶', category: '交通' },
  { name: '快艇', emoji: '🚤', category: '交通' },
  { name: '客輪', emoji: '🛳️', category: '交通' },
  { name: '渡輪', emoji: '⛴️', category: '交通' },
  { name: '汽艇', emoji: '🛥️', category: '交通' },
  { name: '船', emoji: '🚢', category: '交通' },
  { name: '飛機', emoji: '✈️', category: '交通' },
  { name: '小飛機', emoji: '🛩️', category: '交通' },
  { name: '飛機起飛', emoji: '🛫', category: '交通' },
  { name: '飛機降落', emoji: '🛬', category: '交通' },
  { name: '降落傘', emoji: '🪂', category: '交通' },
  { name: '座位', emoji: '💺', category: '交通' },
  { name: '直升機', emoji: '🚁', category: '交通' },
  { name: '懸掛鐵路', emoji: '🚟', category: '交通' },
  { name: '纜車', emoji: '🚠', category: '交通' },
  { name: '空中纜車', emoji: '🚡', category: '交通' },
  { name: '衛星', emoji: '🛰️', category: '交通' },
  { name: '火箭', emoji: '🚀', category: '交通' },
  { name: '飛碟', emoji: '🛸', category: '交通' },
  
  // 時間
  { name: '鈴鐺', emoji: '🔔', category: '物品' },
  { name: '靜音鈴', emoji: '🔕', category: '物品' },
  { name: '揚聲器', emoji: '📢', category: '物品' },
  { name: '擴音器', emoji: '📣', category: '物品' },
  { name: '喇叭', emoji: '📯', category: '物品' },
  { name: '鈴', emoji: '🔔', category: '物品' },
  { name: '音樂', emoji: '🎵', category: '物品' },
  { name: '音符', emoji: '🎶', category: '物品' },
  
  // 以下省略更多 emoji...
  // 完整列表約 3600+ 個
]