// 完全清潔且相容的 Emoji 列表 - 移除所有變化選擇器和複合字符
export const cleanEmojis = [
  // 表情與情緒 - 擴展版本
  { name: '微笑', emoji: '😀', category: '表情' },
  { name: '露齒笑', emoji: '😃', category: '表情' },
  { name: '大笑', emoji: '😄', category: '表情' },
  { name: '眯眼笑', emoji: '😁', category: '表情' },
  { name: '笑哭', emoji: '😆', category: '表情' },
  { name: '汗笑', emoji: '😅', category: '表情' },
  { name: '笑翻', emoji: '🤣', category: '表情' },
  { name: '喜極而泣', emoji: '😂', category: '表情' },
  { name: '微微笑', emoji: '🙂', category: '表情' },
  { name: '倒臉', emoji: '🙃', category: '表情' },
  { name: '眨眼', emoji: '😉', category: '表情' },
  { name: '羞笑', emoji: '😊', category: '表情' },
  { name: '天使', emoji: '😇', category: '表情' },
  { name: '愛心眼', emoji: '😍', category: '表情' },
  { name: '星星眼', emoji: '🤩', category: '表情' },
  { name: '飛吻', emoji: '😘', category: '表情' },
  { name: '親吻', emoji: '😗', category: '表情' },
  { name: '微笑2', emoji: '☺', category: '表情' },
  { name: '親親', emoji: '😚', category: '表情' },
  { name: '含笑', emoji: '😙', category: '表情' },
  { name: '吐舌', emoji: '😋', category: '表情' },
  { name: '吐舌眨眼', emoji: '😜', category: '表情' },
  { name: '搞怪', emoji: '🤪', category: '表情' },
  { name: '吐舌笑', emoji: '😝', category: '表情' },
  { name: '錢', emoji: '🤑', category: '表情' },
  { name: '擁抱', emoji: '🤗', category: '表情' },
  { name: '噓', emoji: '🤭', category: '表情' },
  { name: '安靜', emoji: '🤫', category: '表情' },
  { name: '沉思', emoji: '🤔', category: '表情' },
  { name: '拉鍊嘴', emoji: '🤐', category: '表情' },
  { name: '挑眉', emoji: '🤨', category: '表情' },
  { name: '無語', emoji: '😐', category: '表情' },
  { name: '面無表情', emoji: '😑', category: '表情' },
  { name: '無口', emoji: '😶', category: '表情' },
  { name: '假笑', emoji: '😏', category: '表情' },
  { name: '不爽', emoji: '😒', category: '表情' },
  { name: '翻白眼', emoji: '🙄', category: '表情' },
  { name: '做鬼臉', emoji: '😬', category: '表情' },
  { name: '說謊', emoji: '🤥', category: '表情' },
  { name: '鬆口氣', emoji: '😌', category: '表情' },
  { name: '疲憊', emoji: '😔', category: '表情' },
  { name: '睏', emoji: '😪', category: '表情' },
  { name: '口罩', emoji: '😷', category: '表情' },
  { name: '發燒', emoji: '🤒', category: '表情' },
  { name: '包紮', emoji: '🤕', category: '表情' },
  { name: '嘔吐', emoji: '🤢', category: '表情' },
  { name: '噁心', emoji: '🤮', category: '表情' },
  { name: '打噴嚏', emoji: '🤧', category: '表情' },
  { name: '發熱', emoji: '🥵', category: '表情' },
  { name: '冰冷', emoji: '🥶', category: '表情' },
  { name: '暈', emoji: '🥴', category: '表情' },
  { name: '暈倒', emoji: '😵', category: '表情' },
  { name: '爆炸頭', emoji: '🤯', category: '表情' },
  { name: '冷臉', emoji: '🥱', category: '表情' },
  { name: '黨', emoji: '🤠', category: '表情' },
  { name: '書呆子', emoji: '🤓', category: '表情' },
  { name: '墨鏡', emoji: '😎', category: '表情' },
  { name: '困惑', emoji: '😕', category: '表情' },
  { name: '擔心', emoji: '😟', category: '表情' },
  { name: '稍微皺眉', emoji: '🙁', category: '表情' },
  { name: '白眼', emoji: '☹', category: '表情' },
  { name: '張口', emoji: '😮', category: '表情' },
  { name: '安靜張口', emoji: '😯', category: '表情' },
  { name: '驚訝', emoji: '😲', category: '表情' },
  { name: '沖洗', emoji: '😳', category: '表情' },
  { name: '皺眉', emoji: '🥺', category: '表情' },
  { name: '哭', emoji: '😢', category: '表情' },
  { name: '大哭', emoji: '😭', category: '表情' },
  { name: '哀號', emoji: '😤', category: '表情' },
  { name: '生氣', emoji: '😠', category: '表情' },
  { name: '憤怒', emoji: '😡', category: '表情' },
  { name: '髒話', emoji: '🤬', category: '表情' },
  { name: '嚴肅', emoji: '😨', category: '表情' },
  { name: '恐懼', emoji: '😰', category: '表情' },
  { name: '冒汗', emoji: '😥', category: '表情' },
  { name: '失望', emoji: '😞', category: '表情' },
  { name: '困惑2', emoji: '😖', category: '表情' },
  { name: '堅持', emoji: '😣', category: '表情' },
  { name: '哭泣', emoji: '😓', category: '表情' },
  { name: '疲勞', emoji: '😩', category: '表情' },
  { name: '呻吟', emoji: '😫', category: '表情' },
  { name: '委屈', emoji: '🥲', category: '表情' },

  // 動物類 - 大幅擴展
  { name: '猴臉', emoji: '🐵', category: '動物' },
  { name: '猴子', emoji: '🐒', category: '動物' },
  { name: '大猩猩', emoji: '🦍', category: '動物' },
  { name: '猩猩', emoji: '🦧', category: '動物' },
  { name: '狗臉', emoji: '🐶', category: '動物' },
  { name: '狗', emoji: '🐕', category: '動物' },
  { name: '獵犬', emoji: '🦮', category: '動物' },
  { name: '貴賓狗', emoji: '🐩', category: '動物' },
  { name: '狼', emoji: '🐺', category: '動物' },
  { name: '狐狸', emoji: '🦊', category: '動物' },
  { name: '浣熊', emoji: '🦝', category: '動物' },
  { name: '貓臉', emoji: '🐱', category: '動物' },
  { name: '貓', emoji: '🐈', category: '動物' },
  { name: '獅子', emoji: '🦁', category: '動物' },
  { name: '老虎臉', emoji: '🐯', category: '動物' },
  { name: '老虎', emoji: '🐅', category: '動物' },
  { name: '豹', emoji: '🐆', category: '動物' },
  { name: '馬臉', emoji: '🐴', category: '動物' },
  { name: '馬', emoji: '🐎', category: '動物' },
  { name: '獨角獸', emoji: '🦄', category: '動物' },
  { name: '斑馬', emoji: '🦓', category: '動物' },
  { name: '鹿', emoji: '🦌', category: '動物' },
  { name: '牛臉', emoji: '🐮', category: '動物' },
  { name: '牛', emoji: '🐄', category: '動物' },
  { name: '水牛', emoji: '🐃', category: '動物' },
  { name: '牦牛', emoji: '🦬', category: '動物' },
  { name: '豬臉', emoji: '🐷', category: '動物' },
  { name: '豬', emoji: '🐖', category: '動物' },
  { name: '野豬', emoji: '🐗', category: '動物' },
  { name: '羊', emoji: '🐑', category: '動物' },
  { name: '綿羊', emoji: '🐏', category: '動物' },
  { name: '山羊', emoji: '🐐', category: '動物' },
  { name: '駱駝', emoji: '🐪', category: '動物' },
  { name: '雙峰駱駝', emoji: '🐫', category: '動物' },
  { name: '長頸鹿', emoji: '🦒', category: '動物' },
  { name: '大象', emoji: '🐘', category: '動物' },
  { name: '犀牛', emoji: '🦏', category: '動物' },
  { name: '河馬', emoji: '🦛', category: '動物' },
  { name: '老鼠臉', emoji: '🐭', category: '動物' },
  { name: '老鼠', emoji: '🐁', category: '動物' },
  { name: '倉鼠', emoji: '🐹', category: '動物' },
  { name: '兔臉', emoji: '🐰', category: '動物' },
  { name: '兔子', emoji: '🐇', category: '動物' },
  { name: '松鼠', emoji: '🐿', category: '動物' },
  { name: '刺蝟', emoji: '🦔', category: '動物' },
  { name: '熊臉', emoji: '🐻', category: '動物' },
  { name: '無尾熊', emoji: '🐨', category: '動物' },
  { name: '熊貓', emoji: '🐼', category: '動物' },
  { name: '懶熊', emoji: '🦥', category: '動物' },
  { name: '水獺', emoji: '🦦', category: '動物' },
  { name: '臭鼬', emoji: '🦨', category: '動物' },
  { name: '袋鼠', emoji: '🦘', category: '動物' },
  { name: '穿山甲', emoji: '🦡', category: '動物' },
  { name: '蝙蝠', emoji: '🦇', category: '動物' },

  // 海洋動物
  { name: '鯊魚', emoji: '🦈', category: '海洋' },
  { name: '章魚', emoji: '🐙', category: '海洋' },
  { name: '蝸牛', emoji: '🐌', category: '海洋' },
  { name: '蝴蝶', emoji: '🦋', category: '昆蟲' },
  { name: '蟲', emoji: '🐛', category: '昆蟲' },
  { name: '螞蟻', emoji: '🐜', category: '昆蟲' },
  { name: '蜜蜂', emoji: '🐝', category: '昆蟲' },
  { name: '瓢蟲', emoji: '🐞', category: '昆蟲' },
  { name: '蟋蟀', emoji: '🦗', category: '昆蟲' },
  { name: '蜘蛛', emoji: '🕷', category: '昆蟲' },
  { name: '蕁蛛網', emoji: '🕸', category: '昆蟲' },
  { name: '蠍子', emoji: '🦂', category: '昆蟲' },
  { name: '蚊子', emoji: '🦟', category: '昆蟲' },
  { name: '蒼蠅', emoji: '🪰', category: '昆蟲' },
  { name: '蚯蚓', emoji: '🪱', category: '昆蟲' },
  { name: '微生物', emoji: '🦠', category: '昆蟲' },

  // 鳥類
  { name: '火雞', emoji: '🦃', category: '鳥類' },
  { name: '雞', emoji: '🐔', category: '鳥類' },
  { name: '公雞', emoji: '🐓', category: '鳥類' },
  { name: '小雞', emoji: '🐣', category: '鳥類' },
  { name: '孵蛋', emoji: '🐤', category: '鳥類' },
  { name: '小鳥', emoji: '🐥', category: '鳥類' },
  { name: '鳥', emoji: '🐦', category: '鳥類' },
  { name: '企鵝', emoji: '🐧', category: '鳥類' },
  { name: '鴿子', emoji: '🕊', category: '鳥類' },
  { name: '老鷹', emoji: '🦅', category: '鳥類' },
  { name: '鴨子', emoji: '🦆', category: '鳥類' },
  { name: '天鵝', emoji: '🦢', category: '鳥類' },
  { name: '貓頭鷹', emoji: '🦉', category: '鳥類' },
  { name: '大嘴鳥', emoji: '🦜', category: '鳥類' },
  { name: '孔雀', emoji: '🦚', category: '鳥類' },
  { name: '火烈鳥', emoji: '🦩', category: '鳥類' },

  // 植物
  { name: '聖誕樹', emoji: '🎄', category: '植物' },
  { name: '松樹', emoji: '🌲', category: '植物' },
  { name: '棕櫚樹', emoji: '🌴', category: '植物' },
  { name: '仙人掌', emoji: '🌵', category: '植物' },
  { name: '鬱金香', emoji: '🌷', category: '植物' },
  { name: '櫻花', emoji: '🌸', category: '植物' },
  { name: '玫瑰', emoji: '🌹', category: '植物' },
  { name: '枯萎花', emoji: '🥀', category: '植物' },
  { name: '向日葵', emoji: '🌻', category: '植物' },
  { name: '花', emoji: '🌺', category: '植物' },
  { name: '白花', emoji: '💮', category: '植物' },
  { name: '花束', emoji: '💐', category: '植物' },
  { name: '四葉草', emoji: '🍀', category: '植物' },
  { name: '三葉草', emoji: '☘', category: '植物' },
  { name: '葉子', emoji: '🍃', category: '植物' },
  { name: '楓葉', emoji: '🍂', category: '植物' },
  { name: '落葉', emoji: '🍁', category: '植物' },

  // 食物類 - 大幅擴展
  { name: '葡萄', emoji: '🍇', category: '食物' },
  { name: '哈密瓜', emoji: '🍈', category: '食物' },
  { name: '西瓜', emoji: '🍉', category: '食物' },
  { name: '橘子', emoji: '🍊', category: '食物' },
  { name: '檸檬', emoji: '🍋', category: '食物' },
  { name: '香蕉', emoji: '🍌', category: '食物' },
  { name: '鳳梨', emoji: '🍍', category: '食物' },
  { name: '芒果', emoji: '🥭', category: '食物' },
  { name: '蘋果', emoji: '🍎', category: '食物' },
  { name: '青蘋果', emoji: '🍏', category: '食物' },
  { name: '梨子', emoji: '🍐', category: '食物' },
  { name: '桃子', emoji: '🍑', category: '食物' },
  { name: '櫻桃', emoji: '🍒', category: '食物' },
  { name: '草莓', emoji: '🍓', category: '食物' },
  { name: '奇異果', emoji: '🥝', category: '食物' },
  { name: '番茄', emoji: '🍅', category: '食物' },
  { name: '椰子', emoji: '🥥', category: '食物' },
  { name: '酪梨', emoji: '🥑', category: '食物' },
  { name: '茄子', emoji: '🍆', category: '食物' },
  { name: '馬鈴薯', emoji: '🥔', category: '食物' },
  { name: '胡蘿蔔', emoji: '🥕', category: '食物' },
  { name: '玉米', emoji: '🌽', category: '食物' },
  { name: '辣椒', emoji: '🌶', category: '食物' },
  { name: '黃瓜', emoji: '🥒', category: '食物' },
  { name: '綠花椰菜', emoji: '🥦', category: '食物' },
  { name: '蘑菇', emoji: '🍄', category: '食物' },
  { name: '花生', emoji: '🥜', category: '食物' },
  { name: '栗子', emoji: '🌰', category: '食物' },
  { name: '麵包', emoji: '🍞', category: '食物' },
  { name: '牛角麵包', emoji: '🥐', category: '食物' },
  { name: '法國麵包', emoji: '🥖', category: '食物' },
  { name: '椒鹽脆餅', emoji: '🥨', category: '食物' },
  { name: '貝果', emoji: '🥯', category: '食物' },
  { name: '煎餅', emoji: '🥞', category: '食物' },
  { name: '起司', emoji: '🧀', category: '食物' },
  { name: '肉', emoji: '🍖', category: '食物' },
  { name: '雞腿', emoji: '🍗', category: '食物' },
  { name: '培根', emoji: '🥓', category: '食物' },
  { name: '漢堡', emoji: '🍔', category: '食物' },
  { name: '薯條', emoji: '🍟', category: '食物' },
  { name: '披薩', emoji: '🍕', category: '食物' },
  { name: '熱狗', emoji: '🌭', category: '食物' },
  { name: '三明治', emoji: '🥪', category: '食物' },
  { name: '塔可', emoji: '🌮', category: '食物' },
  { name: '墨西哥捲餅', emoji: '🌯', category: '食物' },
  { name: '蛋', emoji: '🥚', category: '食物' },
  { name: '料理', emoji: '🍳', category: '食物' },
  { name: '鍋', emoji: '🥘', category: '食物' },
  { name: '燉鍋', emoji: '🍲', category: '食物' },
  { name: '沙拉', emoji: '🥗', category: '食物' },
  { name: '爆米花', emoji: '🍿', category: '食物' },
  { name: '奶油', emoji: '🧈', category: '食物' },
  { name: '鹽', emoji: '🧂', category: '食物' },
  { name: '罐頭', emoji: '🥫', category: '食物' },

  // 飲品
  { name: '嬰兒奶瓶', emoji: '🍼', category: '飲品' },
  { name: '牛奶', emoji: '🥛', category: '飲品' },
  { name: '咖啡', emoji: '☕', category: '飲品' },
  { name: '茶', emoji: '🍵', category: '飲品' },
  { name: '清酒', emoji: '🍶', category: '飲品' },
  { name: '香檳', emoji: '🍾', category: '飲品' },
  { name: '紅酒', emoji: '🍷', category: '飲品' },
  { name: '雞尾酒', emoji: '🍸', category: '飲品' },
  { name: '熱帶飲料', emoji: '🍹', category: '飲品' },
  { name: '啤酒', emoji: '🍺', category: '飲品' },
  { name: '乾杯', emoji: '🍻', category: '飲品' },
  { name: '威士忌', emoji: '🥃', category: '飲品' },
  { name: '汽水', emoji: '🥤', category: '飲品' },

  // 甜點
  { name: '冰淇淋', emoji: '🍦', category: '甜點' },
  { name: '聖代', emoji: '🍧', category: '甜點' },
  { name: '刨冰', emoji: '🍨', category: '甜點' },
  { name: '甜甜圈', emoji: '🍩', category: '甜點' },
  { name: '餅乾', emoji: '🍪', category: '甜點' },
  { name: '蛋糕', emoji: '🎂', category: '甜點' },
  { name: '蛋糕切片', emoji: '🍰', category: '甜點' },
  { name: '紙杯蛋糕', emoji: '🧁', category: '甜點' },
  { name: '派', emoji: '🥧', category: '甜點' },
  { name: '巧克力棒', emoji: '🍫', category: '甜點' },
  { name: '糖果', emoji: '🍬', category: '甜點' },
  { name: '棒棒糖', emoji: '🍭', category: '甜點' },
  { name: '蜂蜜', emoji: '🍯', category: '甜點' },

  // 活動與運動
  { name: '足球', emoji: '⚽', category: '運動' },
  { name: '籃球', emoji: '🏀', category: '運動' },
  { name: '美式足球', emoji: '🏈', category: '運動' },
  { name: '棒球', emoji: '⚾', category: '運動' },
  { name: '軟式網球', emoji: '🥎', category: '運動' },
  { name: '網球', emoji: '🎾', category: '運動' },
  { name: '排球', emoji: '🏐', category: '運動' },
  { name: '橄欖球', emoji: '🏉', category: '運動' },
  { name: '桌球', emoji: '🏓', category: '運動' },
  { name: '羽球', emoji: '🏸', category: '運動' },
  { name: '冰球', emoji: '🏒', category: '運動' },
  { name: '曲棍球', emoji: '🏑', category: '運動' },
  { name: '高爾夫', emoji: '⛳', category: '運動' },
  { name: '弓箭', emoji: '🏹', category: '運動' },
  { name: '釣魚', emoji: '🎣', category: '運動' },
  { name: '拳擊手套', emoji: '🥊', category: '運動' },
  { name: '武術服', emoji: '🥋', category: '運動' },
  { name: '滑雪', emoji: '🎿', category: '運動' },
  { name: '冰刀鞋', emoji: '⛸', category: '運動' },
  { name: '雪橇', emoji: '🛷', category: '運動' },

  // 符號類 - 基礎符號
  { name: '紅心', emoji: '❤', category: '符號' },
  { name: '橘心', emoji: '🧡', category: '符號' },
  { name: '黃心', emoji: '💛', category: '符號' },
  { name: '綠心', emoji: '💚', category: '符號' },
  { name: '藍心', emoji: '💙', category: '符號' },
  { name: '紫心', emoji: '💜', category: '符號' },
  { name: '棕心', emoji: '🤎', category: '符號' },
  { name: '黑心', emoji: '🖤', category: '符號' },
  { name: '白心', emoji: '🤍', category: '符號' },
  { name: '破心', emoji: '💔', category: '符號' },
  { name: '愛心感嘆號', emoji: '❣', category: '符號' },
  { name: '兩個心', emoji: '💕', category: '符號' },
  { name: '轉心', emoji: '💞', category: '符號' },
  { name: '跳心', emoji: '💓', category: '符號' },
  { name: '成長心', emoji: '💗', category: '符號' },
  { name: '閃心', emoji: '💖', category: '符號' },
  { name: '星星', emoji: '⭐', category: '符號' },
  { name: '閃爍', emoji: '🌟', category: '符號' },
  { name: '火花', emoji: '✨', category: '符號' },
  { name: '爆炸', emoji: '💥', category: '符號' },
  { name: '火焰', emoji: '🔥', category: '符號' },
  { name: '彩虹', emoji: '🌈', category: '符號' },
  { name: '太陽', emoji: '☀', category: '符號' },
  { name: '月亮', emoji: '🌙', category: '符號' },
  { name: '雲朵', emoji: '☁', category: '符號' },
  { name: '雨滴', emoji: '💧', category: '符號' },
  { name: '雪花', emoji: '❄', category: '符號' },
  { name: '閃電', emoji: '⚡', category: '符號' },
  { name: '龍捲風', emoji: '🌪', category: '符號' },
  { name: '霧', emoji: '🌫', category: '符號' },

  // 交通工具
  { name: '汽車', emoji: '🚗', category: '交通' },
  { name: '計程車', emoji: '🚕', category: '交通' },
  { name: '藍色汽車', emoji: '🚙', category: '交通' },
  { name: '公車', emoji: '🚌', category: '交通' },
  { name: '消防車', emoji: '🚒', category: '交通' },
  { name: '警車', emoji: '🚓', category: '交通' },
  { name: '救護車', emoji: '🚑', category: '交通' },
  { name: '貨車', emoji: '🚚', category: '交通' },
  { name: '貨櫃車', emoji: '🚛', category: '交通' },
  { name: '拖車', emoji: '🚜', category: '交通' },
  { name: '腳踏車', emoji: '🚲', category: '交通' },
  { name: '機車', emoji: '🏍', category: '交通' },
  { name: '滑板車', emoji: '🛴', category: '交通' },
  { name: '火車', emoji: '🚂', category: '交通' },
  { name: '地鐵', emoji: '🚇', category: '交通' },
  { name: '電車', emoji: '🚊', category: '交通' },
  { name: '單軌電車', emoji: '🚝', category: '交通' },
  { name: '高速電車', emoji: '🚄', category: '交通' },
  { name: '子彈列車', emoji: '🚅', category: '交通' },
  { name: '飛機', emoji: '✈', category: '交通' },
  { name: '小型飛機', emoji: '🛩', category: '交通' },
  { name: '船', emoji: '🚢', category: '交通' },
  { name: '快艇', emoji: '🛥', category: '交通' },
  { name: '帆船', emoji: '⛵', category: '交通' },
  { name: '汽艇', emoji: '🚤', category: '交通' },
  { name: '火箭', emoji: '🚀', category: '交通' },
  { name: '直升機', emoji: '🚁', category: '交通' },

  // 基礎人物 - 避免膚色變化
  { name: '嬰兒', emoji: '👶', category: '人物' },
  { name: '小孩', emoji: '🧒', category: '人物' },
  { name: '男孩', emoji: '👦', category: '人物' },
  { name: '女孩', emoji: '👧', category: '人物' },
  { name: '成人', emoji: '🧑', category: '人物' },
  { name: '男人', emoji: '👨', category: '人物' },
  { name: '女人', emoji: '👩', category: '人物' },
  { name: '老人', emoji: '🧓', category: '人物' },
  { name: '老爺爺', emoji: '👴', category: '人物' },
  { name: '老奶奶', emoji: '👵', category: '人物' },

  // 手勢 - 基礎手勢
  { name: '揮手', emoji: '👋', category: '手勢' },
  { name: '舉手', emoji: '🤚', category: '手勢' },
  { name: '手掌', emoji: '🖐', category: '手勢' },
  { name: 'OK', emoji: '👌', category: '手勢' },
  { name: '和平', emoji: '✌', category: '手勢' },
  { name: '搖滾', emoji: '🤟', category: '手勢' },
  { name: '愛你', emoji: '🤘', category: '手勢' },
  { name: '食指', emoji: '☝', category: '手勢' },
  { name: '向上', emoji: '👆', category: '手勢' },
  { name: '向下', emoji: '👇', category: '手勢' },
  { name: '向左', emoji: '👈', category: '手勢' },
  { name: '向右', emoji: '👉', category: '手勢' },
  { name: '讚', emoji: '👍', category: '手勢' },
  { name: '倒讚', emoji: '👎', category: '手勢' },
  { name: '拳頭', emoji: '✊', category: '手勢' },
  { name: '前拳', emoji: '👊', category: '手勢' },
  { name: '碰拳', emoji: '🤛', category: '手勢' },
  { name: '右拳', emoji: '🤜', category: '手勢' },
  { name: '拍手', emoji: '👏', category: '手勢' },
  { name: '握手', emoji: '🤝', category: '手勢' },
  { name: '祈禱', emoji: '🙏', category: '手勢' },
  { name: '寫字', emoji: '✍', category: '手勢' },
  { name: '指甲', emoji: '💅', category: '手勢' },
  { name: '肌肉', emoji: '💪', category: '手勢' },

  // 物品
  { name: '電腦', emoji: '💻', category: '物品' },
  { name: '手機', emoji: '📱', category: '物品' },
  { name: '電話', emoji: '☎', category: '物品' },
  { name: '相機', emoji: '📷', category: '物品' },
  { name: '錶', emoji: '⌚', category: '物品' },
  { name: '電視', emoji: '📺', category: '物品' },
  { name: '收音機', emoji: '📻', category: '物品' },
  { name: '遊戲機', emoji: '🎮', category: '物品' },
  { name: '鍵盤', emoji: '⌨', category: '物品' },
  { name: '滑鼠', emoji: '🖱', category: '物品' },
  { name: '書', emoji: '📖', category: '物品' },
  { name: '筆記本', emoji: '📓', category: '物品' },
  { name: '筆', emoji: '✏', category: '物品' },
  { name: '鉛筆', emoji: '📝', category: '物品' },
  { name: '剪刀', emoji: '✂', category: '物品' },
  { name: '鎖', emoji: '🔒', category: '物品' },
  { name: '開鎖', emoji: '🔓', category: '物品' },
  { name: '鑰匙', emoji: '🔑', category: '物品' },
  { name: '舊鑰匙', emoji: '🗝', category: '物品' },
  { name: '錢', emoji: '💰', category: '物品' },
  { name: '錢袋', emoji: '💸', category: '物品' },
  { name: '信用卡', emoji: '💳', category: '物品' },
  { name: '寶石', emoji: '💎', category: '物品' },
  { name: '禮物', emoji: '🎁', category: '物品' },
  { name: '氣球', emoji: '🎈', category: '物品' },
  { name: '聚會', emoji: '🎉', category: '物品' },
  { name: '彩帶', emoji: '🎊', category: '物品' },
  { name: '皇冠', emoji: '👑', category: '物品' },
  { name: '帽子', emoji: '🎩', category: '物品' },
  { name: '畢業帽', emoji: '🎓', category: '物品' },
  { name: '眼鏡', emoji: '👓', category: '物品' },
  { name: '太陽眼鏡', emoji: '🕶', category: '物品' },
  { name: '領帶', emoji: '👔', category: '物品' },
  { name: 'T恤', emoji: '👕', category: '物品' },
  { name: '牛仔褲', emoji: '👖', category: '物品' },
  { name: '洋裝', emoji: '👗', category: '物品' },
  { name: '比基尼', emoji: '👙', category: '物品' },
  { name: '和服', emoji: '👘', category: '物品' },
  { name: '高跟鞋', emoji: '👠', category: '物品' },
  { name: '女鞋', emoji: '👡', category: '物品' },
  { name: '涼鞋', emoji: '👢', category: '物品' },
  { name: '男鞋', emoji: '👞', category: '物品' },
  { name: '運動鞋', emoji: '👟', category: '物品' },
  { name: '包包', emoji: '👜', category: '物品' },
  { name: '手提包', emoji: '👛', category: '物品' },
  { name: '錢包', emoji: '👝', category: '物品' },
  { name: '背包', emoji: '🎒', category: '物品' },
  { name: '雨傘', emoji: '☂', category: '物品' },
  { name: '雨傘2', emoji: '☔', category: '物品' },

  // 音樂
  { name: '音符', emoji: '🎵', category: '音樂' },
  { name: '音符2', emoji: '🎶', category: '音樂' },
  { name: '麥克風', emoji: '🎤', category: '音樂' },
  { name: '耳機', emoji: '🎧', category: '音樂' },
  { name: '薩克斯風', emoji: '🎷', category: '音樂' },
  { name: '小提琴', emoji: '🎻', category: '音樂' },
  { name: '鼓', emoji: '🥁', category: '音樂' },
  { name: '鋼琴', emoji: '🎹', category: '音樂' },
  { name: '喇叭', emoji: '📯', category: '音樂' }
]

// 將 emoji 按類別分組
export const cleanEmojiCategories = {
  '表情': cleanEmojis.filter(e => e.category === '表情'),
  '動物': cleanEmojis.filter(e => e.category === '動物'),
  '海洋': cleanEmojis.filter(e => e.category === '海洋'),
  '昆蟲': cleanEmojis.filter(e => e.category === '昆蟲'),
  '鳥類': cleanEmojis.filter(e => e.category === '鳥類'),
  '植物': cleanEmojis.filter(e => e.category === '植物'),
  '食物': cleanEmojis.filter(e => e.category === '食物'),
  '飲品': cleanEmojis.filter(e => e.category === '飲品'),
  '甜點': cleanEmojis.filter(e => e.category === '甜點'),
  '運動': cleanEmojis.filter(e => e.category === '運動'),
  '符號': cleanEmojis.filter(e => e.category === '符號'),
  '交通': cleanEmojis.filter(e => e.category === '交通'),
  '人物': cleanEmojis.filter(e => e.category === '人物'),
  '手勢': cleanEmojis.filter(e => e.category === '手勢'),
  '物品': cleanEmojis.filter(e => e.category === '物品'),
  '音樂': cleanEmojis.filter(e => e.category === '音樂')
}