// 相容性更好的 Emoji 列表 - 移除複合 emoji 和膚色變化
export const compatibleEmojis = [
  // 表情與情緒 - 基礎表情符號
  { name: '微笑', emoji: '😀', category: '表情' },
  { name: '露齒笑', emoji: '😃', category: '表情' },
  { name: '大笑', emoji: '😄', category: '表情' },
  { name: '眯眼笑', emoji: '😁', category: '表情' },
  { name: '笑哭', emoji: '😆', category: '表情' },
  { name: '汗笑', emoji: '😅', category: '表情' },
  { name: '笑翻', emoji: '🤣', category: '表情' },
  { name: '喜極而泣', emoji: '😂', category: '表情' },
  { name: '微微笑', emoji: '🙂', category: '表情' },
  { name: '倒臉', emoji: '🙃', category: '表情' },
  { name: '眨眼', emoji: '😉', category: '表情' },
  { name: '羞笑', emoji: '😊', category: '表情' },
  { name: '天使', emoji: '😇', category: '表情' },
  { name: '愛心眼', emoji: '😍', category: '表情' },
  { name: '星星眼', emoji: '🤩', category: '表情' },
  { name: '飛吻', emoji: '😘', category: '表情' },
  { name: '親吻', emoji: '😗', category: '表情' },
  { name: '微笑2', emoji: '☺️', category: '表情' },
  { name: '親親', emoji: '😚', category: '表情' },
  { name: '含笑', emoji: '😙', category: '表情' },
  { name: '吐舌', emoji: '😋', category: '表情' },
  { name: '吐舌眨眼', emoji: '😜', category: '表情' },
  { name: '搞怪', emoji: '🤪', category: '表情' },
  { name: '吐舌笑', emoji: '😝', category: '表情' },
  { name: '錢', emoji: '🤑', category: '表情' },
  { name: '擁抱', emoji: '🤗', category: '表情' },
  { name: '噓', emoji: '🤭', category: '表情' },
  { name: '安靜', emoji: '🤫', category: '表情' },
  { name: '沉思', emoji: '🤔', category: '表情' },
  { name: '拉鍊嘴', emoji: '🤐', category: '表情' },
  { name: '挑眉', emoji: '🤨', category: '表情' },
  { name: '無語', emoji: '😐', category: '表情' },
  { name: '面無表情', emoji: '😑', category: '表情' },
  { name: '無口', emoji: '😶', category: '表情' },
  { name: '假笑', emoji: '😏', category: '表情' },
  { name: '不爽', emoji: '😒', category: '表情' },
  { name: '翻白眼', emoji: '🙄', category: '表情' },
  { name: '做鬼臉', emoji: '😬', category: '表情' },
  { name: '說謊', emoji: '🤥', category: '表情' },
  { name: '鬆口氣', emoji: '😌', category: '表情' },
  { name: '疲憊', emoji: '😔', category: '表情' },
  { name: '睏', emoji: '😪', category: '表情' },
  { name: '口罩', emoji: '😷', category: '表情' },
  { name: '發燒', emoji: '🤒', category: '表情' },
  { name: '包紮', emoji: '🤕', category: '表情' },
  { name: '嘔吐', emoji: '🤢', category: '表情' },
  { name: '噁心', emoji: '🤮', category: '表情' },
  { name: '打噴嚏', emoji: '🤧', category: '表情' },
  { name: '發熱', emoji: '🥵', category: '表情' },
  { name: '冰冷', emoji: '🥶', category: '表情' },
  { name: '暈', emoji: '🥴', category: '表情' },
  { name: '暈倒', emoji: '😵', category: '表情' },
  { name: '爆炸頭', emoji: '🤯', category: '表情' },

  // 動物類 - 基礎動物符號
  { name: '猴臉', emoji: '🐵', category: '動物' },
  { name: '猴子', emoji: '🐒', category: '動物' },
  { name: '大猩猩', emoji: '🦍', category: '動物' },
  { name: '猩猩', emoji: '🦧', category: '動物' },
  { name: '狗臉', emoji: '🐶', category: '動物' },
  { name: '狗', emoji: '🐕', category: '動物' },
  { name: '獵犬', emoji: '🦮', category: '動物' },
  { name: '貴賓狗', emoji: '🐩', category: '動物' },
  { name: '狼', emoji: '🐺', category: '動物' },
  { name: '狐狸', emoji: '🦊', category: '動物' },
  { name: '浣熊', emoji: '🦝', category: '動物' },
  { name: '貓臉', emoji: '🐱', category: '動物' },
  { name: '貓', emoji: '🐈', category: '動物' },
  { name: '獅子', emoji: '🦁', category: '動物' },
  { name: '老虎臉', emoji: '🐯', category: '動物' },
  { name: '老虎', emoji: '🐅', category: '動物' },
  { name: '豹', emoji: '🐆', category: '動物' },
  { name: '馬臉', emoji: '🐴', category: '動物' },
  { name: '馬', emoji: '🐎', category: '動物' },
  { name: '獨角獸', emoji: '🦄', category: '動物' },
  { name: '斑馬', emoji: '🦓', category: '動物' },
  { name: '鹿', emoji: '🦌', category: '動物' },
  { name: '牛臉', emoji: '🐮', category: '動物' },
  { name: '牛', emoji: '🐄', category: '動物' },
  { name: '水牛', emoji: '🐃', category: '動物' },
  { name: '牦牛', emoji: '🦬', category: '動物' },
  { name: '豬臉', emoji: '🐷', category: '動物' },
  { name: '豬', emoji: '🐖', category: '動物' },
  { name: '野豬', emoji: '🐗', category: '動物' },
  { name: '羊', emoji: '🐑', category: '動物' },
  { name: '綿羊', emoji: '🐏', category: '動物' },
  { name: '山羊', emoji: '🐐', category: '動物' },
  { name: '駱駝', emoji: '🐪', category: '動物' },
  { name: '雙峰駱駝', emoji: '🐫', category: '動物' },
  { name: '長頸鹿', emoji: '🦒', category: '動物' },
  { name: '大象', emoji: '🐘', category: '動物' },
  { name: '犀牛', emoji: '🦏', category: '動物' },
  { name: '河馬', emoji: '🦛', category: '動物' },
  { name: '老鼠臉', emoji: '🐭', category: '動物' },
  { name: '老鼠', emoji: '🐁', category: '動物' },
  { name: '倉鼠', emoji: '🐹', category: '動物' },
  { name: '兔臉', emoji: '🐰', category: '動物' },
  { name: '兔子', emoji: '🐇', category: '動物' },
  { name: '松鼠', emoji: '🐿️', category: '動物' },
  { name: '刺蝟', emoji: '🦔', category: '動物' },
  { name: '熊臉', emoji: '🐻', category: '動物' },
  { name: '無尾熊', emoji: '🐨', category: '動物' },
  { name: '熊貓', emoji: '🐼', category: '動物' },
  { name: '懶熊', emoji: '🦥', category: '動物' },
  { name: '水獺', emoji: '🦦', category: '動物' },
  { name: '臭鼬', emoji: '🦨', category: '動物' },
  { name: '袋鼠', emoji: '🦘', category: '動物' },
  { name: '穿山甲', emoji: '🦡', category: '動物' },

  // 鳥類
  { name: '火雞', emoji: '🦃', category: '鳥類' },
  { name: '雞', emoji: '🐔', category: '鳥類' },
  { name: '公雞', emoji: '🐓', category: '鳥類' },
  { name: '小雞', emoji: '🐣', category: '鳥類' },
  { name: '孵蛋', emoji: '🐤', category: '鳥類' },
  { name: '小鳥', emoji: '🐥', category: '鳥類' },
  { name: '鳥', emoji: '🐦', category: '鳥類' },
  { name: '企鵝', emoji: '🐧', category: '鳥類' },
  { name: '鴿子', emoji: '🕊️', category: '鳥類' },
  { name: '老鷹', emoji: '🦅', category: '鳥類' },
  { name: '鴨子', emoji: '🦆', category: '鳥類' },
  { name: '天鵝', emoji: '🦢', category: '鳥類' },
  { name: '貓頭鷹', emoji: '🦉', category: '鳥類' },
  { name: '大嘴鳥', emoji: '🦜', category: '鳥類' },
  { name: '孔雀', emoji: '🦚', category: '鳥類' },
  { name: '火烈鳥', emoji: '🦩', category: '鳥類' },

  // 食物類 - 基礎食物符號
  { name: '蘋果', emoji: '🍎', category: '食物' },
  { name: '青蘋果', emoji: '🍏', category: '食物' },
  { name: '梨子', emoji: '🍐', category: '食物' },
  { name: '橘子', emoji: '🍊', category: '食物' },
  { name: '檸檬', emoji: '🍋', category: '食物' },
  { name: '香蕉', emoji: '🍌', category: '食物' },
  { name: '西瓜', emoji: '🍉', category: '食物' },
  { name: '葡萄', emoji: '🍇', category: '食物' },
  { name: '草莓', emoji: '🍓', category: '食物' },
  { name: '藍莓', emoji: '🫐', category: '食物' },
  { name: '哈密瓜', emoji: '🍈', category: '食物' },
  { name: '櫻桃', emoji: '🍒', category: '食物' },
  { name: '桃子', emoji: '🍑', category: '食物' },
  { name: '芒果', emoji: '🥭', category: '食物' },
  { name: '鳳梨', emoji: '🍍', category: '食物' },
  { name: '椰子', emoji: '🥥', category: '食物' },
  { name: '奇異果', emoji: '🥝', category: '食物' },
  { name: '番茄', emoji: '🍅', category: '食物' },
  { name: '茄子', emoji: '🍆', category: '食物' },
  { name: '玉米', emoji: '🌽', category: '食物' },
  { name: '胡蘿蔔', emoji: '🥕', category: '食物' },
  { name: '橄欖', emoji: '🫒', category: '食物' },
  { name: '青椒', emoji: '🫑', category: '食物' },
  { name: '黃瓜', emoji: '🥒', category: '食物' },
  { name: '綠花椰菜', emoji: '🥦', category: '食物' },
  { name: '蒜', emoji: '🧄', category: '食物' },
  { name: '洋蔥', emoji: '🧅', category: '食物' },
  { name: '馬鈴薯', emoji: '🥔', category: '食物' },
  { name: '地瓜', emoji: '🍠', category: '食物' },
  { name: '豆子', emoji: '🫘', category: '食物' },
  { name: '蘑菇', emoji: '🍄', category: '食物' },

  // 活動與娛樂
  { name: '足球', emoji: '⚽', category: '運動' },
  { name: '籃球', emoji: '🏀', category: '運動' },
  { name: '美式足球', emoji: '🏈', category: '運動' },
  { name: '棒球', emoji: '⚾', category: '運動' },
  { name: '網球', emoji: '🎾', category: '運動' },
  { name: '排球', emoji: '🏐', category: '運動' },
  { name: '桌球', emoji: '🏓', category: '運動' },
  { name: '羽球', emoji: '🏸', category: '運動' },
  { name: '曲棍球', emoji: '🏑', category: '運動' },
  { name: '保齡球', emoji: '🎳', category: '運動' },
  { name: '板球', emoji: '🏏', category: '運動' },

  // 符號類 - 基礎符號
  { name: '紅心', emoji: '❤️', category: '符號' },
  { name: '橘心', emoji: '🧡', category: '符號' },
  { name: '黃心', emoji: '💛', category: '符號' },
  { name: '綠心', emoji: '💚', category: '符號' },
  { name: '藍心', emoji: '💙', category: '符號' },
  { name: '紫心', emoji: '💜', category: '符號' },
  { name: '棕心', emoji: '🤎', category: '符號' },
  { name: '黑心', emoji: '🖤', category: '符號' },
  { name: '白心', emoji: '🤍', category: '符號' },
  { name: '粉心', emoji: '🩷', category: '符號' },
  { name: '破心', emoji: '💔', category: '符號' },
  { name: '愛心感嘆號', emoji: '❣️', category: '符號' },
  { name: '兩個心', emoji: '💕', category: '符號' },
  { name: '轉心', emoji: '💞', category: '符號' },
  { name: '跳心', emoji: '💓', category: '符號' },
  { name: '成長心', emoji: '💗', category: '符號' },
  { name: '閃心', emoji: '💖', category: '符號' },
  { name: '星星', emoji: '⭐', category: '符號' },
  { name: '閃爍', emoji: '🌟', category: '符號' },
  { name: '火花', emoji: '✨', category: '符號' },
  { name: '爆炸', emoji: '💥', category: '符號' },
  { name: '火焰', emoji: '🔥', category: '符號' },
  { name: '彩虹', emoji: '🌈', category: '符號' },
  { name: '太陽', emoji: '☀️', category: '符號' },
  { name: '月亮', emoji: '🌙', category: '符號' },
  { name: '雲朵', emoji: '☁️', category: '符號' },
  { name: '雨滴', emoji: '💧', category: '符號' },
  { name: '雪花', emoji: '❄️', category: '符號' },

  // 基礎人物 - 避免膚色變化
  { name: '嬰兒', emoji: '👶', category: '人物' },
  { name: '小孩', emoji: '🧒', category: '人物' },
  { name: '男孩', emoji: '👦', category: '人物' },
  { name: '女孩', emoji: '👧', category: '人物' },
  { name: '成人', emoji: '🧑', category: '人物' },
  { name: '男人', emoji: '👨', category: '人物' },
  { name: '女人', emoji: '👩', category: '人物' },
  { name: '老人', emoji: '🧓', category: '人物' },
  { name: '老爺爺', emoji: '👴', category: '人物' },
  { name: '老奶奶', emoji: '👵', category: '人物' },

  // 手勢 - 基礎手勢
  { name: '揮手', emoji: '👋', category: '手勢' },
  { name: '舉手', emoji: '🤚', category: '手勢' },
  { name: '手掌', emoji: '🖐️', category: '手勢' },
  { name: 'OK', emoji: '👌', category: '手勢' },
  { name: '和平', emoji: '✌️', category: '手勢' },
  { name: '搖滾', emoji: '🤟', category: '手勢' },
  { name: '愛你', emoji: '🤘', category: '手勢' },
  { name: '食指', emoji: '☝️', category: '手勢' },
  { name: '向上', emoji: '👆', category: '手勢' },
  { name: '向下', emoji: '👇', category: '手勢' },
  { name: '向左', emoji: '👈', category: '手勢' },
  { name: '向右', emoji: '👉', category: '手勢' },
  { name: '讚', emoji: '👍', category: '手勢' },
  { name: '倒讚', emoji: '👎', category: '手勢' },
  { name: '拳頭', emoji: '✊', category: '手勢' },
  { name: '前拳', emoji: '👊', category: '手勢' },
  { name: '碰拳', emoji: '🤛', category: '手勢' },
  { name: '右拳', emoji: '🤜', category: '手勢' },
  { name: '拍手', emoji: '👏', category: '手勢' },
  { name: '握手', emoji: '🤝', category: '手勢' },
  { name: '祈禱', emoji: '🙏', category: '手勢' },

  // 物品
  { name: '電腦', emoji: '💻', category: '物品' },
  { name: '手機', emoji: '📱', category: '物品' },
  { name: '電話', emoji: '☎️', category: '物品' },
  { name: '相機', emoji: '📷', category: '物品' },
  { name: '錶', emoji: '⌚', category: '物品' },
  { name: '電視', emoji: '📺', category: '物品' },
  { name: '收音機', emoji: '📻', category: '物品' },
  { name: '遊戲機', emoji: '🎮', category: '物品' },
  { name: '鍵盤', emoji: '⌨️', category: '物品' },
  { name: '滑鼠', emoji: '🖱️', category: '物品' },
  { name: '書', emoji: '📖', category: '物品' },
  { name: '筆記本', emoji: '📓', category: '物品' },
  { name: '筆', emoji: '✏️', category: '物品' },
  { name: '鉛筆', emoji: '📝', category: '物品' },
  { name: '剪刀', emoji: '✂️', category: '物品' },
  { name: '鎖', emoji: '🔒', category: '物品' },
  { name: '鑰匙', emoji: '🔑', category: '物品' },
  { name: '錢', emoji: '💰', category: '物品' },
  { name: '信用卡', emoji: '💳', category: '物品' },
  { name: '禮物', emoji: '🎁', category: '物品' },
  { name: '氣球', emoji: '🎈', category: '物品' },
  { name: '聚會', emoji: '🎉', category: '物品' },
  { name: '蛋糕', emoji: '🎂', category: '物品' },
  { name: '皇冠', emoji: '👑', category: '物品' },
  { name: '帽子', emoji: '🎩', category: '物品' },
  { name: '眼鏡', emoji: '👓', category: '物品' },
  { name: '太陽眼鏡', emoji: '🕶️', category: '物品' },
  { name: '領帶', emoji: '👔', category: '物品' },
  { name: 'T恤', emoji: '👕', category: '物品' },
  { name: '鞋子', emoji: '👞', category: '物品' },
  { name: '運動鞋', emoji: '👟', category: '物品' },
  { name: '高跟鞋', emoji: '👠', category: '物品' },
  { name: '包包', emoji: '👜', category: '物品' },
  { name: '背包', emoji: '🎒', category: '物品' }
]

// 將 emoji 按類別分組
export const emojiCategories = {
  '表情': compatibleEmojis.filter(e => e.category === '表情'),
  '動物': compatibleEmojis.filter(e => e.category === '動物'),
  '鳥類': compatibleEmojis.filter(e => e.category === '鳥類'),
  '食物': compatibleEmojis.filter(e => e.category === '食物'),
  '運動': compatibleEmojis.filter(e => e.category === '運動'),
  '符號': compatibleEmojis.filter(e => e.category === '符號'),
  '人物': compatibleEmojis.filter(e => e.category === '人物'),
  '手勢': compatibleEmojis.filter(e => e.category === '手勢'),
  '物品': compatibleEmojis.filter(e => e.category === '物品')
}