// 完整的 Bootstrap Icons 清單
export const bootstrapIcons = [
  // 基本圖標
  { name: '首頁 Home', class: 'bi-house' },
  { name: '使用者 Person', class: 'bi-person' },
  { name: '使用者群組 People', class: 'bi-people' },
  { name: '設定 Gear', class: 'bi-gear' },
  { name: '設定填滿 Gear Fill', class: 'bi-gear-fill' },
  { name: '文件 File', class: 'bi-file-text' },
  { name: '文件填滿 File Fill', class: 'bi-file-text-fill' },
  { name: '資料夾 Folder', class: 'bi-folder' },
  { name: '資料夾填滿 Folder Fill', class: 'bi-folder-fill' },
  { name: '愛心 Heart', class: 'bi-heart' },
  { name: '愛心填滿 Heart Fill', class: 'bi-heart-fill' },
  { name: '星星 Star', class: 'bi-star' },
  { name: '星星填滿 Star Fill', class: 'bi-star-fill' },
  { name: '鈴鐺 Bell', class: 'bi-bell' },
  { name: '鈴鐺填滿 Bell Fill', class: 'bi-bell-fill' },
  { name: '聊天 Chat', class: 'bi-chat' },
  { name: '聊天填滿 Chat Fill', class: 'bi-chat-fill' },
  
  // 操作圖標
  { name: '加號 Plus', class: 'bi-plus' },
  { name: '減號 Dash', class: 'bi-dash' },
  { name: '關閉 X', class: 'bi-x' },
  { name: '勾選 Check', class: 'bi-check' },
  { name: '勾選2 Check2', class: 'bi-check2' },
  { name: '編輯 Pencil', class: 'bi-pencil' },
  { name: '編輯填滿 Pencil Fill', class: 'bi-pencil-fill' },
  { name: '刪除 Trash', class: 'bi-trash' },
  { name: '刪除填滿 Trash Fill', class: 'bi-trash-fill' },
  { name: '眼睛 Eye', class: 'bi-eye' },
  { name: '眼睛填滿 Eye Fill', class: 'bi-eye-fill' },
  { name: '眼睛斜線 Eye Slash', class: 'bi-eye-slash' },
  { name: '搜尋 Search', class: 'bi-search' },
  
  // 通訊圖標
  { name: '信件 Envelope', class: 'bi-envelope' },
  { name: '信件填滿 Envelope Fill', class: 'bi-envelope-fill' },
  { name: '電話 Phone', class: 'bi-telephone' },
  { name: '電話填滿 Phone Fill', class: 'bi-telephone-fill' },
  { name: '手機 Phone', class: 'bi-phone' },
  { name: '手機填滿 Phone Fill', class: 'bi-phone-fill' },
  
  // 時間與日期
  { name: '日曆 Calendar', class: 'bi-calendar' },
  { name: '日曆填滿 Calendar Fill', class: 'bi-calendar-fill' },
  { name: '時鐘 Clock', class: 'bi-clock' },
  { name: '時鐘填滿 Clock Fill', class: 'bi-clock-fill' },
  { name: '鬧鐘 Alarm', class: 'bi-alarm' },
  { name: '鬧鐘填滿 Alarm Fill', class: 'bi-alarm-fill' },
  
  // 媒體圖標
  { name: '相機 Camera', class: 'bi-camera' },
  { name: '相機填滿 Camera Fill', class: 'bi-camera-fill' },
  { name: '圖片 Image', class: 'bi-image' },
  { name: '圖片填滿 Image Fill', class: 'bi-image-fill' },
  { name: '音樂 Music', class: 'bi-music-note' },
  { name: '播放 Play', class: 'bi-play' },
  { name: '播放填滿 Play Fill', class: 'bi-play-fill' },
  { name: '暫停 Pause', class: 'bi-pause' },
  { name: '暫停填滿 Pause Fill', class: 'bi-pause-fill' },
  { name: '停止 Stop', class: 'bi-stop' },
  { name: '停止填滿 Stop Fill', class: 'bi-stop-fill' },
  { name: '影片 Camera Video', class: 'bi-camera-video' },
  { name: '影片填滿 Camera Video Fill', class: 'bi-camera-video-fill' },
  
  // 導航圖標
  { name: '地圖 Map', class: 'bi-map' },
  { name: '地圖填滿 Map Fill', class: 'bi-map-fill' },
  { name: '指南針 Compass', class: 'bi-compass' },
  { name: '指南針填滿 Compass Fill', class: 'bi-compass-fill' },
  { name: '位置 Geo Alt', class: 'bi-geo-alt' },
  { name: '位置填滿 Geo Alt Fill', class: 'bi-geo-alt-fill' },
  
  // 箭頭圖標
  { name: '箭頭上 Arrow Up', class: 'bi-arrow-up' },
  { name: '箭頭下 Arrow Down', class: 'bi-arrow-down' },
  { name: '箭頭左 Arrow Left', class: 'bi-arrow-left' },
  { name: '箭頭右 Arrow Right', class: 'bi-arrow-right' },
  { name: '箭頭上短 Arrow Up Short', class: 'bi-arrow-up-short' },
  { name: '箭頭下短 Arrow Down Short', class: 'bi-arrow-down-short' },
  { name: '箭頭左短 Arrow Left Short', class: 'bi-arrow-left-short' },
  { name: '箭頭右短 Arrow Right Short', class: 'bi-arrow-right-short' },
  
  // 購物與商務
  { name: '購物車 Cart', class: 'bi-cart' },
  { name: '購物車填滿 Cart Fill', class: 'bi-cart-fill' },
  { name: '購物袋 Bag', class: 'bi-bag' },
  { name: '購物袋填滿 Bag Fill', class: 'bi-bag-fill' },
  { name: '錢包 Wallet', class: 'bi-wallet' },
  { name: '錢包填滿 Wallet Fill', class: 'bi-wallet-fill' },
  { name: '信用卡 Credit Card', class: 'bi-credit-card' },
  { name: '信用卡填滿 Credit Card Fill', class: 'bi-credit-card-fill' },
  
  // 安全圖標
  { name: '鑰匙 Key', class: 'bi-key' },
  { name: '鑰匙填滿 Key Fill', class: 'bi-key-fill' },
  { name: '鎖 Lock', class: 'bi-lock' },
  { name: '鎖填滿 Lock Fill', class: 'bi-lock-fill' },
  { name: '解鎖 Unlock', class: 'bi-unlock' },
  { name: '解鎖填滿 Unlock Fill', class: 'bi-unlock-fill' },
  { name: '盾牌 Shield', class: 'bi-shield' },
  { name: '盾牌填滿 Shield Fill', class: 'bi-shield-fill' },
  { name: '盾牌勾選 Shield Check', class: 'bi-shield-check' },
  { name: '盾牌勾選填滿 Shield Check Fill', class: 'bi-shield-check-fill' },
  
  // 狀態圖標
  { name: '警告 Warning', class: 'bi-exclamation-triangle' },
  { name: '警告填滿 Warning Fill', class: 'bi-exclamation-triangle-fill' },
  { name: '資訊 Info', class: 'bi-info-circle' },
  { name: '資訊填滿 Info Fill', class: 'bi-info-circle-fill' },
  { name: '問號 Question', class: 'bi-question-circle' },
  { name: '問號填滿 Question Fill', class: 'bi-question-circle-fill' },
  { name: '驚嘆號 Exclamation', class: 'bi-exclamation' },
  
  // 網路與雲端
  { name: '雲端 Cloud', class: 'bi-cloud' },
  { name: '雲端填滿 Cloud Fill', class: 'bi-cloud-fill' },
  { name: '雲端下載 Cloud Download', class: 'bi-cloud-download' },
  { name: '雲端下載填滿 Cloud Download Fill', class: 'bi-cloud-download-fill' },
  { name: '雲端上傳 Cloud Upload', class: 'bi-cloud-upload' },
  { name: '雲端上傳填滿 Cloud Upload Fill', class: 'bi-cloud-upload-fill' },
  { name: '下載 Download', class: 'bi-download' },
  { name: '上傳 Upload', class: 'bi-upload' },
  { name: '分享 Share', class: 'bi-share' },
  { name: '分享填滿 Share Fill', class: 'bi-share-fill' },
  
  // 書籤與收藏
  { name: '書籤 Bookmark', class: 'bi-bookmark' },
  { name: '書籤填滿 Bookmark Fill', class: 'bi-bookmark-fill' },
  { name: '旗幟 Flag', class: 'bi-flag' },
  { name: '旗幟填滿 Flag Fill', class: 'bi-flag-fill' },
  { name: '標籤 Tag', class: 'bi-tag' },
  { name: '標籤填滿 Tag Fill', class: 'bi-tag-fill' }
]

// 完整的 Emoji 清單
export const emojis = [
  // 表情符號
  { name: '微笑 Smile', emoji: '😊' },
  { name: '大笑 Laugh', emoji: '😂' },
  { name: '眨眼 Wink', emoji: '😉' },
  { name: '親吻 Kiss', emoji: '😘' },
  { name: '驚訝 Surprised', emoji: '😮' },
  { name: '思考 Think', emoji: '🤔' },
  { name: '酷 Cool', emoji: '😎' },
  { name: '愛心眼 Love Eyes', emoji: '😍' },
  { name: '臉紅 Blush', emoji: '😳' },
  { name: '哭泣 Cry', emoji: '😢' },
  { name: '生氣 Angry', emoji: '😡' },
  { name: '害怕 Fear', emoji: '😨' },
  
  // 手勢
  { name: '讚 Thumbs Up', emoji: '👍' },
  { name: '倒讚 Thumbs Down', emoji: '👎' },
  { name: 'OK手勢 OK', emoji: '👌' },
  { name: '勝利 Victory', emoji: '✌️' },
  { name: '揮手 Wave', emoji: '👋' },
  { name: '拳頭 Fist', emoji: '✊' },
  { name: '祈禱 Pray', emoji: '🙏' },
  { name: '拍手 Clap', emoji: '👏' },
  { name: '愛心手 Love Hand', emoji: '🤟' },
  { name: '指向 Point', emoji: '👉' },
  
  // 愛心與符號
  { name: '愛心 Heart', emoji: '❤️' },
  { name: '橘色愛心 Orange Heart', emoji: '🧡' },
  { name: '黃色愛心 Yellow Heart', emoji: '💛' },
  { name: '綠色愛心 Green Heart', emoji: '💚' },
  { name: '藍色愛心 Blue Heart', emoji: '💙' },
  { name: '紫色愛心 Purple Heart', emoji: '💜' },
  { name: '黑色愛心 Black Heart', emoji: '🖤' },
  { name: '破碎愛心 Broken Heart', emoji: '💔' },
  { name: '火 Fire', emoji: '🔥' },
  { name: '閃電 Lightning', emoji: '⚡' },
  { name: '星星 Star', emoji: '⭐' },
  { name: '閃亮 Sparkles', emoji: '✨' },
  
  // 天氣與自然
  { name: '太陽 Sun', emoji: '☀️' },
  { name: '月亮 Moon', emoji: '🌙' },
  { name: '雲朵 Cloud', emoji: '☁️' },
  { name: '雨 Rain', emoji: '🌧️' },
  { name: '雪花 Snow', emoji: '❄️' },
  { name: '彩虹 Rainbow', emoji: '🌈' },
  { name: '海浪 Wave', emoji: '🌊' },
  { name: '山 Mountain', emoji: '⛰️' },
  { name: '樹 Tree', emoji: '🌳' },
  { name: '花 Flower', emoji: '🌸' },
  { name: '玫瑰 Rose', emoji: '🌹' },
  { name: '葉子 Leaf', emoji: '🍃' },
  
  // 動物
  { name: '貓 Cat', emoji: '🐱' },
  { name: '狗 Dog', emoji: '🐶' },
  { name: '熊 Bear', emoji: '🐻' },
  { name: '兔子 Rabbit', emoji: '🐰' },
  { name: '老虎 Tiger', emoji: '🐯' },
  { name: '獅子 Lion', emoji: '🦁' },
  { name: '猴子 Monkey', emoji: '🐵' },
  { name: '大象 Elephant', emoji: '🐘' },
  { name: '企鵝 Penguin', emoji: '🐧' },
  { name: '鳥 Bird', emoji: '🐦' },
  { name: '魚 Fish', emoji: '🐟' },
  { name: '蝴蝶 Butterfly', emoji: '🦋' },
  
  // 食物
  { name: '蛋糕 Cake', emoji: '🎂' },
  { name: '披薩 Pizza', emoji: '🍕' },
  { name: '漢堡 Burger', emoji: '🍔' },
  { name: '咖啡 Coffee', emoji: '☕' },
  { name: '茶 Tea', emoji: '🍵' },
  { name: '蘋果 Apple', emoji: '🍎' },
  { name: '香蕉 Banana', emoji: '🍌' },
  { name: '草莓 Strawberry', emoji: '🍓' },
  { name: '甜甜圈 Donut', emoji: '🍩' },
  { name: '冰淇淋 Ice Cream', emoji: '🍦' },
  { name: '巧克力 Chocolate', emoji: '🍫' },
  { name: '糖果 Candy', emoji: '🍬' },
  
  // 交通
  { name: '汽車 Car', emoji: '🚗' },
  { name: '公車 Bus', emoji: '🚌' },
  { name: '火車 Train', emoji: '🚆' },
  { name: '飛機 Plane', emoji: '✈️' },
  { name: '火箭 Rocket', emoji: '🚀' },
  { name: '船 Ship', emoji: '🚢' },
  { name: '單車 Bike', emoji: '🚲' },
  { name: '機車 Motorcycle', emoji: '🏍️' },
  { name: '救護車 Ambulance', emoji: '🚑' },
  { name: '消防車 Fire Truck', emoji: '🚒' },
  { name: '警車 Police Car', emoji: '🚓' },
  { name: '計程車 Taxi', emoji: '🚕' },
  
  // 物品與工具
  { name: '家 House', emoji: '🏠' },
  { name: '辦公室 Office', emoji: '🏢' },
  { name: '學校 School', emoji: '🏫' },
  { name: '醫院 Hospital', emoji: '🏥' },
  { name: '書 Book', emoji: '📖' },
  { name: '筆記本 Notebook', emoji: '📓' },
  { name: '鉛筆 Pencil', emoji: '✏️' },
  { name: '剪刀 Scissors', emoji: '✂️' },
  { name: '鑰匙 Key', emoji: '🔑' },
  { name: '鎖 Lock', emoji: '🔒' },
  { name: '燈泡 Bulb', emoji: '💡' },
  { name: '電池 Battery', emoji: '🔋' },
  
  // 科技
  { name: '電腦 Computer', emoji: '💻' },
  { name: '手機 Phone', emoji: '📱' },
  { name: '相機 Camera', emoji: '📷' },
  { name: '電視 TV', emoji: '📺' },
  { name: '收音機 Radio', emoji: '📻' },
  { name: '耳機 Headphones', emoji: '🎧' },
  { name: '遊戲手把 Game Controller', emoji: '🎮' },
  { name: '鍵盤 Keyboard', emoji: '⌨️' },
  { name: '滑鼠 Mouse', emoji: '🖱️' },
  { name: 'CD', emoji: '💿' },
  { name: 'USB', emoji: '💾' },
  { name: '機器人 Robot', emoji: '🤖' },
  
  // 活動與娛樂
  { name: '音樂 Music', emoji: '🎵' },
  { name: '麥克風 Microphone', emoji: '🎤' },
  { name: '吉他 Guitar', emoji: '🎸' },
  { name: '鋼琴 Piano', emoji: '🎹' },
  { name: '電影 Movie', emoji: '🎬' },
  { name: '藝術 Art', emoji: '🎨' },
  { name: '足球 Soccer', emoji: '⚽' },
  { name: '籃球 Basketball', emoji: '🏀' },
  { name: '網球 Tennis', emoji: '🎾' },
  { name: '游泳 Swimming', emoji: '🏊' },
  { name: '跑步 Running', emoji: '🏃' },
  { name: '禮物 Gift', emoji: '🎁' },
  
  // 其他符號
  { name: '皇冠 Crown', emoji: '👑' },
  { name: '鑽石 Diamond', emoji: '💎' },
  { name: '戒指 Ring', emoji: '💍' },
  { name: '寶石 Gem', emoji: '💎' },
  { name: '氣球 Balloon', emoji: '🎈' },
  { name: '煙火 Fireworks', emoji: '🎆' },
  { name: '派對 Party', emoji: '🎉' },
  { name: '旗幟 Flag', emoji: '🚩' },
  { name: '獎杯 Trophy', emoji: '🏆' },
  { name: '獎牌 Medal', emoji: '🏅' }
]