/**
 * Activities Emojis
 * Source: Unicode 16.0 emoji-test.txt
 * Auto-generated from official Unicode data
 */

export const ACTIVITIES_EMOJIS = {
  event: [
    { emoji: '🎃', name: 'jack-o-lantern' },
    { emoji: '🎄', name: 'Christmas tree' },
    { emoji: '🎆', name: 'fireworks' },
    { emoji: '🎇', name: 'sparkler' },
    { emoji: '🧨', name: 'firecracker' },
    { emoji: '✨', name: 'sparkles' },
    { emoji: '🎈', name: 'balloon' },
    { emoji: '🎉', name: 'party popper' },
    { emoji: '🎊', name: 'confetti ball' },
    { emoji: '🎋', name: 'tanabata tree' },
    { emoji: '🎍', name: 'pine decoration' },
    { emoji: '🎎', name: 'Japanese dolls' },
    { emoji: '🎏', name: 'carp streamer' },
    { emoji: '🎐', name: 'wind chime' },
    { emoji: '🎑', name: 'moon viewing ceremony' },
    { emoji: '🧧', name: 'red envelope' },
    { emoji: '🎀', name: 'ribbon' },
    { emoji: '🎁', name: 'wrapped gift' },
    { emoji: '🎗️', name: 'reminder ribbon' },
    { emoji: '🎟️', name: 'admission tickets' },
    { emoji: '🎫', name: 'ticket' },
  ],

  awardMedal: [
    { emoji: '🎖️', name: 'military medal' },
    { emoji: '🏆', name: 'trophy' },
    { emoji: '🏅', name: 'sports medal' },
    { emoji: '🥇', name: '1st place medal' },
    { emoji: '🥈', name: '2nd place medal' },
    { emoji: '🥉', name: '3rd place medal' },
  ],

  sport: [
    { emoji: '⚽', name: 'soccer ball' },
    { emoji: '⚾', name: 'baseball' },
    { emoji: '🥎', name: 'softball' },
    { emoji: '🏀', name: 'basketball' },
    { emoji: '🏐', name: 'volleyball' },
    { emoji: '🏈', name: 'american football' },
    { emoji: '🏉', name: 'rugby football' },
    { emoji: '🎾', name: 'tennis' },
    { emoji: '🥏', name: 'flying disc' },
    { emoji: '🎳', name: 'bowling' },
    { emoji: '🏏', name: 'cricket game' },
    { emoji: '🏑', name: 'field hockey' },
    { emoji: '🏒', name: 'ice hockey' },
    { emoji: '🥍', name: 'lacrosse' },
    { emoji: '🏓', name: 'ping pong' },
    { emoji: '🏸', name: 'badminton' },
    { emoji: '🥊', name: 'boxing glove' },
    { emoji: '🥋', name: 'martial arts uniform' },
    { emoji: '🥅', name: 'goal net' },
    { emoji: '⛳', name: 'flag in hole' },
    { emoji: '⛸️', name: 'ice skate' },
    { emoji: '🎣', name: 'fishing pole' },
    { emoji: '🤿', name: 'diving mask' },
    { emoji: '🎽', name: 'running shirt' },
    { emoji: '🎿', name: 'skis' },
    { emoji: '🛷', name: 'sled' },
    { emoji: '🥌', name: 'curling stone' },
  ],

  game: [
    { emoji: '🎯', name: 'bullseye' },
    { emoji: '🪀', name: 'yo-yo' },
    { emoji: '🪁', name: 'kite' },
    { emoji: '🔫', name: 'water pistol' },
    { emoji: '🎱', name: 'pool 8 ball' },
    { emoji: '🔮', name: 'crystal ball' },
    { emoji: '🪄', name: 'magic wand' },
    { emoji: '🎮', name: 'video game' },
    { emoji: '🕹️', name: 'joystick' },
    { emoji: '🎰', name: 'slot machine' },
    { emoji: '🎲', name: 'game die' },
    { emoji: '🧩', name: 'puzzle piece' },
    { emoji: '🧸', name: 'teddy bear' },
    { emoji: '🪅', name: 'piñata' },
    { emoji: '🪩', name: 'mirror ball' },
    { emoji: '🪆', name: 'nesting dolls' },
    { emoji: '♠️', name: 'spade suit' },
    { emoji: '♥️', name: 'heart suit' },
    { emoji: '♦️', name: 'diamond suit' },
    { emoji: '♣️', name: 'club suit' },
    { emoji: '♟️', name: 'chess pawn' },
    { emoji: '🃏', name: 'joker' },
    { emoji: '🀄', name: 'mahjong red dragon' },
    { emoji: '🎴', name: 'flower playing cards' },
  ],

  artsCrafts: [
    { emoji: '🎭', name: 'performing arts' },
    { emoji: '🖼️', name: 'framed picture' },
    { emoji: '🎨', name: 'artist palette' },
    { emoji: '🧵', name: 'thread' },
    { emoji: '🪡', name: 'sewing needle' },
    { emoji: '🧶', name: 'yarn' },
    { emoji: '🪢', name: 'knot' },
  ],

};

export default ACTIVITIES_EMOJIS;
