// Emoji - 動物與自然分類
// 包含：動物、植物、天氣、自然現象等

export const animalsNatureEmojis = [
  // 哺乳動物臉部
  { name: '猴臉', emoji: '🐵', category: '動物與自然' },
  { name: '猴子', emoji: '🐒', category: '動物與自然' },
  { name: '狗臉', emoji: '🐶', category: '動物與自然' },
  { name: '狗', emoji: '🐕', category: '動物與自然' },
  { name: '貴賓狗', emoji: '🐩', category: '動物與自然' },
  { name: '狼', emoji: '🐺', category: '動物與自然' },
  { name: '狐狸', emoji: '🦊', category: '動物與自然' },
  { name: '浣熊', emoji: '🦝', category: '動物與自然' },
  { name: '貓臉', emoji: '🐱', category: '動物與自然' },
  { name: '貓', emoji: '🐈', category: '動物與自然' },
  { name: '黑貓', emoji: '🐈‍⬛', category: '動物與自然' },
  { name: '獅子', emoji: '🦁', category: '動物與自然' },
  { name: '老虎臉', emoji: '🐯', category: '動物與自然' },
  { name: '老虎', emoji: '🐅', category: '動物與自然' },
  { name: '豹', emoji: '🐆', category: '動物與自然' },
  { name: '馬臉', emoji: '🐴', category: '動物與自然' },
  { name: '馬', emoji: '🐎', category: '動物與自然' },
  { name: '獨角獸', emoji: '🦄', category: '動物與自然' },
  { name: '斑馬', emoji: '🦓', category: '動物與自然' },
  { name: '鹿', emoji: '🦌', category: '動物與自然' },
  { name: '長頸鹿', emoji: '🦒', category: '動物與自然' },
  { name: '大象', emoji: '🐘', category: '動物與自然' },
  { name: '犀牛', emoji: '🦏', category: '動物與自然' },
  { name: '河馬', emoji: '🦛', category: '動物與自然' },
  { name: '牛臉', emoji: '🐮', category: '動物與自然' },
  { name: '牛', emoji: '🐄', category: '動物與自然' },
  { name: '水牛', emoji: '🐃', category: '動物與自然' },
  { name: '野牛', emoji: '🦬', category: '動物與自然' },
  { name: '豬臉', emoji: '🐷', category: '動物與自然' },
  { name: '豬', emoji: '🐖', category: '動物與自然' },
  { name: '野豬', emoji: '🐗', category: '動物與自然' },
  { name: '羊', emoji: '🐑', category: '動物與自然' },
  { name: '綿羊', emoji: '🐏', category: '動物與自然' },
  { name: '山羊', emoji: '🐐', category: '動物與自然' },
  { name: '駱駝', emoji: '🐪', category: '動物與自然' },
  { name: '雙峰駱駝', emoji: '🐫', category: '動物與自然' },
  { name: '駱馬', emoji: '🦙', category: '動物與自然' },
  
  // 小動物
  { name: '老鼠臉', emoji: '🐭', category: '動物與自然' },
  { name: '老鼠', emoji: '🐁', category: '動物與自然' },
  { name: '倉鼠', emoji: '🐹', category: '動物與自然' },
  { name: '兔臉', emoji: '🐰', category: '動物與自然' },
  { name: '兔子', emoji: '🐇', category: '動物與自然' },
  { name: '花栗鼠', emoji: '🐿️', category: '動物與自然' },
  { name: '刺蝟', emoji: '🦔', category: '動物與自然' },
  { name: '蝙蝠', emoji: '🦇', category: '動物與自然' },
  { name: '熊臉', emoji: '🐻', category: '動物與自然' },
  { name: '熊', emoji: '🐻‍❄️', category: '動物與自然' },
  { name: '無尾熊', emoji: '🐨', category: '動物與自然' },
  { name: '熊貓', emoji: '🐼', category: '動物與自然' },
  { name: '樹懶', emoji: '🦥', category: '動物與自然' },
  { name: '水獺', emoji: '🦦', category: '動物與自然' },
  { name: '臭鼬', emoji: '🦨', category: '動物與自然' },
  { name: '袋鼠', emoji: '🦘', category: '動物與自然' },
  { name: '獾', emoji: '🦡', category: '動物與自然' },
  
  // 爪子與腳印
  { name: '爪印', emoji: '🐾', category: '動物與自然' },
  
  // 鳥類
  { name: '火雞', emoji: '🦃', category: '動物與自然' },
  { name: '雞', emoji: '🐔', category: '動物與自然' },
  { name: '公雞', emoji: '🐓', category: '動物與自然' },
  { name: '孵蛋', emoji: '🐣', category: '動物與自然' },
  { name: '小雞', emoji: '🐤', category: '動物與自然' },
  { name: '小雞頭', emoji: '🐥', category: '動物與自然' },
  { name: '鳥', emoji: '🐦', category: '動物與自然' },
  { name: '企鵝', emoji: '🐧', category: '動物與自然' },
  { name: '鴿子', emoji: '🕊️', category: '動物與自然' },
  { name: '老鷹', emoji: '🦅', category: '動物與自然' },
  { name: '鴨子', emoji: '🦆', category: '動物與自然' },
  { name: '天鵝', emoji: '🦢', category: '動物與自然' },
  { name: '貓頭鷹', emoji: '🦉', category: '動物與自然' },
  { name: '鸚鵡', emoji: '🦜', category: '動物與自然' },
  { name: '孔雀', emoji: '🦚', category: '動物與自然' },
  { name: '火烈鳥', emoji: '🦩', category: '動物與自然' },
  
  // 海洋動物
  { name: '鯊魚', emoji: '🦈', category: '動物與自然' },
  { name: '鯨魚', emoji: '🐳', category: '動物與自然' },
  { name: '抹香鯨', emoji: '🐋', category: '動物與自然' },
  { name: '海豚', emoji: '🐬', category: '動物與自然' },
  { name: '海豹', emoji: '🦭', category: '動物與自然' },
  { name: '魚', emoji: '🐟', category: '動物與自然' },
  { name: '熱帶魚', emoji: '🐠', category: '動物與自然' },
  { name: '河豚', emoji: '🐡', category: '動物與自然' },
  { name: '章魚', emoji: '🐙', category: '動物與自然' },
  { name: '螺貝', emoji: '🐚', category: '動物與自然' },
  
  // 爬蟲類
  { name: '蛇', emoji: '🐍', category: '動物與自然' },
  { name: '龍', emoji: '🐲', category: '動物與自然' },
  { name: '噴火龍', emoji: '🐉', category: '動物與自然' },
  { name: '蜥蜴', emoji: '🦎', category: '動物與自然' },
  { name: '恐龍', emoji: '🦕', category: '動物與自然' },
  { name: '暴龍', emoji: '🦖', category: '動物與自然' },
  { name: '烏龜', emoji: '🐢', category: '動物與自然' },
  { name: '鱷魚', emoji: '🐊', category: '動物與自然' },
  
  // 兩棲類
  { name: '青蛙', emoji: '🐸', category: '動物與自然' },
  
  // 昆蟲
  { name: '蝸牛', emoji: '🐌', category: '動物與自然' },
  { name: '蝶', emoji: '🦋', category: '動物與自然' },
  { name: '蟲', emoji: '🐛', category: '動物與自然' },
  { name: '螞蟻', emoji: '🐜', category: '動物與自然' },
  { name: '蜜蜂', emoji: '🐝', category: '動物與自然' },
  { name: '甲蟲', emoji: '🪲', category: '動物與自然' },
  { name: '瓢蟲', emoji: '🐞', category: '動物與自然' },
  { name: '蟋蟀', emoji: '🦗', category: '動物與自然' },
  { name: '蜘蛛', emoji: '🕷️', category: '動物與自然' },
  { name: '蕊', emoji: '🕸️', category: '動物與自然' },
  { name: '蠍子', emoji: '🦂', category: '動物與自然' },
  { name: '蚊子', emoji: '🦟', category: '動物與自然' },
  { name: '蒼蠅', emoji: '🪰', category: '動物與自然' },
  { name: '蠕蟲', emoji: '🪱', category: '動物與自然' },
  { name: '微生物', emoji: '🦠', category: '動物與自然' },
  
  // 植物與花朵
  { name: '花束', emoji: '💐', category: '動物與自然' },
  { name: '櫻花', emoji: '🌸', category: '動物與自然' },
  { name: '白花', emoji: '💮', category: '動物與自然' },
  { name: '蓮花', emoji: '🏵️', category: '動物與自然' },
  { name: '向日葵', emoji: '🌻', category: '動物與自然' },
  { name: '花', emoji: '🌺', category: '動物與自然' },
  { name: '鬱金香', emoji: '🌷', category: '動物與自然' },
  { name: '玫瑰', emoji: '🌹', category: '動物與自然' },
  { name: '枯花', emoji: '🥀', category: '動物與自然' },
  { name: '新芽', emoji: '🌱', category: '動物與自然' },
  { name: '幼苗', emoji: '🪴', category: '動物與自然' },
  { name: '常青樹', emoji: '🌲', category: '動物與自然' },
  { name: '落葉樹', emoji: '🌳', category: '動物與自然' },
  { name: '棕櫚樹', emoji: '🌴', category: '動物與自然' },
  { name: '仙人掌', emoji: '🌵', category: '動物與自然' },
  { name: '稻穗', emoji: '🌾', category: '動物與自然' },
  { name: '竹子', emoji: '🎋', category: '動物與自然' },
  
  // 樹葉與草本
  { name: '葉子', emoji: '🍃', category: '動物與自然' },
  { name: '楓葉', emoji: '🍂', category: '動物與自然' },
  { name: '四葉草', emoji: '🍀', category: '動物與自然' },
  { name: '草', emoji: '🌿', category: '動物與自然' },
  { name: '苔蘚', emoji: '🪵', category: '動物與自然' },
  { name: '蘑菇', emoji: '🍄', category: '動物與自然' },
  
  // 水果
  { name: '葡萄', emoji: '🍇', category: '動物與自然' },
  { name: '哈密瓜', emoji: '🍈', category: '動物與自然' },
  { name: '西瓜', emoji: '🍉', category: '動物與自然' },
  { name: '橘子', emoji: '🍊', category: '動物與自然' },
  { name: '檸檬', emoji: '🍋', category: '動物與自然' },
  { name: '香蕉', emoji: '🍌', category: '動物與自然' },
  { name: '鳳梨', emoji: '🍍', category: '動物與自然' },
  { name: '芒果', emoji: '🥭', category: '動物與自然' },
  { name: '蘋果', emoji: '🍎', category: '動物與自然' },
  { name: '青蘋果', emoji: '🍏', category: '動物與自然' },
  { name: '梨子', emoji: '🍐', category: '動物與自然' },
  { name: '桃子', emoji: '🍑', category: '動物與自然' },
  { name: '櫻桃', emoji: '🍒', category: '動物與自然' },
  { name: '草莓', emoji: '🍓', category: '動物與自然' },
  { name: '奇異果', emoji: '🥝', category: '動物與自然' },
  { name: '番茄', emoji: '🍅', category: '動物與自然' },
  { name: '椰子', emoji: '🥥', category: '動物與自然' },
  
  // 天氣與自然現象
  { name: '太陽', emoji: '☀️', category: '動物與自然' },
  { name: '月亮', emoji: '🌙', category: '動物與自然' },
  { name: '新月', emoji: '🌚', category: '動物與自然' },
  { name: '滿月', emoji: '🌝', category: '動物與自然' },
  { name: '半月', emoji: '🌛', category: '動物與自然' },
  { name: '彎月', emoji: '🌜', category: '動物與自然' },
  { name: '月牙', emoji: '🌒', category: '動物與自然' },
  { name: '凸月', emoji: '🌓', category: '動物與自然' },
  { name: '凸月2', emoji: '🌔', category: '動物與自然' },
  { name: '月缺', emoji: '🌕', category: '動物與自然' },
  { name: '月缺2', emoji: '🌖', category: '動物與自然' },
  { name: '月缺3', emoji: '🌗', category: '動物與自然' },
  { name: '月缺4', emoji: '🌘', category: '動物與自然' },
  { name: '星星', emoji: '⭐', category: '動物與自然' },
  { name: '閃爍星', emoji: '🌟', category: '動物與自然' },
  { name: '螢火', emoji: '✨', category: '動物與自然' },
  { name: '彗星', emoji: '☄️', category: '動物與自然' },
  { name: '雲朵', emoji: '☁️', category: '動物與自然' },
  { name: '晴雲', emoji: '⛅', category: '動物與自然' },
  { name: '雲雨', emoji: '🌦️', category: '動物與自然' },
  { name: '雷雲', emoji: '⛈️', category: '動物與自然' },
  { name: '閃電', emoji: '⚡', category: '動物與自然' },
  { name: '火', emoji: '🔥', category: '動物與自然' },
  { name: '爆炸', emoji: '💥', category: '動物與自然' },
  { name: '雪花', emoji: '❄️', category: '動物與自然' },
  { name: '雪人', emoji: '☃️', category: '動物與自然' },
  { name: '無雪人', emoji: '⛄', category: '動物與自然' },
  { name: '風', emoji: '💨', category: '動物與自然' },
  { name: '水滴', emoji: '💧', category: '動物與自然' },
  { name: '海浪', emoji: '🌊', category: '動物與自然' },
  { name: '霧', emoji: '🌫️', category: '動物與自然' },
  { name: '龍捲風', emoji: '🌪️', category: '動物與自然' },
  { name: '彩虹', emoji: '🌈', category: '動物與自然' },
  
  // 地球與天體
  { name: '地球亞非', emoji: '🌍', category: '動物與自然' },
  { name: '地球美洲', emoji: '🌎', category: '動物與自然' },
  { name: '地球亞太', emoji: '🌏', category: '動物與自然' },
  { name: '滿月臉', emoji: '🌕', category: '動物與自然' },
  { name: '新月臉', emoji: '🌑', category: '動物與自然' }
]

export const categoryInfo = {
  id: 'animals-nature',
  name: '動物與自然',
  description: '動物、植物、天氣、自然現象等',
  priority: 'high'
}