/**
 * Food & Drink Emojis
 * Source: Unicode 16.0 emoji-test.txt
 * Auto-generated from official Unicode data
 */

export const FOOD_DRINK_EMOJIS = {
  foodFruit: [
    { emoji: '🍇', name: 'grapes' },
    { emoji: '🍈', name: 'melon' },
    { emoji: '🍉', name: 'watermelon' },
    { emoji: '🍊', name: 'tangerine' },
    { emoji: '🍋', name: 'lemon' },
    { emoji: '🍋‍🟩', name: 'lime' },
    { emoji: '🍌', name: 'banana' },
    { emoji: '🍍', name: 'pineapple' },
    { emoji: '🥭', name: 'mango' },
    { emoji: '🍎', name: 'red apple' },
    { emoji: '🍏', name: 'green apple' },
    { emoji: '🍐', name: 'pear' },
    { emoji: '🍑', name: 'peach' },
    { emoji: '🍒', name: 'cherries' },
    { emoji: '🍓', name: 'strawberry' },
    { emoji: '🫐', name: 'blueberries' },
    { emoji: '🥝', name: 'kiwi fruit' },
    { emoji: '🍅', name: 'tomato' },
    { emoji: '🫒', name: 'olive' },
    { emoji: '🥥', name: 'coconut' },
  ],

  foodVegetable: [
    { emoji: '🥑', name: 'avocado' },
    { emoji: '🍆', name: 'eggplant' },
    { emoji: '🥔', name: 'potato' },
    { emoji: '🥕', name: 'carrot' },
    { emoji: '🌽', name: 'ear of corn' },
    { emoji: '🌶️', name: 'hot pepper' },
    { emoji: '🫑', name: 'bell pepper' },
    { emoji: '🥒', name: 'cucumber' },
    { emoji: '🥬', name: 'leafy green' },
    { emoji: '🥦', name: 'broccoli' },
    { emoji: '🧄', name: 'garlic' },
    { emoji: '🧅', name: 'onion' },
    { emoji: '🥜', name: 'peanuts' },
    { emoji: '🫘', name: 'beans' },
    { emoji: '🌰', name: 'chestnut' },
    { emoji: '🫚', name: 'ginger root' },
    { emoji: '🫛', name: 'pea pod' },
    { emoji: '🍄‍🟫', name: 'brown mushroom' },
    { emoji: '🫜', name: 'root vegetable' },
  ],

  foodPrepared: [
    { emoji: '🍞', name: 'bread' },
    { emoji: '🥐', name: 'croissant' },
    { emoji: '🥖', name: 'baguette bread' },
    { emoji: '🫓', name: 'flatbread' },
    { emoji: '🥨', name: 'pretzel' },
    { emoji: '🥯', name: 'bagel' },
    { emoji: '🥞', name: 'pancakes' },
    { emoji: '🧇', name: 'waffle' },
    { emoji: '🧀', name: 'cheese wedge' },
    { emoji: '🍖', name: 'meat on bone' },
    { emoji: '🍗', name: 'poultry leg' },
    { emoji: '🥩', name: 'cut of meat' },
    { emoji: '🥓', name: 'bacon' },
    { emoji: '🍔', name: 'hamburger' },
    { emoji: '🍟', name: 'french fries' },
    { emoji: '🍕', name: 'pizza' },
    { emoji: '🌭', name: 'hot dog' },
    { emoji: '🥪', name: 'sandwich' },
    { emoji: '🌮', name: 'taco' },
    { emoji: '🌯', name: 'burrito' },
    { emoji: '🫔', name: 'tamale' },
    { emoji: '🥙', name: 'stuffed flatbread' },
    { emoji: '🧆', name: 'falafel' },
    { emoji: '🥚', name: 'egg' },
    { emoji: '🍳', name: 'cooking' },
    { emoji: '🥘', name: 'shallow pan of food' },
    { emoji: '🍲', name: 'pot of food' },
    { emoji: '🫕', name: 'fondue' },
    { emoji: '🥣', name: 'bowl with spoon' },
    { emoji: '🥗', name: 'green salad' },
    { emoji: '🍿', name: 'popcorn' },
    { emoji: '🧈', name: 'butter' },
    { emoji: '🧂', name: 'salt' },
    { emoji: '🥫', name: 'canned food' },
  ],

  foodAsian: [
    { emoji: '🍱', name: 'bento box' },
    { emoji: '🍘', name: 'rice cracker' },
    { emoji: '🍙', name: 'rice ball' },
    { emoji: '🍚', name: 'cooked rice' },
    { emoji: '🍛', name: 'curry rice' },
    { emoji: '🍜', name: 'steaming bowl' },
    { emoji: '🍝', name: 'spaghetti' },
    { emoji: '🍠', name: 'roasted sweet potato' },
    { emoji: '🍢', name: 'oden' },
    { emoji: '🍣', name: 'sushi' },
    { emoji: '🍤', name: 'fried shrimp' },
    { emoji: '🍥', name: 'fish cake with swirl' },
    { emoji: '🥮', name: 'moon cake' },
    { emoji: '🍡', name: 'dango' },
    { emoji: '🥟', name: 'dumpling' },
    { emoji: '🥠', name: 'fortune cookie' },
    { emoji: '🥡', name: 'takeout box' },
  ],

  foodSweet: [
    { emoji: '🍦', name: 'soft ice cream' },
    { emoji: '🍧', name: 'shaved ice' },
    { emoji: '🍨', name: 'ice cream' },
    { emoji: '🍩', name: 'doughnut' },
    { emoji: '🍪', name: 'cookie' },
    { emoji: '🎂', name: 'birthday cake' },
    { emoji: '🍰', name: 'shortcake' },
    { emoji: '🧁', name: 'cupcake' },
    { emoji: '🥧', name: 'pie' },
    { emoji: '🍫', name: 'chocolate bar' },
    { emoji: '🍬', name: 'candy' },
    { emoji: '🍭', name: 'lollipop' },
    { emoji: '🍮', name: 'custard' },
    { emoji: '🍯', name: 'honey pot' },
  ],

  drink: [
    { emoji: '🍼', name: 'baby bottle' },
    { emoji: '🥛', name: 'glass of milk' },
    { emoji: '☕', name: 'hot beverage' },
    { emoji: '🫖', name: 'teapot' },
    { emoji: '🍵', name: 'teacup without handle' },
    { emoji: '🍶', name: 'sake' },
    { emoji: '🍾', name: 'bottle with popping cork' },
    { emoji: '🍷', name: 'wine glass' },
    { emoji: '🍸', name: 'cocktail glass' },
    { emoji: '🍹', name: 'tropical drink' },
    { emoji: '🍺', name: 'beer mug' },
    { emoji: '🍻', name: 'clinking beer mugs' },
    { emoji: '🥂', name: 'clinking glasses' },
    { emoji: '🥃', name: 'tumbler glass' },
    { emoji: '🫗', name: 'pouring liquid' },
    { emoji: '🥤', name: 'cup with straw' },
    { emoji: '🧋', name: 'bubble tea' },
    { emoji: '🧃', name: 'beverage box' },
    { emoji: '🧉', name: 'mate' },
    { emoji: '🧊', name: 'ice' },
  ],

  dishware: [
    { emoji: '🥢', name: 'chopsticks' },
    { emoji: '🍽️', name: 'fork and knife with plate' },
    { emoji: '🍴', name: 'fork and knife' },
    { emoji: '🥄', name: 'spoon' },
    { emoji: '🔪', name: 'kitchen knife' },
    { emoji: '🫙', name: 'jar' },
    { emoji: '🏺', name: 'amphora' },
  ],

};

export default FOOD_DRINK_EMOJIS;
