/**
 * Objects Emojis
 * Source: Unicode 16.0 emoji-test.txt
 * Auto-generated from official Unicode data
 */

export const OBJECTS_EMOJIS = {
  clothing: [
    { emoji: '👓', name: 'glasses' },
    { emoji: '🕶️', name: 'sunglasses' },
    { emoji: '🥽', name: 'goggles' },
    { emoji: '🥼', name: 'lab coat' },
    { emoji: '🦺', name: 'safety vest' },
    { emoji: '👔', name: 'necktie' },
    { emoji: '👕', name: 't-shirt' },
    { emoji: '👖', name: 'jeans' },
    { emoji: '🧣', name: 'scarf' },
    { emoji: '🧤', name: 'gloves' },
    { emoji: '🧥', name: 'coat' },
    { emoji: '🧦', name: 'socks' },
    { emoji: '👗', name: 'dress' },
    { emoji: '👘', name: 'kimono' },
    { emoji: '🥻', name: 'sari' },
    { emoji: '🩱', name: 'one-piece swimsuit' },
    { emoji: '🩲', name: 'briefs' },
    { emoji: '🩳', name: 'shorts' },
    { emoji: '👙', name: 'bikini' },
    { emoji: '👚', name: 'woman’s clothes' },
    { emoji: '🪭', name: 'folding hand fan' },
    { emoji: '👛', name: 'purse' },
    { emoji: '👜', name: 'handbag' },
    { emoji: '👝', name: 'clutch bag' },
    { emoji: '🛍️', name: 'shopping bags' },
    { emoji: '🎒', name: 'backpack' },
    { emoji: '🩴', name: 'thong sandal' },
    { emoji: '👞', name: 'man’s shoe' },
    { emoji: '👟', name: 'running shoe' },
    { emoji: '🥾', name: 'hiking boot' },
    { emoji: '🥿', name: 'flat shoe' },
    { emoji: '👠', name: 'high-heeled shoe' },
    { emoji: '👡', name: 'woman’s sandal' },
    { emoji: '🩰', name: 'ballet shoes' },
    { emoji: '👢', name: 'woman’s boot' },
    { emoji: '🪮', name: 'hair pick' },
    { emoji: '👑', name: 'crown' },
    { emoji: '👒', name: 'woman’s hat' },
    { emoji: '🎩', name: 'top hat' },
    { emoji: '🎓', name: 'graduation cap' },
    { emoji: '🧢', name: 'billed cap' },
    { emoji: '🪖', name: 'military helmet' },
    { emoji: '⛑️', name: 'rescue worker’s helmet' },
    { emoji: '📿', name: 'prayer beads' },
    { emoji: '💄', name: 'lipstick' },
    { emoji: '💍', name: 'ring' },
    { emoji: '💎', name: 'gem stone' },
  ],

  sound: [
    { emoji: '🔇', name: 'muted speaker' },
    { emoji: '🔈', name: 'speaker low volume' },
    { emoji: '🔉', name: 'speaker medium volume' },
    { emoji: '🔊', name: 'speaker high volume' },
    { emoji: '📢', name: 'loudspeaker' },
    { emoji: '📣', name: 'megaphone' },
    { emoji: '📯', name: 'postal horn' },
    { emoji: '🔔', name: 'bell' },
    { emoji: '🔕', name: 'bell with slash' },
  ],

  music: [
    { emoji: '🎼', name: 'musical score' },
    { emoji: '🎵', name: 'musical note' },
    { emoji: '🎶', name: 'musical notes' },
    { emoji: '🎙️', name: 'studio microphone' },
    { emoji: '🎚️', name: 'level slider' },
    { emoji: '🎛️', name: 'control knobs' },
    { emoji: '🎤', name: 'microphone' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '📻', name: 'radio' },
  ],

  musicalInstrument: [
    { emoji: '🎷', name: 'saxophone' },
    { emoji: '🪗', name: 'accordion' },
    { emoji: '🎸', name: 'guitar' },
    { emoji: '🎹', name: 'musical keyboard' },
    { emoji: '🎺', name: 'trumpet' },
    { emoji: '🎻', name: 'violin' },
    { emoji: '🪕', name: 'banjo' },
    { emoji: '🥁', name: 'drum' },
    { emoji: '🪘', name: 'long drum' },
    { emoji: '🪇', name: 'maracas' },
    { emoji: '🪈', name: 'flute' },
    { emoji: '🪉', name: 'harp' },
  ],

  phone: [
    { emoji: '📱', name: 'mobile phone' },
    { emoji: '📲', name: 'mobile phone with arrow' },
    { emoji: '☎️', name: 'telephone' },
    { emoji: '📞', name: 'telephone receiver' },
    { emoji: '📟', name: 'pager' },
    { emoji: '📠', name: 'fax machine' },
  ],

  computer: [
    { emoji: '🔋', name: 'battery' },
    { emoji: '🪫', name: 'low battery' },
    { emoji: '🔌', name: 'electric plug' },
    { emoji: '💻', name: 'laptop' },
    { emoji: '🖥️', name: 'desktop computer' },
    { emoji: '🖨️', name: 'printer' },
    { emoji: '⌨️', name: 'keyboard' },
    { emoji: '🖱️', name: 'computer mouse' },
    { emoji: '🖲️', name: 'trackball' },
    { emoji: '💽', name: 'computer disk' },
    { emoji: '💾', name: 'floppy disk' },
    { emoji: '💿', name: 'optical disk' },
    { emoji: '📀', name: 'dvd' },
    { emoji: '🧮', name: 'abacus' },
  ],

  lightVideo: [
    { emoji: '🎥', name: 'movie camera' },
    { emoji: '🎞️', name: 'film frames' },
    { emoji: '📽️', name: 'film projector' },
    { emoji: '🎬', name: 'clapper board' },
    { emoji: '📺', name: 'television' },
    { emoji: '📷', name: 'camera' },
    { emoji: '📸', name: 'camera with flash' },
    { emoji: '📹', name: 'video camera' },
    { emoji: '📼', name: 'videocassette' },
    { emoji: '🔍', name: 'magnifying glass tilted left' },
    { emoji: '🔎', name: 'magnifying glass tilted right' },
    { emoji: '🕯️', name: 'candle' },
    { emoji: '💡', name: 'light bulb' },
    { emoji: '🔦', name: 'flashlight' },
    { emoji: '🏮', name: 'red paper lantern' },
    { emoji: '🪔', name: 'diya lamp' },
  ],

  bookPaper: [
    { emoji: '📔', name: 'notebook with decorative cover' },
    { emoji: '📕', name: 'closed book' },
    { emoji: '📖', name: 'open book' },
    { emoji: '📗', name: 'green book' },
    { emoji: '📘', name: 'blue book' },
    { emoji: '📙', name: 'orange book' },
    { emoji: '📚', name: 'books' },
    { emoji: '📓', name: 'notebook' },
    { emoji: '📒', name: 'ledger' },
    { emoji: '📃', name: 'page with curl' },
    { emoji: '📜', name: 'scroll' },
    { emoji: '📄', name: 'page facing up' },
    { emoji: '📰', name: 'newspaper' },
    { emoji: '🗞️', name: 'rolled-up newspaper' },
    { emoji: '📑', name: 'bookmark tabs' },
    { emoji: '🔖', name: 'bookmark' },
    { emoji: '🏷️', name: 'label' },
  ],

  money: [
    { emoji: '💰', name: 'money bag' },
    { emoji: '🪙', name: 'coin' },
    { emoji: '💴', name: 'yen banknote' },
    { emoji: '💵', name: 'dollar banknote' },
    { emoji: '💶', name: 'euro banknote' },
    { emoji: '💷', name: 'pound banknote' },
    { emoji: '💸', name: 'money with wings' },
    { emoji: '💳', name: 'credit card' },
    { emoji: '🧾', name: 'receipt' },
    { emoji: '💹', name: 'chart increasing with yen' },
  ],

  mail: [
    { emoji: '✉️', name: 'envelope' },
    { emoji: '📧', name: 'e-mail' },
    { emoji: '📨', name: 'incoming envelope' },
    { emoji: '📩', name: 'envelope with arrow' },
    { emoji: '📤', name: 'outbox tray' },
    { emoji: '📥', name: 'inbox tray' },
    { emoji: '📦', name: 'package' },
    { emoji: '📫', name: 'closed mailbox with raised flag' },
    { emoji: '📪', name: 'closed mailbox with lowered flag' },
    { emoji: '📬', name: 'open mailbox with raised flag' },
    { emoji: '📭', name: 'open mailbox with lowered flag' },
    { emoji: '📮', name: 'postbox' },
    { emoji: '🗳️', name: 'ballot box with ballot' },
  ],

  writing: [
    { emoji: '✏️', name: 'pencil' },
    { emoji: '✒️', name: 'black nib' },
    { emoji: '🖋️', name: 'fountain pen' },
    { emoji: '🖊️', name: 'pen' },
    { emoji: '🖌️', name: 'paintbrush' },
    { emoji: '🖍️', name: 'crayon' },
    { emoji: '📝', name: 'memo' },
  ],

  office: [
    { emoji: '💼', name: 'briefcase' },
    { emoji: '📁', name: 'file folder' },
    { emoji: '📂', name: 'open file folder' },
    { emoji: '🗂️', name: 'card index dividers' },
    { emoji: '📅', name: 'calendar' },
    { emoji: '📆', name: 'tear-off calendar' },
    { emoji: '🗒️', name: 'spiral notepad' },
    { emoji: '🗓️', name: 'spiral calendar' },
    { emoji: '📇', name: 'card index' },
    { emoji: '📈', name: 'chart increasing' },
    { emoji: '📉', name: 'chart decreasing' },
    { emoji: '📊', name: 'bar chart' },
    { emoji: '📋', name: 'clipboard' },
    { emoji: '📌', name: 'pushpin' },
    { emoji: '📍', name: 'round pushpin' },
    { emoji: '📎', name: 'paperclip' },
    { emoji: '🖇️', name: 'linked paperclips' },
    { emoji: '📏', name: 'straight ruler' },
    { emoji: '📐', name: 'triangular ruler' },
    { emoji: '✂️', name: 'scissors' },
    { emoji: '🗃️', name: 'card file box' },
    { emoji: '🗄️', name: 'file cabinet' },
    { emoji: '🗑️', name: 'wastebasket' },
  ],

  lock: [
    { emoji: '🔒', name: 'locked' },
    { emoji: '🔓', name: 'unlocked' },
    { emoji: '🔏', name: 'locked with pen' },
    { emoji: '🔐', name: 'locked with key' },
    { emoji: '🔑', name: 'key' },
    { emoji: '🗝️', name: 'old key' },
  ],

  tool: [
    { emoji: '🔨', name: 'hammer' },
    { emoji: '🪓', name: 'axe' },
    { emoji: '⛏️', name: 'pick' },
    { emoji: '⚒️', name: 'hammer and pick' },
    { emoji: '🛠️', name: 'hammer and wrench' },
    { emoji: '🗡️', name: 'dagger' },
    { emoji: '⚔️', name: 'crossed swords' },
    { emoji: '💣', name: 'bomb' },
    { emoji: '🪃', name: 'boomerang' },
    { emoji: '🏹', name: 'bow and arrow' },
    { emoji: '🛡️', name: 'shield' },
    { emoji: '🪚', name: 'carpentry saw' },
    { emoji: '🔧', name: 'wrench' },
    { emoji: '🪛', name: 'screwdriver' },
    { emoji: '🔩', name: 'nut and bolt' },
    { emoji: '⚙️', name: 'gear' },
    { emoji: '🗜️', name: 'clamp' },
    { emoji: '⚖️', name: 'balance scale' },
    { emoji: '🦯', name: 'white cane' },
    { emoji: '🔗', name: 'link' },
    { emoji: '⛓️‍💥', name: 'broken chain' },
    { emoji: '⛓️', name: 'chains' },
    { emoji: '🪝', name: 'hook' },
    { emoji: '🧰', name: 'toolbox' },
    { emoji: '🧲', name: 'magnet' },
    { emoji: '🪜', name: 'ladder' },
    { emoji: '🪏', name: 'shovel' },
  ],

  science: [
    { emoji: '⚗️', name: 'alembic' },
    { emoji: '🧪', name: 'test tube' },
    { emoji: '🧫', name: 'petri dish' },
    { emoji: '🧬', name: 'dna' },
    { emoji: '🔬', name: 'microscope' },
    { emoji: '🔭', name: 'telescope' },
    { emoji: '📡', name: 'satellite antenna' },
  ],

  medical: [
    { emoji: '💉', name: 'syringe' },
    { emoji: '🩸', name: 'drop of blood' },
    { emoji: '💊', name: 'pill' },
    { emoji: '🩹', name: 'adhesive bandage' },
    { emoji: '🩼', name: 'crutch' },
    { emoji: '🩺', name: 'stethoscope' },
    { emoji: '🩻', name: 'x-ray' },
  ],

  household: [
    { emoji: '🚪', name: 'door' },
    { emoji: '🛗', name: 'elevator' },
    { emoji: '🪞', name: 'mirror' },
    { emoji: '🪟', name: 'window' },
    { emoji: '🛏️', name: 'bed' },
    { emoji: '🛋️', name: 'couch and lamp' },
    { emoji: '🪑', name: 'chair' },
    { emoji: '🚽', name: 'toilet' },
    { emoji: '🪠', name: 'plunger' },
    { emoji: '🚿', name: 'shower' },
    { emoji: '🛁', name: 'bathtub' },
    { emoji: '🪤', name: 'mouse trap' },
    { emoji: '🪒', name: 'razor' },
    { emoji: '🧴', name: 'lotion bottle' },
    { emoji: '🧷', name: 'safety pin' },
    { emoji: '🧹', name: 'broom' },
    { emoji: '🧺', name: 'basket' },
    { emoji: '🧻', name: 'roll of paper' },
    { emoji: '🪣', name: 'bucket' },
    { emoji: '🧼', name: 'soap' },
    { emoji: '🫧', name: 'bubbles' },
    { emoji: '🪥', name: 'toothbrush' },
    { emoji: '🧽', name: 'sponge' },
    { emoji: '🧯', name: 'fire extinguisher' },
    { emoji: '🛒', name: 'shopping cart' },
  ],

  otherObject: [
    { emoji: '🚬', name: 'cigarette' },
    { emoji: '⚰️', name: 'coffin' },
    { emoji: '🪦', name: 'headstone' },
    { emoji: '⚱️', name: 'funeral urn' },
    { emoji: '🧿', name: 'nazar amulet' },
    { emoji: '🪬', name: 'hamsa' },
    { emoji: '🗿', name: 'moai' },
    { emoji: '🪧', name: 'placard' },
    { emoji: '🪪', name: 'identification card' },
  ],

};

export default OBJECTS_EMOJIS;
