/**
 * Smileys & Emotion Emojis
 * Source: Unicode 16.0 emoji-test.txt
 * Auto-generated from official Unicode data
 */

export const SMILEYS_EMOTION_EMOJIS = {
  faceSmiling: [
    { emoji: '😀', name: 'grinning face' },
    { emoji: '😃', name: 'grinning face with big eyes' },
    { emoji: '😄', name: 'grinning face with smiling eyes' },
    { emoji: '😁', name: 'beaming face with smiling eyes' },
    { emoji: '😆', name: 'grinning squinting face' },
    { emoji: '😅', name: 'grinning face with sweat' },
    { emoji: '🤣', name: 'rolling on the floor laughing' },
    { emoji: '😂', name: 'face with tears of joy' },
    { emoji: '🙂', name: 'slightly smiling face' },
    { emoji: '🙃', name: 'upside-down face' },
    { emoji: '🫠', name: 'melting face' },
    { emoji: '😉', name: 'winking face' },
    { emoji: '😊', name: 'smiling face with smiling eyes' },
    { emoji: '😇', name: 'smiling face with halo' },
  ],

  faceAffection: [
    { emoji: '🥰', name: 'smiling face with hearts' },
    { emoji: '😍', name: 'smiling face with heart-eyes' },
    { emoji: '🤩', name: 'star-struck' },
    { emoji: '😘', name: 'face blowing a kiss' },
    { emoji: '😗', name: 'kissing face' },
    { emoji: '☺️', name: 'smiling face' },
    { emoji: '😚', name: 'kissing face with closed eyes' },
    { emoji: '😙', name: 'kissing face with smiling eyes' },
    { emoji: '🥲', name: 'smiling face with tear' },
  ],

  faceTongue: [
    { emoji: '😋', name: 'face savoring food' },
    { emoji: '😛', name: 'face with tongue' },
    { emoji: '😜', name: 'winking face with tongue' },
    { emoji: '🤪', name: 'zany face' },
    { emoji: '😝', name: 'squinting face with tongue' },
    { emoji: '🤑', name: 'money-mouth face' },
  ],

  faceHand: [
    { emoji: '🤗', name: 'smiling face with open hands' },
    { emoji: '🤭', name: 'face with hand over mouth' },
    { emoji: '🫢', name: 'face with open eyes and hand over mouth' },
    { emoji: '🫣', name: 'face with peeking eye' },
    { emoji: '🤫', name: 'shushing face' },
    { emoji: '🤔', name: 'thinking face' },
    { emoji: '🫡', name: 'saluting face' },
  ],

  faceNeutralSkeptical: [
    { emoji: '🤐', name: 'zipper-mouth face' },
    { emoji: '🤨', name: 'face with raised eyebrow' },
    { emoji: '😐', name: 'neutral face' },
    { emoji: '😑', name: 'expressionless face' },
    { emoji: '😶', name: 'face without mouth' },
    { emoji: '🫥', name: 'dotted line face' },
    { emoji: '😶‍🌫️', name: 'face in clouds' },
    { emoji: '😏', name: 'smirking face' },
    { emoji: '😒', name: 'unamused face' },
    { emoji: '🙄', name: 'face with rolling eyes' },
    { emoji: '😬', name: 'grimacing face' },
    { emoji: '😮‍💨', name: 'face exhaling' },
    { emoji: '🤥', name: 'lying face' },
    { emoji: '🫨', name: 'shaking face' },
    { emoji: '🙂‍↔️', name: 'head shaking horizontally' },
    { emoji: '🙂‍↕️', name: 'head shaking vertically' },
  ],

  faceSleepy: [
    { emoji: '😌', name: 'relieved face' },
    { emoji: '😔', name: 'pensive face' },
    { emoji: '😪', name: 'sleepy face' },
    { emoji: '🤤', name: 'drooling face' },
    { emoji: '😴', name: 'sleeping face' },
    { emoji: '🫩', name: 'face with bags under eyes' },
  ],

  faceUnwell: [
    { emoji: '😷', name: 'face with medical mask' },
    { emoji: '🤒', name: 'face with thermometer' },
    { emoji: '🤕', name: 'face with head-bandage' },
    { emoji: '🤢', name: 'nauseated face' },
    { emoji: '🤮', name: 'face vomiting' },
    { emoji: '🤧', name: 'sneezing face' },
    { emoji: '🥵', name: 'hot face' },
    { emoji: '🥶', name: 'cold face' },
    { emoji: '🥴', name: 'woozy face' },
    { emoji: '😵', name: 'face with crossed-out eyes' },
    { emoji: '😵‍💫', name: 'face with spiral eyes' },
    { emoji: '🤯', name: 'exploding head' },
  ],

  faceHat: [
    { emoji: '🤠', name: 'cowboy hat face' },
    { emoji: '🥳', name: 'partying face' },
    { emoji: '🥸', name: 'disguised face' },
  ],

  faceGlasses: [
    { emoji: '😎', name: 'smiling face with sunglasses' },
    { emoji: '🤓', name: 'nerd face' },
    { emoji: '🧐', name: 'face with monocle' },
  ],

  faceConcerned: [
    { emoji: '😕', name: 'confused face' },
    { emoji: '🫤', name: 'face with diagonal mouth' },
    { emoji: '😟', name: 'worried face' },
    { emoji: '🙁', name: 'slightly frowning face' },
    { emoji: '☹️', name: 'frowning face' },
    { emoji: '😮', name: 'face with open mouth' },
    { emoji: '😯', name: 'hushed face' },
    { emoji: '😲', name: 'astonished face' },
    { emoji: '😳', name: 'flushed face' },
    { emoji: '🥺', name: 'pleading face' },
    { emoji: '🥹', name: 'face holding back tears' },
    { emoji: '😦', name: 'frowning face with open mouth' },
    { emoji: '😧', name: 'anguished face' },
    { emoji: '😨', name: 'fearful face' },
    { emoji: '😰', name: 'anxious face with sweat' },
    { emoji: '😥', name: 'sad but relieved face' },
    { emoji: '😢', name: 'crying face' },
    { emoji: '😭', name: 'loudly crying face' },
    { emoji: '😱', name: 'face screaming in fear' },
    { emoji: '😖', name: 'confounded face' },
    { emoji: '😣', name: 'persevering face' },
    { emoji: '😞', name: 'disappointed face' },
    { emoji: '😓', name: 'downcast face with sweat' },
    { emoji: '😩', name: 'weary face' },
    { emoji: '😫', name: 'tired face' },
    { emoji: '🥱', name: 'yawning face' },
  ],

  faceNegative: [
    { emoji: '😤', name: 'face with steam from nose' },
    { emoji: '😡', name: 'enraged face' },
    { emoji: '😠', name: 'angry face' },
    { emoji: '🤬', name: 'face with symbols on mouth' },
    { emoji: '😈', name: 'smiling face with horns' },
    { emoji: '👿', name: 'angry face with horns' },
    { emoji: '💀', name: 'skull' },
    { emoji: '☠️', name: 'skull and crossbones' },
  ],

  faceCostume: [
    { emoji: '💩', name: 'pile of poo' },
    { emoji: '🤡', name: 'clown face' },
    { emoji: '👹', name: 'ogre' },
    { emoji: '👺', name: 'goblin' },
    { emoji: '👻', name: 'ghost' },
    { emoji: '👽', name: 'alien' },
    { emoji: '👾', name: 'alien monster' },
    { emoji: '🤖', name: 'robot' },
  ],

  catFace: [
    { emoji: '😺', name: 'grinning cat' },
    { emoji: '😸', name: 'grinning cat with smiling eyes' },
    { emoji: '😹', name: 'cat with tears of joy' },
    { emoji: '😻', name: 'smiling cat with heart-eyes' },
    { emoji: '😼', name: 'cat with wry smile' },
    { emoji: '😽', name: 'kissing cat' },
    { emoji: '🙀', name: 'weary cat' },
    { emoji: '😿', name: 'crying cat' },
    { emoji: '😾', name: 'pouting cat' },
  ],

  monkeyFace: [
    { emoji: '🙈', name: 'see-no-evil monkey' },
    { emoji: '🙉', name: 'hear-no-evil monkey' },
    { emoji: '🙊', name: 'speak-no-evil monkey' },
  ],

  heart: [
    { emoji: '💌', name: 'love letter' },
    { emoji: '💘', name: 'heart with arrow' },
    { emoji: '💝', name: 'heart with ribbon' },
    { emoji: '💖', name: 'sparkling heart' },
    { emoji: '💗', name: 'growing heart' },
    { emoji: '💓', name: 'beating heart' },
    { emoji: '💞', name: 'revolving hearts' },
    { emoji: '💕', name: 'two hearts' },
    { emoji: '💟', name: 'heart decoration' },
    { emoji: '❣️', name: 'heart exclamation' },
    { emoji: '💔', name: 'broken heart' },
    { emoji: '❤️‍🔥', name: 'heart on fire' },
    { emoji: '❤️‍🩹', name: 'mending heart' },
    { emoji: '❤️', name: 'red heart' },
    { emoji: '🩷', name: 'pink heart' },
    { emoji: '🧡', name: 'orange heart' },
    { emoji: '💛', name: 'yellow heart' },
    { emoji: '💚', name: 'green heart' },
    { emoji: '💙', name: 'blue heart' },
    { emoji: '🩵', name: 'light blue heart' },
    { emoji: '💜', name: 'purple heart' },
    { emoji: '🤎', name: 'brown heart' },
    { emoji: '🖤', name: 'black heart' },
    { emoji: '🩶', name: 'grey heart' },
    { emoji: '🤍', name: 'white heart' },
  ],

  emotion: [
    { emoji: '💋', name: 'kiss mark' },
    { emoji: '💯', name: 'hundred points' },
    { emoji: '💢', name: 'anger symbol' },
    { emoji: '💥', name: 'collision' },
    { emoji: '💫', name: 'dizzy' },
    { emoji: '💦', name: 'sweat droplets' },
    { emoji: '💨', name: 'dashing away' },
    { emoji: '🕳️', name: 'hole' },
    { emoji: '💬', name: 'speech balloon' },
    { emoji: '👁️‍🗨️', name: 'eye in speech bubble' },
    { emoji: '🗨️', name: 'left speech bubble' },
    { emoji: '🗯️', name: 'right anger bubble' },
    { emoji: '💭', name: 'thought balloon' },
    { emoji: '💤', name: 'ZZZ' },
  ],

};

export default SMILEYS_EMOTION_EMOJIS;
