/**
 * Symbols Emojis
 * Source: Unicode 16.0 emoji-test.txt
 * Auto-generated from official Unicode data
 */

export const SYMBOLS_EMOJIS = {
  transportSign: [
    { emoji: '🏧', name: 'ATM sign' },
    { emoji: '🚮', name: 'litter in bin sign' },
    { emoji: '🚰', name: 'potable water' },
    { emoji: '♿', name: 'wheelchair symbol' },
    { emoji: '🚹', name: 'men’s room' },
    { emoji: '🚺', name: 'women’s room' },
    { emoji: '🚻', name: 'restroom' },
    { emoji: '🚼', name: 'baby symbol' },
    { emoji: '🚾', name: 'water closet' },
    { emoji: '🛂', name: 'passport control' },
    { emoji: '🛃', name: 'customs' },
    { emoji: '🛄', name: 'baggage claim' },
    { emoji: '🛅', name: 'left luggage' },
  ],

  warning: [
    { emoji: '⚠️', name: 'warning' },
    { emoji: '🚸', name: 'children crossing' },
    { emoji: '⛔', name: 'no entry' },
    { emoji: '🚫', name: 'prohibited' },
    { emoji: '🚳', name: 'no bicycles' },
    { emoji: '🚭', name: 'no smoking' },
    { emoji: '🚯', name: 'no littering' },
    { emoji: '🚱', name: 'non-potable water' },
    { emoji: '🚷', name: 'no pedestrians' },
    { emoji: '📵', name: 'no mobile phones' },
    { emoji: '🔞', name: 'no one under eighteen' },
    { emoji: '☢️', name: 'radioactive' },
    { emoji: '☣️', name: 'biohazard' },
  ],

  arrow: [
    { emoji: '⬆️', name: 'up arrow' },
    { emoji: '↗️', name: 'up-right arrow' },
    { emoji: '➡️', name: 'right arrow' },
    { emoji: '↘️', name: 'down-right arrow' },
    { emoji: '⬇️', name: 'down arrow' },
    { emoji: '↙️', name: 'down-left arrow' },
    { emoji: '⬅️', name: 'left arrow' },
    { emoji: '↖️', name: 'up-left arrow' },
    { emoji: '↕️', name: 'up-down arrow' },
    { emoji: '↔️', name: 'left-right arrow' },
    { emoji: '↩️', name: 'right arrow curving left' },
    { emoji: '↪️', name: 'left arrow curving right' },
    { emoji: '⤴️', name: 'right arrow curving up' },
    { emoji: '⤵️', name: 'right arrow curving down' },
    { emoji: '🔃', name: 'clockwise vertical arrows' },
    { emoji: '🔄', name: 'counterclockwise arrows button' },
    { emoji: '🔙', name: 'BACK arrow' },
    { emoji: '🔚', name: 'END arrow' },
    { emoji: '🔛', name: 'ON! arrow' },
    { emoji: '🔜', name: 'SOON arrow' },
    { emoji: '🔝', name: 'TOP arrow' },
  ],

  religion: [
    { emoji: '🛐', name: 'place of worship' },
    { emoji: '⚛️', name: 'atom symbol' },
    { emoji: '🕉️', name: 'om' },
    { emoji: '✡️', name: 'star of David' },
    { emoji: '☸️', name: 'wheel of dharma' },
    { emoji: '☯️', name: 'yin yang' },
    { emoji: '✝️', name: 'latin cross' },
    { emoji: '☦️', name: 'orthodox cross' },
    { emoji: '☪️', name: 'star and crescent' },
    { emoji: '☮️', name: 'peace symbol' },
    { emoji: '🕎', name: 'menorah' },
    { emoji: '🔯', name: 'dotted six-pointed star' },
    { emoji: '🪯', name: 'khanda' },
  ],

  zodiac: [
    { emoji: '♈', name: 'Aries' },
    { emoji: '♉', name: 'Taurus' },
    { emoji: '♊', name: 'Gemini' },
    { emoji: '♋', name: 'Cancer' },
    { emoji: '♌', name: 'Leo' },
    { emoji: '♍', name: 'Virgo' },
    { emoji: '♎', name: 'Libra' },
    { emoji: '♏', name: 'Scorpio' },
    { emoji: '♐', name: 'Sagittarius' },
    { emoji: '♑', name: 'Capricorn' },
    { emoji: '♒', name: 'Aquarius' },
    { emoji: '♓', name: 'Pisces' },
    { emoji: '⛎', name: 'Ophiuchus' },
  ],

  avSymbol: [
    { emoji: '🔀', name: 'shuffle tracks button' },
    { emoji: '🔁', name: 'repeat button' },
    { emoji: '🔂', name: 'repeat single button' },
    { emoji: '▶️', name: 'play button' },
    { emoji: '⏩', name: 'fast-forward button' },
    { emoji: '⏭️', name: 'next track button' },
    { emoji: '⏯️', name: 'play or pause button' },
    { emoji: '◀️', name: 'reverse button' },
    { emoji: '⏪', name: 'fast reverse button' },
    { emoji: '⏮️', name: 'last track button' },
    { emoji: '🔼', name: 'upwards button' },
    { emoji: '⏫', name: 'fast up button' },
    { emoji: '🔽', name: 'downwards button' },
    { emoji: '⏬', name: 'fast down button' },
    { emoji: '⏸️', name: 'pause button' },
    { emoji: '⏹️', name: 'stop button' },
    { emoji: '⏺️', name: 'record button' },
    { emoji: '⏏️', name: 'eject button' },
    { emoji: '🎦', name: 'cinema' },
    { emoji: '🔅', name: 'dim button' },
    { emoji: '🔆', name: 'bright button' },
    { emoji: '📶', name: 'antenna bars' },
    { emoji: '🛜', name: 'wireless' },
    { emoji: '📳', name: 'vibration mode' },
    { emoji: '📴', name: 'mobile phone off' },
  ],

  gender: [
    { emoji: '♀️', name: 'female sign' },
    { emoji: '♂️', name: 'male sign' },
    { emoji: '⚧️', name: 'transgender symbol' },
  ],

  math: [
    { emoji: '✖️', name: 'multiply' },
    { emoji: '➕', name: 'plus' },
    { emoji: '➖', name: 'minus' },
    { emoji: '➗', name: 'divide' },
    { emoji: '🟰', name: 'heavy equals sign' },
    { emoji: '♾️', name: 'infinity' },
  ],

  punctuation: [
    { emoji: '‼️', name: 'double exclamation mark' },
    { emoji: '⁉️', name: 'exclamation question mark' },
    { emoji: '❓', name: 'red question mark' },
    { emoji: '❔', name: 'white question mark' },
    { emoji: '❕', name: 'white exclamation mark' },
    { emoji: '❗', name: 'red exclamation mark' },
    { emoji: '〰️', name: 'wavy dash' },
  ],

  currency: [
    { emoji: '💱', name: 'currency exchange' },
    { emoji: '💲', name: 'heavy dollar sign' },
  ],

  otherSymbol: [
    { emoji: '⚕️', name: 'medical symbol' },
    { emoji: '♻️', name: 'recycling symbol' },
    { emoji: '⚜️', name: 'fleur-de-lis' },
    { emoji: '🔱', name: 'trident emblem' },
    { emoji: '📛', name: 'name badge' },
    { emoji: '🔰', name: 'Japanese symbol for beginner' },
    { emoji: '⭕', name: 'hollow red circle' },
    { emoji: '✅', name: 'check mark button' },
    { emoji: '☑️', name: 'check box with check' },
    { emoji: '✔️', name: 'check mark' },
    { emoji: '❌', name: 'cross mark' },
    { emoji: '❎', name: 'cross mark button' },
    { emoji: '➰', name: 'curly loop' },
    { emoji: '➿', name: 'double curly loop' },
    { emoji: '〽️', name: 'part alternation mark' },
    { emoji: '✳️', name: 'eight-spoked asterisk' },
    { emoji: '✴️', name: 'eight-pointed star' },
    { emoji: '❇️', name: 'sparkle' },
    { emoji: '©️', name: 'copyright' },
    { emoji: '®️', name: 'registered' },
    { emoji: '™️', name: 'trade mark' },
    { emoji: '🫟', name: 'splatter' },
  ],

  keycap: [
    { emoji: '#️⃣', name: 'keycap: #' },
    { emoji: '*️⃣', name: 'keycap: *' },
    { emoji: '0️⃣', name: 'keycap: 0' },
    { emoji: '1️⃣', name: 'keycap: 1' },
    { emoji: '2️⃣', name: 'keycap: 2' },
    { emoji: '3️⃣', name: 'keycap: 3' },
    { emoji: '4️⃣', name: 'keycap: 4' },
    { emoji: '5️⃣', name: 'keycap: 5' },
    { emoji: '6️⃣', name: 'keycap: 6' },
    { emoji: '7️⃣', name: 'keycap: 7' },
    { emoji: '8️⃣', name: 'keycap: 8' },
    { emoji: '9️⃣', name: 'keycap: 9' },
    { emoji: '🔟', name: 'keycap: 10' },
  ],

  alphanum: [
    { emoji: '🔠', name: 'input latin uppercase' },
    { emoji: '🔡', name: 'input latin lowercase' },
    { emoji: '🔢', name: 'input numbers' },
    { emoji: '🔣', name: 'input symbols' },
    { emoji: '🔤', name: 'input latin letters' },
    { emoji: '🅰️', name: 'A button (blood type)' },
    { emoji: '🆎', name: 'AB button (blood type)' },
    { emoji: '🅱️', name: 'B button (blood type)' },
    { emoji: '🆑', name: 'CL button' },
    { emoji: '🆒', name: 'COOL button' },
    { emoji: '🆓', name: 'FREE button' },
    { emoji: 'ℹ️', name: 'information' },
    { emoji: '🆔', name: 'ID button' },
    { emoji: 'Ⓜ️', name: 'circled M' },
    { emoji: '🆕', name: 'NEW button' },
    { emoji: '🆖', name: 'NG button' },
    { emoji: '🅾️', name: 'O button (blood type)' },
    { emoji: '🆗', name: 'OK button' },
    { emoji: '🅿️', name: 'P button' },
    { emoji: '🆘', name: 'SOS button' },
    { emoji: '🆙', name: 'UP! button' },
    { emoji: '🆚', name: 'VS button' },
    { emoji: '🈁', name: 'Japanese “here” button' },
    { emoji: '🈂️', name: 'Japanese “service charge” button' },
    { emoji: '🈷️', name: 'Japanese “monthly amount” button' },
    { emoji: '🈶', name: 'Japanese “not free of charge” button' },
    { emoji: '🈯', name: 'Japanese “reserved” button' },
    { emoji: '🉐', name: 'Japanese “bargain” button' },
    { emoji: '🈹', name: 'Japanese “discount” button' },
    { emoji: '🈚', name: 'Japanese “free of charge” button' },
    { emoji: '🈲', name: 'Japanese “prohibited” button' },
    { emoji: '🉑', name: 'Japanese “acceptable” button' },
    { emoji: '🈸', name: 'Japanese “application” button' },
    { emoji: '🈴', name: 'Japanese “passing grade” button' },
    { emoji: '🈳', name: 'Japanese “vacancy” button' },
    { emoji: '㊗️', name: 'Japanese “congratulations” button' },
    { emoji: '㊙️', name: 'Japanese “secret” button' },
    { emoji: '🈺', name: 'Japanese “open for business” button' },
    { emoji: '🈵', name: 'Japanese “no vacancy” button' },
  ],

  geometric: [
    { emoji: '🔴', name: 'red circle' },
    { emoji: '🟠', name: 'orange circle' },
    { emoji: '🟡', name: 'yellow circle' },
    { emoji: '🟢', name: 'green circle' },
    { emoji: '🔵', name: 'blue circle' },
    { emoji: '🟣', name: 'purple circle' },
    { emoji: '🟤', name: 'brown circle' },
    { emoji: '⚫', name: 'black circle' },
    { emoji: '⚪', name: 'white circle' },
    { emoji: '🟥', name: 'red square' },
    { emoji: '🟧', name: 'orange square' },
    { emoji: '🟨', name: 'yellow square' },
    { emoji: '🟩', name: 'green square' },
    { emoji: '🟦', name: 'blue square' },
    { emoji: '🟪', name: 'purple square' },
    { emoji: '🟫', name: 'brown square' },
    { emoji: '⬛', name: 'black large square' },
    { emoji: '⬜', name: 'white large square' },
    { emoji: '◼️', name: 'black medium square' },
    { emoji: '◻️', name: 'white medium square' },
    { emoji: '◾', name: 'black medium-small square' },
    { emoji: '◽', name: 'white medium-small square' },
    { emoji: '▪️', name: 'black small square' },
    { emoji: '▫️', name: 'white small square' },
    { emoji: '🔶', name: 'large orange diamond' },
    { emoji: '🔷', name: 'large blue diamond' },
    { emoji: '🔸', name: 'small orange diamond' },
    { emoji: '🔹', name: 'small blue diamond' },
    { emoji: '🔺', name: 'red triangle pointed up' },
    { emoji: '🔻', name: 'red triangle pointed down' },
    { emoji: '💠', name: 'diamond with a dot' },
    { emoji: '🔘', name: 'radio button' },
    { emoji: '🔳', name: 'white square button' },
    { emoji: '🔲', name: 'black square button' },
  ],

};

export default SYMBOLS_EMOJIS;
