/**
 * Heroicons v1 完整圖標列表
 * 總計 230 個圖標（outline 樣式）
 * 
 * 使用方式：
 * 1. 從 @heroicons/vue/outline 動態導入需要的圖標
 * 2. 或在組件中預先導入所有需要的圖標
 */

export const heroiconsOutline = [
  { name: 'Academic Cap', component: 'AcademicCapIcon' },
  { name: 'Adjustments', component: 'AdjustmentsIcon' },
  { name: 'Annotation', component: 'AnnotationIcon' },
  { name: 'Archive', component: 'ArchiveIcon' },
  { name: 'Arrow Circle Down', component: 'ArrowCircleDownIcon' },
  { name: 'Arrow Circle Left', component: 'ArrowCircleLeftIcon' },
  { name: 'Arrow Circle Right', component: 'ArrowCircleRightIcon' },
  { name: 'Arrow Circle Up', component: 'ArrowCircleUpIcon' },
  { name: 'Arrow Down', component: 'ArrowDownIcon' },
  { name: 'Arrow Left', component: 'ArrowLeftIcon' },
  { name: 'Arrow Narrow Down', component: 'ArrowNarrowDownIcon' },
  { name: 'Arrow Narrow Left', component: 'ArrowNarrowLeftIcon' },
  { name: 'Arrow Narrow Right', component: 'ArrowNarrowRightIcon' },
  { name: 'Arrow Narrow Up', component: 'ArrowNarrowUpIcon' },
  { name: 'Arrow Right', component: 'ArrowRightIcon' },
  { name: 'Arrow Sm Down', component: 'ArrowSmDownIcon' },
  { name: 'Arrow Sm Left', component: 'ArrowSmLeftIcon' },
  { name: 'Arrow Sm Right', component: 'ArrowSmRightIcon' },
  { name: 'Arrow Sm Up', component: 'ArrowSmUpIcon' },
  { name: 'Arrow Up', component: 'ArrowUpIcon' },
  { name: 'Arrows Expand', component: 'ArrowsExpandIcon' },
  { name: 'At Symbol', component: 'AtSymbolIcon' },
  { name: 'Backspace', component: 'BackspaceIcon' },
  { name: 'Badge Check', component: 'BadgeCheckIcon' },
  { name: 'Ban', component: 'BanIcon' },
  { name: 'Beaker', component: 'BeakerIcon' },
  { name: 'Bell', component: 'BellIcon' },
  { name: 'Book Open', component: 'BookOpenIcon' },
  { name: 'Bookmark', component: 'BookmarkIcon' },
  { name: 'Bookmark Alt', component: 'BookmarkAltIcon' },
  { name: 'Briefcase', component: 'BriefcaseIcon' },
  { name: 'Cake', component: 'CakeIcon' },
  { name: 'Calculator', component: 'CalculatorIcon' },
  { name: 'Calendar', component: 'CalendarIcon' },
  { name: 'Camera', component: 'CameraIcon' },
  { name: 'Cash', component: 'CashIcon' },
  { name: 'Chart Bar', component: 'ChartBarIcon' },
  { name: 'Chart Pie', component: 'ChartPieIcon' },
  { name: 'Chart Square Bar', component: 'ChartSquareBarIcon' },
  { name: 'Chat', component: 'ChatIcon' },
  { name: 'Chat Alt', component: 'ChatAltIcon' },
  { name: 'Chat Alt 2', component: 'ChatAlt2Icon' },
  { name: 'Check', component: 'CheckIcon' },
  { name: 'Check Circle', component: 'CheckCircleIcon' },
  { name: 'Chevron Double Down', component: 'ChevronDoubleDownIcon' },
  { name: 'Chevron Double Left', component: 'ChevronDoubleLeftIcon' },
  { name: 'Chevron Double Right', component: 'ChevronDoubleRightIcon' },
  { name: 'Chevron Double Up', component: 'ChevronDoubleUpIcon' },
  { name: 'Chevron Down', component: 'ChevronDownIcon' },
  { name: 'Chevron Left', component: 'ChevronLeftIcon' },
  { name: 'Chevron Right', component: 'ChevronRightIcon' },
  { name: 'Chevron Up', component: 'ChevronUpIcon' },
  { name: 'Chip', component: 'ChipIcon' },
  { name: 'Clipboard', component: 'ClipboardIcon' },
  { name: 'Clipboard Check', component: 'ClipboardCheckIcon' },
  { name: 'Clipboard Copy', component: 'ClipboardCopyIcon' },
  { name: 'Clipboard List', component: 'ClipboardListIcon' },
  { name: 'Clock', component: 'ClockIcon' },
  { name: 'Cloud', component: 'CloudIcon' },
  { name: 'Cloud Download', component: 'CloudDownloadIcon' },
  { name: 'Cloud Upload', component: 'CloudUploadIcon' },
  { name: 'Code', component: 'CodeIcon' },
  { name: 'Cog', component: 'CogIcon' },
  { name: 'Collection', component: 'CollectionIcon' },
  { name: 'Color Swatch', component: 'ColorSwatchIcon' },
  { name: 'Credit Card', component: 'CreditCardIcon' },
  { name: 'Cube', component: 'CubeIcon' },
  { name: 'Cube Transparent', component: 'CubeTransparentIcon' },
  { name: 'Currency Bangladeshi', component: 'CurrencyBangladeshiIcon' },
  { name: 'Currency Dollar', component: 'CurrencyDollarIcon' },
  { name: 'Currency Euro', component: 'CurrencyEuroIcon' },
  { name: 'Currency Pound', component: 'CurrencyPoundIcon' },
  { name: 'Currency Rupee', component: 'CurrencyRupeeIcon' },
  { name: 'Currency Yen', component: 'CurrencyYenIcon' },
  { name: 'Cursor Click', component: 'CursorClickIcon' },
  { name: 'Database', component: 'DatabaseIcon' },
  { name: 'Desktop Computer', component: 'DesktopComputerIcon' },
  { name: 'Device Mobile', component: 'DeviceMobileIcon' },
  { name: 'Device Tablet', component: 'DeviceTabletIcon' },
  { name: 'Document', component: 'DocumentIcon' },
  { name: 'Document Add', component: 'DocumentAddIcon' },
  { name: 'Document Download', component: 'DocumentDownloadIcon' },
  { name: 'Document Duplicate', component: 'DocumentDuplicateIcon' },
  { name: 'Document Remove', component: 'DocumentRemoveIcon' },
  { name: 'Document Report', component: 'DocumentReportIcon' },
  { name: 'Document Search', component: 'DocumentSearchIcon' },
  { name: 'Document Text', component: 'DocumentTextIcon' },
  { name: 'Dots Circle Horizontal', component: 'DotsCircleHorizontalIcon' },
  { name: 'Dots Horizontal', component: 'DotsHorizontalIcon' },
  { name: 'Dots Vertical', component: 'DotsVerticalIcon' },
  { name: 'Download', component: 'DownloadIcon' },
  { name: 'Duplicate', component: 'DuplicateIcon' },
  { name: 'Emoji Happy', component: 'EmojiHappyIcon' },
  { name: 'Emoji Sad', component: 'EmojiSadIcon' },
  { name: 'Exclamation', component: 'ExclamationIcon' },
  { name: 'Exclamation Circle', component: 'ExclamationCircleIcon' },
  { name: 'External Link', component: 'ExternalLinkIcon' },
  { name: 'Eye', component: 'EyeIcon' },
  { name: 'Eye Off', component: 'EyeOffIcon' },
  { name: 'Fast Forward', component: 'FastForwardIcon' },
  { name: 'Film', component: 'FilmIcon' },
  { name: 'Filter', component: 'FilterIcon' },
  { name: 'Finger Print', component: 'FingerPrintIcon' },
  { name: 'Fire', component: 'FireIcon' },
  { name: 'Flag', component: 'FlagIcon' },
  { name: 'Folder', component: 'FolderIcon' },
  { name: 'Folder Add', component: 'FolderAddIcon' },
  { name: 'Folder Download', component: 'FolderDownloadIcon' },
  { name: 'Folder Open', component: 'FolderOpenIcon' },
  { name: 'Folder Remove', component: 'FolderRemoveIcon' },
  { name: 'Gift', component: 'GiftIcon' },
  { name: 'Globe', component: 'GlobeIcon' },
  { name: 'Globe Alt', component: 'GlobeAltIcon' },
  { name: 'Hand', component: 'HandIcon' },
  { name: 'Hashtag', component: 'HashtagIcon' },
  { name: 'Heart', component: 'HeartIcon' },
  { name: 'Home', component: 'HomeIcon' },
  { name: 'Identification', component: 'IdentificationIcon' },
  { name: 'Inbox', component: 'InboxIcon' },
  { name: 'Inbox In', component: 'InboxInIcon' },
  { name: 'Information Circle', component: 'InformationCircleIcon' },
  { name: 'Key', component: 'KeyIcon' },
  { name: 'Library', component: 'LibraryIcon' },
  { name: 'Light Bulb', component: 'LightBulbIcon' },
  { name: 'Lightning Bolt', component: 'LightningBoltIcon' },
  { name: 'Link', component: 'LinkIcon' },
  { name: 'Location Marker', component: 'LocationMarkerIcon' },
  { name: 'Lock Closed', component: 'LockClosedIcon' },
  { name: 'Lock Open', component: 'LockOpenIcon' },
  { name: 'Login', component: 'LoginIcon' },
  { name: 'Logout', component: 'LogoutIcon' },
  { name: 'Mail', component: 'MailIcon' },
  { name: 'Mail Open', component: 'MailOpenIcon' },
  { name: 'Map', component: 'MapIcon' },
  { name: 'Menu', component: 'MenuIcon' },
  { name: 'Menu Alt 1', component: 'MenuAlt1Icon' },
  { name: 'Menu Alt 2', component: 'MenuAlt2Icon' },
  { name: 'Menu Alt 3', component: 'MenuAlt3Icon' },
  { name: 'Menu Alt 4', component: 'MenuAlt4Icon' },
  { name: 'Microphone', component: 'MicrophoneIcon' },
  { name: 'Minus', component: 'MinusIcon' },
  { name: 'Minus Circle', component: 'MinusCircleIcon' },
  { name: 'Minus Sm', component: 'MinusSmIcon' },
  { name: 'Moon', component: 'MoonIcon' },
  { name: 'Music Note', component: 'MusicNoteIcon' },
  { name: 'Newspaper', component: 'NewspaperIcon' },
  { name: 'Office Building', component: 'OfficeBuildingIcon' },
  { name: 'Paper Airplane', component: 'PaperAirplaneIcon' },
  { name: 'Paper Clip', component: 'PaperClipIcon' },
  { name: 'Pause', component: 'PauseIcon' },
  { name: 'Pencil', component: 'PencilIcon' },
  { name: 'Pencil Alt', component: 'PencilAltIcon' },
  { name: 'Phone', component: 'PhoneIcon' },
  { name: 'Phone Incoming', component: 'PhoneIncomingIcon' },
  { name: 'Phone Missed Call', component: 'PhoneMissedCallIcon' },
  { name: 'Phone Outgoing', component: 'PhoneOutgoingIcon' },
  { name: 'Photograph', component: 'PhotographIcon' },
  { name: 'Play', component: 'PlayIcon' },
  { name: 'Plus', component: 'PlusIcon' },
  { name: 'Plus Circle', component: 'PlusCircleIcon' },
  { name: 'Plus Sm', component: 'PlusSmIcon' },
  { name: 'Presentation Chart Bar', component: 'PresentationChartBarIcon' },
  { name: 'Presentation Chart Line', component: 'PresentationChartLineIcon' },
  { name: 'Printer', component: 'PrinterIcon' },
  { name: 'Puzzle', component: 'PuzzleIcon' },
  { name: 'Qrcode', component: 'QrcodeIcon' },
  { name: 'Question Mark Circle', component: 'QuestionMarkCircleIcon' },
  { name: 'Receipt Refund', component: 'ReceiptRefundIcon' },
  { name: 'Receipt Tax', component: 'ReceiptTaxIcon' },
  { name: 'Refresh', component: 'RefreshIcon' },
  { name: 'Reply', component: 'ReplyIcon' },
  { name: 'Rewind', component: 'RewindIcon' },
  { name: 'Rss', component: 'RssIcon' },
  { name: 'Save', component: 'SaveIcon' },
  { name: 'Save As', component: 'SaveAsIcon' },
  { name: 'Scale', component: 'ScaleIcon' },
  { name: 'Scissors', component: 'ScissorsIcon' },
  { name: 'Search', component: 'SearchIcon' },
  { name: 'Search Circle', component: 'SearchCircleIcon' },
  { name: 'Selector', component: 'SelectorIcon' },
  { name: 'Server', component: 'ServerIcon' },
  { name: 'Share', component: 'ShareIcon' },
  { name: 'Shield Check', component: 'ShieldCheckIcon' },
  { name: 'Shield Exclamation', component: 'ShieldExclamationIcon' },
  { name: 'Shopping Bag', component: 'ShoppingBagIcon' },
  { name: 'Shopping Cart', component: 'ShoppingCartIcon' },
  { name: 'Sort Ascending', component: 'SortAscendingIcon' },
  { name: 'Sort Descending', component: 'SortDescendingIcon' },
  { name: 'Sparkles', component: 'SparklesIcon' },
  { name: 'Speakerphone', component: 'SpeakerphoneIcon' },
  { name: 'Star', component: 'StarIcon' },
  { name: 'Status Offline', component: 'StatusOfflineIcon' },
  { name: 'Status Online', component: 'StatusOnlineIcon' },
  { name: 'Stop', component: 'StopIcon' },
  { name: 'Sun', component: 'SunIcon' },
  { name: 'Support', component: 'SupportIcon' },
  { name: 'Switch Horizontal', component: 'SwitchHorizontalIcon' },
  { name: 'Switch Vertical', component: 'SwitchVerticalIcon' },
  { name: 'Table', component: 'TableIcon' },
  { name: 'Tag', component: 'TagIcon' },
  { name: 'Template', component: 'TemplateIcon' },
  { name: 'Terminal', component: 'TerminalIcon' },
  { name: 'Thumb Down', component: 'ThumbDownIcon' },
  { name: 'Thumb Up', component: 'ThumbUpIcon' },
  { name: 'Ticket', component: 'TicketIcon' },
  { name: 'Translate', component: 'TranslateIcon' },
  { name: 'Trash', component: 'TrashIcon' },
  { name: 'Trending Down', component: 'TrendingDownIcon' },
  { name: 'Trending Up', component: 'TrendingUpIcon' },
  { name: 'Truck', component: 'TruckIcon' },
  { name: 'Upload', component: 'UploadIcon' },
  { name: 'User', component: 'UserIcon' },
  { name: 'User Add', component: 'UserAddIcon' },
  { name: 'User Circle', component: 'UserCircleIcon' },
  { name: 'User Group', component: 'UserGroupIcon' },
  { name: 'User Remove', component: 'UserRemoveIcon' },
  { name: 'Users', component: 'UsersIcon' },
  { name: 'Variable', component: 'VariableIcon' },
  { name: 'Video Camera', component: 'VideoCameraIcon' },
  { name: 'View Boards', component: 'ViewBoardsIcon' },
  { name: 'View Grid', component: 'ViewGridIcon' },
  { name: 'View Grid Add', component: 'ViewGridAddIcon' },
  { name: 'View List', component: 'ViewListIcon' },
  { name: 'Volume Off', component: 'VolumeOffIcon' },
  { name: 'Volume Up', component: 'VolumeUpIcon' },
  { name: 'Wifi', component: 'WifiIcon' },
  { name: 'X', component: 'XIcon' },
  { name: 'X Circle', component: 'XCircleIcon' },
  { name: 'Zoom In', component: 'ZoomInIcon' },
  { name: 'Zoom Out', component: 'ZoomOutIcon' }
];

// 導出所有圖標組件名稱，方便動態導入
export const heroiconComponentNames = heroiconsOutline.map(icon => icon.component);

// 導出圖標總數
export const HEROICONS_COUNT = heroiconsOutline.length;

export default heroiconsOutline;